### ISSUE TITLE
MA - Failed to Setup

### ISSUE THREAD

**Issue by Alexis-Grant** [music-assistant/hass-music-assistant#1000]
### What version of Music Assistant has the issue?

2022.11.0

### The problem

Setting up MA for the first time and getting "Failed to set up. Check the logs". Logs are below.

This is being running a RPi 4 and DietPi as the OS

### How to reproduce

Download 2022.11.0 from HACS
Restart HA
Add MA
Choose 2 entities
No other options enabled (no TuneIn, YT, Spotify etc..)
Submit

### Relevant log output

Logger: homeassistant.config_entries
Source: deps/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py:164
First occurred: 10:14:06 (1 occurrences)
Last logged: 10:14:06

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.15/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/mass/__init__.py", line 197, in async_setup_entry
    raise exc
  File "/mnt/dietpi_userdata/homeassistant/custom_components/mass/__init__.py", line 190, in async_setup_entry
    await mass.setup()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/music_assistant/mass.py", line 79, in setup
    await self.database.setup()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/music_assistant/controllers/database.py", line 43, in setup
    await self._migrate()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/music_assistant/controllers/database.py", line 216, in _migrate
    await self.set_setting("version", str(SCHEMA_VERSION))
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/music_assistant/controllers/database.py", line 60, in set_setting
    return await self.insert(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/music_assistant/controllers/database.py", line 137, in insert
    return await self.get_row(table, lookup_vals)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/music_assistant/controllers/database.py", line 115, in get_row
    return await self._db.fetch_one(sql_query, match)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/databases/core.py", line 148, in fetch_one
    return await connection.fetch_one(query, values)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/databases/core.py", line 257, in fetch_one
    return await self._connection.fetch_one(built_query)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/databases/backends/sqlite.py", line 120, in fetch_one
    metadata = CursorResultMetaData(context, cursor.description)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 164, in __init__
    (
ValueError: not enough values to unpack (expected 5, got 4)

### What version of Home Assistant Core are your running

2022.11.4

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Possibly a dependency is missing. sqlalchemy is mentioned at the top. You might not have the correct version. Recommend running HassOS to avoid these issues

**Comment by Alexis-Grant** [comment]
Reading around a bit more, seems I did the 2nd half of the paragraph for my first install 😟:

![image](https://user-images.githubusercontent.com/91332845/204017329-cc5e60df-c9c7-4be1-a202-5bb25d8eda95.png)

I've upgraded my HA and it still doesn't work so it seems like I'm a bit stuck on this

OzGav, thanks for the suggestion but I don't think I can upgrade to HassOS due to what I'm currently running on the Pi

**Comment by Alexis-Grant** [comment]
Closing this off as did a fresh install of HA 2022.11 and MA 2022.11 and all working fine now

**Comment by erkr** [comment]
Thanks for reporting back, and enjoy the working setup!
