### ISSUE TITLE
[Library sync for provider Tune-in Radio]  failed in MA Version 2022.12.1

### ISSUE THREAD

**Issue by jweston2112** [music-assistant/hass-music-assistant#1024]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

On Restart I always Check my Logs and I found an Error about the Tune-In Radio provider  

It appears there is a Column missing

qlite3.OperationalError: no such column: provider_ids

### How to reproduce

I guess have Tune-In Provider Configured

Update to 2022.12.1

Check the Log

### Relevant log output

```
Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232
First occurred: 5:22:14 AM (1 occurrences)
Last logged: 5:22:14 AM

Job [Library sync for provider Tune-in Radio] failed with error no such column: provider_ids.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 405, in sync_library
    db_item: MediaItemType = await controller.get_db_item_by_prov_id(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 349, in get_db_item_by_prov_id
    for item in await self.get_db_items_by_prov_id(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 385, in get_db_items_by_prov_id
    return await self.get_db_items_by_query(query, limit=limit, offset=offset)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 325, in get_db_items_by_query
    for db_row in await self.mass.database.get_rows_from_query(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 90, in get_rows_from_query
    return await self._db.fetch_all(query, params)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 142, in fetch_all
    return await connection.fetch_all(query, values)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 250, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 98, in fetch_all
    async with self._connection.execute(query_str, args) as cursor:
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/context.py", line 41, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: no such column: provider_ids

```

### What version of Home Assistant Core are your running

2022.12.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Let me guess... You have been fiddling with the manifest file before and had the music-assistant 1.8.8 in there ?
In that case your db schema is now messed up because its already on the upcoming release.

There is no way to get out of this state now, can you restore a backup of the MA database from just before your manual changes ?

**Comment by jweston2112** [comment]
Ummm Yes...  and Yes... I guess you have seen This before... :) ... sorry I guess this is self inflicted.. 💯 %

**Comment by marcelveldt** [comment]
I kind of expected this to happen when I saw people started to manual mess with the manifest file even though I was warning that could cause side effects haha. Lucky you have a backup then. Have a nice weekend!

**Comment by jweston2112** [comment]
You Have a Great Weekend ... You deserve  it for all this hard work... 👍🏻
