### ISSUE TITLE
Error setting up entry Music Assistant for mass

### ISSUE THREAD

**Issue by RobertZwets** [music-assistant/hass-music-assistant#1032]
### What version of Music Assistant has the issue?

v2022.12.1

### The problem

Music Assistant fails to start/load

### How to reproduce

loading or reloading MA, restarting Docker and or HA was unsuccessfull

### Relevant log output

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:187
Integration: Music Assistant (documentation, issues)
First occurred: 17:59:43 (2 occurrences)
Last logged: 22:35:17

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/databases/importer.py", line 18, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'databases.backends.sqlite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 187, in async_setup_entry
    mass = MusicAssistant(mass_conf, session=http_session)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 59, in __init__
    self.database = DatabaseController(self)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 37, in __init__
    self._db = Db(self.url, timeout=360)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 62, in __init__
    backend_cls = import_from_string(backend_str)
  File "/usr/local/lib/python3.10/site-packages/databases/importer.py", line 23, in import_from_string
    raise ImportFromStringError(message.format(module_str=module_str))
databases.importer.ImportFromStringError: Could not import module "databases.backends.sqlite".

### Additional information

running on Docker on Synology

### What version of Home Assistant Core are your running

2022.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Synology

**Comment by OzGav** [comment]
Can you advise what you have done to try and fix the issue. For example, have you tried a restart of HA?

**Comment by RobertZwets** [comment]
The statement running on RPi comes from the issue harwarde choice.
I've restarted the docker and, HA and MA several times

**Comment by OzGav** [comment]
Ok from what I know, since you are running HAOS, it should work ok. My suggestion is to remove the integration, restart HA and then re-add MA

**Comment by OzGav** [comment]
That might remove the db so if you don’t want to rebuild it make a copy before the above.

**Comment by OzGav** [comment]
Also if you made any manual changes to any of the MA files then likely your db is corrupt so you will need to delete the db and start again.

**Comment by RobertZwets** [comment]
HA Version 2022.12.5 repaired by it's own before i could re install, thnks for the help!

**Comment by RobertZwets** [comment]
HA Version 2022.12.5 repaired by it's own before i could re install, thnks for the help!
