### ISSUE TITLE
Port 8080 in use

### ISSUE THREAD

**Issue by jannis3005** [music-assistant/hass-music-assistant#1039]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

Integration does not start when Port 8080 is used by something else - it is not clear what that port is used for.

### How to reproduce

Start someting that listens on Port 8080 and then Add Music Assistant integration

### Relevant log output

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 197, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 190, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 84, in setup
    await self.streams.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 120, in setup
    await http_site.start()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1505, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address in use

### What version of Home Assistant Core are your running

2022.12.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Did you ever manually alter something on the files of Music Assistant ?
This error simply can not happen. A port is auto selected in a range between 8095 and 8195 unless a port was hardcoded.

**Comment by jannis3005** [comment]
no I did not touch the files. I even tried deleting and reinstalling the integration. I'll check the files if I can find the one containing the port(s).

**Comment by jannis3005** [comment]
No, I did move my home assistant from docker to a hassos VM and there it works just fine, in my docker install it is still broken and I don't know why.

**Comment by OzGav** [comment]
As this does not seem to be a MA issue then I will close this. Please feel free to report any other MA issues in the future.
