### ISSUE TITLE
Music Assistant and Denon/HEOS don't seem to work

### ISSUE THREAD

**Issue by sderungs** [music-assistant/hass-music-assistant#1043]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

I recently installed Music Assistant and can't seem to get it to work with my Denon AVR-X4300H and my Denon HEOS 3 speaker.
I installed Music Assistant according to the docs and configured both Spotify and TuneIn.
However, no music is played at all.

### How to reproduce

When I search for a song or album on Spotify and hit play no music is played at all (no matter which of both devices I chose).
The loading spinner on the top right just spins endlessly.
The same happens when I try to play a radio station from TuneIn.

### Relevant log output

2022-12-19 20:40:15.479 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-19 20:41:18.833 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-19 20:42:56.343 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-19 20:44:11.716 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.19 seconds
2022-12-19 20:44:11.925 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.2 seconds
2022-12-19 20:44:12.263 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.18 seconds
2022-12-19 20:44:12.515 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.23 seconds
2022-12-19 20:44:12.720 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.19 seconds
2022-12-19 20:44:12.932 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.2 seconds
2022-12-19 20:44:13.309 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.22 seconds
2022-12-19 20:44:13.516 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.21 seconds
2022-12-19 20:44:13.733 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.2 seconds
2022-12-19 20:44:13.966 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.23 seconds
2022-12-19 20:44:14.372 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.27 seconds
2022-12-19 20:44:14.582 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.21 seconds
2022-12-19 20:44:14.703 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/tracks took 0.12 seconds
2022-12-19 20:44:30.435 DEBUG (MainThread) [music_assistant.event] queue_items_updated media_player.heos_3
2022-12-19 20:44:30.438 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.heos_3
2022-12-19 20:44:30.797 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.heos_3
2022-12-19 20:44:30.802 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.heos_3
2022-12-19 20:44:30.808 DEBUG (MainThread) [music_assistant.event] player_updated media_player.heos_3
2022-12-19 20:44:30.955 DEBUG (MainThread) [music_assistant.players.stream] Starting Queue audio stream for Queue HEOS 3 (PCM format: s16le - sample rate: 44100)
2022-12-19 20:44:30.956 INFO (MainThread) [music_assistant.players.stream] Start Streaming queue track: tunein://radio/s15439 (Radio Argovia) for queue HEOS 3 - crossfade: False
2022-12-19 20:44:30.956 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.heos_3
2022-12-19 20:44:31.090 DEBUG (MainThread) [music_assistant.helpers.audio] start media stream for: tunein://radio/s15439
2022-12-19 20:44:31.092 DEBUG (MainThread) [music_assistant.helpers.audio] writer started for tunein://radio/s15439
2022-12-19 20:44:31.640 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.heos_3
2022-12-19 20:44:34.346 DEBUG (MainThread) [music_assistant.event] player_updated media_player.heos_avr
2022-12-19 20:44:38.810 DEBUG (MainThread) [music_assistant.music.spotify] Start sync of playlist items.
2022-12-19 20:44:38.978 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/playlists took 0.16 seconds
2022-12-19 20:44:39.182 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/playlists took 0.2 seconds
2022-12-19 20:44:39.321 DEBUG (MainThread) [music_assistant.music.spotify] Processing GET/me/playlists took 0.14 seconds
2022-12-19 20:44:40.735 INFO (MainThread) [music_assistant] Finished job [Library sync for provider Spotify] in 36.38 seconds.
2022-12-19 20:44:40.735 DEBUG (MainThread) [music_assistant.event] background_job_finished Library sync for provider Spotify
2022-12-19 20:44:40.954 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-19 20:44:40.957 DEBUG (MainThread) [music_assistant.helpers.audio] media stream aborted for: tunein://radio/s15439
2022-12-19 20:44:40.958 DEBUG (MainThread) [music_assistant.event] background_job_updated Analyze audio for tunein://radio/s15439
2022-12-19 20:44:40.960 DEBUG (MainThread) [music_assistant.event] background_job_updated Analyze audio for tunein://radio/s15439
2022-12-19 20:44:40.967 DEBUG (MainThread) [music_assistant.helpers.audio] Start analyzing track tunein://radio/s15439

### What version of Home Assistant Core are your running

2022.12.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by frantzphilippe** [comment]
It may be due your HEOS HA Integration. Have you checked that you have signed in your heos account in Home Assistant, it must be done in "Dev Tools" menu, then choose "Services", then type 'Heos' in service, it should find something like "Denon HEOS: Sign in", here you can enter your Heos Credentials. After that, try again to play some music.

**Comment by erkr** [comment]
The Denon integration doesn't work. But as you can read here: https://github.com/music-assistant/hass-music-assistant/discussions/494, you can use DNLA

**Comment by sderungs** [comment]
Hi @erkr 

thank you for the hint about DLNA - I did not know about that integration.

So I removed my existing Denon and HEOS integrations and then configured the "DLNA Digital Media Renderer" integrations for both Denon devices. Both devices show up in Music Assistant. However, no music is played at all.

To check connectivity I just changed the volume and I can follow the volume change live in the Denon app as well - so connectivity to the device seems to be there from Music Assistant.

However, when I try to play a song from an album:

- if I select the Denon AVR as destination, the web-player at the bottom of the page briefly pops up and then disappears again.
- if I select the Denon HEOS 3 speaker, the web-player stays but nothing happens at all (song timer also remains at 00:00)

In the logs I only find this:

> 2022-12-22 22:23:35.714 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/mass/player_controls.py", line 1134, in async_hass_state_event
source_player.on_hass_event(event)
File "/config/custom_components/mass/player_controls.py", line 211, in on_hass_event
self.update_state()
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player.py", line 304, in update_state
cur_state = self.to_dict()
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player.py", line 342, in to_dict
"name": self.name,
File "/config/custom_components/mass/player_controls.py", line 126, in name
if self.entity.has_entity_name:
AttributeError: 'NoneType' object has no attribute 'has_entity_name'
2022-12-22 22:26:46.300 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-22 22:26:51.860 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-22 22:27:56.077 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-22 22:27:58.289 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-22 22:28:00.287 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-22 22:29:17.164 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.helios_heat_recovery_efficiency is taking over 10 seconds
2022-12-22 22:29:17.302 WARNING (MainThread) [homeassistant.helpers.entity] Update of fan.helios is taking over 10 seconds
2022-12-22 22:29:36.430 WARNING (MainThread) [homeassistant.components.media_player] Error retrieving proxied image from http://192.168.2.74:60006/upnp/desc/aios_device/%22%22
2022-12-22 22:30:15.449 WARNING (MainThread) [music_assistant.players.stream] Abort: client(s) did not connect within 10 seconds.
2022-12-22 22:30:17.303 WARNING (MainThread) [homeassistant.helpers.entity] Update of fan.helios is taking over 10 seconds

The "did not connect within 10" message doens't seem to only be related to music assistant but also other integrations log that from time to time but those integrations still work properly.

And not sure what to think about the task exception...

**Comment by OzGav** [comment]
Go though the trouble shooting FAQ for these players and see if that reveals anything more useful…

**Comment by sderungs** [comment]
> Go though the trouble shooting FAQ for these players and see if that reveals anything more useful…

Not sure what player you mean (Music Assistant I‘m already trying to troubleshoot by going through its docs and these issues) and what FAQs you’re referring to?

**Comment by heinzma** [comment]
FAQ: https://github.com/music-assistant/hass-music-assistant/discussions/709

**Comment by sderungs** [comment]
Thanks heinzma for the FAQ link.

After some analysis here is what I've found out.

> Probably the most common issue is people trying to run MA with complicated network setups. To reiterate the setup instructions, MA must be able to be reached LOCALLY on port 8095. Running behind VPNs, across subnets, behind firewalls or inside containers is not supported (it might work but we can’t troubleshoot for you)

Both my Home Assistant and the Denon devices are in the same subnet. Therefore, no restrictions on the port are in place.

> Make sure the HA internal url is set correctly. 

I'm using custom domains with SSL certificates both on the internet URL as well as the local one. For my local URL I have a local DNS server that resolves the URL to the IP address. Address resolution works within the subnet. For the local network I have a custom SSL certificate in place that holds both the devices IP address as well as the local domain name in the SAN settings (so I have the flexibility to access it with either of both).

> Look in the LOGS for errors.
> You can also look in the Browser console when you have front end issues which in Chrome browser is

Nothing new besides what I've already shared above and nothing in the browser console in terms of errors.

> See the supported players...

I'm using DLNA Digital Media Renderer - so should be ok

> Further testing advise here #622
> Second situation: ... after you checked if playback works in the standard media browser ...

The DLNA player doesn't work with the standard media browser. The reason is because it tries the public internet url instead of the local one. The problem here is that on the public internet I have protected my HA setup with cloudflare's Zero Trust setup.

2022-12-23 18:50:26.245 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547206501456] Invalid uri: https://MY.PUBLIC.URL/media/local/04%20Every%20Breath%20You%20Take.m4a?authSig=REMOVED_AUTH_TOKEN

After some googling I found out that there are other native components in HA that also use the internet URL instead of the local one when accessing HA resources. However, I couldn't find out why this is the case (doesn't make sense to me though).

I couldn't find any configuration to tell HA to use the local network URL. So I presume I'll have to fallback to the old Denon/Heos integrations unfortunately and just go with the built-in standard media browser for radio streaming and use the Spotify integration separately.

**Comment by OzGav** [comment]
If HA is not using the correct internal URL have a look at SETTINGS>>NETWORK>>HOME ASSISTANT URL. Try specifying the IP URL as well as try automatic

**Comment by sderungs** [comment]
> If HA is not using the correct internal URL have a look at SETTINGS>>NETWORK>>HOME ASSISTANT URL. Try specifying the IP URL as well as try automatic

I've already tried that (both with fixed internal URL as well as automatic -> changed setting -> restarted HA -> tried to stream from MA again) - it still uses the external URL

**Comment by OzGav** [comment]
> The DLNA player doesn't work with the standard media browser. The reason is because it tries the public internet url instead of the local one. The problem here is that on the public internet I have protected my HA setup with cloudflare's Zero Trust setup.

If you have a networking problem such as this you need to resolve it for MA to work.

**Comment by OzGav** [comment]
Just checking if you have resolved the network issue?

**Comment by OzGav** [comment]
I will close this soon as no response received.

**Comment by sderungs** [comment]
Apologies for the lack of response but the holidays... 🥳
I will give it another try this week

**Comment by OzGav** [comment]
Any further update? As this seems to be a networking issue I am inclined to close?

**Comment by sderungs** [comment]
The issue can be closed. Unfortunately, I don't have the time at the moment to pursue this further. Sorry...
