### ISSUE TITLE
Job [Library sync for provider Youtube Music] failed with error 'gridRenderer'.

### ISSUE THREAD

**Issue by Joo01** [music-assistant/hass-music-assistant#1050]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

On each start HA logging the error.
The background job collect also my playlists/artists/... e.g. for Youtube music but the music don't start to play. 
Other errors are not logged.   

### How to reproduce

Just only installed and configured Music Assistant.

### Relevant log output

2022-12-30 11:21:38.449 ERROR (MainThread) [music_assistant] Job [Library sync for provider Youtube Music] failed with error 'gridRenderer'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 402, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 141, in get_library_albums
    albums_obj = await get_library_albums(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 117, in get_library_albums
    return await loop.run_in_executor(None, _get_library_albums)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 114, in _get_library_albums
    return ytm.get_library_albums(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 131, in get_library_albums
    return parse_library_albums(
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 27, in parse_library_albums
    results = get_library_contents(response, GRID)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 113, in get_library_contents
    return nav(results, ITEM_SECTION + renderer)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 76, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 70, in nav
    root = root[k]
KeyError: 'gridRenderer'

### What version of Home Assistant Core are your running

2022.12.8

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
Besides the YouTube error is MA working ok?

**Comment by Joo01** [comment]
No, no music is played.
I see the covers/titles/artits, but nothing happens as soon as I start it.

**Comment by OzGav** [comment]
Have you been through the trouble shooting FAQ? https://github.com/music-assistant/hass-music-assistant/discussions/709

**Comment by erkr** [comment]
@MarvinSchenkel 
Do these 'gridrenderer' errors make sense to you? Two users reported them.

**Comment by erkr** [comment]
@MarvinSchenkel Thanks for the elaborate explanation!
