### ISSUE TITLE
Provider file_saempdy is not available

### ISSUE THREAD

**Issue by override80** [music-assistant/hass-music-assistant#1053]
### What version of Music Assistant has the issue?

v2022.12.1

### The problem

Hi! When trying to play a music track, I get the following error logged (and the track is not played):

```
music_assistant.models.errors.ProviderUnavailableError: Provider file_saempdy is not available
2023-01-04 19:58:37.662 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140501167152128] Error handling message: Unknown error (unknown_error) from 192.168.1.13 (Mozilla/5.0 (Linux; Android 10; ONEPLUS A5010 Build/QQ3A.200805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.152 Mobile Safari/537.36 Home Assistant/2022.12.0-3026 (Android 10))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 448, in websocket_track
    item = await mass.music.tracks.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 49, in get
    track.album = await self.mass.music.albums.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/albums.py", line 44, in get
    album.artist = await self.mass.music.artists.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 158, in get
    provider_id, provider_item_id = await self.get_provider_id(db_item)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 311, in get_provider_id
    if self.mass.music.get_provider(prov.prov_id):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 127, in get_provider
    raise ProviderUnavailableError(f"Provider {provider_id} is not available")
music_assistant.models.errors.ProviderUnavailableError: Provider file_saempdy is not available
```

or

```
2023-01-04 20:51:53.524 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140232455459104] Error handling message: Unknown error (unknown_error) from 192.168.1.10 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:108.0) Gecko/20100101 Firefox/108.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 1188, in websocket_play_media
    await player_queue.play_media(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 275, in play_media
    await self.play_index(cur_index)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 535, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 712, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 322, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 241, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 231, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 254, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 49, in get
    track.album = await self.mass.music.albums.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/albums.py", line 44, in get
    album.artist = await self.mass.music.artists.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 158, in get
    provider_id, provider_item_id = await self.get_provider_id(db_item)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 311, in get_provider_id
    if self.mass.music.get_provider(prov.prov_id):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 127, in get_provider
    raise ProviderUnavailableError(f"Provider {provider_id} is not available")
music_assistant.models.errors.ProviderUnavailableError: Provider file_saempdy is not available
```

The ID3 tag looks correct...

### How to reproduce

I can share the mp3 file if you want to debug

### What version of Home Assistant Core are your running

2022.12.9

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by override80** [comment]
Ok apparently the provider id is some kind of a random... Now i get this error:


```
2023-01-06 10:41:37.889 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140038263055616] Error handling message: Unknown error (unknown_error) from 10.11.12.93 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:108.0) Gecko/20100101 Firefox/108.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 1106, in websocket_playerqueue_command
    await player_queue.play_index(msg[COMMAND_ARG])
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 535, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 712, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 322, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 241, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 231, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 254, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 49, in get
    track.album = await self.mass.music.albums.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/albums.py", line 44, in get
    album.artist = await self.mass.music.artists.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 158, in get
    provider_id, provider_item_id = await self.get_provider_id(db_item)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 311, in get_provider_id
    if self.mass.music.get_provider(prov.prov_id):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 127, in get_provider
    raise ProviderUnavailableError(f"Provider {provider_id} is not available")
music_assistant.models.errors.ProviderUnavailableError: Provider file_saefswbm3/ is not available
```

**Comment by marcelveldt** [comment]
You have an issue with the availability of your files

**Comment by override80** [comment]
You are right! Defective external hard drive. Weird that files played with VLC, maybe it is a little bit more tolerant.

Replacing the HD fixed the issue.

Thanks
