### ISSUE TITLE
Job [Library sync for provider Youtube Music] failed with error Track is missing artist(s).

### ISSUE THREAD

**Issue by marcokitzmann** [music-assistant/hass-music-assistant#1062]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

There are several album folders that doesn't show any tracks, logfile says sync failed with error "Track is missing artist(s)"

### How to reproduce

Don't know exactly how to reproduce, I think it happens while syncing. 

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232
First occurred: 8. Januar 2023 um 02:45:16 (25 occurrences)
Last logged: 21:06:51

Job [Library sync for provider Youtube Music] failed with error Track is missing artist(s).
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 411, in sync_library
    db_item = await controller.add_db_item(prov_item)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 194, in add_db_item
    assert item.artists, "Track is missing artist(s)"
AssertionError: Track is missing artist(s)

### What version of Home Assistant Core are your running

2022.12.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Hi @marcokitzmann 
Thanks for raising your issue. I leave it open for now (@MarvinSchenkel can you plz confirm my answer):
To my knowledge this is a know issue. Not all music tracks on YT have the minimum set of required meta tags. Those tracks are then skipped by MA. 
Best Eric

**Comment by MarvinSchenkel** [comment]
You are absolutely correct. Since YT Music does not have an official api,
we just do the best we can 😁. But the metadata isn't as good as for
example Spotify.

Op di 10 jan. 2023 om 22:54 schreef Eric ***@***.***>

**Comment by marcokitzmann** [comment]
Ok, so that's not the reason for missing tracks inside album folders? The error message reads as if the sync process gets interrupted.

**Comment by erkr** [comment]
The error above just indicates missing meta data: "Track is missing artist(s)". 
That error doesn't imply the whole sync failed, just a track got skipped. Reading your initial comments, I read some albums are empty, so others are not empty?! If so it is working.

Best Eric

**Comment by marcokitzmann** [comment]
That's right, most folders show tracks in them. Only a few stay empty. Do you know of any workaround? Thx for your support!

**Comment by erkr** [comment]
Thanks for confirming. To my knowledge, there is no work around. I will close the issue.
Best Eric
