### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'musicbrainz_id'

### ISSUE THREAD

**Issue by override80** [music-assistant/hass-music-assistant#108]
Hi! I'm trying to make Hass Music Assistant to work on single mp3 file in a specific folder. The mp3 file is tagged with Song Title, Artist and Album. I have configured nothing as a music provider but filesystem provider and typed the folder containing that mp3 file. I get this error in the logs:

```
2022-05-10 09:31:43 ERROR (MainThread) [music_assistant.mass] Job [Library sync of tracks for provider Filesystem] failed with error 'NoneType' object has no attribute 'musicbrainz_id'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 397, in _library_items_sync
    db_item = await controller.add_db_item(prov_item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/tracks.py", line 145, in add_db_item
    or await self.mass.music.albums.add_db_item(track.album)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 121, in add_db_item
    if album.artist.musicbrainz_id and album.artist.provider != "database":
AttributeError: 'NoneType' object has no attribute 'musicbrainz_id'
```

It came out that this was due to missing infos in the id3 tag. As a minimum requirement, it looks like that you need at least the following:

Song Title:	SongTitle
Artist:		ArtistName     
Album:		AlbumName     
Track:		5
Year:		2022

so that it gets the proper musicbrainz_id. A software like MusicBrainz Picard could be used to properly tag the mp3s.

I did not find specific details in the docs, maybe this should be added :)

**Comment by marcelveldt** [comment]
The minimum required tags should be title and artist. Otherwise an error will be logged so I'm not sure why you get the error you see now. What version do you have running ?
