### ISSUE TITLE
Youtube music error

### ISSUE THREAD

**Issue by deanfourie1** [music-assistant/hass-music-assistant#1081]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

Cannot integrate YoutubeMusic Premium account.

Receiving error

`Retrying setup: Setup failed of provider ytmusic: '__Secure-3PAPISID'`

### How to reproduce

try to integrate a YoutubeMusic Premium account?

### What version of Home Assistant Core are your running

 2023.1.7

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by deanfourie1** [comment]
I have added the cookie and the error appears to have cleared.
However, nothing loads in the media player windows, its all just blank. 
Tried a sync and force sync, nothing.

**Comment by OzGav** [comment]
https://github.com/music-assistant/hass-music-assistant/discussions/606#discussioncomment-3622779

**Comment by deanfourie1** [comment]
Nope, I dont think this is the issue.

`Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232
First occurred: 10:50:00 (2 occurrences)
Last logged: 10:50:22

Job [Library sync for provider Youtube Music] failed with error 'musicShelfRenderer'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 402, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 133, in get_library_artists
    artists_obj = await get_library_artists(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 105, in get_library_artists
    return await loop.run_in_executor(None, _get_library_artists)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 95, in _get_library_artists
    artists = ytm.get_library_subscriptions(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 178, in get_library_subscriptions
    return parse_library_artists(
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 84, in parse_library_artists
    results = get_library_contents(response, MUSIC_SHELF)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 113, in get_library_contents
    return nav(results, ITEM_SECTION + renderer)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 76, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 70, in nav
    root = root[k]
KeyError: 'musicShelfRenderer'`


`Logger: custom_components.mass
Source: custom_components/mass/__init__.py:122
Integration: Music Assistant ([documentation](https://github.com/music-assistant/hass-music-assistant), [issues](https://github.com/music-assistant/hass-music-assistant/issues))
First occurred: 10:49:56 (1 occurrences)
Last logged: 10:49:56

This version of Music Assistant is compatible with Home Assistant version 2022.11, and you are running 2023.1.7. You may run into compatibility issues. Please check if there's a newer (beta) version available of Music Assistant.`

**Comment by deanfourie1** [comment]
This is the cookie I copied

![image](https://user-images.githubusercontent.com/71812804/215606956-ab996110-ec69-4a25-a4a7-456133a6467d.png)

**Comment by deanfourie1** [comment]
Looks like #1058

**Comment by OzGav** [comment]
Yes. Please note Marvin’s final response. See how the next version of MA works for you.
