### ISSUE TITLE
Repeating Error in Log file "can't subtract offset-naive and offset-aware datetimes"

### ISSUE THREAD

**Issue by adam-olson** [music-assistant/hass-music-assistant#1093]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

Continuous repeating error in the log file, had to disable integration to stop it.

### How to reproduce

No apparent cause, was not using the integration at the time.

### Relevant log output

```2023-02-06 22:36:18.294 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mass/player_controls.py", line 1134, in async_hass_state_event
    source_player.on_hass_event(event)
  File "/config/custom_components/mass/player_controls.py", line 211, in on_hass_event
    self.update_state()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player.py", line 304, in update_state
    cur_state = self.to_dict()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player.py", line 344, in to_dict
    "elapsed_time": int(self.elapsed_time),
  File "/config/custom_components/mass/player_controls.py", line 163, in elapsed_time
    diff = (utcnow() - last_upd).seconds
```

### What version of Home Assistant Core are your running

2023.2.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Can you provide more info about your install. We can only support standard installs.

**Comment by adam-olson** [comment]
This is a container install in Docker running on a Synology.

**Comment by OzGav** [comment]
Have you previously had MA working ok?

**Comment by adam-olson** [comment]
Yes, and it appears to work now, just getting that error spamming the log file after a while.

**Comment by OzGav** [comment]
What happened between it working and now? Did something get upgraded?

**Comment by adam-olson** [comment]
I believe it was happening in the previous release of Home Assistant 2023.1.x as well as this current one, 2023.02.x, not sure if I noticed it in an earlier release of Home Assistant, 2022.12.x or not. Kept up with the corresponding Music Assistant  release to keep functionality running in HA.

**Comment by OzGav** [comment]
OK. you will have to wait until the V2 comes out in a couple of weeks as no bug fixes are being made on the current version.

**Comment by OzGav** [comment]
https://github.com/music-assistant/home-assistant-addon

Please move to V2 to resolve this. Note that it is still in beta so other issues may arise.

**Comment by OzGav** [comment]
Closing. Request to reopen if this is still an issue in MA V2
