### ISSUE TITLE
I can't play anything on any media player

### ISSUE THREAD

**Issue by BondfinderBR** [music-assistant/hass-music-assistant#1094]
### What version of Music Assistant has the issue?

V2023-21.

### The problem

I can't play anything on any media player

### What version of Home Assistant Core are your running

2023.2.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Desculpe, só posso ajudar em inglês

Have you been through the trouble shooting steps here https://github.com/music-assistant/hass-music-assistant/discussions/709

**Comment by BondfinderBR** [comment]
Ok Sorry.

**Comment by BondfinderBR** [comment]
I choose player and I click on the music and reload effect as if the music were to start and the above error happens.

**Comment by OzGav** [comment]
Have you been through the trouble shooting steps here https://github.com/music-assistant/hass-music-assistant/discussions/709

**Comment by BondfinderBR** [comment]
Hello I looked as indicated.

I passed a direct test to the chromecast and no.

I tested the HASS multimedia browser and it worked on all the players I played with.

test I did with chromecast was to send music assist directly to google chromecast and it doesn't always give an error when sending the url and etc.


follow log:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_player.py:331
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:47:12 (2 occurrences)
Last logged: 12:05:13

[1844894184] The read operation timed out
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/config/custom_components/mass/media_player.py", line 331, in async_media_play
    await self.player.active_queue.play()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 389, in play
    await self.resume()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 462, in resume
    await self.play_index(resume_item.item_id, resume_pos, fade_in)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 535, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 712, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 322, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 253, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 395, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 638, in _parse_stream_url
    signature = await self._decipher_signature(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 685, in _decipher_signature
    self._cipher = await self.mass.loop.run_in_executor(None, _decipher)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 678, in _decipher
    embed_html = pytube.request.get(embed_url)
  File "/usr/local/lib/python3.10/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out


this usage log with chromecast.

Logger: homeassistant.core
Source: custom_components/mass/media_player.py:429
Integration: Music Assistant ([documentation](https://github.com/music-assistant/hass-music-assistant), [issues](https://github.com/music-assistant/hass-music-assistant/issues))
First occurred: 13:19:09 (16 occurrences)
Last logged: 13:19:27

Error executing service: <ServiceCall media_player.play_media (c:01GRRX535E7XHCF1XYRCFPT2AD): entity_id=['media_player.mass_quarto'], extra=, media_type=audio/flac, media_id=media-source://mass/database://artist/16>
Error executing service: <ServiceCall media_player.play_media (c:01GRRX52GYB09EZWRVQ627E259): entity_id=['media_player.mass_quarto'], extra=, media_type=audio/flac, media_id=media-source://mass/database://artist/16>
Error executing service: <ServiceCall media_player.play_media (c:01GRRX5BKSTSQZX09EQSZ6DCR4): entity_id=['media_player.mass_quarto'], extra=, media_type=audio/flac, media_id=media-source://mass/database://artist/16>
Error executing service: <ServiceCall media_player.play_media (c:01GRRX52AM52RJRB5JNF1CK3MH): entity_id=['media_player.mass_quarto'], extra=, media_type=audio/flac, media_id=media-source://mass/database://artist/16>
Error executing service: <ServiceCall media_player.play_media (c:01GRRX54FY2BXVJWAH80Q79WZR): entity_id=['media_player.mass_quarto'], extra=, media_type=audio/flac, media_id=media-source://mass/database://artist/16>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1805, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/config/custom_components/mass/media_player.py", line 429, in async_play_media
    await self.player.active_queue.play_media(media_id, queue_opt)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 275, in play_media
    await self.play_index(cur_index)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 535, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 712, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 322, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 253, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 395, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 638, in _parse_stream_url
    signature = await self._decipher_signature(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 685, in _decipher_signature
    self._cipher = await self.mass.loop.run_in_executor(None, _decipher)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 678, in _decipher
    embed_html = pytube.request.get(embed_url)
  File "/usr/local/lib/python3.10/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

**Comment by OzGav** [comment]
Ok so I understand that the HA media player entities work.

Can you try sending a Text to speech (TTS) message to the MA media player entity.

**Comment by OzGav** [comment]
We will close this issue soon as no further info was provided. Please also note v2 has been released.

https://github.com/music-assistant/home-assistant-addon
