### ISSUE TITLE
Error on with Youtube Music 

### ISSUE THREAD

**Issue by marc3k18** [music-assistant/hass-music-assistant#1101]
### What version of Music Assistant has the issue?

2023.2.1 

### The problem

Can't browser my Playlist, Artist or anything. But search fonction is working.

![Capture](https://user-images.githubusercontent.com/97817024/219925878-73ca1cc0-0c7e-4111-8bd3-e74319711484.PNG)

### How to reproduce

Browser for anything in Youtube Music is not working.

Search is working.

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232
First occurred: 12:14:01 AM (2 occurrences)
Last logged: 12:15:24 AM

Job [Library sync for provider Youtube Music] failed with error 'NoneType' object is not subscriptable.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 402, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 133, in get_library_artists
    artists_obj = await get_library_artists(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 105, in get_library_artists
    return await loop.run_in_executor(None, _get_library_artists)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 95, in _get_library_artists
    artists = ytm.get_library_subscriptions(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 174, in get_library_subscriptions
    return parse_library_artists(
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 86, in parse_library_artists
    results = nav(results, ITEM_SECTION)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
TypeError: 'NoneType' object is not subscriptable

-------------------------------------------------------

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:929
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:21:11 AM (4 occurrences)
Last logged: 12:22:10 AM

[139779505232704] Error handling message: Unknown error (unknown_error) from 10.18.0.157 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
[139780439039504] Error handling message: Unknown error (unknown_error) from 10.18.0.157 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 929, in websocket_browse
    await mass.music.browse(msg.get("path")),
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 224, in browse
    return await prov.browse(path)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 338, in browse
    items=[x async for x in self.get_library_artists()],
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 338, in <listcomp>
    items=[x async for x in self.get_library_artists()],
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 133, in get_library_artists
    artists_obj = await get_library_artists(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 105, in get_library_artists
    return await loop.run_in_executor(None, _get_library_artists)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 95, in _get_library_artists
    artists = ytm.get_library_subscriptions(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 174, in get_library_subscriptions
    return parse_library_artists(
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 86, in parse_library_artists
    results = nav(results, ITEM_SECTION)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
TypeError: 'NoneType' object is not subscriptable

### What version of Home Assistant Core are your running

2023.2.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please confirm you have YouTube premium

**Comment by Lucho99se** [comment]
I have the same issue and i have youtube premium

**Comment by marc3k18** [comment]
I have youtube premium

Le dim. 19 févr. 2023, 4 h 17 a.m., OzGav ***@***.***> a
écrit :

**Comment by OzGav** [comment]
@marc3k18 Can you provide more detail where you say "search function is working"?

**Comment by DATuttleJr** [comment]
I seem to be having a similar issue... Music assistant downloaded my playlists from YTMusic... Yes I have premium... but it won't play any songs.  Instead I get this:
![failed to call service media player](https://user-images.githubusercontent.com/47952682/221191972-d9d76a05-b7bb-4fd6-b1fe-a889d5faf2cb.jpg)


![Music assistant screenshot](https://user-images.githubusercontent.com/47952682/221192055-ee951cb4-93f8-4fdc-a6d0-3c22576693d2.jpg)


Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_player.py:359
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:31:55 AM (3 occurrences)
Last logged: 8:32:05 AM

[139921945320304] 'streamingData'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/config/custom_components/mass/media_player.py", line 359, in async_media_previous_track
    await self.player.active_queue.previous()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 417, in previous
    await self.play_index(max(self._current_index - 1, 0))
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 535, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 712, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 322, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 253, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 394, in get_stream_details
    stream_format = await self._parse_stream_format(track_obj)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 662, in _parse_stream_format
    for adaptive_format in track_obj["streamingData"]["adaptiveFormats"]:
KeyError: 'streamingData'

**Comment by Lucho99se** [comment]
In my case, when clicking on playlist or any of the options, it remains loading and does not show the content
![image](https://user-images.githubusercontent.com/64111929/221317774-07948981-423f-46b2-b2ef-29ec5d89b809.png)

**Comment by bugui2007** [comment]
I have the same issue with Youtube premium, I can't play songs an also player cant download song list from playlist, it keeps searching.

**Comment by OzGav** [comment]
Ill tag @MarvinSchenkel just so he is aware but YT is a problem generally as they have no official API. See the disclaimer at the top of this post https://github.com/music-assistant/hass-music-assistant/discussions/606 and a more detailed explanation here https://github.com/music-assistant/hass-music-assistant/issues/1050#issuecomment-1402393376

**Comment by MarvinSchenkel** [comment]
> Ill tag @MarvinSchenkel just so he is aware but YT is a problem generally as they have no official API. See the disclaimer at the top of this post #606 and a more detailed explanation here [#1050 (comment)](https://github.com/music-assistant/hass-music-assistant/issues/1050#issuecomment-1402393376)

Pretty much got nothing to add :-). When 2.0 gets released, it will be easier to trace and solve these kind of issues. So let's (im)patiently wait for 2.0 to be released!

**Comment by OzGav** [comment]
https://github.com/music-assistant/home-assistant-addon

Please move to V2 to resolve this. Note that it is still in beta so other issues may arise. Please report back if it is fixed in v2

**Comment by azoner2965** [comment]
> https://github.com/music-assistant/home-assistant-addon
> 
> Please move to V2 to resolve this. Note that it is still in beta so other issues may arise. Please report back if it is fixed in v2

I have the same issue in V2.

**Comment by OzGav** [comment]
Ok thanks. This will continue to be investigated.

**Comment by OzGav** [comment]
Please confirm if this still present on MA 2.0.0b7

**Comment by azoner2965** [comment]
Loving it!

**Comment by DATuttleJr** [comment]
It was not working for me so I uninstalled it... Now I try to reinstall it and it fails:

Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by DATuttleJr** [comment]
Never mind... After actually reading the instructions and following them... It seems to be working now... I will give my impressions after I have used for a while.

Thank you for all you do!!

**Comment by MarvinSchenkel** [comment]
Great! I am gonna close this issue for now then. If you run into any issues, feel free to open a new one :-)
