### ISSUE TITLE
Unable to trigger radio station playback via script (.play.media)

### ISSUE THREAD

**Issue by borez** [music-assistant/hass-music-assistant#1105]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

Am getting a problem where triggering a TuneIn radio station playback (via a script) does not work, to a Google Home device.

On GUI basis it shows:
Failed to call service script/dad_gh_958. 'NoneType' object has no attribute 'url'

Triggering radio station playback via the MA add-on works perfectly. To highlight, my Google Home devices are on a different subnet, but have forwarded port 8095. Home Assistant installation also has the right internal URL.

### How to reproduce

Script output is as follows:

```
service: media_player.play_media
target:
  entity_id: media_player.yin_le
data:
  media_content_id: media-source://mass/database://radio/1
  media_content_type: audio/flac
metadata:
  title: Capital 95.8 FM
  thumbnail: >-
    https://images.weserv.nl/?w=200&url=http://cdn-profiles.tunein.com/s24959/images/logoq.png
  media_class: music
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://mass
    - media_content_type: music
      media_content_id: media-source://mass/radio
```

### Relevant log output

```
`2023-02-25 11:49:17.460 DEBUG (MainThread) [music_assistant.event] queue_items_updated media_player.yin_le
2023-02-25 11:49:17.470 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.yin_le
2023-02-25 11:49:17.501 ERROR (MainThread) [homeassistant.components.script.dad_gh_958] Dad-GH-958: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'url'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 644, in async_play_media
    sourced_media = await media_source.async_resolve_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 155, in async_resolve_media
    return await item.async_resolve()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 83, in async_resolve
    return await self.async_media_source().async_resolve_media(self)
  File "/config/custom_components/mass/media_source.py", line 118, in async_resolve_media
    return PlayMedia(player.active_queue.stream.url, f"audio/{content_type}")
AttributeError: 'NoneType' object has no attribute 'url'
2023-02-25 11:49:17.511 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472665912800] 'NoneType' object has no attribute 'url'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 472, in _service_handler
    await self.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 431, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 461, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 644, in async_play_media
    sourced_media = await media_source.async_resolve_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 155, in async_resolve_media
    return await item.async_resolve()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 83, in async_resolve
    return await self.async_media_source().async_resolve_media(self)
  File "/config/custom_components/mass/media_source.py", line 118, in async_resolve_media
    return PlayMedia(player.active_queue.stream.url, f"audio/{content_type}")
AttributeError: 'NoneType' object has no attribute 'url'
2023-02-25 11:49:22.371 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"`
```

### What version of Home Assistant Core are your running

2023.3.5

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please refer to the first paragraph of the troubleshooting document https://github.com/music-assistant/hass-music-assistant/discussions/709

**Comment by borez** [comment]
> Please refer to the first paragraph of the troubleshooting document #709

Thanks for getting back! I did go through the FAQ and believe port forwarding + internal IP is configured properly. As mentioned, sending the radio stream directly through MA works (after enabling a port forward rule). Turning off the port forward rule breaks functionality.

Have attached debug logs when playing a stream directly via MA):

```
2023-02-25 11:29:31.969 DEBUG (MainThread) [music_assistant.stream] Got GET request to /4308ad52e24b41b0bfbcace58a548550.flac from 192.168.3.192
headers: <CIMultiDictProxy('Host': '192.168.2.100:8095', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.225 Safari/537.36 CrKey/1.56.500000 DeviceType/SmartSpeaker', 'Range': 'bytes=0-', 'Accept-Encoding': 'identity;q=1, *;q=0', 'Accept': '*/*', 'CAST-DEVICE-CAPABILITIES': '{"audio_assistant":true,"bluetooth_supported":true,"display_supported":false,"hi_res_audio_supported":false,"remote_control_input_supported":false,"touch_input_supported":false}', 'Accept-Language': 'en-US,en;q=0.9')>

2023-02-25 11:29:31.971 DEBUG (MainThread) [music_assistant.players.stream] client connected: 192.168.3.192
2023-02-25 11:29:31.972 DEBUG (MainThread) [music_assistant.players.stream] 1 clients connected
2023-02-25 11:29:32.932 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.yin_le
2023-02-25 11:29:32.935 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.yin_le
2023-02-25 11:29:32.939 DEBUG (MainThread) [music_assistant.event] player_updated media_player.yin_le
2023-02-25 11:29:33.638 DEBUG (MainThread) [music_assistant.players.stream] Starting Queue audio stream for Queue 音乐 (PCM format: s16le - sample rate: 44100)
2023-02-25 11:29:33.639 INFO (MainThread) [music_assistant.players.stream] Start Streaming queue track: tunein://radio/s24959 (Capital 95.8 FM) for queue 音乐 - crossfade: False
2023-02-25 11:29:33.639 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.yin_le
2023-02-25 11:29:33.720 DEBUG (MainThread) [music_assistant.helpers.audio] start media stream for: tunein://radio/s24959
2023-02-25 11:29:33.721 DEBUG (MainThread) [music_assistant.helpers.audio] writer started for tunein://radio/s24959
2023-02-25 11:29:36.265 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.yin_le
2023-02-25 11:29:36.506 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.yin_le
2023-02-25 11:29:36.507 DEBUG (MainThread) [music_assistant.event] player_updated media_player.yin_le
2023-02-25 11:29:36.535 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.yin_le
2023-02-25 11:29:36.536 DEBUG (MainThread) [music_assistant.event] player_updated media_player.yin_le
2023-02-25 11:29:36.542 DEBUG (MainThread) [music_assistant.players.stream] client disconnected: 192.168.3.192
2023-02-25 11:29:36.575 DEBUG (MainThread) [music_assistant.stream] Got GET request to /c0d3c7a0327b4c22a4d423016f127782.flac from 192.168.3.192
headers: <CIMultiDictProxy('Host': '192.168.2.100:8095', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.225 Safari/537.36 CrKey/1.56.500000 DeviceType/SmartSpeaker', 'Range': 'bytes=0-', 'Accept-Encoding': 'identity;q=1, *;q=0', 'Accept': '*/*', 'CAST-DEVICE-CAPABILITIES': '{"audio_assistant":true,"bluetooth_supported":true,"display_supported":false,"hi_res_audio_supported":false,"remote_control_input_supported":false,"touch_input_supported":false}', 'Accept-Language': 'en-US,en;q=0.9')>

2023-02-25 11:29:36.578 DEBUG (MainThread) [music_assistant.players.stream] client connected: 192.168.3.192
2023-02-25 11:29:36.586 DEBUG (MainThread) [music_assistant.players.stream] 1 clients connected
2023-02-25 11:29:37.092 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.yin_le
2023-02-25 11:29:37.093 DEBUG (MainThread) [music_assistant.event] player_updated media_player.yin_le
2023-02-25 11:29:41.554 DEBUG (MainThread) [music_assistant.helpers.audio] media stream aborted for: tunein://radio/s24959
2023-02-25 11:29:44.178 DEBUG (MainThread) [music_assistant.players.stream] Stream job 4308ad52e24b41b0bfbcace58a548550 cleaned up
```

**Comment by borez** [comment]
Another update - tried using the mass.queue_command service and this worked perfectly.
```

service: mass.queue_command
data:
  command: play_media
  uri: http://22893.live.streamtheworld.com/LOVE972FM_PREM.aac
  enqueue_mode: play
  radio_mode: false
target:
  entity_id: media_player.yin_le
```

**Comment by OzGav** [comment]
suggest you rewrite your script using mass queue command.

**Comment by borez** [comment]
Thanks, have done so. Will leave the mods to decide if this issue should be closed.
