### ISSUE TITLE
Unable to remove integration

### ISSUE THREAD

**Issue by qp68** [music-assistant/hass-music-assistant#1106]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

Since MA won't be updated anymore, I tried to remove it from my HA integrations but nothing happens. I tried with integration activated and not, same result.

### How to reproduce

Update to HA 2023.3.0b3, try to remove the integration from Integrations>MA>3 dots>Delete

### Relevant log output

```
Logger: aiohttp.server
Source: custom_components/mass/__init__.py:22
Integration: Music Assistant (documentation, issues)
First occurred: 20:45:44 (1 occurrences)
Last logged: 20:45:44

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 86, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1071, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 570, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/mass/__init__.py", line 22, in <module>
    from music_assistant import MusicAssistant
ModuleNotFoundError: No module named 'music_assistant'

```

### What version of Home Assistant Core are your running

2023.3.0b3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Did you try to remove it from HACS as well?

**Comment by qp68** [comment]
Yes, I get an error saying that the integration is configured and must be deleted from HA first.

**Comment by OzGav** [comment]
Try downgrading to 2023.2.x

**Comment by Tribble329** [comment]
I'm having the same problem. Did you find solution?

**Comment by DanielOrneling** [comment]
Same issue here. Now I´m on 2023.03.0 but a downgrade wouldn´t help as I have had this problem for several earlier versions of HA as well.
Anyone who has an idea of how to get rid of this integration?

**Comment by OzGav** [comment]
You will need to manually remove 
![BEBC3BDC-D6AA-4052-8411-E7CB2E86EBC0](https://user-images.githubusercontent.com/19848947/222384257-90862f80-0b56-4f0e-9d61-47bfce449ef5.jpeg)

**Comment by bjornidar** [comment]
> You will need to manually remove ![BEBC3BDC-D6AA-4052-8411-E7CB2E86EBC0](https://user-images.githubusercontent.com/19848947/222384257-90862f80-0b56-4f0e-9d61-47bfce449ef5.jpeg)

The entry in config_entries is re-added to the file during reboot and prevent removal of the integration. Any tips?

**Comment by OzGav** [comment]
> > You will need to manually remove
> 
> The entry in config_entries is re-added to the file during reboot and prevent removal of the integration. Any tips?

I can't recreate it so I am not sure. Try manually removing it and then see if you can remove MA from HACS before rebooting HA?

**Comment by mfabiani53** [comment]
I followed the instructions to remove the mass entries in the file "core.config_entries" and was able to delete the integration from HA and from HACS, but now i have all the mass media players created unavailable and they are impossible to delete.
How to remove them?

![Schermata 2023-03-08 alle 17 14 36](https://user-images.githubusercontent.com/37701688/223768077-0e95fe02-d8ad-462f-860c-fd154998312a.png)

**Comment by OzGav** [comment]
See if anything here helps https://www.google.com/search?q=hassio+how+to+remove+unavailable+entity

**Comment by matusk** [comment]
I was successful with this steps:

1. remove Music Assistant block from `core.config_entries`
2. force remove Music Assistant from HACS
3. restart HA

After the reboot, the integration is removed and all devices and entities are removed as well.
