### ISSUE TITLE
[2b6] Port 3483 already in use

### ISSUE THREAD

**Issue by cociweb** [music-assistant/hass-music-assistant#1148]
### What version of Music Assistant has the issue?

2.0.0b6

### The problem

error discovered in the logs:

2023-03-15 23:13:24 INFO  music_assistant.providers.slimproto  -- Starting SLIMProto server on port 3483
2023-03-15 23:13:24 ERROR music_assistant  -- Error loading provider(instance) Slimproto: [Errno 98] error while attempting to bind on address ('0.0.0.0', 3483): address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 351, in load_provider
    raise err
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 347, in load_provider
    await provider.setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/slimproto/__init__.py", line 99, in setup
    await asyncio.start_server(self._create_client, "0.0.0.0", slimproto_port),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 85, in start_server
    return await loop.create_server(factory, host, port, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 3483): address already in use

### How to reproduce

Add slimproto (https://www.home-assistant.io/integrations/slimproto) integration to HA.

### Relevant log output

*see above

### What version of Home Assistant Core are your running

2023.03.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Please refer to here https://github.com/music-assistant/hass-music-assistant/discussions/1123
