### ISSUE TITLE
Version conflict error when installing Music Assistant in Home Assistant

### ISSUE THREAD

**Issue by tabano86** [music-assistant/hass-music-assistant#1149]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

When trying to install Music Assistant in Home Assistant version 2023.3.2, a version conflict error is encountered. Other version attempted without success are 2022.12.1, 2023.2.0, and 2023.2.1. 

Home Assistant 2023.3.2
Frontend 20230306.0 - latest

### How to reproduce

1. Go to the HACS panel in Home Assistant and select "Integrations" from the menu.
2. In the search bar, type "Music Assistant" and press Enter. The Music Assistant integration should appear in the search results.
3. Click the "Download this repository with HACS" button next to the Music Assistant integration.
4. Once the download is complete, restart Home Assistant.
5. After restarting, go to the Configuration menu in Home Assistant and select "Integrations".
6. Click the big "+" button to add a new integration.
7. In the search bar, type "Music Assistant" and press Enter. The Music Assistant integration should appear in the search results.
8. Click the Music Assistant integration to add it.
9. Follow the prompts to configure the integration and start using Music Assistant in Home Assistant.

Issue seems related to "mass" manifest json ( "music-assistant>=1.8.7.4"):

`{
  "domain": "mass",
  "name": "Music Assistant",
  "version": "2023.2.1",
  "documentation": "https://github.com/music-assistant/hass-music-assistant",
  "issue_tracker": "https://github.com/music-assistant/hass-music-assistant/issues",
  "requirements": [
    "music-assistant>=1.8.7.4"
  ],
  "codeowners": [
    "@marcelveldt"
  ],
  "dependencies": [
    "http>=0.0.0",
    "panel_custom>=0.0.0"
  ],
  "after_dependencies": [
    "media_source", "media_player", "cast", "group"
  ],
  "config_flow": true,
  "iot_class": "local_push",
  "loggers": ["music_assistant"]
}
`

### Relevant log output

2023-03-16 07:19:28.714 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

2023-03-16 07:19:28.716 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 831, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 849, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 955, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 385, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 290, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for mass not found: ['music-assistant==1.8.7.4'].

### Additional information

**OS:** https://blog.hypriot.com/
**Image:**  image: "ghcr.io/home-assistant/home-assistant:stable"

![image](https://user-images.githubusercontent.com/13357245/225545553-60b1bdb2-233c-4077-97a8-4104e6a5eea9.png)

docker-compose.yml for home assistant
`version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/pirate/home-assistant:/config
      - /home/pirate/home-assistant/custom_components:/config/custom_components
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host`

### What version of Home Assistant Core are your running

2023.3.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
https://github.com/music-assistant/hass-music-assistant/issues/1143

**Comment by marcelveldt** [comment]
![Scherm­afbeelding 2023-03-16 om 08 47 49](https://user-images.githubusercontent.com/6389780/225549348-70e280e2-d516-4820-8dc1-0b2d86a18b14.png)

You didn't see that big fat warning next to the button where you submitted the issue ? :-)
