### ISSUE TITLE
Cannot connect to SMB share 

### ISSUE THREAD

**Issue by Jacco192** [music-assistant/hass-music-assistant#1164]
### What version of Music Assistant has the issue?

2.0.0b16

### The problem

with MA 2.0.0b16 unable to connect anymore to SMB share on N-3865 Combo384 Amanero Media Renderer. 

### How to reproduce

Restart MA

### Relevant log output

File "/usr/local/lib/python3.11/site-packages/smbprotocol/connection.py", line 1177, in _check_worker_running
    raise SMBConnectionClosed("SMB socket was closed, cannot send or receive any more data")
smbprotocol.exceptions.SMBConnectionClosed: SMB socket was closed, cannot send or receive any more data
2023-03-26 11:05:22 INFO  music_assistant.metadata  -- Start scan for missing artist metadata
2023-03-26 11:05:22 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-922' coro=<FileSystemProviderBase.sync_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py:258> exception=SMBAuthenticationError('Failed to authenticate with server: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/smbprotocol/session.py", line 286, in connect
    out_token = context.step(in_token)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/spnego/_negotiate.py", line 141, in step
    mech_token_in, mech_list_mic, is_spnego = self._step_spnego_input(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/spnego/_negotiate.py", line 192, in _step_spnego_input
    mech_list = self._rebuild_context_list(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/spnego/_negotiate.py", line 462, in _rebuild_context_list
    raise BadMechanismError(context_msg="Unable to negotiate common mechanism", base_error=last_err)
spnego.exceptions.BadMechanismError: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 270, in sync_library
    async for item in self.listdir("", recursive=True):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 172, in listdir
    for entry in await asyncio.to_thread(smbclient.scandir, abs_path):
  File "/usr/local/lib/python3.11/site-packages/smbclient/_os.py", line 545, in scandir
    with SMBDirectoryIO(path, share_access="rwd", **kwargs) as fd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/smbclient/_io.py", line 353, in __init__
    tree, fd_path = get_smb_tree(path, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/smbclient/_pool.py", line 304, in get_smb_tree
    session = register_session(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/smbclient/_pool.py", line 422, in register_session
    session.connect()
  File "/usr/local/lib/python3.11/site-packages/smbprotocol/session.py", line 288, in connect
    raise SMBAuthenticationError("Failed to authenticate with server: %s" % str(err.message))
smbprotocol.exceptions.SMBAuthenticationError: Failed to authenticate with server: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism
2023-03-26 11:05:22 INFO  music_assistant.metadata  -- Finished scan for missing artist metadata

### What version of Home Assistant Core are your running

2023.3.6

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
1) make sure that your NAS or whatever server you connect to supports minimal SMBv2 (smbv1 is not supported anymore)
2) authentication is required, so a valid username and password

**Comment by OzGav** [comment]
Hi @Jacco192 have you got this working now?

**Comment by Jacco192** [comment]
Hi,
No, I didn’t.  Not able to modify username  or password, this is set by Melco to nobody. 

future: <Task finished name='Task-374' coro=<FileSystemProviderBase.sync_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py:258> exception=SMBConnectionClosed('SMB socket was closed, cannot send or receive any more data')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 270, in sync_library
    async for item in self.listdir("", recursive=True):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 210, in listdir
    async for subitem in self.listdir(item.absolute_path, True):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 207, in listdir
    item = await create_item(self._root_path, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 139, in create_item
    return await asyncio.to_thread(_create_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 127, in _create_item


Sent from Mail for Windows

**Comment by Jacco192** [comment]
I'm running Melco firmware 4.32. See https://www.audiotherapyuk.com/2019/01/03/melco-release-3-90-firmware/

**Comment by OzGav** [comment]
Looks to be a different error message now. @marcelveldt ?

**Comment by marcelveldt** [comment]
Looks like your device does not support the authentication and/or is still running SMBv1. 
Does it have some settings for you to configure ?

**Comment by marcelveldt** [comment]
https://github.com/jborean93/smbprotocol/issues/88

**Comment by marcelveldt** [comment]
Ah that's too bad, SMBv1 is really old and crappy. Can't you complain with the manufacturer ?
Maybe you can swap it and let that device connect to HA to access the files ?

**Comment by Jacco192** [comment]
Share maps to HA, I've already looked into it but that didn't make me very happy. I'm going to see what can be done. I was so happy with the first releases :-)

**Comment by marcelveldt** [comment]
A lot of users had issues with the old SMB implementation based on pysmb so I swapped to a newer library with SMBv2/3 support. As you can read there is not a lot of interest to still support SMBv1 but what I could so if there are others too that have this issue is place the old implementation back under a legacy toggle for now. 

So you can switch to legacy SMBv1 if really needed

**Comment by Jacco192** [comment]
Yes, that would be nice. Then it's my own security issue, what was it 1984 ?

**Comment by Jacco192** [comment]
Dropped the SMB question at Melco

**Comment by Jacco192** [comment]
That’s okOn Mar 30, 2023, at 4:09 PM, OzGav ***@***.***> wrote:﻿
@Jacco192 as this is not something MA can resolve I am inclined to close unless if you anything further?
