### ISSUE TITLE
Issue installing Docker Image on another machine to HA

### ISSUE THREAD

**Issue by millie75** [music-assistant/hass-music-assistant#1172]
### What version of Music Assistant has the issue?

Beta

### The problem

I am trying to install the beta docker on another machine that I have Docker installed on (so completely separate to HA which is in a container on a proxmox) and get the below after running

docker run --network host ghcr.io/music-assistant/server:2.0.0b4 

Traceback (most recent call last):
  File "/usr/local/bin/mass", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 82, in main
    mass = MusicAssistant(data_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 64, in __init__
    self.zeroconf = Zeroconf(interfaces=InterfaceChoice.All)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 450, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 373, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 288, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available

There is plenty of space on the hdd

Thanks

### How to reproduce

docker run --network host ghcr.io/music-assistant/server:2.0.0b4 

### What version of Home Assistant Core are your running

2022.3.6

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
we are up to beta 22 now so Ithink you need docker run --network host ghcr.io/music-assistant/server:2.0.0b22

**Comment by OzGav** [comment]
yes it can

**Comment by millie75** [comment]
Just tried on another machine and all working - thanks again

**Comment by Maximus48p** [comment]
Having similar issue with docker-compose

```
services:
  music-assistant-server:
    container_name: music-assistant-server
    hostname: musicserver
    network_mode: host
    ports:
      - 8095:8095
    image: ghcr.io/music-assistant/server
    volumes:
      - /share/..../musicassserver/media:/media
      - /share/..../musicassserver/data:/data
```

error message:

```
2023-07-19 13:01:42.769 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> exception=OSError(105, 'No buffer space available')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 237, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 176, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 102, in start
    self.zeroconf = Zeroconf(interfaces=InterfaceChoice.All)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 493, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 373, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 288, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
```

**Comment by OzGav** [comment]
This isn’t a MA problem. Suggest you Google “ OSError: [Errno 105] No buffer space available docker”
