### ISSUE TITLE
Asyncio timeout error when resuming a stream

### ISSUE THREAD

**Issue by gieljnssns** [music-assistant/hass-music-assistant#1179]
### What version of Music Assistant has the issue?

v2.0.0b27

### The problem

When I try to resume a stoped stream (the day after).
This is a tunein stream https://tunein.com/radio/KINK-Distortion-s276282/

When I go to my radio stations and click back on the same station music starts playing. 

### How to reproduce

Pause the stream 
Press on play the next day

### Relevant log output

```
2023-04-07 09:21:19 WARNING music_assistant.websocket_api  -- [140707156124496] Disconnected: Received non-Text message.
2023-04-07 09:23:17 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-113549' coro=<StreamJob._stream_job_runner() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py:146> exception=TimeoutError() created at /usr/local/lib/python3.11/asyncio/tasks.py:374>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/mass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 108, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 273, in run
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 234, in _run_handler
    result = await result
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 373, in play_pause
    await self.play(queue_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 350, in play
    await self.resume(queue_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 454, in resume
    await self.play_index(queue_id, resume_item.queue_item_id, resume_pos, fade_in)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 484, in play_index
    await player_prov.cmd_play_media(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 289, in cmd_play_media
    url = await self.mass.streams.resolve_stream_url(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 282, in resolve_stream_url
    stream_job.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 173, in start
    self._audio_task = asyncio.create_task(self._stream_job_runner())
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 374, in create_task
    task = loop.create_task(coro)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/process.py", line 98, in readexactly
    return await self._proc.stdout.readexactly(n)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 728, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 522, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 149, in _stream_job_runner
    async for chunk in self.audio_source:
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 437, in get_media_stream
    async for chunk in ffmpeg_proc.iter_chunked(chunk_size):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/process.py", line 79, in iter_chunked
    chunk = await self.readexactly(n)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/process.py", line 97, in readexactly
    async with asyncio.timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 98, in __aexit__
    raise TimeoutError
TimeoutError
```

### What version of Home Assistant Core are your running

2023.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Not sure but this might be impossible if it is trying to resume the radio station from the day before…? See what @marcelveldt  says

**Comment by gieljnssns** [comment]
I think this one is solved...
