### ISSUE TITLE
Music assistant cannot connect to my two dlna device （two sony bravia tvs）

### ISSUE THREAD

**Issue by SikaiGGMU** [music-assistant/hass-music-assistant#1183]
### What version of Music Assistant has the issue?

 2.0.0b4

### The problem

the log is as follows:

2023-04-08 12:53:24 WARNING pychromecast.dial  -- Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='Livingroom._googlecast._tcp.local.')})
2023-04-08 12:53:24 WARNING pychromecast.dial  -- Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='Livingroom._googlecast._tcp.local.')})
2023-04-08 12:53:24 WARNING pychromecast.dial  -- Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='BRAVIA4KVH21-54._googlecast._tcp.local.')})
2023-04-08 12:53:24 ERROR pychromecast.socket_client  -- [Livingroom(192.168.3.5):8009] Failed to connect to service ServiceInfo(type='mdns', data='Livingroom._googlecast._tcp.local.'), retrying in 5.0s
2023-04-08 12:53:24 WARNING pychromecast.dial  -- Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='BRAVIA4KVH21-54._googlecast._tcp.local.')})
2023-04-08 12:53:24 ERROR pychromecast.socket_client  -- [BRAVIA4KVH21-54(192.168.3.54):8009] Failed to connect to service ServiceInfo(type='mdns', data='BRAVIA4KVH21-54._googlecast._tcp.local.'), retrying in 5.0s

Both of the dlna digital media renderer integrations works well in my home assistant. P.S. , the the google cast integrations do not work, but I do not care it since the dlna digital media renderer integrations work properly.

### How to reproduce

Always

### Relevant log output

2023-04-08 12:53:24 WARNING pychromecast.dial  -- Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='Livingroom._googlecast._tcp.local.')})
2023-04-08 12:53:24 WARNING pychromecast.dial  -- Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='Livingroom._googlecast._tcp.local.')})
2023-04-08 12:53:24 WARNING pychromecast.dial  -- Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='BRAVIA4KVH21-54._googlecast._tcp.local.')})
2023-04-08 12:53:24 ERROR pychromecast.socket_client  -- [Livingroom(192.168.3.5):8009] Failed to connect to service ServiceInfo(type='mdns', data='Livingroom._googlecast._tcp.local.'), retrying in 5.0s
2023-04-08 12:53:24 WARNING pychromecast.dial  -- Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='BRAVIA4KVH21-54._googlecast._tcp.local.')})
2023-04-08 12:53:24 ERROR pychromecast.socket_client  -- [BRAVIA4KVH21-54(192.168.3.54):8009] Failed to connect to service ServiceInfo(type='mdns', data='BRAVIA4KVH21-54._googlecast._tcp.local.'), retrying in 5.0s

### What version of Home Assistant Core are your running

2023.4.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Start by upgrading via a fresh install to b27

**Comment by OzGav** [comment]
This will closed soon unless this is still confirmed to be an issue on b29+

**Comment by SikaiGGMU** [comment]
unfortunately, the issue is still there on 2.0.0b29

**Comment by OzGav** [comment]
I'm not hopeful but please try on 2.0.0b30

**Comment by OzGav** [comment]
@SikaiGGMU Please try with beta32 or above. We will close this soon if there is no follow up. Thanks

**Comment by marcelveldt** [comment]
There is very little information provided to actually provide support. Also the log lines are from the cast provided so irrelevant to this issue.

Are the players detected by Music Assistant and then not able to be used or not detected at all ?

Is Music Assistant on the same subnet as the TV's ?

Do you need to do anything special (e.g. manual configuration) to make these players work in Home Assistant ?

As Music Assistant uses the same underlying libraries as Home Assistant it should theoretically work.

**Comment by SikaiGGMU** [comment]
2023-05-29 22:23:15 DEBUG music_assistant.providers.chromecast.Livingroom  -- Received connection status update - status: CONNECTING
2023-05-29 22:23:15 DEBUG music_assistant.providers.chromecast.Livingroom  -- Received connection status update - status: FAILED
2023-05-29 22:23:17 DEBUG pychromecast.discovery  -- add_service _googlecast._tcp.local., BRAVIA4KVH21-54._googlecast._tcp.local.
2023-05-29 22:23:17 DEBUG music_assistant.providers.chromecast  -- Discovered new or updated chromecast CastInfo(services={ServiceInfo(type='mdns', data='BRAVIA4KVH21-54._googlecast._tcp.local.')}, uuid=UUID('8598bed9-96b3-4730-9df7-efdfc92cf244'), model_name='AirReceiver', friendly_name='BRAVIA4KVH21-54', host='192.168.3.54', port=8009, cast_type=None, manufacturer=None)
2023-05-29 22:23:21 DEBUG music_assistant.providers.chromecast.BRAVIA4KVH21-54  -- Received connection status update - status: CONNECTING
2023-05-29 22:23:21 DEBUG music_assistant.providers.chromecast.BRAVIA4KVH21-54  -- Received connection status update - status: FAILED
2023-05-29 22:23:25 DEBUG music_assistant.providers.chromecast.Livingroom  -- Received connection status update - status: CONNECTING
2023-05-29 22:23:25 DEBUG music_assistant.providers.chromecast.Livingroom  -- Received connection status update - status: FAILED
2023-05-29 22:23:36 DEBUG music_assistant.providers.dlna  -- Connecting to device at http://192.168.3.54:37911/upnp/dev/12671003-98ce-4e9e-8993-cba130471a4c/desc
2023-05-29 22:23:36 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-167' coro=<DLNAPlayerProvider._run_discovery.<locals>.on_response() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:373> exception=UpnpConnectionError('ClientConnectorError(ConnectionKey(host=\'192.168.3.54\', port=37911, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed (\'192.168.3.54\', 37911)"))', None) created at /usr/local/lib/python3.11/site-packages/async_upnp_client/search.py:108>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/mass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 108, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 273, in run
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1169, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
File "/usr/local/lib/python3.11/site-packages/async_upnp_client/search.py", line 108, in _on_data
    self.loop.create_task(coro)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.3.54', 37911)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/aiohttp.py", line 170, in async_http_request
    return await self._async_http_request(method, url, headers, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/aiohttp.py", line 204, in _async_http_request
    async with self._session.request(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.3.54:37911 ssl:default [Connect call failed ('192.168.3.54', 37911)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 394, in on_response
    await self._device_discovered(ssdp_udn, discovery_info["location"])
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 468, in _device_discovered
    await self._device_connect(dlna_player)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 483, in _device_connect
    upnp_device = await self.upnp_factory.async_create_device(dlna_player.description_url)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/client_factory.py", line 72, in async_create_device
    root_el = await self._async_get(description_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/client_factory.py", line 394, in _async_get
    ) = await self.requester.async_http_request("GET", url)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/async_upnp_client/aiohttp.py", line 172, in async_http_request
    raise UpnpConnectionError(repr(err)) from err
async_upnp_client.exceptions.UpnpConnectionError: ('ClientConnectorError(ConnectionKey(host=\'192.168.3.54\', port=37911, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed (\'192.168.3.54\', 37911)"))', None)
2023-05-29 22:23:41 DEBUG music_assistant.providers.chromecast.BRAVIA4KVH21-54  -- Received connection status update - status: CONNECTING
2023-05-29 22:23:41 DEBUG music_assistant.providers.chromecast.BRAVIA4KVH21-54  -- Received connection status update - status: FAILED
2023-05-29 22:23:45 DEBUG music_assistant.providers.chromecast.Livingroom  -- Received connection status update - status: CONNECTING
2023-05-29 22:23:45 DEBUG music_assistant.providers.chromecast.Livingroom  -- Received connection status update - status: FAILED

**Comment by SikaiGGMU** [comment]
New logs.

Yes, my music assistant host machine (192.168.3.41/24) is in the same subnet with my two sony TVs (192.168.3.5/24, 192.168.3.54/24, respectively).

I am afraid the failure has nothing to do with music assistant, since both of my sony TVS are in special firmware (customised firmware in China). Most of the google stuffs are absent in the firmware; however, both of them work well as a dlna render, since I can cast my film collections (.mkv, .mp4) from my local minidlna server to both of TVs.

Furthermore, I installed Kodi in my two Sony Bravia TVs, the Kodi integration in my homeassistant work good as well, I can play local music on the Kodi devices, I can do the above minidlna stuff, and I can play homeassistant tts on them. But I just can't play music with music assistant add-on on neither of them.

**Comment by SikaiGGMU** [comment]
Logs concerning the Kodi stuff are as follows:
2023-05-29 22:36:46 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:36:46 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:36:46 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:36:46 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:36:46 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:36:46 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:36:47 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:36:52 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:36:52 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:36:52 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:36:52 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:02 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:02 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:02 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:02 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:02 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:02 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:02 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:02 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:02 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:02 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:04 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:02 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:02 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:04 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:04 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:04 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:04 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:04 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:04 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:06 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:06 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:06 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:06 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:08 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:08 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:09 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:09 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:09 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:09 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:14 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:14 DEBUG music_assistant.providers.dlna  -- Received event for Player Kodi (192.168.3.5): <UpnpService(urn:upnp-org:serviceId:AVTransport, uuid:39af78e3-08bf-923c-fdff-7b02ec320843)>
2023-05-29 22:37:14 DEBUG music_assistant.event  -- queue_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843
2023-05-29 22:37:14 DEBUG music_assistant.event  -- player_updated uuid:39af78e3-08bf-923c-fdff-7b02ec320843

**Comment by marcelveldt** [comment]
Please answer all the questions we asked before, you answered the question about the network but these are left unanswered:

Are the players detected by Music Assistant and then not able to be used or not detected at all ?

Is Music Assistant on the same subnet as the TV's ?

Do you need to do anything special (e.g. manual configuration) to make these players work in Home Assistant ?

**Comment by SikaiGGMU** [comment]
Hi, thank you for your reoply.
Are the players detected by Music Assistant and then not able to be used or not detected at all ?

Those players (including Kodi players) are detected by MA, and they are not able to be used.

Is Music Assistant on the same subnet as the TV's ?
The host machine is on the same subnet as the TVs'.  Since MA is deloyed in docker, and therefore MA per se is not on the same subnet as the TVs'.

Do you need to do anything special (e.g. manual configuration) to make these players work in Home Assistant ?

No.  Those players are automatically detected by HA. 
For  Kodi players, I must first open the Kodi App.

**Comment by marcelveldt** [comment]
What do you mean with "not able to be used" ?
What does work and what not ?

If only playback is failing, you could try to set another output codec in the player settings.
Maybe Sony Bravia does not support flac and you need to set it to e.g. Mp3.

**Comment by OzGav** [comment]
@SikaiGGMU have you tried Marcel’s suggestion? Also please respond with the details he has requested.

**Comment by OzGav** [comment]
Closing pending further information
