### ISSUE TITLE
B27: Error in log when en/dis-abling an unavailable player

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1185]
### What version of Music Assistant has the issue?

2B27

### The problem

When I either enable or disable a player that is not available, I see an error in the log. Seen this for both chromecast and slimproto players.

### How to reproduce

Select a player that is not available. Change the enabled status. Check the log.

### Relevant log output

``` 
2023-04-08 15:43:30 ERROR music_assistant.websocket_api  -- [548033048016] Error handling message: CommandMessage(message_id=10, command='config/players/update', args={'player_id': '3c:ed:d3:ac:21:b3', 'update': {'enabled': False}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 219, in _run_handler
    result = handler.target(**args)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 296, in update_player_config
    player.enabled = config.enabled
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'enabled'
``` 

### What version of Home Assistant Core are your running

2023.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Just trying this on B29 and I can't recreate it with a picoreplayer. I pulled the power from it. disabled, enabled. Plugged it back in. Disabled and enabled. And nothing appeared in the log during any of that.

**Comment by erkr** [comment]
I'll check it

**Comment by OzGav** [comment]
I just tried with a Google home and didn’t see any errors. Just the lost connection and reconnection info messages as I unplugged and replugged it?

**Comment by erkr** [comment]
Very important is that the player that tot enable/disable must be unavailable

**Comment by OzGav** [comment]
I just tried with my picoreplayer. I had the unavailable symbol and then disabled it and the icon changed to the disabled icon but no errors logged. I enabled it again and the icon changed to an hour glass but still no error in the logs. So I'm trying hard but I can't reproduce that here.

**Comment by erkr** [comment]
Thanks for trying 👍 I don't know. It reproduces easily here, let's see if Marcel can reproduce.

**Comment by OzGav** [comment]
@erkr are you still seeing this in B36?

**Comment by erkr** [comment]
Now it only reproduced for Chromcast player (disabled while unavailable):

``` 

2023-06-10 14:55:09 ERROR music_assistant.websocket_api  -- [548167644048] Error handling message: CommandMessage(message_id=9, command='config/players/save', args={'player_id': 'ca2fe19d-8458-f206-e7ef-0d9595071ba2', 'values': {'enabled': False}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 237, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 369, in save_player_config
    provider.on_player_config_changed(config, changed_keys)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/__init__.py", line 176, in on_player_config_changed
    self.mass.create_task(self.mass.config.reload_provider, self.instance_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 282, in create_task
    task = self.loop.create_task(target(*args, **kwargs))
                                 ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigController.reload_provider() missing 1 required positional argument: 'config'
```

**Comment by OzGav** [comment]
OK yes I am seeing that now. Confirmed! Adding to the backlog!
