### ISSUE TITLE
WMA audio file scan results in an error in the log

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1205]
### What version of Music Assistant has the issue?

2B29

### The problem

Looks like during the directory scan of the SMB provider an error is thrown when some WMA files are enountered. Error message is that it is not an audio file when it is.

### How to reproduce

Place a WMA audio file in your music directory. Start MA.

### Relevant log output

```
2023-04-02 17:25:23 ERROR music_assistant.providers.filesystem_smb  -- Error processing Anthony Warlow/Doctor Zhivago/02 On The Edge Of Time.wma - Unable to retrieve info for /tmp/filesystem_smb/Anthony Warlow/Doctor Zhivago/02 On The Edge Of Time.wma: Not an audio file
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 347, in parse_tags
    raise InvalidDataError("Not an audio file")
music_assistant.common.models.errors.InvalidDataError: Not an audio file
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 319, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 590, in _parse_track
    tags = await parse_tags(input_file, file_item.file_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 356, in parse_tags
    raise InvalidDataError(f"Unable to retrieve info for {file_path}: {str(err)}") from err
music_assistant.common.models.errors.InvalidDataError: Unable to retrieve info for /tmp/filesystem_smb/Anthony Warlow/Doctor Zhivago/02 On The Edge Of Time.wma: Not an audio file
```

### What version of Home Assistant Core are your running

2023.4.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
wma files working in beta 30
