### ISSUE TITLE
Raspiaudio Muse Proto Not working as playback device

### ISSUE THREAD

**Issue by darrenblanchard** [music-assistant/hass-music-assistant#1209]
### What version of Music Assistant has the issue?

2.0.0b29

### The problem

The playback device works under HA media playback but not MA Beta,  With  esp-wrover-kit flashed to it. Not interested in Squeesbox because i was to use with voice control as well

### How to reproduce

you can listen through local media browse in HA but not listed in MA Beta

### What version of Home Assistant Core are your running

2023.4.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by SeByDocKy** [comment]
The deluxe model too is not recognized ....

```2023-04-23 19:55:23 INFO  music_assistant  -- Starting Music Assistant Server (33b5f9774b554495b4c855e6aab87ca7) - autodetected IP-address: 192.168.1.2
2023-04-23 19:55:24 INFO  music_assistant.web  -- Starting webserver on port 8095
2023-04-23 19:55:25 INFO  music_assistant.streams  -- Started stream controller (using ffmpeg version 4.3.5 with libsoxr support)
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded player provider UPnP/DLNA Player provider
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded metadata provider TheAudioDB Metadata provider
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded metadata provider fanart.tv Metadata provider
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded player provider SONOS
2023-04-23 19:55:26 INFO  music_assistant.providers.lms_cli  -- Registering jsonrpc endpoints on the webserver
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded plugin provider Websocket API
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded music provider URL
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded metadata provider MusicBrainz Metadata provider
2023-04-23 19:55:26 INFO  music_assistant.providers.lms_cli  -- Starting (telnet) CLI on port 9090
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded player provider Chromecast
2023-04-23 19:55:26 INFO  music_assistant  -- Loaded plugin provider LMS CLI
2023-04-23 19:55:27 INFO  music_assistant.providers.slimproto  -- Starting SLIMProto server on port 3483
2023-04-23 19:55:27 INFO  music_assistant  -- Loaded player provider Slimproto
2023-04-23 19:55:28 INFO  music_assistant  -- Loaded player provider Airplay
2023-04-23 19:55:29 WARNING asyncio  -- Executing <Task finished name='Task-2' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> result=None> took 0.814 seconds
2023-04-23 19:56:11 ERROR music_assistant.websocket_api  -- [281473140799696] Error handling message: CommandMessage(message_id=8, command='config/players', args={})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 229, in _run_handler
    result = handler.target(**args)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 269, in get_player_configs
    for player_id, raw_conf in self.get(CONF_PLAYERS).items()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
2023-04-23 19:56:45 INFO  music_assistant  -- Loaded music provider Filesystem (local disk)
2023-04-23 19:56:45 WARNING music_assistant.providers.filesystem_local  -- stephy-a-la-claire-fontaine-chanson.mp3 is missing ID3 tag [album]
2023-04-23 19:56:46 WARNING music_assistant.providers.filesystem_local  -- stephy-il-etait-un-petit-navire-chanson.mp3 is missing ID3 tag [album]
2023-04-23 19:56:47 WARNING music_assistant.providers.filesystem_local  -- detskiy-myuzikl--volk-i-semero-kozlyat.mp3 is missing ID3 tag [album]
2023-04-23 19:56:48 ERROR music_assistant.providers.filesystem_local  -- Error processing Pisco_Sour.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 320, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 643, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-04-23 19:56:48 WARNING music_assistant.providers.filesystem_local  -- Club.mp3 is missing ID3 tag [album]
2023-04-23 19:56:49 WARNING music_assistant.providers.filesystem_local  -- les_enfants_de_noel_trotte_trotte_renne_rose_2010.mp3 is missing ID3 tag [album]
2023-04-23 19:56:50 WARNING music_assistant.providers.filesystem_local  -- Gas_Pedal.mp3 is missing ID3 tag [album]
2023-04-23 19:56:51 WARNING music_assistant.providers.filesystem_local  -- volk-i-semero-kozlyat-tanec-kozlyat.mp3 is missing ID3 tag [album]
2023-04-23 19:56:51 WARNING music_assistant.providers.filesystem_local  -- myuzikl-volk-i-semero-kozlyat.mp3 is missing ID3 tag [album]
2023-04-23 19:56:52 WARNING music_assistant.providers.filesystem_local  -- Y2Mate.is - Henri Dès - Les bêtises à l'école-_Uf3P6RD65w-128k-1655326266734.mp3 is missing ID3 tag [album]
2023-04-23 19:56:53 WARNING music_assistant.providers.filesystem_local  -- stephy-au-clair-de-la-lune-chanson.mp3 is missing ID3 tag [album]
2023-04-23 19:56:54 WARNING music_assistant.providers.filesystem_local  -- volk-i-semero-kozlyat-zapevayte-bratcy.mp3 is missing ID3 tag [album]
2023-04-23 19:56:55 ERROR music_assistant.providers.filesystem_local  -- Error processing rybnikov-volk-i-semero-kozlyat.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 320, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 643, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-04-23 19:56:55 WARNING music_assistant.providers.filesystem_local  -- yt5s.io - Bande son arrivée du Père Noël (128 kbps).mp3 is missing ID3 tag [album]
2023-04-23 19:56:56 WARNING music_assistant.providers.filesystem_local  -- Nimbus.mp3 is missing ID3 tag [album]
2023-04-23 19:56:57 WARNING music_assistant.providers.filesystem_local  -- volk-i-semero-kozlyat-zaklyuchitel-naya.mp3 is missing ID3 tag [album]
2023-04-23 19:56:57 ERROR music_assistant.providers.filesystem_local  -- Error processing volk-i-semero-kozlyat-pesenka-volka.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 320, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 643, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-04-23 19:56:58 ERROR music_assistant.providers.filesystem_local  -- Error processing Beat_Your_Competition.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 320, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 643, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-04-23 19:56:58 WARNING music_assistant.providers.filesystem_local  -- stephy-une-souris-verte-chanson.mp3 is missing ID3 tag [album]
2023-04-23 19:56:59 WARNING music_assistant.providers.filesystem_local  -- Y2Mate.is - Les Grenouilles-76tXtYsMq-g-128k-1656201578991.mp3 is missing ID3 tag [album]
2023-04-23 19:57:00 WARNING music_assistant.providers.filesystem_local  -- mul-t-v-mp3-volk-i-semero-kozlyat.mp3 is missing ID3 tag [album]
2023-04-23 19:57:01 WARNING music_assistant.providers.filesystem_local  -- detskaya-pesnya-iz-volk-i-semero-kozlyat.mp3 is missing ID3 tag [album]
2023-04-23 19:57:05 ERROR music_assistant.websocket_api  -- [281473140799696] Error handling message: CommandMessage(message_id=16, command='config/players', args={})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 229, in _run_handler
    result = handler.target(**args)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 269, in get_player_configs
    for player_id, raw_conf in self.get(CONF_PLAYERS).items()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'```

**Comment by OzGav** [comment]
This is not an issue it is just an unsupported device. Please continue the discussion in the existing thread https://github.com/orgs/music-assistant/discussions/1207

As an aside you need to properly tag your music as most of the errors in your log are because of that.
