### ISSUE TITLE
B29 Music stops playing

### ISSUE THREAD

**Issue by gieljnssns** [music-assistant/hass-music-assistant#1227]
### What version of Music Assistant has the issue?

v2.0.0b29

### The problem

I was playing music to a sonos group of 3 players and it suddenly stops playing.

```Player Keuken is making multiple requests for the same stream, please create an issue report on the Music Assistant issue tracker.```

### How to reproduce

The same as above

### Relevant log output
```
2023-04-29 14:15:15 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.238 seconds
2023-04-29 14:16:46 WARNING music_assistant.players  -- Error while requesting latest state from player Keuken: HTTPConnectionPool(host='192.168.79.85', port=1400): Max retries exceeded with url: /ZoneGroupTopology/Control (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f690874f990>, 'Connection to 192.168.79.85 timed out. (connect timeout=20.0)'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f690874f990>, 'Connection to 192.168.79.85 timed out. (connect timeout=20.0)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.79.85', port=1400): Max retries exceeded with url: /ZoneGroupTopology/Control (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f690874f990>, 'Connection to 192.168.79.85 timed out. (connect timeout=20.0)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 574, in _poll_players
    await player_prov.poll_player(player_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 397, in poll_player
    await self._update_player(sonos_player, signal_update=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 615, in _update_player
    sonos_player.update_attributes()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 184, in update_attributes
    self.player.group_childs = {
                               ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 185, in <setcomp>
    x.uid for x in self.group_info.members if x.uid != self.player_id and x.is_visible
                                                                          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/core.py", line 460, in is_visible
    return self in self.visible_zones
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/core.py", line 1603, in visible_zones
    self.zone_group_state.poll(self)
  File "/usr/local/lib/python3.11/site-packages/soco/zonegroupstate.py", line 157, in poll
    zgs = soco.zoneGroupTopology.GetZoneGroupState()["ZoneGroupState"]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 206, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 486, in send_command
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.79.85', port=1400): Max retries exceeded with url: /ZoneGroupTopology/Control (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f690874f990>, 'Connection to 192.168.79.85 timed out. (connect timeout=20.0)'))
2023-04-29 14:16:46 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 20.041 seconds
2023-04-29 14:16:46 ERROR music_assistant.streams  -- Player Keuken is making multiple requests for the same stream, please create an issue report on the Music Assistant issue tracker.
2023-04-29 14:17:43 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 1.114 seconds
2023-04-29 14:18:18 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 2.526 seconds
```

### What version of Home Assistant Core are your running

2023.4.x

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by gieljnssns** [comment]
Just happened again @ 15:03:44
```
2023-04-29 14:16:46 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 20.041 seconds
2023-04-29 14:16:46 ERROR music_assistant.streams  -- Player Keuken is making multiple requests for the same stream, please create an issue report on the Music Assistant issue tracker.
2023-04-29 14:17:43 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 1.114 seconds
2023-04-29 14:18:18 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 2.526 seconds
2023-04-29 14:37:14 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 1.096 seconds
2023-04-29 14:37:27 INFO  music_assistant  -- Loaded player provider SONOS
2023-04-29 14:37:35 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.104 seconds
2023-04-29 14:37:45 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.294 seconds
2023-04-29 14:37:55 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.129 seconds
2023-04-29 14:38:05 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.107 seconds
2023-04-29 14:38:15 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.164 seconds
2023-04-29 14:41:08 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.232 seconds
2023-04-29 14:41:30 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 1.051 seconds
2023-04-29 14:45:35 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.246 seconds
2023-04-29 14:46:15 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.105 seconds
2023-04-29 14:46:47 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.210 seconds
2023-04-29 14:46:58 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 1.189 seconds
2023-04-29 14:47:19 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.152 seconds
2023-04-29 14:49:21 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.152 seconds
2023-04-29 14:54:46 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 6.515 seconds
2023-04-29 14:55:16 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.103 seconds
2023-04-29 14:59:11 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.113 seconds
2023-04-29 14:59:21 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.240 seconds
2023-04-29 14:59:33 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.615 seconds
2023-04-29 14:59:43 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.117 seconds
2023-04-29 15:00:34 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.101 seconds
2023-04-29 15:01:05 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:574> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.118 seconds
2023-04-29 15:01:56 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.170 seconds
2023-04-29 15:03:21 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 3.526 seconds
2023-04-29 15:03:44 ERROR music_assistant.streams  -- Player Keuken is making multiple requests for the same stream, please create an issue report on the Music Assistant issue tracker.
2023-04-29 15:04:12 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 7.452 seconds
2023-04-29 15:05:13 WARNING asyncio  -- Executing <Task pending name='Task-6' coro=<PlayerController._poll_players() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py:589> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:261] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:254> took 0.527 seconds
```

**Comment by OzGav** [comment]
Seems like there is some weird network things going on with different Sonos speakers together. There is also the issue with people having s1 and s2 speakers together being a problem….?

**Comment by gieljnssns** [comment]
I haven't had this issue again, so I'm closing.
