### ISSUE TITLE
[feature request] Fix playback to Airplay devices

### ISSUE THREAD

**Issue by marcelveldt** [music-assistant/hass-music-assistant#124]
The current state of the atv integration in HA is that it won't stream audio to Airplay speakers.
An official ATV 4K does work (sometimes) and Homepod is hit and miss.

Maybe we can fix something to send the stream directly to the pyatv library because MA is using a raw PCM stream internally.

**Comment by Mariusthvdb** [comment]
just letting you know that on v16, and trying to play a Tunein Radio 4 Nl stream to my HomePod (select the stream in Radio, click Play in the bottom control section), I get:
```
Logger: homeassistant.core
Source: components/apple_tv/media_player.py:297 
First occurred: 08:18:58 (1 occurrences) 
Last logged: 08:18:58

Error executing service: <ServiceCall media_player.play_media (c:01G2VEQ90PPFC8QZKSV90KZJVF): entity_id=['media_player.homepod_keuken'], extra=, media_type=music, media_id=http://192.168.1.71:8095/media_player.homepod_keuken.flac>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1662, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1681, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 690, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 728, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/media_player.py", line 297, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 341, in stream_file
    self.playback_manager.acquire()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 141, in acquire
    raise exceptions.InvalidStateError("already streaming to device")
pyatv.exceptions.InvalidStateError: already streaming to device

```

Even while nothing was playing at all....

**Comment by marcelveldt** [comment]
ATV streaming implementation is flaky. I think the only way would be if MA is going to send the stream to airplay devices itself.

**Comment by Mariusthvdb** [comment]
for MA I guess that would safest. For HA, the ATV is a horror, and should be fixed nonetheless...

**Comment by marcelveldt** [comment]
Agreed

**Comment by erkr** [comment]
Moved to discussions, raise your votes!
