### ISSUE TITLE
When setting Music assistant up I get the error message Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by XVBinh** [music-assistant/hass-music-assistant#1257]
### What version of Music Assistant has the issue?

2023.2.1

### The problem

When I'm adding the music assistant to HA (Configuration -> Integrations) it gives me that error.

### How to reproduce

Add Music assistant to HA

### Relevant log output

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

This is a log
```
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 20:09:38 (6 occurrences)
Last logged: 20:10:28

Unable to install package pyatv==0.10.3: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [56 lines of output] /mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg` !! ******************************************************************************** The license_file parameter is deprecated, use license_files instead. By 2023-Oct-30, you need to update your project and remove deprecated calls or your builds will no longer be supported. See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details. ******************************************************************************** !! parsed = self.parsers.get(option_name, lambda x: x)(value) /mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. !! ******************************************************************************** Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`. ******************************************************************************** !! dist.fetch_build_eggs(dist.setup_requires) Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-p2wanmex/miniaudio_8bf15cd97aa548bc845e978ef1564c58/setup.py", line 20, in <module> setup( File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup return distutils.core.setup(**attrs) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup _setup_distribution = dist = klass(attrs) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 496, in __init__ _Distribution.__init__( File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__ self.finalize_options() File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 935, in finalize_options ep(self) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 955, in _finalize_setup_keywords ep.load()(self, ep.name, value) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules add_cffi_module(dist, cffi_module) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module execfile(build_file_name, mod_vars) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 25, in execfile exec(code, glob, glob) File "build_ffi_module.py", line 853, in <module> if check_linker_need_libatomic(): File "build_ffi_module.py", line 832, in check_linker_need_libatomic cpp_test = subprocess.Popen(cxx + ['-x', 'c++', '-std=c++14', '-'], File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 971, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 1863, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'c++' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
Unable to install package pyatv==0.10.3: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [56 lines of output] /mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg` !! ******************************************************************************** The license_file parameter is deprecated, use license_files instead. By 2023-Oct-30, you need to update your project and remove deprecated calls or your builds will no longer be supported. See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details. ******************************************************************************** !! parsed = self.parsers.get(option_name, lambda x: x)(value) /mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. !! ******************************************************************************** Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`. ******************************************************************************** !! dist.fetch_build_eggs(dist.setup_requires) Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-a0yvumgl/miniaudio_06fff2e5234c4259a5d28bb5fb2e90fc/setup.py", line 20, in <module> setup( File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup return distutils.core.setup(**attrs) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup _setup_distribution = dist = klass(attrs) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 496, in __init__ _Distribution.__init__( File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__ self.finalize_options() File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 935, in finalize_options ep(self) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 955, in _finalize_setup_keywords ep.load()(self, ep.name, value) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules add_cffi_module(dist, cffi_module) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module execfile(build_file_name, mod_vars) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 25, in execfile exec(code, glob, glob) File "build_ffi_module.py", line 853, in <module> if check_linker_need_libatomic(): File "build_ffi_module.py", line 832, in check_linker_need_libatomic cpp_test = subprocess.Popen(cxx + ['-x', 'c++', '-std=c++14', '-'], File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 971, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 1863, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'c++' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
Unable to install package pyatv==0.10.3: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [56 lines of output] /mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg` !! ******************************************************************************** The license_file parameter is deprecated, use license_files instead. By 2023-Oct-30, you need to update your project and remove deprecated calls or your builds will no longer be supported. See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details. ******************************************************************************** !! parsed = self.parsers.get(option_name, lambda x: x)(value) /mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. !! ******************************************************************************** Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`. ******************************************************************************** !! dist.fetch_build_eggs(dist.setup_requires) Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-afz0s25e/miniaudio_0b96bb30e6b2458cbcaac2ee58a16291/setup.py", line 20, in <module> setup( File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup return distutils.core.setup(**attrs) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup _setup_distribution = dist = klass(attrs) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 496, in __init__ _Distribution.__init__( File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__ self.finalize_options() File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 935, in finalize_options ep(self) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/setuptools/dist.py", line 955, in _finalize_setup_keywords ep.load()(self, ep.name, value) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules add_cffi_module(dist, cffi_module) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module execfile(build_file_name, mod_vars) File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 25, in execfile exec(code, glob, glob) File "build_ffi_module.py", line 853, in <module> if check_linker_need_libatomic(): File "build_ffi_module.py", line 832, in check_linker_need_libatomic cpp_test = subprocess.Popen(cxx + ['-x', 'c++', '-std=c++14', '-'], File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 971, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 1863, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'c++' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
Unable to install package music-assistant==1.8.7.4: ERROR: Cannot install music-assistant because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
```
Logger: aiohttp.server
Source: requirements.py:290
First occurred: 20:10:28 (1 occurrences)
Last logged: 20:10:28

Error handling request
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/config_entries.py", line 863, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/config_entries.py", line 962, in async_create_flow
    await _load_integration(self.hass, handler_key, self._hass_config)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/config_entries.py", line 2026, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/setup.py", line 389, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/requirements.py", line 252, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/home/homeassistant/.pyenv/versions/3.10.11/lib/python3.10/site-packages/homeassistant/requirements.py", line 290, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for mass not found: ['music-assistant==1.8.7.4'].
```

### What version of Home Assistant Core are your running

2023.5.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
https://github.com/music-assistant/hass-music-assistant/issues/1143
