### ISSUE TITLE
Unexpected exception 999 on Chromecast devices using MASS player entity

### ISSUE THREAD

**Issue by fliespl** [music-assistant/hass-music-assistant#1293]
### What version of Music Assistant has the issue?

v2

### The problem

Using for example tts as source file.

```
2023-06-07 21:51:50 ERROR music_assistant.websocket_api  -- [139673348762896] Error handling message: CommandMessage(message_id='4ea2f5cf0d614644b590594ddb845eb8', command='players/queue/play_media', args={'queue_id': 'd2ca266c-e69a-afbd-c8e1-1394e778d3bb', 'media': 'http://192.168.88.12:8123/api/tts_proxy/cf146c515f880aadcdb12fb92ea43496312eced3_pl_-_google_translate.mp3', 'option': 'play', 'radio_mode': False})
```

or http file

```
023-06-07 21:54:01 ERROR music_assistant.websocket_api  -- [139673344216016] Error handling message: CommandMessage(message_id='92683d01f17d490e80ab799fa83605b2', command='players/queue/play_media', args={'queue_id': 'd2ca266c-e69a-afbd-c8e1-1394e778d3bb', 'media': 'http://192.168.88.14:8080/lo69Ypj5TFs.mp3', 'option': 'play', 'radio_mode': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 237, in _run_handler
    result = await result
```

ends up

```
Unexpected exception: 999
Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 147, in _client_listen
    await mass.start_listening(init_ready)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/client/client.py", line 212, in start_listening
    self._handle_incoming_message(msg)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/client/client.py", line 252, in _handle_incoming_message
    exc = ERROR_MAP[msg.error_code]
KeyError: 999
```

### How to reproduce

Unsure - happens most of the time with my chromecasts, but only when using entity from MASS. HA entity works correctly everytime.

Happy to provide more debug / investigate things once instructed (not afraid to use docker / code in python etc - normal day in the office).

### Relevant log output

```
Unexpected exception: 999
Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 147, in _client_listen
    await mass.start_listening(init_ready)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/client/client.py", line 212, in start_listening
    self._handle_incoming_message(msg)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/client/client.py", line 252, in _handle_incoming_message
    exc = ERROR_MAP[msg.error_code]
KeyError: 999
```

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Could you provide more detail as to what you are doing which causes this?

**Comment by OzGav** [comment]
There is this thread which is linked from the FAQ which may help. https://github.com/orgs/music-assistant/discussions/834
