### ISSUE TITLE
Unable to add track to playlist

### ISSUE THREAD

**Issue by ArunGupta2017** [music-assistant/hass-music-assistant#1300]
### What version of Music Assistant has the issue?

2023.6.0b0

### The problem

I am sorry to report this issue here. Not sure it is a bug or I am doing something wrong.

I have stored six mp3 files locally on HA in /media directory. I have also created a local filesystem playlist. I can play each of the files on any player discovered by MA. When I try to add any of these tracks to the playlist, it does not get added. 

### How to reproduce

Go to Tracks, select the three dot against the track and select Add to Playlist, click on the Playlist.

### Relevant log output

`2023-06-10 05:02:51 DEBUG music_assistant.websocket_api  -- [139823332097808] Handling command music/playlists
2023-06-10 05:02:55 DEBUG music_assistant.websocket_api  -- [139823332097808] Handling command music/playlist/tracks/add
2023-06-10 05:02:55 WARNING music_assistant.providers.filesystem_local  -- Error while parsing playlist Aarti Playlist.m3u
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 454, in get_playlist_tracks
    playlist_data = playlist_data.decode(encoding_details["encoding"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decode() argument 'encoding' must be str, not None
2023-06-10 05:02:55 ERROR music_assistant  -- Exception in task Task-187
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 174, in add_playlist_track
    await provider.add_playlist_tracks(playlist_prov.item_id, [track_id_to_add])
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 495, in add_playlist_tracks
    playlist_data = playlist_data.decode(encoding_details["encoding"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decode() argument 'encoding' must be str, not None
`

### What version of Home Assistant Core are your running

2023.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This might have been reported on discord. Try opening the playlist with a file editor and add any character on the first line. Then try again adding to it. If this works then let us know and delete that character from the first line as it will cause errors. The playlist is now useable but the bug will be addressed.

**Comment by ArunGupta2017** [comment]
Yes, it works now...!!! Thank you so much for the quick reply.

**Comment by OzGav** [comment]
This has been fixed
