### ISSUE TITLE
No Found MediaPlayers

### ISSUE THREAD

**Issue by danniyy** [music-assistant/hass-music-assistant#1303]
### What version of Music Assistant has the issue?

2023.6.0b0

### The problem

I have installed everything, but the config page for the players is blank 

### How to reproduce

Just installed on HA 2023.6.1

### Relevant log output

2023-06-10 23:08:18 INFO  music_assistant  -- Starting Music Assistant Server (a31d3aeafc0a4ebaad05e6dcc25110d2) - autodetected IP-address: 192.168.2.161
2023-06-10 23:08:21 INFO  music_assistant.web  -- Starting webserver on port 8095
2023-06-10 23:08:22 INFO  music_assistant.streams  -- Started stream controller (using ffmpeg version 4.3.6 with libsoxr support)
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded metadata provider TheAudioDB Metadata provider
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded player provider SONOS
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded metadata provider fanart.tv Metadata provider
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded plugin provider Websocket API
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded player provider UPnP/DLNA Player provider
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded music provider URL
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded metadata provider MusicBrainz Metadata provider
2023-06-10 23:08:23 WARNING asyncio  -- Executing <Task pending name='Task-35' coro=<MusicAssistant._load_providers.<locals>.load_provider() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:433> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[TaskGroup._on_task_done()] created at /usr/local/lib/python3.11/asyncio/taskgroups.py:163> took 0.250 seconds
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded player provider Chromecast
2023-06-10 23:08:23 INFO  music_assistant.providers.slimproto  -- Started SLIMProto server on port 3483
2023-06-10 23:08:23 INFO  music_assistant.providers.slimproto.cli  -- Registering jsonrpc endpoints on the webserver
2023-06-10 23:08:23 INFO  music_assistant.providers.slimproto.cli  -- Starting (telnet) CLI on port 9090
2023-06-10 23:08:23 INFO  music_assistant  -- Loaded player provider Slimproto
authorized
2023-06-10 23:08:24 INFO  music_assistant  -- Loaded player provider Airplay
2023-06-10 23:08:24 INFO  music_assistant.providers.spotify  -- Successfully logged in to Spotify as danielbruns00
2023-06-10 23:08:24 INFO  music_assistant  -- Loaded music provider Spotify
2023-06-10 23:08:25 WARNING asyncio  -- Executing <Task finished name='Task-2' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> result=None> took 0.826 seconds
2023-06-10 23:09:00 ERROR music_assistant.websocket_api  -- [547841122064] Error handling message: CommandMessage(message_id=20, command='config/players', args={})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 237, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 286, in get_player_configs
    for player_id, raw_conf in self.get(CONF_PLAYERS).items()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
2023-06-10 23:10:57 INFO  music_assistant.metadata  -- Unable to get musicbrainz ID for artist Alis Shuka
 - using lookup-album(s): The Day Before (Sped Up)/The Day Before/Trippin' in Dubai/Creepin'/Summertime Sadness/In the end/Not About Us/Not About Us/Bum Bum/Not About Us/Not About Us/Crying At The Party/Broken Angel
 - using lookup-track(s): Broken Angel/Not About Us/Not About Us/Bum Bum/In the end/Summertime Sadness/Trippin' in Dubai/The Day Before/Creepin'/Not About Us

### Additional information

I have a couple of players installed on HA

- ESPHome Media Player
- HassAgent
- Alexa Media Player
- XBOX One
- Samsung Series 6 TV

### What version of Home Assistant Core are your running

2023.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Which of those players do you think should be discovered given the current player providers available?

**Comment by danniyy** [comment]
I think at least the ESPHome Players should be available because I had seen it before that they work

**Comment by OzGav** [comment]
Only if you are using squeezelite32.
It comes with an installer: https://sle118.github.io/squeezelite-esp32-installer/

**Comment by danniyy** [comment]
Are there any plans that the ESPHome Media Player will be supported in the future?

**Comment by marcelveldt** [comment]
Yes, support for ESPHome will be added later

**Comment by OzGav** [comment]
@danniyy If you don’t have any supported media players we will close this and ask you to vote in the player provider poll or open a discussion
