### ISSUE TITLE
Some local tracks on SMB share don't show up in MA

### ISSUE THREAD

**Issue by homenet589** [music-assistant/hass-music-assistant#1334]
### What version of Music Assistant has the issue?

2.0.0b39

### The problem

A few local tracks on a SMB share just don't show up in MA. When I browse the directory, it gets into a loading loop like this so the track doesn't show up there as well:

![Screenshot 2023-06-27 113457](https://github.com/music-assistant/hass-music-assistant/assets/101356311/81753df7-00ff-4708-9287-d77d1e324eb4)

The files work with all other music players.  

An example: [MP3] [5:18] 北乃きい. - 葉桜 </44 kHz/320 kbps/12.16 MB/>

My first guess was because of the Japanese characters in the metadata or file name, but then other Jpop songs load just fine, and this song doesn't have any and still doesn't show up:
[MP3] [3:57] Ms.OOJA - It’s OK (Nightcore) </44 kHz/320 kbps/9.37 MB/>

Folder structure:
Artist
- Album
- - Song

### How to reproduce

1) Put the tracks on an SMB share.
2) Add the SMB share to MA.
3) Synchronize/Scan.
4) A few tracks don't show up.

### Relevant log output

```
2023-06-27 15:59:30 ERROR music_assistant.websocket_api  -- [140369897001296] Error handling message: CommandMessage(message_id=11, command='music/browse', args={'path': 'filesystem_local://北乃きい/Can you hear me'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 237, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 242, in browse
    return await prov.browse(path)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 246, in browse
    elif track := await self.get_track(item.path):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 393, in get_track
    return await self._parse_track(file_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 654, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
```

### What version of Home Assistant Core are your running

2023.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Have a look in the MA log

**Comment by homenet589** [comment]
This is the log of trying to browse the directory of the track that doesn't show up
`2023-06-27 15:59:30 ERROR music_assistant.websocket_api  -- [140369897001296] Error handling message: CommandMessage(message_id=11, command='music/browse', args={'path': 'filesystem_local://北乃きい/Can you hear me'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/websocket_api/__init__.py", line 237, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 242, in browse
    return await prov.browse(path)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 246, in browse
    elif track := await self.get_track(item.path):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 393, in get_track
    return await self._parse_track(file_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 654, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]`
