### ISSUE TITLE
Playback issues with Kodi / OSMC (again)

### ISSUE THREAD

**Issue by jeroenterheerdt** [music-assistant/hass-music-assistant#1336]
### What version of Music Assistant has the issue?

addon: 2.0.0b39

### The problem

It looks like playback with Kodi / OSMC has regressed after it was fixed (see #358). I see issues in the log related to plex as the source, but nothing really about OSMC playback being an issue. I tried both with and without queue flow.

### How to reproduce

Plex any music from Plex to a OSMC player

### Relevant log output

2023-06-27 17:20:56 INFO  music_assistant  -- Starting Music Assistant Server (4b6139b59a664e8db47d8a2e0824647f) - autodetected IP-address: 192.168.X.X
2023-06-27 17:20:58 INFO  music_assistant.web  -- Starting webserver on port 8095
2023-06-27 17:20:59 INFO  music_assistant.streams  -- Started stream controller (using ffmpeg version 5.1.3 with libsoxr support)
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded music provider URL
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded plugin provider Websocket API
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded metadata provider MusicBrainz Metadata provider
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded player provider SONOS
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded metadata provider TheAudioDB Metadata provider
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded player provider UPnP/DLNA Player provider
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded metadata provider fanart.tv Metadata provider
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded player provider Chromecast
2023-06-27 17:20:59 INFO  music_assistant.providers.slimproto  -- Started SLIMProto server on port 3483
2023-06-27 17:20:59 INFO  music_assistant.providers.slimproto.cli  -- Registering jsonrpc endpoints on the webserver
2023-06-27 17:20:59 INFO  music_assistant.providers.slimproto.cli  -- Starting (telnet) CLI on port 9090
2023-06-27 17:20:59 INFO  music_assistant  -- Loaded player provider Slimproto
2023-06-27 17:21:00 INFO  music_assistant.players  -- Player registered: d1d4c160-f565-cc85-0575-6f0886882019/TV Room
2023-06-27 17:21:00 INFO  music_assistant  -- Loaded player provider Airplay
2023-06-27 17:21:00 ERROR plexapi  -- http://X.Y.Z.A:8443: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-06-27 17:21:00 INFO  music_assistant.players  -- Player registered: aa:aa:e7:e8:ae:d8/osmc
2023-06-27 17:21:00 INFO  music_assistant.players  -- Player registered: aa:aa:bf:27:54:59/TV Room
2023-06-27 17:21:00 INFO  music_assistant  -- Loaded music provider RadioBrowser
2023-06-27 17:21:03 WARNING async_upnp_client.profiles.dlna  -- Only InstanceID 0 is supported
2023-06-27 17:21:03 INFO  music_assistant.players  -- Player registered: uuid:d78ff173-8a37-ca94-3cd7-b6f3e8e9e966/TV Room
2023-06-27 17:21:03 WARNING async_upnp_client.profiles.dlna  -- Only InstanceID 0 is supported
2023-06-27 17:21:10 ERROR plexapi  -- http://66.235.6.39:32400: HTTPConnectionPool(host='66.235.6.39', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f5825442f10>, 'Connection to 66.235.6.39 timed out. (connect timeout=10)'))
2023-06-27 17:21:10 ERROR plexapi  -- https://X.Y.Z.A.c640bd00d4fe4e32b5d63f17df9040c1.plex.direct:32400: HTTPSConnectionPool(host='66-235-6-39.c640bd00d4fe4e32b5d63f17df9040c1.plex.direct', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5825441410>, 'Connection to 66-235-6-39.c640bd00d4fe4e32b5d63f17df9040c1.plex.direct timed out. (connect timeout=10)'))
2023-06-27 17:21:11 ERROR plexapi  -- https://X.Y.Z.A.c640bd00d4fe4e32b5d63f17df9040c1.plex.direct:8443: HTTPSConnectionPool(host='X.Y.Z.A.c640bd00d4fe4e32b5d63f17df9040c1.plex.direct', port=8443): Read timed out. (read timeout=10)
2023-06-27 17:21:11 INFO  music_assistant  -- Loaded music provider Plex Media Server Library
2023-06-27 17:21:21 WARNING asyncio  -- Executing <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> exception=EventLoopBlocked()> took 10.676 seconds
2023-06-27 17:21:21 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> exception=EventLoopBlocked()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 86, in run_coro_with_timeout
    return asyncio.run_coroutine_threadsafe(aw, loop).result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 237, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 106, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 123, in start
    self._setup_discovery()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 512, in _setup_discovery
    self.zeroconf.register_service(info)
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 623, in register_service
    run_coro_with_timeout(
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 90, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked
2023-06-27 17:22:09 INFO  music_assistant.streams  -- Start Queue Flow stream for Queue osmc
2023-06-27 17:22:13 WARNING asyncio  -- Executing <Task pending name='Task-190' coro=<MusicController._start_provider_sync.<locals>.run_sync() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py:544> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:292, MusicController._start_provider_sync.<locals>.on_sync_task_done() at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py:558] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:285> took 0.136 seconds

### What version of Home Assistant Core are your running

2023.6.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
What is the IP of your plex server?

**Comment by jeroenterheerdt** [comment]
It's on my local network: 192.168.X.X, not sure why it is relevant though.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by OzGav** [comment]
Because in the logs I see the connection to 66.235.6.39 is failing? That seemed like an odd ip address which is why i asked. Not sure how you have setup the connection to plex as I don’t use it but I would look to make sure everything was correctly setup, that you don’t have some sort of dns failure and perhaps remove the provider and then re-add it

**Comment by jeroenterheerdt** [comment]
Ah, so the 66.235.... Is my public IP. The connection to plex works fine as all the artists etc get 'scanned' correctly. However, playing anything is a different matter. That just doesn't work. The connection issues in the log don't have anything to do with playing I think, but with indexing. Anyway, not the expert that's why I came here for help.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by OzGav** [comment]
Will see what @marcelveldt thinks.

**Comment by jeroenterheerdt** [comment]
just checking in and letting you know I gave up on OSMC/KODI with Music Assistant. Instead, I moved to RAudio (successor of the 'dead' Rune Audio) and it works beautifully using Airplay and UPNP (both are provided). For anyone looking to do the same: https://github.com/rern/rAudio
