### ISSUE TITLE
home-assistant-addon "Music providers issue"

### ISSUE THREAD

**Issue by molly200** [music-assistant/hass-music-assistant#1340]
### What version of Music Assistant has the issue?

version: "2.0.0b39"

### The problem

The Filesystem (local disk) does not show the HA local mapped subdirectories. It only shows the top 2 directories (i.e /media/Music/.
Home assistant shows all the mapped paths under the Media including SMB shares and the mounted directories, subdirectories and associated files.

Thanks

### How to reproduce

N/A

### Relevant log output

No errors

### What version of Home Assistant Core are your running

2023.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by molly200** [comment]
Addition to the above.

Installed today the docker version and had the same problem with the local providers. This time the setup doesn't even map the local media folder.

Here is the log:

"2023-07-05 19:52:21 INFO  music_assistant  -- Loaded player provider Airplay
2023-07-05 19:52:31 WARNING asyncio  -- Executing <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> exception=EventLoopBlocked()> took 10.677 seconds
2023-07-05 19:52:31 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> exception=EventLoopBlocked()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 86, in run_coro_with_timeout
    return asyncio.run_coroutine_threadsafe(aw, loop).result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 237, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 106, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 123, in start
    self._setup_discovery()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 512, in _setup_discovery
    self.zeroconf.register_service(info)
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 623, in register_service
    run_coro_with_timeout(
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/asyncio.py", line 90, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked"

**Comment by OzGav** [comment]
I’m not sure that error is related but @marcelveldt ?

**Comment by molly200** [comment]
Is there a way to map any local source folders like "docker run --network host --privileged -v /media:/media ghcr.io/music-assistant/server"? 

Since MA runs privileged in host mode there should be no access restrictions to root folders.

Remote shares like samba aren't find either.

If MA has the DLNA media render implemented and discovers automatically the speakers, then why my nas servers (i.e. synology) with DLNA media servers enabled are not discovered and automatically mapped as media sources?

**Comment by OzGav** [comment]
They are not mapped automatically you need to add them as local providers

**Comment by molly200** [comment]
Is the stand alone docker version mapping the local /media folder to the root folder of the OS, or is trying to map the /media folder to a HASS container with docker? Does the MA container has its's own local /media folder which needs to be mapped with the OS /media folder?
I still can't figure out how to map a local folder within the OS root media folder from within the MA settings!

**Comment by marcelveldt** [comment]
You can map whatever you want and then you van add that path in the "Local files" provider.
So e.g. map your music files into /media and then add the Filesystem provider and at the path you enter /media

**Comment by molly200** [comment]
Thanks Marcel, it works just fine!

One thing I would suggest for the docker version is an "About" button or any provided information regarding the installed MA version. 

Overall great job!
