### ISSUE TITLE
Trying to configure integration gives '192.168.0.123 is not a valid url' error

### ISSUE THREAD

**Issue by paulius2k** [music-assistant/hass-music-assistant#1347]
### What version of Music Assistant has the issue?

2.0.0b41

### The problem

Trying to configure Music Assistant BETA:
<img src="https://github.com/music-assistant/hass-music-assistant/assets/24705262/e45243bc-80b9-4a20-920b-453759a10adf" width=60%>

gives this error:
<img src="https://github.com/music-assistant/hass-music-assistant/assets/24705262/170c6005-78d5-46d8-b1b4-8d59faf068a5" width=60%>

### How to reproduce

Settings --> Devices and Services --> Music Assistant BETA Configure

### Relevant log output

```
2023-07-07 15:58:01.289 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 297, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 393, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/config_flow.py", line 243, in async_step_discovery_confirm
    await get_server_info(self.hass, self.server_info.base_url)
  File "/config/custom_components/mass/config_flow.py", line 51, in get_server_info
    async with MusicAssistantClient(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 48, in __init__
    self.connection = WebsocketsConnection(server_url, aiohttp_session)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/connection.py", line 38, in __init__
    self.ws_server_url = get_websocket_url(server_url)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/connection.py", line 26, in get_websocket_url
    raise RuntimeError(f"{url} is not a valid url")
RuntimeError: 192.168.0.123 is not a valid url
```

### What version of Home Assistant Core are your running

2023.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please confirm if this is still and issue with b43

**Comment by paulius2k** [comment]
I updated the `Addon` to b50 - that did not solve the issue.
Then I updated the HACS custom component Music Assistant to `2023.6.0b1`, restarted HA, and the issue was resolved (the URL address changed to 172.*).

So I am not sure which update exactly solved my problem.
