### ISSUE TITLE
No address associated with hostname when trying to run MASS server 

### ISSUE THREAD

**Issue by IlPicasso** [music-assistant/hass-music-assistant#1353]
### What version of Music Assistant has the issue?

2023.0B

### The problem

I use proxmox, when trying to run the Music assistant server I get error 
socket.gaierror: [Errno -5] No address associated with hostname

### How to reproduce

Use proxmox

Install server

### Relevant log output

`2023-07-08 12:12:48 INFO  music_assistant  -- Starting Music Assistant Server (5431505f75bf4f35829f3a6dd2a5eb06) version 0.0.0
2023-07-08 12:12:52 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> exception=gaierror(-5, 'No address associated with hostname')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 237, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 106, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 125, in start
    await self.webserver.setup(await self.config.get_core_config("webserver"))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 487, in get_core_config
    config_entries = await self.get_core_config_entries(domain)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 521, in get_core_config_entries
    await controller.get_config_entries(action=action, values=values)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 85, in get_config_entries
    internal_ip = next((x for x in await get_ips() if x.startswith("172")), await get_ip())
                                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/util.py", line 70, in get_ips
    return await asyncio.to_thread(call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/util.py", line 62, in call
    for item in socket.getaddrinfo(socket.gethostname(), None):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -5] No address associated with hostname
`

### What version of Home Assistant Core are your running

2023.7.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by fliespl** [comment]
Same issue on my end. Started recently.

**Comment by marcelveldt** [comment]
The solution seems to be to completely reboot the host. I'll keep an eye on it if there is some reason for this

**Comment by OzGav** [comment]
@IlPicasso can you confirm rebooting the host does resolve the issue as a workaround?

**Comment by IlPicasso** [comment]
> @IlPicasso can you confirm rebooting the host does resolve the issue as a workaround?

It did but in second attempt

**Comment by marcelveldt** [comment]
This issue is fixed in beta 51
