### ISSUE TITLE
could not find match for var for

### ISSUE THREAD

**Issue by ukrolelo** [music-assistant/hass-music-assistant#1377]
### What version of Music Assistant has the issue?

2.0.0b58

### The problem

Cant open some folders

### How to reproduce

Click browse, then specific folder will not open

### Relevant log output

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 801, in _decipher_signature
    self._cipher = await asyncio.to_thread(_decipher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 796, in _decipher
    cipher = pytube.cipher.Cipher(js=ytm_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 37, in __init__
    self.transform_map = get_transform_map(js, var)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 245, in get_transform_map
    transform_object = get_transform_object(js, var)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 227, in get_transform_object
    raise RegexMatchError(caller="get_transform_object", pattern=pattern)
pytube.exceptions.RegexMatchError: get_transform_object: could not find match for var for={(.*?)};
2023-07-19 21:08:56.559 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-6851' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=RegexMatchError('get_transform_object: could not find match for var for={(.*?)};')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 688, in preload_next_url
    next_item.streamdetails = await get_stream_details(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 268, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 500, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 775, in _parse_stream_url
    signature = await self._decipher_signature(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 801, in _decipher_signature
    self._cipher = await asyncio.to_thread(_decipher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 796, in _decipher
    cipher = pytube.cipher.Cipher(js=ytm_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 37, in __init__
    self.transform_map = get_transform_map(js, var)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 245, in get_transform_map
    transform_object = get_transform_object(js, var)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 227, in get_transform_object
    raise RegexMatchError(caller="get_transform_object", pattern=pattern)
pytube.exceptions.RegexMatchError: get_transform_object: could not find match for var for={(.*?)};
2023-07-19 21:08:56.940 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-6852' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=RegexMatchError('get_transform_object: could not find match for var for={(.*?)};')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 688, in preload_next_url
    next_item.streamdetails = await get_stream_details(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 268, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 500, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 775, in _parse_stream_url
    signature = await self._decipher_signature(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 801, in _decipher_signature
    self._cipher = await asyncio.to_thread(_decipher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 796, in _decipher
    cipher = pytube.cipher.Cipher(js=ytm_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 37, in __init__
    self.transform_map = get_transform_map(js, var)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 245, in get_transform_map
    transform_object = get_transform_object(js, var)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 227, in get_transform_object
    raise RegexMatchError(caller="get_transform_object", pattern=pattern)
pytube.exceptions.RegexMatchError: get_transform_object: could not find match for var for={(.*?)};

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by austinbeam** [comment]
Seems to be related to this issue in [pytube](https://github.com/pytube/pytube/issues/1728).

**Comment by OzGav** [comment]
Please confirm this is fixed in beta 59

**Comment by ukrolelo** [comment]
It is playing Youtube music !!! WOOOHOOO !!!!
Should i close this issue?
Just have this errors but i don't know if it's important:
`
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 713, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-07-21 14:24:46.978 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing The Best Hits Of 90's/04 - Einz, Zwei, Polizei.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 335, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 713, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-07-21 14:24:47.069 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing The Best Hits Of 90's/08 - Short Dick Man.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 335, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 713, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-07-21 14:24:47.163 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing The Best Hits Of 90's/06 - It's A Rainy Day.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 335, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 713, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-07-21 14:24:47.263 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing VA-MInistry_Of_SOund-The_Chillout_Session/02-va-mos_the_chillout_session_cd2-mpx.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 335, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 713, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-07-21 14:24:47.367 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing VA-MInistry_Of_SOund-The_Chillout_Session/01-va-mos_the_chillout_session_cd1-mpx.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 335, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 713, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2023-07-21 14:26:45.522 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1200' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
2023-07-21 14:26:45.653 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1201' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
`

**Comment by OzGav** [comment]
You need to properly tag your music as the album  artist tag is missing. Alternatively see the options for the file system provider to decide how these should be handled.
