### ISSUE TITLE
Failed to cast media (YouTube Music)

### ISSUE THREAD

**Issue by qupterra** [music-assistant/hass-music-assistant#1378]
### What version of Music Assistant has the issue?

2023.6.0b1

### The problem

When attempting to play a playlist or track through the YouTube Music provider the add-on seems to connect to the chromecast device (Google Nest Mini) but shortly after the player returns to Idle state. An error is thrown in the Add-on logs, and in the HA logs.
The Add-on logs are similar to #1377 but the symptom is different.

### How to reproduce

Fresh install of addon
Set up YT Music connection
Attempt to cast playlist/track to any Google Nest Mini 
Error occurs

### Relevant log output

Addon Logs:

2023-07-20 10:01:53.947 INFO (ThreadPoolExecutor-0_1) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-07-20 10:01:59.318 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 467, in serve_queue_item_stream
    streamdetails = await get_stream_details(self.mass, queue_item=queue_item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 268, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 500, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 775, in _parse_stream_url
    signature = await self._decipher_signature(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 801, in _decipher_signature
    self._cipher = await asyncio.to_thread(_decipher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 796, in _decipher
    cipher = pytube.cipher.Cipher(js=ytm_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 37, in __init__
    self.transform_map = get_transform_map(js, var)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 245, in get_transform_map
    transform_object = get_transform_object(js, var)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 227, in get_transform_object
    raise RegexMatchError(caller="get_transform_object", pattern=pattern)
pytube.exceptions.RegexMatchError: get_transform_object: could not find match for var for={(.*?)};
2023-07-20 10:01:59.355 WARNING (Thread-10) [music_assistant.providers.chromecast] Load media failed: 1 - error code: 104

--------------------------------------------------------------------------------------------------------------

HA Logs:
2023-07-20 09:44:41.901 ERROR (Thread-9) [homeassistant.components.cast.media_player] Failed to cast media http://1.2.3.4:8096/a22e76ef-0e94-b04a-2ab5-c8e03593e549/single/14e3511e402e4628a55c00defd1f12f0.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2023-07-20 09:47:00.719 ERROR (Thread-9) [homeassistant.components.cast.media_player] Failed to cast media http://1.2.3.4:8096/a22e76ef-0e94-b04a-2ab5-c8e03593e549/single/14e3511e402e4628a55c00defd1f12f0.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2023-07-20 09:56:23.731 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Music Assistant' for mass integration not ready yet: Failed to connect to music assistant server; Retrying in background
2023-07-20 10:01:59.370 ERROR (Thread-9) [homeassistant.components.cast.media_player] Failed to cast media http://1.2.3.4:8096/a22e76ef-0e94-b04a-2ab5-c8e03593e549/single/14e3511e402e4628a55c00defd1f12f0.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

### Additional information

Attempting to access the URL in the HA logs throws an internal server error, unsure if this is expected behaviour after a the addon has attempted to provision a track for streaming and failed*

### What version of Home Assistant Core are your running

2023.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Do other media providers work?

**Comment by austinbeam** [comment]
I noticed https://github.com/KoljaWindeler/ytube_music_player/issues/253 looks to be similar. Not a music assistant user, but thought I'd point it out since the underlying issue seems to be in [pytube](https://github.com/pytube/pytube/issues/1728).

**Comment by qupterra** [comment]
> Do other media providers work? It looks like you have a network problem but if something works then that can be discounted.

I agree that's what it looks like, but this function was working a few days ago and no (intentional*) network related changes have been made that would cause this issue. The local filesystem provider works, so I'm inclined to think the endpoint returning a 500 is causing the network exception. 

> I noticed [KoljaWindeler/ytube_music_player#253](https://github.com/KoljaWindeler/ytube_music_player/issues/253) looks to be similar. Not a music assistant user, but thought I'd point it out since the underlying issue seems to be in [pytube](https://github.com/pytube/pytube/issues/1728).

I noted this too, with the lowest level exception being thrown by that regex module in pytube.

**Comment by OzGav** [comment]
Ok sounds good. The YT provider works at the whim of YT who can change their system in ways which can break MA. Will just have to wait for the devs to have a look at this.

**Comment by OzGav** [comment]
The YT dev is onto this and a fix should be available in the next beta. Google changed something…..

**Comment by OzGav** [comment]
Please confirm this is fixed in beta 59

**Comment by qupterra** [comment]
> Please confirm this is fixed in beta 59

Confirmed able to play manually

Getting an error trying to run via automation.

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Invalid uri: database://playlist/7

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 358, in async_play_media
    await self.mass.players.play_media(queue.queue_id, media_id, queue_opt, radio_mode)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 282, in play_media
    await self.client.send_command(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 168, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.MediaNotFoundError: Invalid uri: database://playlist/7

```
Unsure if it's related, have tried reading the media action a few times without success
Happy to raise a new issue if needed

**Comment by OzGav** [comment]
Are you using beta 3 of the integration? Look for updates in HACS

**Comment by qupterra** [comment]
> Are you using beta 3 of the integration? Look for updates in HACS

Can confirm this error was occurring on 2023.6.0b3
Is there another component I should look for an update in?

**Comment by OzGav** [comment]
Your playlist uri looks wrong. Just use the name of the playlist.

**Comment by qupterra** [comment]
> Your playlist uri looks wrong. Just use the name of the playlist.
I was using the automation GUI to avoid any unintended typos or incorrect linking. 

I've just tested the same process again and it seems to be working now regardless so I think we're good to close.

Thanks again for all your help and diligent response to my issue - your work is very much appreciated :)
