### ISSUE TITLE
Playing just one song in playlist YT music

### ISSUE THREAD

**Issue by ukrolelo** [music-assistant/hass-music-assistant#1389]
### What version of Music Assistant has the issue?

2.0.0b59

### The problem

I am not able to play the whole playlist. When i choose a playlist and click play It just playing one song. 

### How to reproduce

Just play the playlist

### Relevant log output

    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
2023-07-22 10:50:48.828 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1573' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
2023-07-22 10:50:52.540 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1631' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
2023-07-22 10:50:52.541 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1632' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
2023-07-22 10:50:57.460 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1676' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
2023-07-22 10:50:57.461 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1677' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
2023-07-22 10:51:01.972 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1834' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
2023-07-22 10:51:01.972 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1835' coro=<DLNAPlayerProvider._enqueue_next_track() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py:537> exception=AttributeError("'NoneType' object has no attribute 'uri'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 544, in _enqueue_next_track
    ) = await self.mass.player_queues.preload_next_url(dlna_player.udn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 715, in preload_next_url
    and cur_item.media_item.album == next_item.media_item.album
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 332, in __eq__
    return self.uri == other.uri
                       ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'

### Additional information

Shuffle and repeat all is selected.

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by ukrolelo** [comment]
FIY local player playing the whole playlist

**Comment by ukrolelo** [comment]
That is strange, let me test it again as it start to work. Maybe it is caused by setting up Enable queue flow mode. It's the only thing i changed

**Comment by ukrolelo** [comment]
I don't know what happened but it started to work and it didn't matter about queue flow mode. When playing the full playlist It is not giving the correct image of the song, but it doesn't matter for me. <3

**Comment by ukrolelo** [comment]
And again not working... I have no idea why...

**Comment by ukrolelo** [comment]
Turned on queue flow mode again and it's working. will test it out for a while

**Comment by ukrolelo** [comment]
This seems to be the case. Closing.
