### ISSUE TITLE
YouTube Music Playlists do not show

### ISSUE THREAD

**Issue by screamy** [music-assistant/hass-music-assistant#1400]
### What version of Music Assistant has the issue?

Server Version: 2.0.0b60

2023.6.0b3

### The problem

Music Assistant does not retrieve YouTube Music playlists (both user defines playlists or YouTube mixed ones like Supermix).

### How to reproduce

Configure YouTube Music integration.
Wait for sync to run
Open Music Assistant and select the Playlists tile. Observe "No items found".

### Relevant log output

```
2023-07-25 12:59:42.312 WARNING (MainThread) [music_assistant.music] Sync task for YouTube Music completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 547, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 418, in sync_library
    library_item = await controller.add_item_to_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 157, in add_item_to_library
    library_item = await self._add_library_item(item)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 394, in _add_library_item
    await self._set_track_album(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 409, in _set_track_album
    db_album = await self.mass.music.albums.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 81, in get
    album.artists = [
                    ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 82, in <listcomp>
    await self.mass.music.artists.get(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 200, in get
    await add_task
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 66, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 237, in get_artist_mbid
    ref_tracks = await self.mass.music.artists.tracks(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 155, in tracks
    return await self.get_provider_artist_toptracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 241, in get_provider_artist_toptracks
    items = await prov.get_artist_toptracks(item_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 378, in get_artist_toptracks
    playlist_tracks = [
                      ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 378, in <listcomp>
    playlist_tracks = [
                      ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 342, in get_playlist_tracks
    playlist_obj = await get_playlist(prov_playlist_id=prov_playlist_id, headers=self._headers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 63, in get_playlist
    return await asyncio.to_thread(_get_playlist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 59, in _get_playlist
    playlist = ytm.get_playlist(playlistId=prov_playlist_id, limit=None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/playlists.py", line 109, in get_playlist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 156, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 429: Too Many Requests.
Resource has been exhausted (e.g. check quota).
2023-07-25 12:59:42.373 INFO (MainThread) [music_assistant.music] Sync task for URL completed
```

<details><summary>Task Exception</summary>
<p>
<code>2023-07-25 13:09:37.328 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1088' coro=<SlimprotoProvider._handle_connected() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/providers/slimproto/__init__.py:773> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x5595f3825ff0>; the handler is closed')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/slimproto/__init__.py", line 797, in _handle_connected
    await client.power(init_power)
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 380, in power
    await self.stop()
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 347, in stop
    await self.set_display()
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 556, in set_display
    await self.render("")
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 550, in render
    await self._update_display(bitmap)
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 567, in _update_display
    await self._send_frame(b"grfe", frame)
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 580, in _send_frame
    self.disconnect()
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 254, in disconnect
    self._writer.write_eof()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 338, in write_eof
    return self._transport.write_eof()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/handles/stream.pyx", line 699, in uvloop.loop.UVStream.write_eof
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x5595f3825ff0>; the handler is closed
</code>
</p>
</details> 

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You have supplied the integration version. Are you running 2.0.0b60 of the server?

**Comment by screamy** [comment]
After several more attempts playlists did appear. But initial sync not completed because of `Exception: Server returned HTTP 429: Too Many Requests.`

Radio tab still empty for youtube music provider, but probably it supposed to be empty for yt music.

**Comment by OzGav** [comment]
@MarvinSchenkel Ideas?

**Comment by marcelveldt** [comment]
@screamy Please check if this issue is resolved with beta67 and onwards.
If your issue is for now resolved, please close this issue, thanks!

If the "429: Too Many Requests" issue comes back, there should be rate limiter implemented in the YTmusic library, @MarvinSchenkel FYI

**Comment by OzGav** [comment]
@screamy we will close this soon as it is believed to be fixed.
