### ISSUE TITLE
server/ytmusic: unhandled exception when queueing nonexistent video

### ISSUE THREAD

**Issue by Sirs0ri** [music-assistant/hass-music-assistant#1403]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

I have a HA Script that grabs song recommendations from last.fm and queues them in music assistant through youtube music.

Every once in a while there's a video in my recommendations that doesn't exist anymore, which causes a nondescript `KeyError: 'videoDetails'`, while other providers would raise a `MediaNotFoundError`.

The [player_queue controller](https://github.com/music-assistant/server/blob/main/music_assistant/server/controllers/player_queues.py#L190) will only handle Errors of the type `MusicAssistantError`, causing this KeyError to bubble up into the webserver, instead of being caught by the queue controller.

### How to reproduce

1. Set up the Youtube Music provider in MAss
2. from HomeAssistant, call these services (you'll have to fill in a working player_id):

```yaml
service: mass.queue_command
data:
  enqueue_mode: replace_next
  player_id: media_player.YOUR_PLAYER_ID_HERE
  command: play_media
  uri:
    - ytmusic://track/some-id-thats-not-real
```

```yaml
service: mass.queue_command
data:
  enqueue_mode: replace_next
  player_id: media_player.YOUR_PLAYER_ID_HERE
  command: play_media
  uri:
    - fake-provider://track/some-id-thats-not-real
```

Result: The service calls will fail, no changes to the queue happen. Logs will show a `KeyError` from Youtube, and a `MediaNotFoundError` from MAss for the 2nd service call.

Expected: Youtube should also raise a MediaNotFoundError, similar to e.g. Spotify's:
`music_assistant.common.models.errors.MediaNotFoundError: Invalid uri: spotify://track/some-id-thats-not-real`

### Relevant log output

First the `KeyError` from Youtube, then a `MediaNotFoundError` from spotify, and another one from MAss, trying to call a provider that doesn't exist.

```
2023-07-26 11:56:04.616 ERROR (MainThread) [music_assistant.webserver] [545755523920] Error handling message: CommandMessage(message_id='4a0c3c6c32674defb4cf61062013a23b', command='players/queue/play_media', args={'queue_id': '38033bdf-0ba5-a8a3-e202-e4ce8ece9149', 'media': ['ytmusic://track/some-id-thats-not-real'], 'option': 'replace_next', 'radio_mode': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 189, in play_media
    media_item = await self.mass.music.get_item_by_uri(item)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 288, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 312, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 62, in get
    track = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 175, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 408, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 267, in get_item
    return await self.get_track(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 316, in get_track
    if track_obj := await get_track(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 91, in get_track
    return await asyncio.to_thread(_get_song)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 75, in _get_song
    track["videoId"] = track_obj["videoDetails"]["videoId"]
                       ~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'
2023-07-26 11:56:38.015 ERROR (MainThread) [music_assistant.providers.spotify] tracks/some-id-thats-not-real - {'error': {'status': 400, 'message': 'invalid id'}}
2023-07-26 11:56:38.020 ERROR (MainThread) [music_assistant.webserver] [545755523920] Error handling message: CommandMessage(message_id='4f1db2e0727c4d288126319d0ea0f422', command='players/queue/play_media', args={'queue_id': '38033bdf-0ba5-a8a3-e202-e4ce8ece9149', 'media': ['spotify://track/some-id-thats-not-real'], 'option': 'replace_next', 'radio_mode': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 189, in play_media
    media_item = await self.mass.music.get_item_by_uri(item)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 288, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 312, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 62, in get
    track = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 175, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 424, in get_provider_item
    raise MediaNotFoundError(
music_assistant.common.models.errors.MediaNotFoundError: track://some-id-thats-not-real not found on provider spotify
ertlm-musicassistant-1  |
The above exception was the direct cause of the following exception:
ertlm-musicassistant-1  |
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 192, in play_media
    raise MediaNotFoundError(f"Invalid uri: {item}") from err
music_assistant.common.models.errors.MediaNotFoundError: Invalid uri: spotify://track/some-id-thats-not-real
2023-07-26 11:56:55.532 ERROR (MainThread) [music_assistant.webserver] [545755523920] Error handling message: CommandMessage(message_id='b4a41747e122439ca9cd3901b4fcd32c', command='players/queue/play_media', args={'queue_id': '38033bdf-0ba5-a8a3-e202-e4ce8ece9149', 'media': ['fake-provider://track/some-id-thats-not-real'], 'option': 'replace_next', 'radio_mode': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 189, in play_media
    media_item = await self.mass.music.get_item_by_uri(item)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 288, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 312, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 62, in get
    track = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 175, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 424, in get_provider_item
    raise MediaNotFoundError(
music_assistant.common.models.errors.MediaNotFoundError: track://some-id-thats-not-real not found on provider fake-provider
ertlm-musicassistant-1  |
The above exception was the direct cause of the following exception:
ertlm-musicassistant-1  |
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 192, in play_media
    raise MediaNotFoundError(f"Invalid uri: {item}") from err
music_assistant.common.models.errors.MediaNotFoundError: Invalid uri: fake-provider://track/some-id-thats-not-real
```

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
@MarvinSchenkel FYI

**Comment by marcelveldt** [comment]
this should be fixed in next beta (b68)

**Comment by OzGav** [comment]
@Sirs0ri please confirm that this has been fixed

**Comment by Sirs0ri** [comment]
yes, the error is now the same `MediaNotFoundError` as with other providers!
