### ISSUE TITLE
OPPO105 not working correctly via DLNA

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1421]
Hi, all cabled, I'm not a fan of wifi so it's reserved for portable devices such as Phones and Tablets only!  I suppose that doesn't fully negate a networking issue though.

...

Actually, I just removed the DLNA Player Provider again and re-added it and it's working again.

I did capture this from the logs though when playing the first track.

2023-08-01 14:17:00.946 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2023-08-01 14:17:31.960 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-96956' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:114> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 160, in add_item_to_library
    library_item = await self._add_library_item(item)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 375, in _add_library_item
    return await self.update_item_in_library(cur_item.item_id, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 200, in update_item_in_library
    await self._set_track_album(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 420, in _set_track_album
    db_album = await self.mass.music.albums.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 81, in get
    album.artists = [
                    ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 82, in <listcomp>
    await self.mass.music.artists.get(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 200, in get
    await add_task
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 66, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 252, in get_artist_mbid
    if mbid := await provider.get_musicbrainz_artist_id(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 110, in get_musicbrainz_artist_id
    if mbid := await self._search_artist_by_track(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 161, in _search_artist_by_track
    assert trackname or track_isrc
AssertionError

I don't however get any indication in Music Assistant that the Oppo105 is playing though, the player shows idle and I cannot see the queue of items setup for playing, but it is working it's way through an album that I have queued.  Actual scratch that, it's repeat playing track 1 over and over.

_Originally posted by @gadgetbazza in https://github.com/music-assistant/hass-music-assistant/discussions/1139#discussioncomment-6606344_

**Comment by marcelveldt** [comment]
@gadgetbazza does this issue still exist in beta63 ?

**Comment by OzGav** [comment]
@gadgetbazza Please confirm this has been fixed

**Comment by gadgetbazza** [comment]
Hi,  Updated to B67 just now and can confirm it's playing through tracks now without issue.  Thanks so much!

As an aside though, when I click on Albums in the nav and then selecting an album there is no content in the main pain (nav and player status still in place and working).  So currently cannot navigate music via the Albums route.

**Comment by OzGav** [comment]
Please open a new issue about that and advise what music provider you are using and include some screenshots. Let us know if the tracks and albums appear under the artist and whether the tracks appear under tracks. Have a look in the logs when you navigate to the Album view.

You could try to restart the addon just in case that fixes it.
