### ISSUE TITLE
Tidal - Track Listings

### ISSUE THREAD

**Issue by oneofthemany** [music-assistant/hass-music-assistant#1424]
### What version of Music Assistant has the issue?

2.0.0b62"

### The problem

Track listings are not being pulled from Tidal:

![image](https://github.com/music-assistant/hass-music-assistant/assets/44924639/c2bc9418-0f1a-4ad8-829a-56d9df81d85d)

### How to reproduce

Open Tidal > Tracks = empty > refresh > remains empty
Delete Tidal > re-authenticate > Open Tidal > Tracks = empty > refresh > remains empty
Delet tidal container > rebuild container > re-authenticate > Open Tidal > Tracks = empty > refresh > remains empty

### Relevant log output

root@rock-5b:/opt/music_assistant# podman logs music-assistant
2023-08-02 08:30:51.936 INFO (MainThread) [music_assistant] Starting Music Assistant Server (1fbda485a15b4fae9979e7c6c33eaebc) version 2.0.0b62 - uvloop: False
2023-08-02 08:30:51.988 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.1.1:8095
2023-08-02 08:30:52.131 INFO (MainThread) [music_assistant.music] Setting up the sync interval to 180 minutes.
2023-08-02 08:30:52.297 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.3 with libsoxr support
2023-08-02 08:30:52.297 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.1.1:8096
2023-08-02 08:30:52.768 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2023-08-02 08:30:52.768 INFO (MainThread) [music_assistant] Loaded music provider URL
2023-08-02 08:30:52.769 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2023-08-02 08:30:52.770 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2023-08-02 08:30:52.770 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2023-08-02 08:30:52.771 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2023-08-02 08:30:52.771 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2023-08-02 08:30:52.775 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-02 08:30:52.779 INFO (MainThread) [music_assistant.providers.slimproto] Started SLIMProto server on port 3483
2023-08-02 08:30:52.780 INFO (MainThread) [music_assistant.providers.slimproto.cli] Registering jsonrpc endpoints on the webserver
2023-08-02 08:30:52.782 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2023-08-02 08:30:52.784 INFO (MainThread) [music_assistant.providers.slimproto.cli] Starting (telnet) CLI on port 9090
2023-08-02 08:30:52.793 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2023-08-02 08:30:52.878 INFO (MainThread) [music_assistant.players] Player registered: 1c16f7cc-add3-c994-ba77-ff709a72817c/Speaker - Master Bedroom
2023-08-02 08:30:53.047 INFO (MainThread) [music_assistant.players] Player registered: b2fe7f85-1797-44f8-957f-1747cf58a76f/Quadrophonic
2023-08-02 08:30:53.207 INFO (MainThread) [music_assistant.players] Player registered: c94acc21-d7ce-4a0d-bca4-1d2167f03302/Elena Broadcast
2023-08-02 08:30:53.367 INFO (MainThread) [music_assistant.players] Player registered: 7af6343c-8e4a-4d96-a6d6-cf971853cc0e/Home
2023-08-02 08:30:53.532 INFO (MainThread) [music_assistant.players] Player registered: c7c621ce-aa0b-44b1-8317-60cd92af9eba/Living Room Speaker
2023-08-02 08:30:53.691 INFO (MainThread) [music_assistant.players] Player registered: e62fde05-9013-ae07-21a8-832b81cbfae0/Speaker - Desk
2023-08-02 08:30:53.781 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2023-08-02 08:30:53.911 INFO (MainThread) [music_assistant.players] Player registered: 7462796e-c3bf-4e19-925d-7d9f6508b938/Alarm Group
2023-08-02 08:30:54.238 INFO (MainThread) [music_assistant.players] Player registered: 4150f58d-0b98-4083-9c78-68df23829d32/Stereo Kitchen Pair
2023-08-02 08:30:54.391 INFO (MainThread) [music_assistant.players] Player registered: f65e5e5f-b6da-0b86-303c-87e3383e3888/Speaker - Elena's Room
2023-08-02 08:30:54.762 ERROR (MainThread) [music_assistant.webserver] [547313847440] Error handling message: CommandMessage(message_id=49, command='music/albums/get_album', args={'item_id': '95', 'provider_instance_id_or_domain': 'library'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 71, in get
    album = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 165, in get
    library_item = await self.get_library_item_by_prov_id(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 303, in get_library_item_by_prov_id
    return await self.get_library_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 292, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 95
2023-08-02 08:34:41.935 INFO (MainThread) [music_assistant] Loaded music provider Tidal
2023-08-02 08:34:45.949 WARNING (MainThread) [music_assistant.music] Sync task for Tidal completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 408, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 253, in get_library_tracks
    yield await self._parse_track(track_obj=track)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
2023-08-02 08:34:46.766 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-276' coro=<MetaDataController.start_scan.<locals>.scan_artist_metadata() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py:91> exception=TypeError("unsupported operand type(s) for ** or pow(): 'set' and 'dict'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 108, in scan_artist_metadata
    await self.mass.music.artists.get(artist.item_id, artist.provider, lazy=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 215, in get
    await add_task
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 66, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 236, in get_artist_mbid
    ref_tracks = await self.mass.music.artists.tracks(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 159, in tracks
    return await self.get_provider_artist_toptracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 245, in get_provider_artist_toptracks
    items = await prov.get_artist_toptracks(item_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 292, in get_artist_toptracks
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 293, in <listcomp>
    await self._parse_track(track_obj=track)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
2023-08-02 08:34:51.564 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-286' coro=<ArtistsController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py:58> exception=TypeError("unsupported operand type(s) for ** or pow(): 'set' and 'dict'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 66, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 236, in get_artist_mbid
    ref_tracks = await self.mass.music.artists.tracks(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 159, in tracks
    return await self.get_provider_artist_toptracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 245, in get_provider_artist_toptracks
    items = await prov.get_artist_toptracks(item_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 292, in get_artist_toptracks
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 293, in <listcomp>
    await self._parse_track(track_obj=track)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
2023-08-02 08:34:54.955 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-295' coro=<ArtistsController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py:58> exception=TypeError("unsupported operand type(s) for ** or pow(): 'set' and 'dict'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 66, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 236, in get_artist_mbid
    ref_tracks = await self.mass.music.artists.tracks(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 159, in tracks
    return await self.get_provider_artist_toptracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 245, in get_provider_artist_toptracks
    items = await prov.get_artist_toptracks(item_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 292, in get_artist_toptracks
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 293, in <listcomp>
    await self._parse_track(track_obj=track)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
2023-08-02 08:34:55.352 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-301' coro=<ArtistsController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py:58> exception=TypeError("unsupported operand type(s) for ** or pow(): 'set' and 'dict'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 66, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 236, in get_artist_mbid
    ref_tracks = await self.mass.music.artists.tracks(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 159, in tracks
    return await self.get_provider_artist_toptracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 245, in get_provider_artist_toptracks
    items = await prov.get_artist_toptracks(item_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 292, in get_artist_toptracks
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 293, in <listcomp>
    await self._parse_track(track_obj=track)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
2023-08-02 08:34:55.671 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-304' coro=<ArtistsController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py:58> exception=TypeError("unsupported operand type(s) for ** or pow(): 'set' and 'dict'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 66, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 236, in get_artist_mbid
    ref_tracks = await self.mass.music.artists.tracks(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 159, in tracks
    return await self.get_provider_artist_toptracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 245, in get_provider_artist_toptracks
    items = await prov.get_artist_toptracks(item_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 292, in get_artist_toptracks
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 293, in <listcomp>
    await self._parse_track(track_obj=track)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
2023-08-02 08:35:03.983 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-02 08:35:04.127 WARNING (MainThread) [music_assistant.music] Sync task for Tidal completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 408, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 253, in get_library_tracks
    yield await self._parse_track(track_obj=track)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
2023-08-02 08:36:05.305 WARNING (MainThread) [music_assistant.webserver] [547313847440] Disconnected: Received non-Text message.
2023-08-02 08:36:25.298 ERROR (Thread-4) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-293' coro=<AlbumsController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py:93> exception=ExceptionGroup('unhandled errors in a TaskGroup', [TypeError("unsupported operand type(s) for ** or pow(): 'set' and 'dict'")])>
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 123, in add_item_to_library
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 147, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 124, in add_item_to_library
    |     for track in await self._get_provider_album_tracks(item.item_id, item.provider):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 301, in _get_provider_album_tracks
    |     for track in await prov.get_album_tracks(item_id):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 268, in get_album_tracks
    |     return [
    |            ^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 269, in <listcomp>
    |     await self._parse_track(
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    |     provider_mappings={
    |                       ^
    | TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
    +------------------------------------
2023-08-02 08:36:25.300 ERROR (Thread-4) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-300' coro=<AlbumsController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py:93> exception=ExceptionGroup('unhandled errors in a TaskGroup', [TypeError("unsupported operand type(s) for ** or pow(): 'set' and 'dict'")])>
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 123, in add_item_to_library
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 147, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 124, in add_item_to_library
    |     for track in await self._get_provider_album_tracks(item.item_id, item.provider):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 301, in _get_provider_album_tracks
    |     for track in await prov.get_album_tracks(item_id):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 268, in get_album_tracks
    |     return [
    |            ^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 269, in <listcomp>
    |     await self._parse_track(
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    |     provider_mappings={
    |                       ^
    | TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
    +------------------------------------

### Additional information

All settings in  MASS were not visible in HA when I opened it up this morning:

Radio Settings
Music Provider

Checked container and music-assistant server was running - readded radio and was functionally working

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by Sirs0ri** [comment]
I'm seeing this as well. For me, my tracks from Tidal are still visible, but I've got the same `unsupported operand type(s) for ** or pow(): 'set' and 'dict'` TypeError in my logs, together with an Error "`Task exception was never retrieved`".

I'm running MAss in Docker directly, this started happening with the update to Beta 62.

**Relevant Log:**

```
2023-08-02 12:10:28.834 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-39' coro=<MetaDataController.start_scan.<locals>.scan_artist_metadata() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py:91> exception=TypeError("unsupported operand type(s) for ** or pow(): 'set' and 'dict'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 108, in scan_artist_metadata
    await self.mass.music.artists.get(artist.item_id, artist.provider, lazy=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 215, in get
    await add_task
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 73, in add_item_to_library
    await self.match_artist(library_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 218, in match_artist
    if await self._match(db_artist, provider):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 460, in _match
    search_results = await self.mass.music.tracks.search(search_str, provider.domain)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 248, in search
    searchresult = await prov.search(
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 225, in search
    parsed_results.tracks.append(await self._parse_track(track_obj=track))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'

2023-08-02 12:10:35.371 WARNING (MainThread) [music_assistant.music] Sync task for Tidal completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 408, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 253, in get_library_tracks
    yield await self._parse_track(track_obj=track)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 583, in _parse_track
    provider_mappings={
                      ^
TypeError: unsupported operand type(s) for ** or pow(): 'set' and 'dict'
```

**Comment by OzGav** [comment]
@oneofthemany @Sirs0ri beta 63 has been released. Please confirm this has been fixed

**Comment by JimmyMPage** [comment]
I can confirm this has been fixed for me. Thanks folks!

**Comment by oneofthemany** [comment]
@marcelveldt - confirmed as working

many thanks

:)
