### ISSUE TITLE
[Tidal] `AttributeError: 'NoneType' object has no attribute 'append'` during SyncTask

### ISSUE THREAD

**Issue by Sirs0ri** [music-assistant/hass-music-assistant#1430]
### What version of Music Assistant has the issue?

music-assistant/server Beta 63

### The problem

My log from docker shows a warning that the "`Sync task for Tidal completed with errors`", that seems to happen while trying to add tracks to my library. 

It's preceded by a couple of warnings caused by 404 errors from tidalapi and `Skipping sync of item tidal://track/XYZ: album://ABC not found on provider tidal`type warnings, I'm not sure if that's related though - I'll include the warnings in the log below just to be sure.

The sync task completes otherwise, I haven't noticed any missing tracks so far

### How to reproduce

1) Set up Tidal, then refresh the tidal music provider
2) Observe the logs

### Relevant log output

```
2023-08-02 15:29:54.324 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:54.326 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/104503115: album://104503114 not found on provider tidal
2023-08-02 15:29:54.493 WARNING (ThreadPoolExecutor-0_2) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:54.495 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/74791494: album://74791488 not found on provider tidal
2023-08-02 15:29:55.132 WARNING (ThreadPoolExecutor-0_1) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:55.134 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/69394803: album://69394796 not found on provider tidal
2023-08-02 15:29:55.288 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:55.289 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/125659223: album://125659222 not found on provider tidal
2023-08-02 15:29:55.473 WARNING (ThreadPoolExecutor-0_3) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:55.474 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/150511974: album://150511973 not found on provider tidal
2023-08-02 15:29:56.253 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:56.255 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/56923095: album://56923093 not found on provider tidal
2023-08-02 15:29:56.455 WARNING (ThreadPoolExecutor-0_3) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:56.456 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/158376917: album://158376916 not found on provider tidal
2023-08-02 15:29:56.615 WARNING (ThreadPoolExecutor-0_1) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:56.616 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/93227227: album://93227226 not found on provider tidal
2023-08-02 15:29:56.774 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:56.775 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/245603206: album://245603203 not found on provider tidal
2023-08-02 15:29:56.941 WARNING (ThreadPoolExecutor-0_3) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:56.942 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/81117459: album://81117455 not found on provider tidal
2023-08-02 15:29:57.344 WARNING (ThreadPoolExecutor-0_1) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:57.346 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/38015027: album://38015024 not found on provider tidal
2023-08-02 15:29:57.506 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:57.507 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/164966692: album://164966685 not found on provider tidal
2023-08-02 15:29:57.990 WARNING (ThreadPoolExecutor-0_1) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:57.992 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/119873464: album://119873456 not found on provider tidal
2023-08-02 15:29:58.158 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:58.160 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/29972390: album://29972384 not found on provider tidal
2023-08-02 15:29:58.318 WARNING (ThreadPoolExecutor-0_3) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:58.320 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/77755089: album://77755084 not found on provider tidal
2023-08-02 15:29:58.701 WARNING (ThreadPoolExecutor-0_1) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:58.704 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/128388407: album://128388405 not found on provider tidal
2023-08-02 15:29:59.168 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:59.169 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/73946036: album://73946033 not found on provider tidal
2023-08-02 15:29:59.320 WARNING (ThreadPoolExecutor-0_3) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:59.322 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/41881101: album://41881099 not found on provider tidal
2023-08-02 15:29:59.499 WARNING (ThreadPoolExecutor-0_1) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:59.501 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/35344156: album://35344155 not found on provider tidal
2023-08-02 15:29:59.665 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:59.666 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/35619010: album://35619001 not found on provider tidal
2023-08-02 15:29:59.828 WARNING (ThreadPoolExecutor-0_3) [tidalapi.request] HTTP error on 404
2023-08-02 15:29:59.829 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/81434227: album://81434208 not found on provider tidal
2023-08-02 15:30:00.740 WARNING (ThreadPoolExecutor-0_4) [tidalapi.request] HTTP error on 404
2023-08-02 15:30:00.742 WARNING (MainThread) [music_assistant.providers.tidal] Skipping sync of item tidal://track/130567356: album://130567355 not found on provider tidal
2023-08-02 15:30:00.954 WARNING (MainThread) [music_assistant.music] Sync task for Tidal completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 418, in sync_library
    library_item = await controller.add_item_to_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 172, in add_item_to_library
    item.metadata.images.append(item.album.image)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
```

### Additional information

I checked some of the items that Tidal's unable to find according to the logs, and they seem to be actually unavailable through the website as well.

### What version of Home Assistant Core are your running

2023.7.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by jozefKruszynski** [comment]
Will be fixed in the next release

**Comment by OzGav** [comment]
@Sirs0ri Please confirm this has been fixed

**Comment by Sirs0ri** [comment]
refreshing the tidal library no longer throws an error, looks good
