### ISSUE TITLE
Casting to google nest groups fails (sort off)

### ISSUE THREAD

**Issue by HA-TB303** [music-assistant/hass-music-assistant#1431]
### What version of Music Assistant has the issue?

2.0.0b63 

### The problem

When playing streaming radio via MA and then tts.cloud a message to 1 single speaker, all is OK
1. Music plays
2. music stops
3. message is played (without the ' ding'  announcement sound)
4. music continues.

When doing the same thing, but then cast the message to a google speaker group (3 google devices, containing also the speaker above)) the message is played multiple times

1. Music plays
2. music stops
3. message is played (without the 'ding' announcement sound)
4. message is played again...
5. message is played again.....
6. music continues.

### How to reproduce

Play music via the radio browser to one single speaker.

![CleanShot 2023-08-02 at 20 56 33](https://github.com/music-assistant/hass-music-assistant/assets/9609805/7f38583c-7c24-47ec-a297-79d9350e6b23)

Play the message to the same (one) speaker:

![CleanShot 2023-08-02 at 20 44 49](https://github.com/music-assistant/hass-music-assistant/assets/9609805/9876b733-4fcc-4c15-89e1-8dd7d1c0e344)

All is good.

Play the message to a google speaker group (speaker group made in the google home app and contains 3 speakers):

![CleanShot 2023-08-02 at 20 44 17](https://github.com/music-assistant/hass-music-assistant/assets/9609805/8fd462b2-7276-4ece-8b39-144dd9215814)

The message is played 3 times...

### Relevant log output

Music Assistant BETA
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 331, in get_item
    return await self.mass.get_provider("url").parse_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/url/__init__.py", line 106, in parse_item
    item_id, url, media_info = await self._get_media_info(item_id_or_url, force_refresh)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/url/__init__.py", line 174, in _get_media_info
    media_info = await parse_tags(url)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 357, in parse_tags
    raise InvalidDataError(f"Unable to retrieve info for {file_path}: {str(err)}") from err
music_assistant.common.models.errors.InvalidDataError: Unable to retrieve info for https://my.ha.com:8123/api/tts_proxy/48a030bc7d17da7efaf3beb706a2fe9c2aaa4d1d_nl-nl_e09b5a0968_cloud.audiooutput.mp3: Server returned 404 Not Found
2023-08-02 20:26:30.149 ERROR (MainThread) [music_assistant.webserver] [140661638189904] Error handling message: CommandMessage(message_id=2, command='music/albums/get_album', args={'item_id': '4', 'provider_instance_id_or_domain': 'library'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 71, in get
    album = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 165, in get
    library_item = await self.get_library_item_by_prov_id(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 303, in get_library_item_by_prov_id
    return await self.get_library_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 292, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 4
2023-08-02 20:26:31.226 ERROR (MainThread) [music_assistant.webserver] [140661638189904] Error handling message: CommandMessage(message_id=7, command='music/recently_played_items', args={'limit': 10, 'media_types': ['track', 'radio']})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 346, in parse_tags
    raise InvalidDataError(error["string"])
music_assistant.common.models.errors.InvalidDataError: Server returned 404 Not Found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 301, in recently_played
    item = await self.get_item(media_type, db_row["item_id"], db_row["provider"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 331, in get_item
    return await self.mass.get_provider("url").parse_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/url/__init__.py", line 106, in parse_item
    item_id, url, media_info = await self._get_media_info(item_id_or_url, force_refresh)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/url/__init__.py", line 174, in _get_media_info
    media_info = await parse_tags(url)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 357, in parse_tags
    raise InvalidDataError(f"Unable to retrieve info for {file_path}: {str(err)}") from err
music_assistant.common.models.errors.InvalidDataError: Unable to retrieve info for https://my.ha.com:8123/api/tts_proxy/48a030bc7d17da7efaf3beb706a2fe9c2aaa4d1d_nl-nl_e09b5a0968_cloud.audiooutput.mp3: Server returned 404 Not Found
2023-08-02 20:26:40.979 INFO (ThreadPoolExecutor-0_3) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-08-02 20:34:14.554 INFO (ThreadPoolExecutor-0_0) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-08-02 20:42:25.130 INFO (ThreadPoolExecutor-0_1) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-08-02 20:42:41.740 INFO (ThreadPoolExecutor-0_3) [pychromecast] Quitting current app
2023-08-02 20:42:41.741 INFO (ThreadPoolExecutor-0_3) [pychromecast.controllers] Receiver:Stopping current app 'CC1AD845'
2023-08-02 20:42:43.971 INFO (ThreadPoolExecutor-0_8) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-08-02 20:47:16.792 ERROR (MainThread) [music_assistant.webserver] [140661993153104] Error handling message: CommandMessage(message_id='515508a1d8b54cd9aaed04354ef94f15', command='players/queue/play_media', args={'queue_id': 'e42f75a7-2a3d-4d00-84b6-de770cb5353e', 'media': 'https://my.ha.com:8123/api/tts_proxy/a6cb4243dd9b6d56c4188f1da57377d5073ac296_en-gb_e09b5a0968_cloud.audiooutput.mp3', 'option': 'play', 'radio_mode': False})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 280, in play_media
    await self.play_index(queue_id, cur_index)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 519, in play_index
    raise FileNotFoundError(f"Unknown index/id: {index}")
FileNotFoundError: Unknown index/id: 1
2023-08-02 20:48:18.103 ERROR (MainThread) [music_assistant.webserver] [140661595018256] Error handling message: CommandMessage(message_id=10, command='music/recently_played_items', args={'limit': 10, 'media_types': ['track', 'radio']})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 346, in parse_tags
    raise InvalidDataError(error["string"])
music_assistant.common.models.errors.InvalidDataError: Server returned 404 Not Found
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 301, in recently_played
    item = await self.get_item(media_type, db_row["item_id"], db_row["provider"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 331, in get_item
    return await self.mass.get_provider("url").parse_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/url/__init__.py", line 106, in parse_item
    item_id, url, media_info = await self._get_media_info(item_id_or_url, force_refresh)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/url/__init__.py", line 174, in _get_media_info
    media_info = await parse_tags(url)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 357, in parse_tags
    raise InvalidDataError(f"Unable to retrieve info for {file_path}: {str(err)}") from err
music_assistant.common.models.errors.InvalidDataError: Unable to retrieve info for https://my.ha.com:8123/api/tts_proxy/48a030bc7d17da7efaf3beb706a2fe9c2aaa4d1d_nl-nl_e09b5a0968_cloud.audiooutput.mp3: Server returned 404 Not Found

### What version of Home Assistant Core are your running

2023.07.03 and 2023.08.01

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by HA-TB303** [comment]
I have tried re-producing the same thing several times, sometimes I succeed, but just now I tried and then it plays the test message in the test-window one time, and then I previous (different) test message I used earlier, another 3 times and then continues playing radio.

Sometimes the radio does not continue after playing the test-message.

I am getting very unpredictable behaviour.

**Comment by OzGav** [comment]
Thanks for the extra testing. We will get to this in due course.

**Comment by OzGav** [comment]
Just an update. This will be fixed when the TTS implementation is finished. It is on the roadmap but ETA still unknown. Thanks for your patience

**Comment by HA-TB303** [comment]
Great, thx!

**Comment by janstadt** [comment]
Any updates on TTS? I see it as in progress on the projects but i dont see any branch or anything associated with the feature. Would really love this to get implemented so i can switch over from LMS.

**Comment by OzGav** [comment]
It is being worked on. There is a desire to have this done by the end of the month but it depends on workload.

**Comment by marcelveldt** [comment]
This one has been implemented. Please test with beta124 (and beta125 even has a few follow up fixes for TTS/announcements)
