### ISSUE TITLE
Can't update from 2.0.0b63 to 2.0.0b64 on Home Assistant OS

### ISSUE THREAD

**Issue by JimmyMPage** [music-assistant/hass-music-assistant#1433]
### What version of Music Assistant has the issue?

2023.7.3 and 2023.8.0

### The problem

When I attempt to update to MA 2.0.0b64, I get the error noted below in the logs.

### How to reproduce

Attempt update

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:11:40 PM (1 occurrences)
Last logged: 10:11:40 PM

[281472996469952] Error updating Music Assistant BETA: Can't install ghcr.io/music-assistant/server:2.0.0b64: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.0.0b64&fromImage=ghcr.io%2Fmusic-assistant%2Fserver&platform=linux%2Farm64: Internal Server Error ("manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 52, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/music-assistant/server:2.0.0b64: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.0.0b64&fromImage=ghcr.io%2Fmusic-assistant%2Fserver&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 421, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Music Assistant BETA: Can't install ghcr.io/music-assistant/server:2.0.0b64: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.0.0b64&fromImage=ghcr.io%2Fmusic-assistant%2Fserver&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

### Additional information

I attempted the update from the "Settings" page in HA and also from the Add-Ons area. The same error occurred for both attempts. I also updated Home Assistant to 2023.8.0 and the same error occurred after the HA update.

### What version of Home Assistant Core are your running

2023.8.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Yes problem with the repo. Will take a little while to resolve

**Comment by OzGav** [comment]
beta 65 released

**Comment by JimmyMPage** [comment]
Thanks!
