### ISSUE TITLE
v1.0.17 - Unable to play Music from network drive - Failed to cast media 

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#144]
I'm unable to play _any_ music from my Network drive - local music plays fine. Here is a sample error log - note this file plays fine via Network via built-in Home Assistant Media Player. Note the "Provider database is not available" issue precedes this ...

The device I'm trying to play it on is a Nvidia Shield. Thanks

```
2022-05-12 13:06:47 WARNING (MainThread) [music_assistant.mass.music] Provider database is not available
2022-05-12 13:06:47 WARNING (MainThread) [music_assistant.mass.music] Provider database is not available
2022-05-12 13:06:47 WARNING (MainThread) [music_assistant.mass.music] Provider database is not available
2022-05-12 13:06:47 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py", line 144, in serve_queue_stream
    start_streamdetails = await queue.queue_stream_prepare()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 706, in queue_stream_prepare
    return await get_stream_details(self.mass, next_item, self.queue_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 205, in get_stream_details
    for prov_media in sorted(
TypeError: '<' not supported between instances of 'NoneType' and 'MediaQuality'
2022-05-12 13:06:47 ERROR (Thread-16) [homeassistant.components.cast.media_player] Failed to cast media http://192.168.1.74:8095/media_player.shield.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
```

**Comment by marcelveldt** [comment]
Although the error is not so nice (and I should fix that) this error is a cause of the other issue where your mounted drive is not yet available when HA is started. My hopes are that the temporary fix I've implemented for that in version 1.0.18 is also going to prevent this error from happening.

**Comment by Ameglialuna** [comment]
Can I ask how did you configure the local path? 
I have files on media folder, I enabled "Enable filesystem provider" but for each directory i write I always have "Directory does not exist or not accessible"

**Comment by vk2him** [comment]
Fixed in new version - thanks
