### ISSUE TITLE
No track in the playlist when playing an album 

### ISSUE THREAD

**Issue by gost4711** [music-assistant/hass-music-assistant#1444]
### What version of Music Assistant has the issue?

2.0.0b68

### The problem

I updated from version b59 to b68. Now no album can be played anymore, but tracks work. I have tested with spotify.

### How to reproduce

I select the album and choose play.

### What version of Home Assistant Core are your running

2023.8.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please post relevant logs

**Comment by OzGav** [comment]
Also I am unable to reproduce. If possible please try a fresh install of the b69 addon as it might be an issue with the big jump in versions

**Comment by gost4711** [comment]
I now have B69 installed. Unfortunately the error still exists. Playlists cannot be played all at once either.
How can I create a log?

<img width="770" alt="s1" src="https://github.com/music-assistant/hass-music-assistant/assets/33178509/d3070e9d-af5f-473b-981a-4d7ff2816532">
<img width="797" alt="s2" src="https://github.com/music-assistant/hass-music-assistant/assets/33178509/d80f532b-8d0f-4e95-8da8-16b9203cb1ce">

**Comment by OzGav** [comment]
Ok someone else had a similar error. It looks like your database is corrupted. You will need to completely remove the addon and reinstall. Can you think what you might have done to cause this?

**Comment by OzGav** [comment]
You also need to remove the integration and reinstall that. Did you restore a partial backup perhaps?

**Comment by gost4711** [comment]
I haven't done anything except install the new version.
I have now deleted MA and reinstalled it. The problem is still there.
I found that I can select all the tracks and then right click and play it works.
Nothing happens with the top button.

2023-08-06 17:57:40.309 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as xanaka1911
2023-08-06 17:57:42.888 INFO (MainThread) [music_assistant.providers.slimproto.cli] Client connected on Telnet CLI
2023-08-06 17:58:08.007 ERROR (MainThread) [music_assistant.webserver] [139626573254672] Error handling message: CommandMessage(message_id=23, command='players/queue/play_media', args={'queue_id': 'aa:aa:b1:75:e5:69', 'media': ['spotify://album/3bTNxJYk2bwdWBMtrjBxb0'], 'option': 'replace'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 218, in play_media
    await self.mass.music.mark_item_played(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 508, in mark_item_played
    await self.database.insert(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 105, in insert
    await self.execute(sql_query, values)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: table playlog has no column named media_type

**Comment by marcelveldt** [comment]
Did you reinstall the addon too?

**Comment by gost4711** [comment]
Yes, I first deleted the integration and then via HACS

**Comment by gost4711** [comment]
Sorry, I forgot something and will try again.

**Comment by gost4711** [comment]
Now everything works again. Thanks for the help.

**Comment by gost4711** [comment]
Yes, I have now reinstalled the addon
