### ISSUE TITLE
Warning thrown when MA parses track causing track to be inaccessible

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1453]
### What version of Music Assistant has the issue?

20.0.0b70

### The problem

When parsing a couple of tracks in my collection I am seeing a message similar to this one:

`2023-08-08 00:19:36.818 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Could not parse uri/file filesystem_smb://track/Soundtracks/Forrest Gump The Soundtrack/Disc 1/09. Respect - Aretha Franklin.flac to track: track://Soundtracks/Forrest Gump The Sound not found on provider filesystem_smb `

yet this was found on the initial scan and you can see it here on disc: 

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/78cb4441-27f2-4ee2-af2e-03453be81bb7)

and here in the library

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/96c4285a-647b-422e-92cf-25c01653d46a)

I do notice that in the warning the full tracks uri is not shown....

### How to reproduce

It occurs on the inital scan and when subsequently trying to access the track

### What version of Home Assistant Core are your running

2023.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Still a problem with b74. But tracks appear in the library ok. It seems no I only see the following error if I browse to this album and try and play a track from there
```
2023-11-09 21:55:41.421 ERROR (MainThread) [music_assistant.webserver] [546431631824] Error handling message: CommandMessage(message_id=145, command='music/item_by_uri', args={'uri': 'filesystem_smb://track/Soundtracks/Forrest Gump The Soundtrack/Disc 1/01. Hound Dog - Elvis Presley.flac'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 308, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 332, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 69, in get
    track = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 187, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 430, in get_provider_item
    raise MediaNotFoundError(
music_assistant.common.models.errors.MediaNotFoundError: track://Soundtracks/Forrest Gump The Sound not found on provider filesystem_smb
2023-11-09 21:55:42.920 ERROR (MainThread) [music_assistant.webserver] [546431631824] Error handling message: CommandMessage(message_id=146, command='players/queue/play_media', args={'queue_id': '80:1f:02:ab:1b:53', 'media': ['filesystem_smb://track/Soundtracks/Forrest Gump The Soundtrack/Disc 1/01. Hound Dog - Elvis Presley.flac'], 'option': 'play'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 194, in play_media
    media_item = await self.mass.music.get_item_by_uri(item)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 308, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 332, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 69, in get
    track = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 187, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 430, in get_provider_item
    raise MediaNotFoundError(
music_assistant.common.models.errors.MediaNotFoundError: track://Soundtracks/Forrest Gump The Sound not found on provider filesystem_smb

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 197, in play_media
    raise MediaNotFoundError(f"Invalid uri: {item}") from err
music_assistant.common.models.errors.MediaNotFoundError: Invalid uri: filesystem_smb://track/Soundtracks/Forrest Gump The Soundtrack/Disc 1/01. Hound Dog - Elvis Presley.flac
```

**Comment by OzGav** [comment]
Still a problem with b78

**Comment by marcelveldt** [comment]
I am testing this but its impossible to reproduce on the local file provider ( I recreated your file/directory structure). So this is either an issue related to SMB (path too long maybe?) or its solved in one of the recent betas.

**Comment by marcelveldt** [comment]
scrap that - the moment I typed this message I could reproduce it
