### ISSUE TITLE
Unable to add players to V2

### ISSUE THREAD

**Issue by Surgical17** [music-assistant/hass-music-assistant#1470]
### What version of Music Assistant has the issue?

2.0.0b70

### The problem

Unable to add any providers to Music Assistant V2

### How to reproduce

Screenshots attached

### Relevant log output

2023-08-13 10:40:25.213 DEBUG (MainThread) [music_assistant.server.controllers.config] Loaded persistent settings from /data/settings.json
2023-08-13 10:40:25.219 DEBUG (MainThread) [music_assistant.server.controllers.config] Started.
2023-08-13 10:40:25.220 INFO (MainThread) [music_assistant] Starting Music Assistant Server (5bd3f7d64f37406fb1059697e66fbeec) version 2.0.0b70 - uvloop: False
2023-08-13 10:40:25.359 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2023-08-13 10:40:26.678 INFO (MainThread) [music_assistant.music] Setting up the sync interval to 180 minutes.
2023-08-13 10:40:27.777 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.3 with libsoxr support
2023-08-13 10:40:27.777 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.0.100:8096
2023-08-13 10:40:27.798 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OSError(98, "error while attempting to bind on address ('0.0.0.0', 8096): address already in use")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 143, in start
    await self.streams.setup(await self.config.get_core_config("streams"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 347, in setup
    await self._server.setup(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/webserver.py", line 71, in setup
    await self._tcp_site.start()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8096): address already in use
2023-08-13 10:41:25.777 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Connection from 172.30.32.2
2023-08-13 10:41:26.058 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Handling command players/all
2023-08-13 10:41:26.059 WARNING (MainThread) [music_assistant.webserver] [139703753151888] Invalid command: players/all
2023-08-13 10:41:26.294 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Handling command music/artists/library_items
2023-08-13 10:41:28.182 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Handling command config/providers
2023-08-13 10:41:28.183 WARNING (MainThread) [music_assistant.webserver] [139703753151888] Invalid command: config/providers
2023-08-13 10:41:31.602 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Handling command config/core
2023-08-13 10:41:31.603 WARNING (MainThread) [music_assistant.webserver] [139703753151888] Invalid command: config/core
2023-08-13 10:41:37.744 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Handling command config/players
2023-08-13 10:41:37.745 WARNING (MainThread) [music_assistant.webserver] [139703753151888] Invalid command: config/players
2023-08-13 10:41:38.572 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Handling command config/providers
2023-08-13 10:41:38.574 WARNING (MainThread) [music_assistant.webserver] [139703753151888] Invalid command: config/providers
2023-08-13 10:42:03.581 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Handling command config/core
2023-08-13 10:42:03.583 WARNING (MainThread) [music_assistant.webserver] [139703753151888] Invalid command: config/core
2023-08-13 10:42:12.599 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Unsubscribed from events
2023-08-13 10:42:12.601 DEBUG (MainThread) [music_assistant.webserver] [139703753151888] Disconnected
2023-08-13 10:47:28.897 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Connection from 172.30.32.2
2023-08-13 10:47:29.051 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Handling command players/all
2023-08-13 10:47:29.052 WARNING (MainThread) [music_assistant.webserver] [139703753200912] Invalid command: players/all
2023-08-13 10:47:29.286 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Handling command music/artists/library_items
2023-08-13 10:47:31.100 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Handling command config/providers
2023-08-13 10:47:31.102 WARNING (MainThread) [music_assistant.webserver] [139703753200912] Invalid command: config/providers
2023-08-13 10:47:36.961 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Handling command config/core
2023-08-13 10:47:36.962 WARNING (MainThread) [music_assistant.webserver] [139703753200912] Invalid command: config/core
2023-08-13 10:48:52.045 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Unsubscribed from events
2023-08-13 10:48:52.047 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Disconnected
2023-08-13 10:48:56.168 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Connection from 172.30.32.2
2023-08-13 10:48:56.305 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Handling command players/all
2023-08-13 10:48:56.307 WARNING (MainThread) [music_assistant.webserver] [139703753200912] Invalid command: players/all
2023-08-13 10:48:56.519 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Handling command music/artists/library_items
2023-08-13 10:49:00.441 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Handling command config/providers
2023-08-13 10:49:00.442 WARNING (MainThread) [music_assistant.webserver] [139703753200912] Invalid command: config/providers
2023-08-13 10:49:01.489 DEBUG (MainThread) [music_assistant.webserver] [139703753200912] Handling command config/core
2023-08-13 10:49:01.491 WARNING (MainThread) [music_assistant.webserver] [139703753200912] Invalid command: config/core

### Additional information

![image](https://github.com/music-assistant/hass-music-assistant/assets/76941635/dae22047-69f3-4b29-b21d-87eb1b79ef95)

### What version of Home Assistant Core are your running

2023.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please go through the trouble shooting FAQ. Additionally, you might have a network setup problem so look closely at that. Lastly you haven’t added any music providers.

**Comment by marcelveldt** [comment]
Do you also have Emby installed ?
If so, you may want to change the port for the stream server to something else than 8096

**Comment by Surgical17** [comment]
> Do you also have Emby installed ? If so, you may want to change the port for the stream server to something else than 8096

Was not Emby but was Jellyfin. Turned it off, changed the port of Music assistant and then everything was sorted. Thanx for the help
