### ISSUE TITLE
[TIDAL] Error when starting a radio based on a playlist

### ISSUE THREAD

**Issue by MarvinSchenkel** [music-assistant/hass-music-assistant#1475]
### What version of Music Assistant has the issue?

2023.6.0b3

### The problem

When starting a radio based on a playlist, nothing happens and an error is thrown in the logs

### How to reproduce

1. Go to the playlist UI
2. Select a playlist
3. Click 'Play' > 'Start radio'

### Relevant log output

```
2023-08-17 12:52:15.252 ERROR (MainThread) [music_assistant.webserver] [140173901331984] Error handling message: CommandMessage(message_id=121, command='players/queue/play_media', args={'queue_id': 'ugp_1', 'media': ['library://playlist/26'], 'option': 'replace', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 238, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 881, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 560, in dynamic_tracks
    return await self._get_provider_dynamic_tracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 351, in _get_provider_dynamic_tracks
    similar_tracks = await provider.get_similar_tracks(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/__init__.py", line 319, in get_similar_tracks
    for track in await get_similar_tracks(tidal_session, prov_track_id, limit)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/helpers.py", line 275, in get_similar_tracks
    return await asyncio.to_thread(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tidal/helpers.py", line 269, in inner
    return TidalTrack(session, prov_track_id).get_track_radio(limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Track.get_track_radio() takes 1 positional argument but 2 were given
```

### What version of Home Assistant Core are your running

2023.8.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Are we satisfied the commit will fix this so we can close here?
