### ISSUE TITLE
Blue Play Button doesn't play

### ISSUE THREAD

**Issue by sspaul1976** [music-assistant/hass-music-assistant#1479]
### What version of Music Assistant has the issue?

2.0.0b73

### The problem

When hitting the blue Play button, nothing seems to happen whether selecting "play now" or "start radio".  Using YouTube Music provider and Google players. 

### How to reproduce

From any method, artist, tracks, playlist, etc. Click blue Play button and make a selection.  Dialog closes but nothing plays and info bar doesn't show anything. 

![Screenshot_20230817-213049](https://github.com/music-assistant/hass-music-assistant/assets/6181510/4d929159-7b53-469e-a163-41ee9dd6cec6)

### Relevant log output

             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 210, in play_media
    await self.mass.music.mark_item_played(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 508, in mark_item_played
    await self.database.insert(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 105, in insert
    await self.execute(sql_query, values)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: table playlog has no column named media_type
2023-08-17 21:21:04.628 ERROR (MainThread) [music_assistant.webserver] [281472768402768] Error handling message: CommandMessage(message_id=11, command='players/queue/play_media', args={'queue_id': 'cb17f464-e9a2-9940-7389-c4706c6cab9a', 'media': ['library://playlist/4'], 'option': 'replace', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 238, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 881, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 560, in dynamic_tracks
    return await self._get_provider_dynamic_tracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 346, in _get_provider_dynamic_tracks
    base_tracks = random.sample(playlist_tracks, 5)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/random.py", line 456, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
2023-08-17 21:28:17.007 ERROR (MainThread) [music_assistant.webserver] [281472769948368] Error handling message: CommandMessage(message_id=10, command='players/queue/play_media', args={'queue_id': 'cb17f464-e9a2-9940-7389-c4706c6cab9a', 'media': ['library://artist/5'], 'option': 'play', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 238, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 881, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 560, in dynamic_tracks
    return await self._get_provider_dynamic_tracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 346, in _get_provider_dynamic_tracks
    base_tracks = random.sample(playlist_tracks, 5)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/random.py", line 456, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
2023-08-17 21:29:44.998 ERROR (MainThread) [music_assistant.webserver] [281472769948368] Error handling message: CommandMessage(message_id=15, command='players/queue/play_media', args={'queue_id': 'cb17f464-e9a2-9940-7389-c4706c6cab9a', 'media': ['library://playlist/4'], 'option': 'replace', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 238, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 881, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 560, in dynamic_tracks
    return await self._get_provider_dynamic_tracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 346, in _get_provider_dynamic_tracks
    base_tracks = random.sample(playlist_tracks, 5)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/random.py", line 456, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
2023-08-17 21:30:24.426 ERROR (MainThread) [music_assistant.webserver] [281472769948368] Error handling message: CommandMessage(message_id=36, command='players/queue/play_media', args={'queue_id': 'cb17f464-e9a2-9940-7389-c4706c6cab9a', 'media': ['ytmusic://artist/UCEBTD8bc2J7wG7Fqhss7Jow'], 'option': 'play', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 238, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 881, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 560, in dynamic_tracks
    return await self._get_provider_dynamic_tracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 346, in _get_provider_dynamic_tracks
    base_tracks = random.sample(playlist_tracks, 5)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/random.py", line 456, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

### What version of Home Assistant Core are your running

2023.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Do you have another music provider you can try? I just used local media and casted it no problems. We just need to work out of this is a YouTube specific problem…

**Comment by OzGav** [comment]
Also does it work if you right click and select play now or if you use the menu?

**Comment by sspaul1976** [comment]
I am using a tablet on the wall, so can't right click. It does seem to work
if I select a song and hit play now or start radio from that dialog, just
not from the blue Play button dialog.

**Comment by OzGav** [comment]
Long press then. Ok weird that it works for me. Have you tried from other browsers?

**Comment by sspaul1976** [comment]
Blue button doesn't seem to respond to long press, but on the track it
does.  I've tried this through the companion app for Android and get the
same issue.

**Comment by OzGav** [comment]
If it is an android tablet as well then might be good if you could try on a PC? Or iOS device?

**Comment by sspaul1976** [comment]
The tablet is an Android as well.  I will try on a PC and let you know.
Thanks for the help!

**Comment by sspaul1976** [comment]
I have tried this morning on Windows PC and result is the same. Will not
play from blue Play button dialog ,but plays from track dialog.

**Comment by OzGav** [comment]
Ok will ask @MarvinSchenkel to have a look

**Comment by MarvinSchenkel** [comment]
Just wondering, how many tracks are there in your playlist you are trying to play a radio for?

**Comment by sspaul1976** [comment]
It doesn't seem to matter on the quantity.  I have tried with one or
dozens. What I find strange is that if I play from any individual track it
works. It's just the blue Play button it does not.

**Comment by OzGav** [comment]
Any further ideas @MarvinSchenkel ?

**Comment by MarvinSchenkel** [comment]
Can you perhaps share the Playlist that is causing this issue? This will help to recreate the issue locally.

**Comment by sspaul1976** [comment]
The playlist doesn't seem to matter. It happens regardless of what I pick.

**Comment by OzGav** [comment]
Do you have any other provider that works? If not add radio browser and see if that works

**Comment by OzGav** [comment]
If we don't have any further followup on this we will cose this soon.
