### ISSUE TITLE
Deezer Sync not working with large library

### ISSUE THREAD

**Issue by fuslwusl** [music-assistant/hass-music-assistant#1497]
### What version of Music Assistant has the issue?

2.0.0b73

### The problem

My large music library gets not synced. I only get about 3000 tracks from more than 40k and small amout of albums and artists. Playlists are completely empty.

### How to reproduce

I think this problem is related to large music libraries in Deezer.

### Relevant log output

2023-08-27 08:57:09.662 WARNING (MainThread) [music_assistant.providers.deezer] Failed getting album: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
2023-08-27 08:57:09.741 WARNING (MainThread) [music_assistant.music] Sync task for Deezer completed with errors
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 576, in run_sync
  |     await provider.sync_library(media_types)
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 386, in sync_library
  |     library_item = await controller.add_item_to_library(
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 115, in add_item_to_library
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 147, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 116, in add_item_to_library
    |     for track in await self._get_provider_album_tracks(item.item_id, item.provider):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 291, in _get_provider_album_tracks
    |     for track in await prov.get_album_tracks(item_id):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 284, in get_album_tracks
    |     album = await self.client.get_album(album_id=int(prov_album_id))
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 195, in get_album
    |     return await self.request("GET", f"album/{album_id}")
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 174, in request
    |     raise DeezerErrorResponse(json_data)
    | deezer.exceptions.DeezerErrorResponse: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
    +------------------------------------
2023-08-27 08:57:33.785 WARNING (MainThread) [music_assistant.providers.deezer] Failed getting album: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
2023-08-27 08:57:33.860 WARNING (MainThread) [music_assistant.music] Sync task for Deezer completed with errors
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 576, in run_sync
  |     await provider.sync_library(media_types)
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 386, in sync_library
  |     library_item = await controller.add_item_to_library(
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 115, in add_item_to_library
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 147, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 116, in add_item_to_library
    |     for track in await self._get_provider_album_tracks(item.item_id, item.provider):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 291, in _get_provider_album_tracks
    |     for track in await prov.get_album_tracks(item_id):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 284, in get_album_tracks
    |     album = await self.client.get_album(album_id=int(prov_album_id))
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 195, in get_album
    |     return await self.request("GET", f"album/{album_id}")
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 174, in request
    |     raise DeezerErrorResponse(json_data)
    | deezer.exceptions.DeezerErrorResponse: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
    +------------------------------------

### What version of Home Assistant Core are your running

2023.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by Un10ck3d** [comment]
Hey @fuslwusl, thanks for reporting the issue, i will look at it when I get home later. Looks like a rate limiting issue. 
More than 40.000 items?! Woah 🤯 😉

**Comment by Un10ck3d** [comment]
Hey, sorry for taking a while to respond. What happens if you try to resynchronize Deezer? (Ma settings -> Deezer three dots -> synchronize now)
Do more tracks show up? Does it give any new errors in the log? Does it crash?

Could you post more of the log? It's a bit hard to reproduce the issue 😅

**Comment by fuslwusl** [comment]
Thanx for trying to fix this problem!
Here are some more logs - 3239 songs before sync:

```
2023-08-29 21:06:02.790 ERROR (Thread-7) [pychromecast.controllers.media] Exception thrown when calling media status callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 737, in _fire_status_changed
    listener.new_media_status(self.status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/helpers.py", line 160, in new_media_status
    self.prov.on_new_media_status(self.castplayer, status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/__init__.py", line 435, in on_new_media_status
    castplayer.player.elapsed_time = status.adjusted_current_time
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 137, in adjusted_current_time
    self.current_time
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
2023-08-29 21:09:32.728 ERROR (Thread-7) [pychromecast.controllers.media] Exception thrown when calling media status callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 737, in _fire_status_changed
    listener.new_media_status(self.status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/helpers.py", line 160, in new_media_status
    self.prov.on_new_media_status(self.castplayer, status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/__init__.py", line 435, in on_new_media_status
    castplayer.player.elapsed_time = status.adjusted_current_time
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 137, in adjusted_current_time
    self.current_time
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
2023-08-29 21:09:46.405 ERROR (Thread-7) [pychromecast.controllers.media] Exception thrown when calling media status callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 737, in _fire_status_changed
    listener.new_media_status(self.status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/helpers.py", line 160, in new_media_status
    self.prov.on_new_media_status(self.castplayer, status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/__init__.py", line 435, in on_new_media_status
    castplayer.player.elapsed_time = status.adjusted_current_time
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 137, in adjusted_current_time
    self.current_time
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
2023-08-29 21:14:17.095 ERROR (Thread-7) [pychromecast.controllers.media] Exception thrown when calling media status callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 737, in _fire_status_changed
    listener.new_media_status(self.status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/helpers.py", line 160, in new_media_status
    self.prov.on_new_media_status(self.castplayer, status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/__init__.py", line 435, in on_new_media_status
    castplayer.player.elapsed_time = status.adjusted_current_time
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 137, in adjusted_current_time
    self.current_time
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

```

After clicking the sync button i can see 3261 songs in my library:

```
2023-08-29 22:00:39.792 ERROR (Thread-7) [pychromecast.controllers.media] Exception thrown when calling media status callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 737, in _fire_status_changed
    listener.new_media_status(self.status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/helpers.py", line 160, in new_media_status
    self.prov.on_new_media_status(self.castplayer, status)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/chromecast/__init__.py", line 435, in on_new_media_status
    castplayer.player.elapsed_time = status.adjusted_current_time
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pychromecast/controllers/media.py", line 137, in adjusted_current_time
    self.current_time
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
2023-08-29 22:20:34.757 WARNING (MainThread) [music_assistant.providers.deezer] Failed getting album: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
2023-08-29 22:20:34.861 WARNING (MainThread) [music_assistant.music] Sync task for Deezer completed with errors
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 576, in run_sync
  |     await provider.sync_library(media_types)
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 386, in sync_library
  |     library_item = await controller.add_item_to_library(
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 115, in add_item_to_library
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 147, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 116, in add_item_to_library
    |     for track in await self._get_provider_album_tracks(item.item_id, item.provider):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 291, in _get_provider_album_tracks
    |     for track in await prov.get_album_tracks(item_id):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 284, in get_album_tracks
    |     album = await self.client.get_album(album_id=int(prov_album_id))
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 195, in get_album
    |     return await self.request("GET", f"album/{album_id}")
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 174, in request
    |     raise DeezerErrorResponse(json_data)
    | deezer.exceptions.DeezerErrorResponse: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
    +------------------------------------
```

**Comment by fuslwusl** [comment]
@Un10ck3d I tried to get more info from debug logs - but there is nothing more than the logs i postet. Is there a way to get more info or is the log i posted helpful enough?

**Comment by Un10ck3d** [comment]
Hey @fuslwusl sorry for taking so long, any log output from `music_assistant.providers.deezer` are helpful. The errors are a bit weird to be honest i am not sure what is going wrong yet.. We are currently in the progress of rewriting some of the deezer fetching code, might have something to do with that.. you could try just uploading the entire log from settings -> core -> download logfile. (Requires the webserver to be exposed i think). 
Have you uploaded mp3's to deezer yourself? Might also be that.
Sorry if it will take a while for us to fix it :slightly_frowning_face:

**Comment by Un10ck3d** [comment]
Actually just noticed there is a general sync issue.

**Comment by fuslwusl** [comment]
I migrated from Spotify to Deezer - but I never uploaded songs to Deezer or Spotify.
Sometimes Deezer removes a song from - this could be the reason for the following warning.
But that many warnings is a bit strange.

```
2023-09-01 16:31:31.069 DEBUG (MainThread) [music_assistant.event] media_item_added library://artist/859
2023-09-01 16:31:31.196 WARNING (MainThread) [music_assistant.providers.deezer] Failed getting album: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
2023-09-01 16:31:31.197 WARNING (MainThread) [music_assistant.providers.deezer] Skipping sync of item deezer://track/65217889 - error details: album://6391993 not found on provider deezer
2023-09-01 16:31:31.402 WARNING (MainThread) [music_assistant.providers.deezer] Failed getting album: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
2023-09-01 16:31:31.403 WARNING (MainThread) [music_assistant.providers.deezer] Skipping sync of item deezer://track/14228375 - error details: album://1305744 not found on provider deezer
2023-09-01 16:31:31.574 DEBUG (MainThread) [music_assistant.music.album] updated Superimpose in database: 662
2023-09-01 16:31:31.583 DEBUG (MainThread) [music_assistant.event] media_item_updated library://album/662
2023-09-01 16:31:31.586 DEBUG (MainThread) [music_assistant.event] media_item_added library://album/662
```

Just tell me when i should test a new version of the addon.

**Comment by fuslwusl** [comment]
Music Assistant version 2.0.074b improved sync a lot. Now i get most playlists but some are still missing.

**Comment by OzGav** [comment]
Thanks. There is a related report on Discord. We are keeping this open to have a further look.

**Comment by OzGav** [comment]
Just checking in. Did all the playlists eventually appear?

**Comment by fuslwusl** [comment]
@OzGav The update from b75 to b77 did not work - there are already issue reports to this topic. But i wanted to start from scratch and removed all my data and the addon. I did a fresh install of music assistant 2.0.0b77, added Deezer as music provider and checked the result. Now all my playlists are missing and many of my stared songs and albums.

Comparing MA vs Deezer
Playlists 0 of 602
Artists 599 of 521
Albums 203 of 398
Tracks 2188 of 6544

Strang is the fact that MA shows more artists than Deezer and Deezer is the only music provider in my setup.

The logs shows this:

```
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 173, in request
    |     raise DeezerErrorResponse(json_data)
    | deezer.exceptions.DeezerErrorResponse: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
    +------------------------------------
2023-12-08 03:45:48.607 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-12-08 03:45:55.618 WARNING (MainThread) [music_assistant.providers.deezer] Failed getting album: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
2023-12-08 03:45:55.688 WARNING (MainThread) [music_assistant.music] Sync task for Deezer completed with errors
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 572, in run_sync
  |     await provider.sync_library(media_types)
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 386, in sync_library
  |     library_item = await controller.add_item_to_library(
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 131, in add_item_to_library
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 132, in add_item_to_library
    |     for track in await self._get_provider_album_tracks(item.item_id, item.provider):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 290, in _get_provider_album_tracks
    |     for track in await prov.get_album_tracks(item_id):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 285, in get_album_tracks
    |     album = await self.client.get_album(album_id=int(prov_album_id))
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 194, in get_album
    |     return await self.request("GET", f"album/{album_id}")
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 173, in request
    |     raise DeezerErrorResponse(json_data)
    | deezer.exceptions.DeezerErrorResponse: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
    +------------------------------------
2023-12-08 06:45:48.608 INFO (MainThread) [music_assistant.music] Sync task for URL completed
```

**Comment by OzGav** [comment]
Please try again with beta 78

**Comment by fuslwusl** [comment]
Thanx, the playlists appear now!!!
But there are still errors in the logs - i don't know what impact this will have:

```
2023-12-10 17:02:41.828 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-659' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 156, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError
2023-12-10 19:58:51.504 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-12-10 20:00:34.680 INFO (MainThread) [music_assistant.music] Sync task for Deezer completed

```

**Comment by fuslwusl** [comment]
@OzGav I noticed that sometimes Deezer webapp shows some songs as unavailable when scrolling through playlists. After a reload of the website and scrolling to the same position the song is then shown as available again. So some errors could be related to a deezer api problem or too many requests to the api from time to time?

**Comment by arctixdev** [comment]
> Thanx, the playlists appear now!!! But there are still errors in the logs - i don't know what impact this will have:
> 
> ```
> 2023-12-10 17:02:41.828 ERROR (MainThread) [asyncio] Task exception was never retrieved
> future: <Task finished name='Task-659' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
>     await self.mass.metadata.get_track_metadata(item)
>   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
>     if metadata := await provider.get_track_metadata(track):
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 156, in get_track_metadata
>     assert isinstance(track_artist, Artist)
> AssertionError
> 2023-12-10 19:58:51.504 INFO (MainThread) [music_assistant.music] Sync task for URL completed
> 2023-12-10 20:00:34.680 INFO (MainThread) [music_assistant.music] Sync task for Deezer completed
> ```
Very cool its working now! Sorry for not really being able to help as i genually had no clue what the problem was. 
And yeah deezers api is a bit weird. It might be related. 

The error you are getting now should be fine. Its a bug I thought already was fixed tho, i can take a look at it.
