### ISSUE TITLE
Error on special character in trackdata

### ISSUE THREAD

**Issue by bafplus** [music-assistant/hass-music-assistant#150]
I try to import my local music library but it encounters (i guess) a special character and halts.
I have no clue to what audiofile is cuasing the issue.

Error log from HA:

First occurred: 09:52:01 (9 occurrences)
Last logged: 13:42:31

Job [Library sync of albums for provider Filesystem] failed with error 'utf-8' codec can't decode byte 0xe9 in position 12: invalid continuation byte.
Job [Library sync of tracks for provider Filesystem] failed with error 'utf-8' codec can't decode byte 0xe9 in position 12: invalid continuation byte.
Job [Library sync of artists for provider Filesystem] failed with error 'utf-8' codec can't decode byte 0xe9 in position 12: invalid continuation byte.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 383, in _library_items_sync
    for prov_item in await music_provider.get_library_items(media_type):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/provider.py", line 174, in get_library_items
    return await self.get_library_albums()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py", line 141, in get_library_albums
    for track in await self.get_library_tracks(True):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py", line 164, in get_library_tracks
    if track := await self._parse_track(filename):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py", line 328, in _parse_track
    tags = await self.mass.loop.run_in_executor(None, parse_tags)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py", line 325, in parse_tags
    return TinyTag.get(filename, image=True, ignore_errors=True)
  File "/usr/local/lib/python3.9/site-packages/tinytag/tinytag.py", line 194, in get
    tag.load(tags=tags, duration=duration, image=image)
  File "/usr/local/lib/python3.9/site-packages/tinytag/tinytag.py", line 208, in load
    self._parse_tag(self._filehandler)
  File "/usr/local/lib/python3.9/site-packages/tinytag/tinytag.py", line 1039, in _parse_tag
    self._determine_duration(fh)  # parse whole file to determine tags:(
  File "/usr/local/lib/python3.9/site-packages/tinytag/tinytag.py", line 1023, in _determine_duration
    data = codecs.decode(data, 'utf-8')
  File "/usr/local/lib/python3.9/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 12: invalid continuation byte

**Comment by marcelveldt** [comment]
Thanks for reporting. I'll add a guard in the code for this so that it does not completely crash.

**Comment by bafplus** [comment]
Thanks that would be great! However...as far as i can understand...its errors on the "é" character. That is a very common character so im kinda suprised it errors on that. If i cn help in providing some logs or test things let me know. Or even better, how to find out on what file it errors?

**Comment by marcelveldt** [comment]
Please check if version 1.1 of the integration resolves this issue, thanks!

**Comment by bafplus** [comment]
Seems to work! Media is comming in and no error in log yet. Will let it run. Thanks for the quick fix!

**Comment by marcelveldt** [comment]
OK, great to hear!
