### ISSUE TITLE
Sync behaviour - possible bug?

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1512]
### Discussed in https://github.com/orgs/music-assistant/discussions/1457

<div type='discussions-op-text'>

<sup>Originally posted by **krisnoble** August  8, 2023</sup>
My logs show very frequent sync events despite my sync interval in the music controller settings being 180? It seems like a sync is running every 5-10 seconds based on my logs. I assume this is a bug unless there is some distinction between a full sync which happens every sync interval, and some smaller more regular sync operation?

Possibly related: I'm also having issues with transferring music over to my SMB share, I wonder if the sync process is trying to work with partially-transferred files causing them to be locked and the transfers to fail? I do also see errors in my logs that the tracks couldn't be parsed correctly for the same tracks that could not be transferred.

Example sync logs over a 2-minute period:
```
2023-08-08 09:29:05.454 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:29:05.833 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:29:15.455 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:29:15.868 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:29:21.008 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:29:21.363 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:29:21.831 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:29:22.163 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:29:25.462 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:29:25.891 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:29:35.457 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:29:35.846 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:29:45.459 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:29:46.272 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:29:55.466 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:29:55.823 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:30:05.461 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:05.866 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:30:15.465 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:15.870 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:30:21.011 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:21.342 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:30:21.832 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:22.252 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:30:25.464 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:25.882 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:30:35.465 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:35.842 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:30:35.843 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:45.469 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:46.261 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2023-08-08 09:30:55.470 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-08-08 09:30:55.882 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
```

and an example of a file error for an incomplete track:
```
2023-08-08 09:02:55.934 ERROR (MainThread) [music_assistant.providers.filesystem_smb] Error processing Chillsynth/HOME - Odyssey/HOME - Odyssey - 12 On The Way Out.mp3 - Unable to retrieve info for /tmp/filesystem_smb/Chillsynth/HOME - Odyssey/HOME - Odyssey - 12 On The Way Out.mp3: Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 346, in parse_tags
    raise InvalidDataError(error["string"])
music_assistant.common.models.errors.InvalidDataError: Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 325, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 619, in _parse_track
    tags = await parse_tags(input_file, file_item.file_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/tags.py", line 357, in parse_tags
    raise InvalidDataError(f"Unable to retrieve info for {file_path}: {str(err)}") from err
music_assistant.common.models.errors.InvalidDataError: Unable to retrieve info for /tmp/filesystem_smb/Chillsynth/HOME - Odyssey/HOME - Odyssey - 12 On The Way Out.mp3: Invalid argument
```</div>

**Comment by krisnoble** [comment]
Okay, so I've done some more testing and I think there's a couple of things happening:

1. When the config item for the sync interval is changed, it gets set in seconds rather than minutes. When the system starts, it gets correctly set in minutes.
2. When the sync interval is changed, existing sync jobs are not destroyed, and since each sync spawns a new sync with the same interval, it's possible to have multiple sync schedules running at once.

I've been able to reproduce this on both Docker and add-on installs with my full library, and also in a clean Docker install with no library. I have tried looking in the code to confirm my theories but I'm not experienced enough with Python to know if I'm missing anything like magic methods etc.

Some evidence from my logs... this is really hard to explain so I've tried to use the colours to make it easier to follow:
![image](https://github.com/music-assistant/hass-music-assistant/assets/872971/559ef9b2-ea43-4687-8be4-65ed4deb1a2d)

So what you see there is at the top, the start of the server, initialising the sync interval at 180 minutes, and performing the first sync, then nothing for the next 6 minutes, as expected.

Then, I set the sync interval to 179 minutes, and it does the initial sync after the change, then performs a sync every 179 seconds in red.

After a while I set the interval to 60 minutes, it does another initial sync and continues syncing every 60 seconds in yellow, but you can see that the red 179-second syncs are still happening.

Then, I set the interval to 180 minutes, and it starts another sync schedule every 180 seconds in green.

Hopefully that makes sense and helps narrow it down!

**Comment by OzGav** [comment]
What music providers are you using? I set my sync interval to 10mins and I saw the job done every 3 mins which is not right but certainly not every 10 secs

**Comment by krisnoble** [comment]
> What music providers are you using?

In my full library - local disk, radio browser and the default URL. So not dissimilar to yours.

In the clean Docker install, nothing except the URL.

I forgot to mention before, I wonder if the issue might be obfuscated by the length of time it takes to actually do the sync. So if your sync takes ~3 minutes to run that might be why? With just the empty URL provider the syncs are basically instant so the pattern is much clearer.

**Comment by OzGav** [comment]
Yeah not sure, I can't see in the code where the sync interval gets ultimately set when the sync task is created. Will have to wait for Marcel to have time to check this.

**Comment by marcelveldt** [comment]
reproduced and fixed in next server beta

**Comment by OzGav** [comment]
Fixed in beta74. Please report any further issues
