### ISSUE TITLE
Spotifylogin Error

### ISSUE THREAD

**Issue by Dustinhoefer** [music-assistant/hass-music-assistant#1535]
### What version of Music Assistant has the issue?

2023.6..0b3

### The problem

Logging in to Spotify gives the error "Login failed for user xyz"

### How to reproduce

Try to login to spotify

### Relevant log output

2023-09-20 20:02:30.208 WARNING (MainThread) [music_assistant.providers.spotify] Error while retrieving Spotify token after 0.33 seconds, details: 

2023-09-20 20:02:37.215 ERROR (MainThread) [music_assistant.webserver] [139898564473296] Error handling message: CommandMessage(message_id=10, command='config/providers/save', args={'provider_domain': 'spotify', 'values': {'username': 'e-mail', 'password': 'supersecretpassword', 'log_level': 'GLOBAL'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 256, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 684, in _add_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 398, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 75, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 119, in handle_setup
    await self.login()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 617, in login
    raise LoginFailed(f"Login failed for user {self.config.get_value(CONF_USERNAME)}")
music_assistant.common.models.errors.LoginFailed: Login failed for user e-mail

_No response_

### What version of Home Assistant Core are your running

2023.09.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by erkr** [comment]
Hi, just to be sure. You have paid license or free? Free accounts don't work

**Comment by Dustinhoefer** [comment]
I have a free account and also spotify just reset my password because of "suspicious activity"....

**Comment by erkr** [comment]
Sorry you missed it.  It's mentioned on many places. E.g.: https://github.com/orgs/music-assistant/discussions/816
In these discussion's all music providers are explained in detail
