### ISSUE TITLE
Sync Issue on certain albums

### ISSUE THREAD

**Issue by DarkAllMan** [music-assistant/hass-music-assistant#1543]
### What version of Music Assistant has the issue?

2.0.0b73

### The problem

A by picard tagged album does not appear in the library.

### How to reproduce

Try to add album to library

### Relevant log output

2023-09-26 11:19:41.935 ERROR (MainThread) [music_assistant.webserver] [140453291528976] Error handling message: CommandMessage(message_id=96, command='music/library/add_item', args={'item': {'media_type': 'folder', 'item_id': 'back', 'provider': 'filesystem_local', 'name': '..', 'metadata': {'description': None, 'review': None, 'explicit': None, 'images': None, 'genres': None, 'mood': None, 'style': None, 'copyright': None, 'lyrics': None, 'ean': None, 'label': None, 'links': None, 'chapters': None, 'performers': None, 'preview': None, 'replaygain': None, 'popularity': None, 'last_refresh': None, 'checksum': None}, 'provider_mappings': [{'item_id': 'back', 'provider_domain': 'filesystem_local', 'provider_instance': 'filesystem_local', 'available': True, 'audio_format': {'content_type': '?', 'sample_rate': 44100, 'bit_depth': 16, 'channels': 2, 'output_format_str': '?', 'bit_rate': 320}, 'url': None, 'isrc': None, 'barcode': None, 'details': None}], 'favorite': False, 'sort_name': '', 'uri': 'filesystem_local://folder/back', 'timestamp_added': 0, 'timestamp_modified': 0, 'path': 'filesystem_local://[re jazz]', 'label': ''}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 411, in add_item_to_library
    return await ctrl.get(
                 ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

### What version of Home Assistant Core are your running

2023.09.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Can you provide any more info. What type of track is it? Do you have more than one or is this the only track? What is the foler structure where this album is located?

**Comment by OzGav** [comment]
Do all of the problem ones have non alpha numeric characters like those []

**Comment by DarkAllMan** [comment]
I have other albums from the same artist that have been imported in the library without issues:
Filename: \\192.168.1.163\Media1\MUSIC\[re jazz]\[re jazz] - Point Of View - 2004\01. [re_Jazz] - Keep On Movin'.mp3
Format: MPEG-1 Layer 3 - ID3v2.3
Size: 11.8 MB (11.3 MiB)
Length: 4:54
Bitrate: 320.0 kbps
Sample rate: 44100 Hz
Channels: Stereo

other albums that are missing have regular characters as well.

**Comment by OzGav** [comment]
Ok will have to wait for the devs to have a look

**Comment by OzGav** [comment]
I just had another user that had an issue which was caused by the square brackets in the path name. I recommend you simplify your path names and follow the structure here https://kodi.wiki/view/Music_tagging and try again

**Comment by DarkAllMan** [comment]
ok, clear. Too bad, the artist name is with the brackets. Still strange others are indexed without issues and other music indexers have no issue with this.
I have subsonic, audiosonic, Plex running and they are fine with it.

**Comment by OzGav** [comment]
It will get looked at but just giving you the info on how you can fix it now.

**Comment by DarkAllMan** [comment]
Hi @OzGav I'm sorry I did not get back to you before, but I have left Music Assistant. I was not what I expected it to be and for me it is just not finished enough to use in my home.
