### ISSUE TITLE
Playback fails from youtube music

### ISSUE THREAD

**Issue by angusb218** [music-assistant/hass-music-assistant#1546]
### What version of Music Assistant has the issue?

 2023.6.0b3

### The problem

Playback from youtube music fails

### How to reproduce

Attempt to play any music from youtube music

### Relevant log output

2023-09-27 15:39:21.650 INFO (ThreadPoolExecutor-0_7) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-09-27 15:39:50.215 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 473, in serve_queue_item_stream
    streamdetails = await get_stream_details(self.mass, queue_item=queue_item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 268, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 498, in get_stream_details
    url = await self._parse_stream_url(stream_format=stream_format, item_id=item_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 797, in _parse_stream_url
    signature = await self._decipher_signature(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 823, in _decipher_signature
    self._cipher = await asyncio.to_thread(_decipher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 818, in _decipher
    cipher = pytube.cipher.Cipher(js=ytm_js)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
                                                               ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'span'
2023-09-27 15:39:50.235 WARNING (Thread-6) [music_assistant.providers.chromecast] Load media failed: 2 - error code: 104

### Additional information

Playback from other sources such as radio works

### What version of Home Assistant Core are your running

2023.09.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
A PR to fix this has been done. Will be in the next HA release. Estimate for that is not yet known. Thanks for your patience.

**Comment by OzGav** [comment]
Has this been fixed in b74?

**Comment by oystermon** [comment]
yes this has been fixed in beta74.
