### ISSUE TITLE
Plex Album browse hangs

### ISSUE THREAD

**Issue by skyw33** [music-assistant/hass-music-assistant#1568]
### What version of Music Assistant has the issue?

2.0.0b73

### The problem

Browsing by plex albums does not show results (perpetually loading).

### How to reproduce

Click on browse -> plex -> album 

### Relevant log output

```
2023-10-19 05:51:29.084 ERROR (MainThread) [music_assistant.webserver] [139897662403344] Error handling message: CommandMessage(message_id=24, command='music/browse', args={'path': 'plex://albums'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 362, in _run_handler
    async for item in result:
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 286, in browse
    async for item in prov.browse(path):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 285, in browse
    async for album in self.get_library_albums():
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 535, in get_library_albums
    yield await self._parse_album(album)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 328, in _parse_album
    self._get_item_mapping(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 213, in _get_item_mapping
    return ItemMapping(
           ^^^^^^^^^^^^
  File "<string>", line 11, in __init__
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 275, in __post_init__
    self.sort_name = create_sort_name(self.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/helpers/util.py", line 49, in create_sort_name
    input_str = input_str.lower().strip()
                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

```

### What version of Home Assistant Core are your running

2023.10.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
So does the Plex library otherwise load into MA? I have seen problems like this before with tagging problems.

**Comment by OzGav** [comment]
We need some follow up otherwise we will close this one.

**Comment by vhsdream** [comment]
This issue still exists on the latest Music Assistant Beta. I am unable to load albums or tracks from Browse. Loading Artists and Playlists works fine.

The logs show the same thing as the original poster. Additionally sync shows the same error except it completes 'with errors'.

> 2024-02-07 12:18:26.183 WARNING (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 572, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 367, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 583, in get_library_albums
    yield await self._parse_album(album)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 376, in _parse_album
    self._get_item_mapping(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 261, in _get_item_mapping
    return ItemMapping(
           ^^^^^^^^^^^^
  File "<string>", line 12, in __init__
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 215, in __post_init__
    self.sort_name = create_sort_name(self.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/helpers/util.py", line 51, in create_sort_name
    input_str = input_str.lower().strip()
                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'[0m
[31m2024-02-07 12:22:47.956 ERROR (MainThread) [music_assistant.webserver] [139938156119056] Error handling message: CommandMessage(message_id=33, command='music/browse', args={'path': 'plex--9CtYeCnh://albums'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 363, in _run_handler
    async for item in result:
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 282, in browse
    async for item in prov.browse(path):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 286, in browse
    async for album in self.get_library_albums():
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 583, in get_library_albums
    yield await self._parse_album(album)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 376, in _parse_album
    self._get_item_mapping(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 261, in _get_item_mapping
    return ItemMapping(
           ^^^^^^^^^^^^
  File "<string>", line 12, in __init__
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 215, in __post_init__
    self.sort_name = create_sort_name(self.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/helpers/util.py", line 51, in create_sort_name
    input_str = input_str.lower().strip()
                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
