### ISSUE TITLE
Can't create container for beta 74

### ISSUE THREAD

**Issue by LukaszP2** [music-assistant/hass-music-assistant#1581]
### What version of Music Assistant has the issue?

2.0.0b73

### The problem

When I started to update from 2.0.0b73 to 74 I got `Can't create container`

### How to reproduce

Do upgrade 

### What version of Home Assistant Core are your running

2023.11.0.b1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Have you tried again? If so docker or HAOS?

**Comment by Adunaphel** [comment]
Occurs in HAOS for me, attaching log output:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:11:19 (4 occurrences)
Last logged: 08:12:21

[140327021705280] Error updating Music Assistant BETA: Can't create container from addon_d5369777_music_assistant_beta: 400 Client Error for http+docker://localhost/v1.43/containers/create?name=addon_d5369777_music_assistant_beta: Bad Request ("invalid reference format")
[140327021705280] Error updating Music Assistant BETA: No update available for add-on d5369777_music_assistant_beta
[140326910753856] Error updating Music Assistant BETA: No update available for add-on d5369777_music_assistant_beta
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't create container from addon_d5369777_music_assistant_beta: 400 Client Error for http+docker://localhost/v1.43/containers/create?name=addon_d5369777_music_assistant_beta: Bad Request ("invalid reference format")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Music Assistant BETA: Can't create container from addon_d5369777_music_assistant_beta: 400 Client Error for http+docker://localhost/v1.43/containers/create?name=addon_d5369777_music_assistant_beta: Bad Request ("invalid reference format")
```

**Comment by OzGav** [comment]
You could do a remove and reinstall. Note you will have to recreate all settings and the database

**Comment by LukaszP2** [comment]
> Have you tried again? If so docker or HAOS?

Container goes down. But after restart it was new version and everything is OK now.
