### ISSUE TITLE
Self-titled albums not importing correctly

### ISSUE THREAD

**Issue by wmvos** [music-assistant/hass-music-assistant#1617]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

MA seems to incorrectly handle the import of self-titled albums (where album===albumartist i.e. Tenacious D - Tenacious D). I'm not sure what actually happens, but so far I've found the following three possible outcomes:

- When it is the only album of the artist in the library it ~~won't be visible within MA~~ will only be visible when the album-artist filter is toggled off(? I think, or on one of the two)
- If there are other albums from the same artist present, the tracks will be visible on the artist page, however the track info page is blank and it's not possible to play the tracks. In case the track is also present on a different album from the same artist the track of that album suffers the same fate (i.e. unplayable etc.)
- In some cases MA chooses to add the tracks to a completely random album of a different artist. Currently in my library the tracks of Black Sabbath - Black Sabbath are attributed to the album 'With The Beatles'

For the first two cases (so when no album is attributed) I'm unable to play the tracks, neither from the artist page (if available) nor from the Browse page.

When the wrong album is attributed the tracks play like normal.

### How to reproduce

Import a filesystem folder containing several self-titled albums tagged by Picard, for example:

Tenacious D - Tenacious D
The Doors - The Doors
3 Doors Down - 3 Doors Down
The United States of America - The United States of America
Black Sabbath - Black Sabbath
The Beatles - The Beatles
Ananda Shankar - Ananda Shankar
etc.

### Relevant log output

Play now from Artist Page:

```
2023-11-08 12:20:39.382 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Tenacious D
2023-11-08 12:20:41.490 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-158849' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=MediaNotFoundError('album not found in library: 304')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 151, in add_item_to_library
    await self._match(library_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 285, in _match
    track_albums = await self.albums(db_track.item_id, db_track.provider)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 239, in albums
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 240, in <listcomp>
    await self.mass.music.albums.get_library_item(album_track_row["album_id"])
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 304
2023-11-08 12:20:52.502 ERROR (MainThread) [music_assistant.webserver] [140176594980816] Error handling message: CommandMessage(message_id=54, command='players/queue/play_media', args={'queue_id': 'd8:bb:c1:6e:6b:0c', 'media': ['library://track/5568'], 'option': 'play'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 94, in get
    track.album = await self.mass.music.albums.get_library_item(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 304

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 194, in play_media
    media_item = await self.mass.music.get_item_by_uri(item)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 308, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 332, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 99, in get
    self.logger.warning("Unable to fetch album details %s", track.album.uri)
                                                            ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
```
Play now from the Browse page:

```
From Browse Page:

2023-11-08 12:19:01.709 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Tenacious D
2023-11-08 12:19:02.916 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Tenacious D/[2001] Tenacious D [mp3]
2023-11-08 12:19:06.822 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 94, in get
    track.album = await self.mass.music.albums.get_library_item(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 304

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 473, in serve_queue_item_stream
    streamdetails = await get_stream_details(self.mass, queue_item=queue_item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 254, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 308, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 332, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 99, in get
    self.logger.warning("Unable to fetch album details %s", track.album.uri)
                                                            ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
```

Accessing track info page:

Chrome console:
`Uncaught (in promise) 'NoneType' object has no attribute 'uri'`

Log:

```
2023-11-08 12:21:41.291 ERROR (MainThread) [music_assistant.webserver] [140176594980816] Error handling message: CommandMessage(message_id=55, command='music/tracks/get_track', args={'item_id': '5568', 'provider_instance_id_or_domain': 'library'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 94, in get
    track.album = await self.mass.music.albums.get_library_item(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 304

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 99, in get
    self.logger.warning("Unable to fetch album details %s", track.album.uri)
                                                            ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'uri'
```

### Additional information

![With The Beatles](https://github.com/music-assistant/hass-music-assistant/assets/64206115/cc804089-c2ae-471d-8c06-eea652845ac5)
![Tenacious D Artist Page](https://github.com/music-assistant/hass-music-assistant/assets/64206115/b7c0931c-11c9-4349-849f-c6e2fddb9683)
![3 Doors Down Artist Page](https://github.com/music-assistant/hass-music-assistant/assets/64206115/368dce3b-7414-4347-90ee-ad271d5d1c1d)
![Black Sabbath Artist Page](https://github.com/music-assistant/hass-music-assistant/assets/64206115/28ca37b3-2903-4544-a87d-4c2a81c0c899)

### What version of Home Assistant Core are your running

2023.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
I have lots of examples where this worked fine so I don't think it is a fundamental MA fault. We need to look more closely at your tagging or if it could be related to https://github.com/music-assistant/hass-music-assistant/issues/1453 

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/ada46b8e-bc22-48fb-80e7-415d6c151439)

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/4891a2fd-c7b3-46cb-bc53-888372ca29ee)

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/166338c5-8d83-4000-b607-7e28ae1b64bc)

**Comment by wmvos** [comment]
As mentioned in #1619 reinstalling MA only seems to change and not solve the behavior, it now tags every album onto a different one:

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress](https://github.com/music-assistant/hass-music-assistant/assets/64206115/55298d76-a398-4430-a9cf-e3074e3b8bb3)

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress (1)](https://github.com/music-assistant/hass-music-assistant/assets/64206115/f114496b-115a-4ee8-afef-8bb1d1f3ec6f)

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress (2)](https://github.com/music-assistant/hass-music-assistant/assets/64206115/dc2bad8f-826a-4a7a-9121-26149f68d2cc)

![10 73 21 128_8123_d5369777_music_assistant_beta_ingress_auth_callback=1 code=0138dfaa98c845fe8abf51bace1c11ac state=eyJoYXNzVXJsIjoiaHR0cDovLzEwLjczLjIxLjEyODo4MTIzIiwiY2xpZW50SWQiOiJodHRwOi8vMTAuNzMuMjEuMTI4Ojgx](https://github.com/music-assistant/hass-music-assistant/assets/64206115/d7d1ed74-79e2-4580-81c4-974e2e5c2cea)

**Comment by wmvos** [comment]
Just to be sure I created a completely new instance of HA and installed MA, the behavior si the same and the self-titled albums are all tagged in exactly the same way, so it doesn't appear to be something random.

**Comment by OzGav** [comment]
Very interesting. Initial instrict is there is something wrong with your tagging...? I'm also looking at your use of square brackets. Both of those things are unusual. I have that Dire Straits Album and it is imported correctly so I still feel it is something at your end... Could also be your folder structure as per my other recommendation. Lets do that one album import and see what happens

**Comment by wmvos** [comment]
Ok, so when importing them by single album or by single artist (with multiple albums) everything works as expected, regardless of the use of brackets in the folder name.

I then removed any brackets or other information from the folder structure, so just:

Library\Artist\Album\Track(s)

And that seems to solve this issue. So somehow the combination of extra data in the album folder name, importing multiple artists and some of these artists having self-titled albums makes things go haywire. 

I guess it gets confused for a while and picks up at the wrong point.

**Comment by OzGav** [comment]
Thanks. I will check with Marcel whether he wants to/can fix the issue with square brackets in the path name. So will leave this open for now

**Comment by OzGav** [comment]
Related to https://github.com/music-assistant/hass-music-assistant/issues/1543

**Comment by OzGav** [comment]
Recent updates have improved the tag reading and matching algorithm. Please check if any of the problems described above are still an issue.

**Comment by OzGav** [comment]
We will close this soon if no follow up is received

**Comment by wmvos** [comment]
Haven't updated yet will see if I can get to it in the next couple of days. Same for #1619

**Comment by OzGav** [comment]
We can open this again if there is more follow up.
