### ISSUE TITLE
Seemingly random tracks are not imported during sync

### ISSUE THREAD

**Issue by wmvos** [music-assistant/hass-music-assistant#1618]
### What version of Music Assistant has the issue?

 2023.6.0b6

### The problem

When importing a large mounted folder into MA (~4500 tracks) a seemingly random part of these tracks around a 100 are not imported into MA. 

I cannot find any commonality between these tracks, I haven't checked all of them but it seems to affect at most one track per album. The rest of the album tracks are imported just fine so a naming/folder structure issue seems unlikely.

All ID3 tags are created with Picard.

Playing the problem tracks from the Browse page doesn't work and gives the following warning:

```
2023-11-08 14:49:17.892 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Nick Drake
2023-11-08 14:49:26.933 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Nick Drake/[1970] Bryter Layter [2013] [mp3]
2023-11-08 14:49:57.029 WARNING (MainThread) [music_assistant.audio] Item not found: Nick Drake/[1970] Bryter Layter [2013] [mp3]/08 Poor Boy.mp3
```

### How to reproduce

Appears to be random, it affects different track numbers, artists and seems to be unrelated to #1617 because although the self-titled album The United States of America ~~is not visible in my library the logs show that one track~~ is also missing one track.

### Relevant log output

```
2023-11-08 12:10:27.861 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: The United States of America
2023-11-08 12:10:27.863 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: The United States of America/[1968] The United States of America [2004] [mp3]
2023-11-08 12:10:28.024 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: The United States of America
2023-11-08 12:10:28.042 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing The United States of America/[1968] The United States of America [2004] [mp3]/05 I Won’t Leave My Wooden Wife for You, Sugar.mp3 - album not found in library: 321
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 326, in sync_library
    await self.mass.music.tracks.add_item_to_library(track, metadata_lookup=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 148, in add_item_to_library
    library_item = await self._add_library_item(item)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 372, in _add_library_item
    track_albums = await self.albums(row_track.item_id, row_track.provider)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 239, in albums
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 240, in <listcomp>
    await self.mass.music.albums.get_library_item(album_track_row["album_id"])
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 321
2023-11-08 12:10:28.049 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Bert Jansch
2023-11-08 12:10:28.051 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Bert Jansch/[1965] Bert Jansch [2015] [mp3]
2023-11-08 12:10:28.061 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: David Crosby
2023-11-08 12:10:28.063 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: David Crosby/[1971] If I Could Only Remember My Name [1990] [mp3]
2023-11-08 12:10:28.070 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: John Lennon
2023-11-08 12:10:28.072 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: John Lennon/[1970] John Lennon_Plastic Ono Band [1988] [mp3]
2023-11-08 12:10:28.078 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Dido
2023-11-08 12:10:28.080 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Dido/[2003] Life for Rent [mp3]
2023-11-08 12:10:28.087 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Smokey Robinson and The Miracles
2023-11-08 12:10:28.088 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Smokey Robinson and The Miracles/[1965] Going to a Go‐Go [1992] [flac]
2023-11-08 12:10:28.097 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Small Faces
2023-11-08 12:10:28.099 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Small Faces/[1968] Ogdens’ Nut Gone Flake [2012] [mp3]
2023-11-08 12:10:28.268 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Small Faces
2023-11-08 12:10:32.058 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Cream
2023-11-08 12:10:32.062 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Cream/[1966] Fresh Cream [2014] [mp3]
2023-11-08 12:10:32.242 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Cream
2023-11-08 12:10:32.261 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing Cream/[1966] Fresh Cream [2014] [mp3]/06 Spoonful.mp3 - album not found in library: 252
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 326, in sync_library
    await self.mass.music.tracks.add_item_to_library(track, metadata_lookup=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 148, in add_item_to_library
    library_item = await self._add_library_item(item)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 372, in _add_library_item
    track_albums = await self.albums(row_track.item_id, row_track.provider)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 239, in albums
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 240, in <listcomp>
    await self.mass.music.albums.get_library_item(album_track_row["album_id"])
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 252
2023-11-08 12:10:32.265 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Cream/[1968] Wheels of Fire [2014] [mp3]
2023-11-08 12:10:32.460 ERROR (MainThread) [music_assistant.providers.filesystem_local] Error processing Cream/[1968] Wheels of Fire [2014] [mp3]/12 Spoonful (live).mp3 - album not found in library: 252
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 326, in sync_library
    await self.mass.music.tracks.add_item_to_library(track, metadata_lookup=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 148, in add_item_to_library
    library_item = await self._add_library_item(item)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 372, in _add_library_item
    track_albums = await self.albums(row_track.item_id, row_track.provider)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 239, in albums
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 240, in <listcomp>
    await self.mass.music.albums.get_library_item(album_track_row["album_id"])
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 252
2023-11-08 12:10:32.463 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Cream/[1967] Disraeli Gears [1992] [mp3]
2023-11-08 12:10:32.474 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: 13th Floor Elevators
2023-11-08 12:10:32.477 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: 13th Floor Elevators/[1966] The Psychedelic Sounds of the 13th Floor Elevators [1993] [mp3]
2023-11-08 12:10:32.486 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Justice
2023-11-08 12:10:32.489 DEBUG (MainThread) [music_assistant.providers.filesystem_local] Processing: Justice/[2007] ✝ [mp3]
```

### What version of Home Assistant Core are your running

2023.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Can you turn off the debug logging so that errors and warnings are easier to see

**Comment by OzGav** [comment]
Based on comment in other issue I will close this one
