### ISSUE TITLE
Real Spotify password written to logs on failed login

### ISSUE THREAD

**Issue by JeffersonBledsoe** [music-assistant/hass-music-assistant#1623]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

If somebody were able to see the logs, they would see the actual password

### How to reproduce

.

### Relevant log output

Example log from exception where I noticed this
```
2023-11-09 21:28:04.539 ERROR (MainThread) [music_assistant.webserver] [546982299088] Error handling message: CommandMessage(message_id=19, command='config/providers/save', args={'provider_domain': 'spotify', 'values': {'username': 'REDACTED_EMAIL', 'password': 'REDACTED_PASSWORD', 'log_level': 'GLOBAL', 'enabled': True, 'name': 'Spotify'}, 'instance_id': 'spotify'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 254, in save_provider_config
    config = await self._update_provider_config(instance_id, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 636, in _update_provider_config
    await self._load_provider_config(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 727, in _load_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 403, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 75, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 119, in handle_setup
    await self.login()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 617, in login
    raise LoginFailed(f"Login failed for user {self.config.get_value(CONF_USERNAME)}")
music_assistant.common.models.errors.LoginFailed: Login failed for user REDACTED_PASSWORD
```

### What version of Home Assistant Core are your running

2023.11.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Well spotted. This will get looked at

**Comment by OzGav** [comment]
Just looking at this now. It looks to me that you put your password in the login field as that error should be followed by the user name? Can you check that again….

**Comment by JeffersonBledsoe** [comment]
@OzGav I was just testing this but can't reproduce it again. It 100% printed the password naturally (and the correct fields). I'm going to close it though as I can't reproduce it
