### ISSUE TITLE
TuneIn Radio Stops After Error Thrown

### ISSUE THREAD

**Issue by rjgrandy** [music-assistant/hass-music-assistant#1627]
### What version of Music Assistant has the issue?

2.0.0b74

### The problem

I see the following error in the logs and the TuneIn Radio stops playing on my speakers:

### How to reproduce

Play TuneIn radio and wait for it to error. I'm not sure what triggers it.

### Relevant log output

````
2023-11-11 12:56:08.555 ERROR (MainThread) [music_assistant.webserver] [139625299115984] Error handling message: CommandMessage(message_id=27, command='music/item_by_uri', args={'uri': 'library://track/3101'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 308, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 332, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 69, in get
    track = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 162, in get
    library_item = await self.get_library_item_by_prov_id(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 295, in get_library_item_by_prov_id
    return await self.get_library_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: track not found in library: 3101
````

### What version of Home Assistant Core are your running

2023.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
How long does it take for you to see this error? I just played a station for 15 mins and it worked fine. Maybe this is a problem with the stream and not MA?

**Comment by OzGav** [comment]
We will have to close this soon if there is no followup
