### ISSUE TITLE
YouTube Music Stops After Errors Thrown

### ISSUE THREAD

**Issue by rjgrandy** [music-assistant/hass-music-assistant#1628]
### What version of Music Assistant has the issue?

2.0.0b74

### The problem

I play a YouTube Music playlist and eventually some errors are thrown. If I try to restart the stream it has problems and throws more errors. Please see my attached logs.

### How to reproduce

Play youtube music playlist and wait for stream to stop.

### Relevant log output

[initial_errors.txt](https://github.com/music-assistant/hass-music-assistant/files/13326317/initial_errors.txt)
[restart_stream_error.txt](https://github.com/music-assistant/hass-music-assistant/files/13326318/restart_stream_error.txt)

### What version of Home Assistant Core are your running

2023.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
It would be great if you didn’t set the logs to debug unless asked to. Can you redo the log post without all the debug lines.

**Comment by rjgrandy** [comment]
I'll update this, this weekend.

**Comment by OzGav** [comment]
We just need an update on this or we will close it as stale.

**Comment by benblb** [comment]
I just commented on another thread, but since this is YTM specific I'll throw my logs here as well. Stopping after one song. Debugging is disabled for me. 

```
2023-11-28 07:33:22.446 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Okieriete Onaodowan
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 07:34:06.610 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Various Artists - Topic
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 08:01:54.405 INFO (MainThread) [music_assistant.providers.slimproto] Player Ben’s MacBook Pro disconnected
2023-11-28 08:21:44.829 WARNING (MainThread) [music_assistant.providers.slimproto] Player squeezeplay: aa:aa:ba:52:e0:f2 connected while previous session still existing!
2023-11-28 08:28:09.537 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 08:34:02.411 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 08:45:15.558 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 09:08:14.606 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 09:15:09.374 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 09:20:03.362 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 09:45:31.305 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:12:09.434 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:17:55.067 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:22:49.186 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:29:57.143 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:30:54.236 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-11-28 10:30:59.194 ERROR (ThreadPoolExecutor-0_5) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-207302' coro=<SlimClient._socket_reader() done, defined at /usr/local/lib/python3.11/site-packages/aioslimproto/client.py:576> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 583, in _socket_reader
    data = await self._reader.read(64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 693, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 525, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2023-11-28 10:31:54.958 WARNING (MainThread) [music_assistant.music] Sync task for YouTube Music completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 570, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 366, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 259, in get_library_playlists
    playlists_obj = await get_library_playlists(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 137, in get_library_playlists
    return await asyncio.to_thread(_get_library_playlists)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 129, in _get_library_playlists
    playlists = ytm.get_library_playlists(limit=9999)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/library.py", line 41, in get_library_playlists
    get_continuations(results, 'gridContinuation', remaining_limit, request_func,
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/continuations.py", line 20, in get_continuations
    contents = get_continuation_contents(results, parse_func)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/continuations.py", line 74, in get_continuation_contents
    return parse_func(continuation[term])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/library.py", line 38, in <lambda>
    parse_func = lambda contents: parse_content_list(contents, parse_playlist)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/parsers/browsing.py", line 47, in parse_content_list
    contents.append(parse_func(result[key]))
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/parsers/browsing.py", line 121, in parse_playlist
    'title': nav(data, TITLE_TEXT),
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 83, in nav
    raise err
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 77, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'runs'
2023-11-28 10:32:04.643 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Kristolyn Lloyd
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 10:32:44.562 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Mike Faist
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 10:33:24.437 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Okieriete Onaodowan
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 10:34:07.087 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Various Artists - Topic
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 10:36:50.057 INFO (MainThread) [music_assistant.providers.slimproto] Player Ben’s MacBook Pro disconnected
2023-11-28 11:53:15.891 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 12:11:10.399 INFO (ThreadPoolExecutor-0_1) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-11-28 12:11:13.815 INFO (MainThread) [music_assistant.providers.slimproto] Player Ben’s MacBook Pro disconnected
```

**Comment by OzGav** [comment]
@MarvinSchenkel can you have a look at the YT error above.

@rjgrandy i can’t follow the “initial_errors.txt” log with all the debug lines in it. If this is still an issue then please post another log file without debug enabled. The ideal way is to restart MA and then just do the minimal steps to get the error to occur so we can the log from startup to error without any additional logging.

**Comment by MarvinSchenkel** [comment]
Looks like there's a funky playlist that is causing trouble during sync. Do you have any 'weird' playlist in your library? Like playlist with custom uploaded songs etc? Would be good if we can isolate this playlist and pinpoint the error.

**Comment by benblb** [comment]
> Looks like there's a funky playlist that is causing trouble during sync. Do you have any 'weird' playlist in your library? Like playlist with custom uploaded songs etc? Would be good if we can isolate this playlist and pinpoint the error.

I started using Google Play Music (YouTube Music) when it launched and uploaded my previous iTunes library (way back in the day) so my uploaded songs have persisted and are scattered across many playlists, but there shouldn't be any on the playlist I use with Music Assistant. I have an automation to shuffle a specific playlist when I get home. 

[The playlist](https://music.youtube.com/playlist?list=PLbs9DSo4zT9w2A7Jcv_4yC9AGh4fO-G3h&si=Ck_v5D1t0fjEhMah). 

I went through the list (which is mostly taken from another user's shared list) and found several entires with `!`. See image. I removed all of these tracks. 

![Screenshot 2023-12-14 at 9 12 42 AM](https://github.com/music-assistant/hass-music-assistant/assets/18690267/89650a03-ed1d-4e33-8904-6b15a4e6b0ba)

Just tried playing the list again and skipping a song, but got errors. 

```
2023-12-14 08:15:25.014 WARNING (MainThread) [music_assistant.music] Sync task for YouTube Music completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 366, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 259, in get_library_playlists
    playlists_obj = await get_library_playlists(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 137, in get_library_playlists
    return await asyncio.to_thread(_get_library_playlists)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 129, in _get_library_playlists
    playlists = ytm.get_library_playlists(limit=9999)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/library.py", line 41, in get_library_playlists
    get_continuations(results, 'gridContinuation', remaining_limit, request_func,
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/continuations.py", line 20, in get_continuations
    contents = get_continuation_contents(results, parse_func)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/continuations.py", line 74, in get_continuation_contents
    return parse_func(continuation[term])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/library.py", line 38, in <lambda>
    parse_func = lambda contents: parse_content_list(contents, parse_playlist)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/parsers/browsing.py", line 47, in parse_content_list
    contents.append(parse_func(result[key]))
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/parsers/browsing.py", line 122, in parse_playlist
    'title': nav(data, TITLE_TEXT),
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 82, in nav
    raise err
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 76, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'runs'
```

**Comment by OzGav** [comment]
> I went through the list (which is mostly taken from another user's shared list) and found several entires with !. See image. I removed all of these tracks.

I still see three with the exclamation mark. Additionally are any of those tracks uploaded by you or are they all publicly accessable?

**Comment by benblb** [comment]
@OzGav those tracks should all be public, I don't think I uploaded any. I checked again and see no `!` tracks remaining, maybe some are YTM premium only (assuming you may not have a subscription)? 

@MarvinSchenkel so weird! Is there a next troubleshooting step you'd like me to try?

Thank you both very much for looking into this.

**Comment by OzGav** [comment]
Yes I don’t have a subscription. FYI these are the tracks I see with an exclamation mark
![IMG_1152](https://github.com/music-assistant/hass-music-assistant/assets/19848947/26baa4e7-661f-41b2-9671-81a39085d572)

**Comment by benblb** [comment]
The subscription must be why. I didn't upload these. 

![Screenshot 2023-12-15 at 1 21 35 PM](https://github.com/music-assistant/hass-music-assistant/assets/18690267/5d074604-5e36-4626-8f41-09a8f50c4a8b)

**Comment by OzGav** [comment]
I thought it odd that I can see all the other tracks on the album though….

**Comment by OzGav** [comment]
Any updates on this? Is it still a problem?

**Comment by benblb** [comment]
Hi @OzGav, if the update question was for me, yes the problem persists.

**Comment by rjgrandy** [comment]
I also continue to have the issue. I changed to running MA in docker on Unraid instead of as an add on in HA. It is a lot better but will still stop if played long enough.

**Comment by OzGav** [comment]
> Hi @OzGav, if the update question was for me, yes the problem persists.

Have you done any more testing as @MarvinSchenkel was able to sync the playlist without issue…?

**Comment by kirashogun** [comment]
Just to add my 2 cents, the player seems only to play the current track and would not proceed to the next track in the playlist (youtube music). If I manually press next trac, it would work.

**Comment by OzGav** [comment]
> Just to add my 2 cents, the player seems only to play the current track and would not proceed to the next track in the playlist (youtube music). If I manually press next trac, it would work.

This is a different problem that will hopefully be solved in the next beta
