### ISSUE TITLE
Connection to Spotify fails - Only Spotify Premium accounts are supported

### ISSUE THREAD

**Issue by Xlinx64** [music-assistant/hass-music-assistant#1632]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

I cannot connect to my spotify account. **I have a premium subscription** but when I try to login I get this error: "Only Spotify Premium accounts are supported". 
I created a device password because I normally use Facebook to login into spotify.

### How to reproduce

- Create password as written here: https://github.com/orgs/music-assistant/discussions/448
- Login with the provided username and selected password

### Relevant log output

2023-11-13 13:07:15.550 WARNING (MainThread) [music_assistant.providers.spotify] Error while retrieving Spotify token after 0.29 seconds, details: 
2023-11-13 13:07:15.550 ERROR (MainThread) [music_assistant.webserver] [281472431698640] Error handling message: CommandMessage(message_id=17, command='config/providers/save', args={'provider_domain': 'spotify', 'values': {'username': 'USERNAME', 'password': 'CLEARTEXT PASSWORD???', 'log_level': 'GLOBAL'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 256, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 712, in _add_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 403, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 75, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 119, in handle_setup
    await self.login()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 616, in login
    raise LoginFailed("Only Spotify Premium accounts are supported")
music_assistant.common.models.errors.LoginFailed: Only Spotify Premium accounts are supported

### What version of Home Assistant Core are your running

2023.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
What type of Spotify account are you paying for?

**Comment by Xlinx64** [comment]
It’s a single premium account. Maybe something special about it that I pay it with my phone bill so it payed by my service provider.

**Comment by OzGav** [comment]
Have you tried logging in somewhere else with the device password?

**Comment by Xlinx64** [comment]
I tried resetting the password again with the page mentioned above. But it threw an unkonw error. So I reset the password and after a few minutes I could login. A little weird and maybe a wrong message from Music Assistant. But now it works. This ticket can be closed.
