### ISSUE TITLE
Music Assistant does not play complete album

### ISSUE THREAD

**Issue by xteaun** [music-assistant/hass-music-assistant#1636]
### What version of Music Assistant has the issue?

2.0.0b75

### The problem

I am using the mass.play_media service on Home Assistant to play music and it works really well. Except for (at least) one album with the URI spotify://album/2vrJuM5PtXuY3EPG6cZQfg. On Spotify this is a full album with 17 tracks. Artist: PUR, Album: Abenteuerland. But Music Assistant only just finds one track from that album and plays it instead of the whole album. Am I doing something wrong? Other albums get played without problems.

### How to reproduce

Use Home Assistant service mass.play_media to play the album spotify://album/2vrJuM5PtXuY3EPG6cZQfg. Instead of 17 album tracks only one gets played: "Dass es dir leid tut".

### What version of Home Assistant Core are your running

2023.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please check the log for errors

**Comment by xteaun** [comment]
```
2023-11-17 13:05:57.573 DEBUG (Thread-110 (process_request_thread)) [music_assistant.providers.sonos] Received ZoneGroupTopology event for Player Hauptschlafzimmer
2023-11-17 13:06:01.238 DEBUG (MainThread) [music_assistant.webserver] [547204582736] Handling command music/tracks/library_items
2023-11-17 13:06:01.245 DEBUG (MainThread) [music_assistant.webserver] [547204582736] Handling command music/albums/library_items
2023-11-17 13:06:01.572 DEBUG (MainThread) [music_assistant.webserver] [547204582736] Handling command music/search
2023-11-17 13:06:01.579 DEBUG (MainThread) [music_assistant.webserver] [547204582736] Handling command music/search
2023-11-17 13:06:01.600 DEBUG (MainThread) [music_assistant.webserver] [547204582736] Handling command players/queue/play_media
2023-11-17 13:06:01.607 DEBUG (MainThread) [music_assistant.webserver] [547204582736] Handling command players/queue/play_media
2023-11-17 13:06:01.651 DEBUG (MainThread) [music_assistant.event] queue_items_updated RINCON_38420B7F6A1601400
2023-11-17 13:06:01.687 DEBUG (MainThread) [music_assistant.event] queue_updated RINCON_38420B7F6A1601400
2023-11-17 13:06:01.755 DEBUG (MainThread) [music_assistant.webserver] [547200222544] Handling command music/item_by_uri
2023-11-17 13:06:01.773 DEBUG (Thread-111 (process_request_thread)) [music_assistant.providers.sonos] Received AVTransport event for Player Hauptschlafzimmer
2023-11-17 13:06:01.779 DEBUG (MainThread) [music_assistant.event] queue_items_updated RINCON_38420B7F6A1601400
2023-11-17 13:06:01.814 DEBUG (MainThread) [music_assistant.event] queue_updated RINCON_38420B7F6A1601400
2023-11-17 13:06:01.852 DEBUG (MainThread) [music_assistant.event] queue_updated RINCON_38420B7F6A1601400
2023-11-17 13:06:01.875 DEBUG (MainThread) [music_assistant.providers.sonos] Enqued track (Pur - Abenteuerland) to player Hauptschlafzimmer
2023-11-17 13:06:01.919 DEBUG (MainThread) [music_assistant.webserver] [547200222544] Handling command music/item_by_uri
2023-11-17 13:06:01.951 DEBUG (Thread-112 (process_request_thread)) [music_assistant.providers.sonos] Received AVTransport event for Player Hauptschlafzimmer
2023-11-17 13:06:01.939 ERROR (MainThread) [music_assistant.webserver] [547204582736] Error handling message: CommandMessage(message_id='aa9ceb3b07f94c8cbee694d9cb688dad', command='players/queue/play_media', args={'queue_id': 'RINCON_38420B7F6A1601400', 'media': ['spotify://track/1tCoC5Jg4rIG6tD3np6nsz'], 'option': 'play', 'radio_mode': None})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 288, in play_media
    await self.play_index(queue_id, next_index)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 560, in play_index
    await player_prov.cmd_play_url(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 328, in cmd_play_url
    await asyncio.to_thread(sonos_player.soco.play_from_queue, 0)
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/core.py", line 148, in inner_function
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/core.py", line 734, in play_from_queue
    self.avTransport.Seek(
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 206, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 514, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 567, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 711 received: Illegal seek target from 192.168.178.52
2023-11-17 13:06:02.042 DEBUG (Thread-113 (process_request_thread)) [music_assistant.providers.sonos] Received AVTransport event for Player Hauptschlafzimmer
2023-11-17 13:06:02.043 DEBUG (MainThread) [music_assistant.providers.sonos] Enqued track (Pur - Dass es dir leid tut) to player Hauptschlafzimmer
2023-11-17 13:06:02.057 DEBUG (MainThread) [music_assistant.webserver] [547200222544] Handling command music/item_by_uri
2023-11-17 13:06:02.082 DEBUG (MainThread) [music_assistant.webserver] [547204582736] Unsubscribed from events
2023-11-17 13:06:02.097 DEBUG (MainThread) [music_assistant.webserver] [547204582736] Disconnected
2023-11-17 13:06:02.151 DEBUG (MainThread) [music_assistant.streams] Got GET request to /RINCON_38420B7F6A1601400/single/3ee29b2766654c249ecba8563f572c40.flac from 192.168.178.52
headers: <CIMultiDictProxy('Connection': 'close', 'Host': '192.168.178.20:8096', 'Accept': '*/*', 'User-Agent': 'Linux UPnP/1.0 Sonos/76.2-47142 (ZPS38)', 'X-Sonos-SWGen': '2', 'X-Sonos-Firmware': '76.2-47142', 'X-Sonos-Muse-Api': '1.37.0', 'X-Sonos-Id-Hash': 'nWs7m44gcBYs3eodgWNRBzs+9TUT1Y5/IOVUN3CX0SQ=')>

2023-11-17 13:06:02.159 DEBUG (Thread-114 (process_request_thread)) [music_assistant.providers.sonos] Received AVTransport event for Player Hauptschlafzimmer
2023-11-17 13:06:02.325 DEBUG (MainThread) [music_assistant.webserver] [547205594384] Connection from 192.168.178.20
2023-11-17 13:06:02.332 DEBUG (MainThread) [music_assistant.webserver] [547205594384] Handling command players/all
2023-11-17 13:06:02.339 DEBUG (MainThread) [music_assistant.webserver] [547205594384] Handling command players/queue/all
2023-11-17 13:06:02.462 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/59ER01Db76rhNlbCZTkzWC took 0.2 seconds
2023-11-17 13:06:02.476 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem library://track/1218 to Hauptschlafzimmer
2023-11-17 13:06:02.499 DEBUG (MainThread) [music_assistant.audio] start media stream for: spotify://track/59ER01Db76rhNlbCZTkzWC
2023-11-17 13:06:02.502 DEBUG (MainThread) [music_assistant.audio] writer started for spotify://track/59ER01Db76rhNlbCZTkzWC
2023-11-17 13:06:03.152 DEBUG (MainThread) [music_assistant.streams] Got HEAD request to /RINCON_38420B7F6A1601400/single/3ee29b2766654c249ecba8563f572c40.flac from 192.168.178.52
headers: <CIMultiDictProxy('Connection': 'close', 'Host': '192.168.178.20:8096', 'User-Agent': 'Linux UPnP/1.0 Sonos/76.2-47142 (ZPS38)', 'X-Sonos-SWGen': '2', 'X-Sonos-Firmware': '76.2-47142', 'X-Sonos-Muse-Api': '1.37.0', 'X-Sonos-Id-Hash': 'nWs7m44gcBYs3eodgWNRBzs+9TUT1Y5/IOVUN3CX0SQ=')>

2023-11-17 13:06:03.337 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/59ER01Db76rhNlbCZTkzWC took 0.11 seconds
2023-11-17 13:06:03.582 DEBUG (Thread-115 (process_request_thread)) [music_assistant.providers.sonos] Received AVTransport event for Player Hauptschlafzimmer
2023-11-17 13:06:03.618 DEBUG (MainThread) [music_assistant.event] queue_updated RINCON_38420B7F6A1601400
2023-11-17 13:06:03.624 DEBUG (MainThread) [music_assistant.event] player_updated RINCON_38420B7F6A1601400
2023-11-17 13:06:03.673 DEBUG (MainThread) [music_assistant.webserver] [547200222544] Handling command music/item_by_uri
2023-11-17 13:06:03.805 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/4iO8b8G48sR4G2XOrNWSP6 took 0.09 seconds
2023-11-17 13:06:03.951 DEBUG (Thread-116 (process_request_thread)) [music_assistant.providers.sonos] Received AVTransport event for Player Hauptschlafzimmer
2023-11-17 13:06:03.956 DEBUG (MainThread) [music_assistant.event] queue_updated RINCON_38420B7F6A1601400
2023-11-17 13:06:04.012 DEBUG (MainThread) [music_assistant.providers.sonos] Enqued track (Pur - Ganz egal) to player Hauptschlafzimmer
2023-11-17 13:06:04.022 DEBUG (MainThread) [music_assistant.webserver] [547200222544] Handling command music/item_by_uri
2023-11-17 13:06:04.149 DEBUG (Thread-117 (process_request_thread)) [music_assistant.providers.sonos] Received AVTransport event for Player Hauptschlafzimmer
2023-11-17 13:06:06.345 DEBUG (Thread-4) [pychromecast.dial] Resolved service ServiceInfo(type='host', data=('192.168.178.62', 8009)) to 192.168.178.62
2023-11-17 13:06:06.476 DEBUG (Thread-4) [pychromecast.dial] Resolved service ServiceInfo(type='host', data=('192.168.178.62', 8009)) to 192.168.178.62
2023-11-17 13:06:06.591 DEBUG (Thread-4) [pychromecast.dial] Resolved service ServiceInfo(type='host', data=('192.168.178.79', 8009)) to 192.168.178.79
2023-11-17 13:06:06.808 DEBUG (Thread-4) [pychromecast.dial] Resolved service ServiceInfo(type='host', data=('192.168.178.79', 8009)) to 192.168.178.79
2023-11-17 13:06:06.987 DEBUG (MainThread) [music_assistant.providers.dlna] DLNA discovery started...

**Comment by OzGav** [comment]
Please turn off debug logging. Looking back at your report does this only happen when you use a service call? That is, can you play the album ok from within the MA UI?

**Comment by xteaun** [comment]
No, the same error occurs when I search the album via the MA UI. Only one track ist listed instead of the 17.

**Comment by OzGav** [comment]
Go to BROWSE>>SPOTIFY>>ALBUMS and find this problem album and click on it then go and look in the logs and see if anything is interesting in there

**Comment by xteaun** [comment]
It is not there. There is no album with that title in that folder.

**Comment by benblb** [comment]
I'm having the same issue but with a playlist of >200 songs. Only one is played. Used to work on previous version of Music Assisant. I use YouTube Music if that's helpful. 

`2023-11-28 07:33:22.446 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Okieriete Onaodowan
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 07:34:06.610 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Various Artists - Topic
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 08:01:54.405 INFO (MainThread) [music_assistant.providers.slimproto] Player Ben’s MacBook Pro disconnected
2023-11-28 08:21:44.829 WARNING (MainThread) [music_assistant.providers.slimproto] Player squeezeplay: aa:aa:ba:52:e0:f2 connected while previous session still existing!
2023-11-28 08:28:09.537 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 08:34:02.411 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 08:45:15.558 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 09:08:14.606 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 09:15:09.374 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 09:20:03.362 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 09:45:31.305 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:12:09.434 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:17:55.067 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:22:49.186 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:29:57.143 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 10:30:54.236 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-11-28 10:30:59.194 ERROR (ThreadPoolExecutor-0_5) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-207302' coro=<SlimClient._socket_reader() done, defined at /usr/local/lib/python3.11/site-packages/aioslimproto/client.py:576> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 583, in _socket_reader
    data = await self._reader.read(64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 693, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 525, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2023-11-28 10:31:54.958 WARNING (MainThread) [music_assistant.music] Sync task for YouTube Music completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 570, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 366, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 259, in get_library_playlists
    playlists_obj = await get_library_playlists(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 137, in get_library_playlists
    return await asyncio.to_thread(_get_library_playlists)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 129, in _get_library_playlists
    playlists = ytm.get_library_playlists(limit=9999)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/library.py", line 41, in get_library_playlists
    get_continuations(results, 'gridContinuation', remaining_limit, request_func,
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/continuations.py", line 20, in get_continuations
    contents = get_continuation_contents(results, parse_func)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/continuations.py", line 74, in get_continuation_contents
    return parse_func(continuation[term])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/library.py", line 38, in <lambda>
    parse_func = lambda contents: parse_content_list(contents, parse_playlist)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/parsers/browsing.py", line 47, in parse_content_list
    contents.append(parse_func(result[key]))
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/parsers/browsing.py", line 121, in parse_playlist
    'title': nav(data, TITLE_TEXT),
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 83, in nav
    raise err
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 77, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'runs'
2023-11-28 10:32:04.643 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Kristolyn Lloyd
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 10:32:44.562 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Mike Faist
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 10:33:24.437 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Okieriete Onaodowan
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 10:34:07.087 INFO (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Various Artists - Topic
 - using lookup-album(s): none
 - using lookup-track(s): none

2023-11-28 10:36:50.057 INFO (MainThread) [music_assistant.providers.slimproto] Player Ben’s MacBook Pro disconnected
2023-11-28 11:53:15.891 INFO (MainThread) [music_assistant.providers.slimproto] Player Bedroom disconnected
2023-11-28 12:11:10.399 INFO (ThreadPoolExecutor-0_1) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-11-28 12:11:13.815 INFO (MainThread) [music_assistant.providers.slimproto] Player Ben’s MacBook Pro disconnected`

**Comment by OzGav** [comment]
@xteaun have you tried removing the offending album and then re-adding it?

**Comment by xteaun** [comment]
Thank you! That did the trick. Now the whole album is shown in music assistant and plays. :)
