### ISSUE TITLE
Timeout on Deezer Provider Adding 

### ISSUE THREAD

**Issue by dathosim** [music-assistant/hass-music-assistant#1650]
### What version of Music Assistant has the issue?

2023.6.0 BETA 6

### The problem

I tried to add Deezer provider in my HA with the funcationnality "Add provider"
I just click on "Authenticate with Deezer"
The screen became grey with the spin loop...
After 30 seconds, a little popup appear on screen : "999"
But the deezer provider was not added

i have verified theses points : 
- I'me on the same network as Music Assistant
- Can access Music Assistant using its local IP address an his port http://192.168.1.10:8095/#/home
- Have a Hifi/Premium/Family account : yes I have BUT I wasn't asked
- Are on the latest Music Assistant version : yes ! on Beta 

### How to reproduce

Attempt to add Deezer on Music Assistant with the button : Authenticate with Deezer

![Capture d’écran 2023-11-24 à 12 14 49](https://github.com/music-assistant/hass-music-assistant/assets/47037724/000fd771-738e-4252-b30d-f8dcf8e78c84)

### Relevant log output

```
2023-11-24 12:12:11.743 ERROR (MainThread) [music_assistant.webserver] [281473236802832] Error handling message: CommandMessage(message_id=18, command='config/providers/get_entries', args={'provider_domain': 'deezer', 'action': 'auth', 'values': {'access_token': None, 'log_level': 'GLOBAL', 'session_id': 'LetbVeLS5Kc'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/auth.py", line 59, in wait_for_callback
    return await self._callback_response.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 233, in get_provider_config_entries
    await prov_mod.get_config_entries(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 137, in get_config_entries
    code = (await auth_helper.authenticate(url))["code"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/auth.py", line 49, in authenticate
    return await self.wait_for_callback(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/auth.py", line 58, in wait_for_callback
    async with asyncio.timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

![Capture d’écran 2023-11-24 à 12 11 35](https://github.com/music-assistant/hass-music-assistant/assets/47037724/f6153d23-3482-4ce9-bdd4-b5d3fe6902a1)

### Additional information

Do you have a documentation to enter Deezer Credential ? 

### What version of Home Assistant Core are your running

2023.11.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Some of what you have posted is confusing. For example, you say “ I tried to add Deezer provider in my HA” but you should be adding it to MA. Later you say “ I'me on the same network as Music Assistant” but networking has no effect on adding the Deezer provider?

I’m going to assume it is a browser problem though as that is what others have found with what you show in the logs. Another user said

> It seems to rely on the browser. It worked with Brave, but not with Firefox and the the macOS Home Assistant App.

So try some different browsers

**Comment by dathosim** [comment]
Thanks ! it's work with chrome ! how didn't I think of that ?
It's very strange, but with Safari on macOS, the new tab is not opened and no notification...

**Comment by dathosim** [comment]
and to complete : 
this page write : https://github.com/orgs/music-assistant/discussions/1245
If this does not work make sure you:

Are on the same network as Music Assistant
Can access Music Assistant using its IP address
Have a Hifi/Premium/Family account
Are on the latest Music Assistant version

**Comment by ssiwinter** [comment]
Hi I have the same issue, all the points have been verified, im running server version 2.0.0b92. Deezer is authenticated but when I want to save the authorization i load for half a minute and then say that "_Provider_ deezer did not load within 30 seconds_"
