### ISSUE TITLE
no music provider after update 

### ISSUE THREAD

**Issue by Dunkelschunkel** [music-assistant/hass-music-assistant#1672]
### What version of Music Assistant has the issue?

2.0.0b77

### The problem

After updating to the latest beta it throws a couple of errors. In can still open the web interface an i do still see all my music. But mediation around it tells me no music providers are configured. I also have no players any more. 
I'll probably end up reinstalling it and setting it up again in a couple of days, nothing of concern on my side regarding my instance of music assistant. 
But I thought the log might be off interest. 

### How to reproduce

Starting and stopping should reproduce it

### Relevant log output

2023-12-07 08:29:13.110 INFO (MainThread) [music_assistant] Starting Music Assistant Server (35953d19ce9146cea4f29a9d938781f1) version 2.0.0b77 - uvloop: True
2023-12-07 08:29:13.193 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.179.4:8095
2023-12-07 08:29:13.253 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-07 08:29:13.254 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-07 08:29:13.256 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 107, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 666, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids

### What version of Home Assistant Core are your running

2023.12.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by Dunkelschunkel** [comment]
Closed. It was a duplicate of
https://github.com/music-assistant/hass-music-assistant/issues/1671 albeit being only 8 minutes apart.
