### ISSUE TITLE
Players not found after upgrade to 2023.12.0

### ISSUE THREAD

**Issue by txwindsurfer** [music-assistant/hass-music-assistant#1675]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

After upgrading HA to 2023.12.0 and MA to 0b6, my players could not initialize. No players found.

### How to reproduce

Upgraded to HA 2023.12.0 and the ability to pull players fails.

### Relevant log output

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:145
First occurred: 8:50:30 PM (3 occurrences)
Last logged: 8:51:40 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 201, in fetch_initial_state
    await self._players.fetch_state()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 294, in fetch_state
    for player in await self.get_players():
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 65, in get_players
    return [Player.from_dict(item) for item in await self.client.send_command("players/all")]
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 168, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: players/all

### Additional information

I went back 0b5 then 0b4 and the issue persists so I believe this due to changes in HA 2023.12.0.  I have not rolled back HA.

### What version of Home Assistant Core are your running

2023.12.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by txwindsurfer** [comment]
Duplicate issue
