### ISSUE TITLE
Webserver invalid command: players/all

### ISSUE THREAD

**Issue by Sarnog** [music-assistant/hass-music-assistant#1678]
### What version of Music Assistant has the issue?

2.0.0b77

### The problem

2023-12-08 15:21:34.300 INFO (MainThread) [music_assistant] Starting Music Assistant Server (9f9df8a7f9ac471daf8fcabba6f6872d) version 2.0.0b77 - uvloop: False
2023-12-08 15:21:34.329 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2023-12-08 15:21:34.355 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-08 15:21:34.355 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-08 15:21:34.357 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 107, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 666, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids
2023-12-08 15:22:19.928 WARNING (MainThread) [music_assistant.webserver] [140356785004496] Invalid command: players/all

### How to reproduce

2023-12-08 15:21:34.300 INFO (MainThread) [music_assistant] Starting Music Assistant Server (9f9df8a7f9ac471daf8fcabba6f6872d) version 2.0.0b77 - uvloop: False
2023-12-08 15:21:34.329 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2023-12-08 15:21:34.355 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-08 15:21:34.355 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-08 15:21:34.357 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 107, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 666, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids
2023-12-08 15:22:19.928 WARNING (MainThread) [music_assistant.webserver] [140356785004496] Invalid command: players/all

### Relevant log output

2023-12-08 15:21:34.300 INFO (MainThread) [music_assistant] Starting Music Assistant Server (9f9df8a7f9ac471daf8fcabba6f6872d) version 2.0.0b77 - uvloop: False
2023-12-08 15:21:34.329 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2023-12-08 15:21:34.355 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-08 15:21:34.355 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-08 15:21:34.357 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 107, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 666, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids
2023-12-08 15:22:19.928 WARNING (MainThread) [music_assistant.webserver] [140356785004496] Invalid command: players/all

### What version of Home Assistant Core are your running

2023.12.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by krisnoble** [comment]
Looks related to #1671 - what worked for me was rolling back to my backup of b75 and then installing b78, which was released in the last couple of hours

**Comment by paulius2k** [comment]
I am getting the same error with b78:
```
2023-12-09 12:34:21.536 INFO (MainThread) [music_assistant.client] Connected to Music Assistant Server b459a4f049c44c168e3591f2e3e70365 using WebsocketsConnection, Version 2.0.0b78, Schema Version 23
2023-12-09 12:34:21.544 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 201, in fetch_initial_state
    await self._players.fetch_state()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 294, in fetch_state
    for player in await self.get_players():
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 65, in get_players
    return [Player.from_dict(item) for item in await self.client.send_command("players/all")]
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 168, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: players/all
```

**Comment by OzGav** [comment]
> I am getting the same error with b78:
> music_assistant.common.models.errors.InvalidCommand: Invalid command: players/all
> ```

All it means is that you are trying to access the MA frontend before the backend is ready. Just wait for everything to finish after the update and then you should be good.

**Comment by paulius2k** [comment]
The integration status is "Failed setup, will retry".

**Comment by OzGav** [comment]
The integration is trying to connect to the server. You need to look at what is happening with the server.

**Comment by AviFix** [comment]
I am getting the same error with b78:
I tried re-installing but nothing helps

**Comment by paulius2k** [comment]
> I am getting the same error with b78: I tried re-installing but nothing helps
> 
> also after I removed the integration and the hasc integration, it still shows on the side menu, like its not completely removed

What helped me:
- downgrade to b75 from backup
- install b78

**Comment by AviFix** [comment]
> > I am getting the same error with b78: I tried re-installing but nothing helps
> > also after I removed the integration and the hasc integration, it still shows on the side menu, like its not completely removed
> 
> What helped me:
> 
> * downgrade to b75 from backup
> * install b78

How do I downgrade from backup?

**Comment by OzGav** [comment]
> I am getting the same error with b78: I tried re-installing but nothing helps
> 
> also after I removed the integration and the hasc integration, it still shows on the side menu, like its not completely removed

The side menu is a link to the ADDON not the INTEGRATION

**Comment by paulius2k** [comment]
@AviFix:
1. Go to Settings-->System-->Backups.
2. Find a copy of your b75 (or another older version) of the  Music Assistant Beta addon (e.g. "addon_d5369777_music_assistant_beta_2.0.0b75), press on it.
3. Press Restore.
4. Then upgrade it to the newest version via Settings-->Add-ons

**Comment by hulidan** [comment]
> @AviFix:
> 
> 1. Go to Settings-->System-->Backups.
> 2. Find a copy of your b75 (or another older version) of the  Music Assistant Beta addon (e.g. "addon_d5369777_music_assistant_beta_2.0.0b75), press on it.
> 3. Press Restore.
> 4. Then upgrade it to the newest version via Settings-->Add-ons

Can confirm that this method solves the issue. A bit peculiar, but does the job.

**Comment by AviFix** [comment]
> > @AviFix:
> > 
> > 1. Go to Settings-->System-->Backups.
> > 2. Find a copy of your b75 (or another older version) of the  Music Assistant Beta addon (e.g. "addon_d5369777_music_assistant_beta_2.0.0b75), press on it.
> > 3. Press Restore.
> > 4. Then upgrade it to the newest version via Settings-->Add-ons
> 
> Can confirm that this method solves the issue. A bit peculiar, but does the job.

Thanks

The installation worked but things are still not working right.


I want to remove the music assistant completely. when I remove the integration and the ad-on,  it still shows on the side menu and shows some junk data.



How can I completely remove ALL things related to the home assistant?

**Comment by OzGav** [comment]
You can’t be removing the addon if there is still something showing. Please provide the exact steps you are using to remove the addon.

**Comment by olskar** [comment]
I sadly only had 0.78 backuped, tried downgrading and then upgrading but still get music_assistant.common.models.errors.InvalidCommand: Invalid command: players/all

**Comment by olskar** [comment]
I found the follwing in the addon-log, completly removing the addon and reinstalling solved it, also solved the original error

> 2024-01-01 12:44:08.998 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 106, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 665, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids

**Comment by mac-city** [comment]
I am running the production version, not the beta.  This issue started with 2.3.4, but restoring a backup of 2.3.3 resolved it for me.
