### ISSUE TITLE
Can't add music provider 2023.6.b78

### ISSUE THREAD

**Issue by domonz** [music-assistant/hass-music-assistant#1681]
### What version of Music Assistant has the issue?

2023.6.b78

### The problem

![Image 09-12-2023 at 07 45](https://github.com/music-assistant/hass-music-assistant/assets/9319869/fefe9955-8690-4c40-9978-58e8d5179222)

Music Privder removed after upgrade, and can't add

### How to reproduce

Restart after HA

### Relevant log output

2023-12-09 07:37:44.820 DEBUG (MainThread) [music_assistant.server.controllers.config] Loaded persistent settings from /data/settings.json
2023-12-09 07:37:44.822 DEBUG (MainThread) [music_assistant.server.controllers.config] Started.
2023-12-09 07:37:44.822 INFO (MainThread) [music_assistant] Starting Music Assistant Server (762e1425e60240ce95500d999f61cdf6) version 2.0.0b78 - uvloop: False
2023-12-09 07:37:44.876 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2023-12-09 07:37:44.885 DEBUG (MainThread) [music_assistant.webserver] [139895427277136] Connection from 172.30.32.2
2023-12-09 07:37:44.891 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-09 07:37:44.891 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-09 07:37:44.892 DEBUG (MainThread) [music_assistant.webserver] [139895427277136] Handling command players/all
2023-12-09 07:37:44.893 WARNING (MainThread) [music_assistant.webserver] [139895427277136] Invalid command: players/all
2023-12-09 07:37:44.894 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 106, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 665, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids
2023-12-09 07:37:45.246 DEBUG (MainThread) [music_assistant.webserver] [139895427277136] Handling command music/search
2023-12-09 07:37:45.247 WARNING (MainThread) [music_assistant.webserver] [139895427277136] Invalid command: music/search
2023-12-09 07:37:45.251 DEBUG (MainThread) [music_assistant.webserver] [139895376099920] Connection from 172.30.32.2
2023-12-09 07:37:45.255 DEBUG (MainThread) [music_assistant.webserver] [139895376099920] Handling command players/all
2023-12-09 07:37:45.256 WARNING (MainThread) [music_assistant.webserver] [139895376099920] Invalid command: players/all
2023-12-09 07:37:45.300 DEBUG (MainThread) [music_assistant.webserver] [139895376099920] Handling command config/providers
2023-12-09 07:37:45.300 WARNING (MainThread) [music_assistant.webserver] [139895376099920] Invalid command: config/providers
2023-12-09 07:38:11.068 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Connection from 172.30.32.2
2023-12-09 07:38:11.083 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command players/all
2023-12-09 07:38:11.085 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: players/all
2023-12-09 07:38:11.166 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/recently_played_items
2023-12-09 07:38:11.167 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/recently_played_items
2023-12-09 07:38:11.169 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/artists/library_items
2023-12-09 07:38:11.171 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/albums/library_items
2023-12-09 07:38:11.173 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/recently_played_items
2023-12-09 07:38:11.174 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/recently_played_items
2023-12-09 07:38:11.175 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/recently_played_items
2023-12-09 07:38:11.176 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/recently_played_items
2023-12-09 07:38:11.177 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/tracks/library_items
2023-12-09 07:38:11.179 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/browse
2023-12-09 07:38:11.179 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/browse
2023-12-09 07:38:13.233 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command config/providers
2023-12-09 07:38:13.234 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: config/providers
2023-12-09 07:38:19.065 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command config/core
2023-12-09 07:38:19.067 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: config/core
2023-12-09 07:38:23.128 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command config/providers
2023-12-09 07:38:23.133 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: config/providers
2023-12-09 07:38:25.156 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/browse
2023-12-09 07:38:25.157 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/browse
2023-12-09 07:38:30.044 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/recently_played_items
2023-12-09 07:38:30.045 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/recently_played_items
2023-12-09 07:38:30.051 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/artists/library_items
2023-12-09 07:38:30.055 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/albums/library_items
2023-12-09 07:38:30.059 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/recently_played_items
2023-12-09 07:38:30.060 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/recently_played_items
2023-12-09 07:38:30.062 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/recently_played_items
2023-12-09 07:38:30.063 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/recently_played_items
2023-12-09 07:38:30.065 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/tracks/library_items
2023-12-09 07:38:30.068 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/browse
2023-12-09 07:38:30.068 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/browse
2023-12-09 07:38:37.830 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command music/refresh_item
2023-12-09 07:38:37.831 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: music/refresh_item
2023-12-09 07:38:39.853 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Handling command config/providers
2023-12-09 07:38:39.853 WARNING (MainThread) [music_assistant.webserver] [139895376244880] Invalid command: config/providers
2023-12-09 07:38:48.457 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Unsubscribed from events
2023-12-09 07:38:48.461 DEBUG (MainThread) [music_assistant.webserver] [139895376244880] Disconnected
2023-12-09 07:42:04.463 DEBUG (MainThread) [music_assistant.webserver] [139895427277136] Unsubscribed from events
2023-12-09 07:42:04.470 DEBUG (MainThread) [music_assistant.webserver] [139895376099920] Unsubscribed from events
2023-12-09 07:42:04.473 DEBUG (MainThread) [music_assistant.webserver] [139895427277136] Disconnected
2023-12-09 07:42:04.476 DEBUG (MainThread) [music_assistant.webserver] [139895376099920] Disconnected
2023-12-09 07:42:27.760 DEBUG (MainThread) [music_assistant.webserver] [139895394598352] Connection from 172.30.32.2
2023-12-09 07:42:27.774 DEBUG (MainThread) [music_assistant.webserver] [139895394598352] Handling command players/all
2023-12-09 07:42:27.776 WARNING (MainThread) [music_assistant.webserver] [139895394598352] Invalid command: players/all
2023-12-09 07:42:28.249 DEBUG (MainThread) [music_assistant.webserver] [139895394598352] Handling command music/search
2023-12-09 07:42:28.251 WARNING (MainThread) [music_assistant.webserver] [139895394598352] Invalid command: music/search
2023-12-09 07:42:29.686 DEBUG (MainThread) [music_assistant.webserver] [139895394598352] Unsubscribed from events
2023-12-09 07:42:29.687 DEBUG (MainThread) [music_assistant.webserver] [139895394598352] Disconnected
2023-12-09 07:42:35.580 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Connection from 172.30.32.2
2023-12-09 07:42:35.844 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Handling command players/all
2023-12-09 07:42:35.845 WARNING (MainThread) [music_assistant.webserver] [139895375938704] Invalid command: players/all
2023-12-09 07:42:36.368 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Handling command music/recently_played_items
2023-12-09 07:42:36.369 WARNING (MainThread) [music_assistant.webserver] [139895375938704] Invalid command: music/recently_played_items
2023-12-09 07:42:36.370 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Handling command music/artists/library_items
2023-12-09 07:42:36.371 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Handling command music/albums/library_items
2023-12-09 07:42:36.374 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Handling command music/recently_played_items
2023-12-09 07:42:36.374 WARNING (MainThread) [music_assistant.webserver] [139895375938704] Invalid command: music/recently_played_items
2023-12-09 07:42:36.375 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Handling command music/recently_played_items
2023-12-09 07:42:36.375 WARNING (MainThread) [music_assistant.webserver] [139895375938704] Invalid command: music/recently_played_items
2023-12-09 07:42:36.376 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Handling command music/tracks/library_items
2023-12-09 07:42:36.378 DEBUG (MainThread) [music_assistant.webserver] [139895375938704] Handling command music/browse
2023-12-09 07:42:36.378 WARNING (MainThread) [music_assistant.webserver] [139895375938704] Invalid command: music/browse
2023-12-09 07:42:47.932 DEBUG (MainThread) [music_assistant.webserver] [139895376270352] Connection from 172.30.32.2
2023-12-09 07:42:47.936 DEBUG (MainThread) [music_assistant.webserver] [139895376270352] Handling command players/all
2023-12-09 07:42:47.937 WARNING (MainThread) [music_assistant.webserver] [139895376270352] Invalid command: players/all
2023-12-09 07:42:47.976 DEBUG (MainThread) [music_assistant.webserver] [139895376270352] Handling command config/providers
2023-12-09 07:42:47.977 WARNING (MainThread) [music_assistant.webserver] [139895376270352] Invalid command: config/providers
2023-12-09 07:43:46.735 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Connection from 172.30.32.2
2023-12-09 07:43:46.747 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command players/all
2023-12-09 07:43:46.748 WARNING (MainThread) [music_assistant.webserver] [139895376408336] Invalid command: players/all
2023-12-09 07:43:46.870 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command music/recently_played_items
2023-12-09 07:43:46.871 WARNING (MainThread) [music_assistant.webserver] [139895376408336] Invalid command: music/recently_played_items
2023-12-09 07:43:46.872 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command music/artists/library_items
2023-12-09 07:43:46.873 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command music/albums/library_items
2023-12-09 07:43:46.875 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command music/recently_played_items
2023-12-09 07:43:46.875 WARNING (MainThread) [music_assistant.webserver] [139895376408336] Invalid command: music/recently_played_items
2023-12-09 07:43:46.876 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command music/recently_played_items
2023-12-09 07:43:46.876 WARNING (MainThread) [music_assistant.webserver] [139895376408336] Invalid command: music/recently_played_items
2023-12-09 07:43:46.877 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command music/tracks/library_items
2023-12-09 07:43:46.878 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command music/browse
2023-12-09 07:43:46.878 WARNING (MainThread) [music_assistant.webserver] [139895376408336] Invalid command: music/browse
2023-12-09 07:43:48.680 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command config/providers
2023-12-09 07:43:48.680 WARNING (MainThread) [music_assistant.webserver] [139895376408336] Invalid command: config/providers
2023-12-09 07:46:28.732 DEBUG (MainThread) [music_assistant.webserver] [139895376408336] Handling command config/core
2023-12-09 07:46:28.733 WARNING (MainThread) [music_assistant.webserver] [139895376408336] Invalid command: config/core

### What version of Home Assistant Core are your running

2023.12.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This might just be temporary while the database upgrade is underway but what version are you upgrading from?

**Comment by domonz** [comment]
Yes, thanks after 1 hours, is work,

**Comment by domonz** [comment]
Closed
