### ISSUE TITLE
Soundcloud not playing or syncing

### ISSUE THREAD

**Issue by Subcode** [music-assistant/hass-music-assistant#1697]
### What version of Music Assistant has the issue?

2.0.0b78

### The problem

On Sync error:
```
2023-12-13 17:01:16.490 WARNING (MainThread) [music_assistant.music] Sync task for Soundcloud completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 366, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/soundcloud/__init__.py", line 207, in get_library_tracks
    async for item in self._soundcloud.get_tracks_liked():
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py", line 135, in get_tracks_liked
    async for track in self._paginated_query(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/soundcloud/soundcloudpy/asyncsoundcloudpy.py", line 340, in _paginated_query
    for k, v in params.values():
        ^^^^
ValueError: too many values to unpack (expected 2)
```

Playback error:
```
2023-12-13 17:03:45.079 ERROR (MainThread) [music_assistant.webserver] [140135226655696] Error handling message: CommandMessage(message_id=32, command='music/tracks/track_albums', args={'item_id': 384528209, 'provider_instance_id_or_domain': 'soundcloud'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 356, in _run_handler
    args = parse_arguments(handler.signature, handler.type_hints, msg.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/api.py", line 73, in parse_arguments
    final_args[name] = parse_value(name, value, func_types[name], default)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/api.py", line 153, in parse_value
    raise TypeError(
TypeError: Value 384528209 of type <class 'int'> is invalid for item_id, expected value of type <class 'str'>
2023-12-13 17:03:45.081 ERROR (MainThread) [music_assistant.webserver] [140135226655696] Error handling message: CommandMessage(message_id=33, command='music/tracks/track_versions', args={'item_id': 384528209, 'provider_instance_id_or_domain': 'soundcloud'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 356, in _run_handler
    args = parse_arguments(handler.signature, handler.type_hints, msg.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/api.py", line 73, in parse_arguments
    final_args[name] = parse_value(name, value, func_types[name], default)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/api.py", line 153, in parse_value
    raise TypeError(
TypeError: Value 384528209 of type <class 'int'> is invalid for item_id, expected value of type <class 'str'>
```

### How to reproduce

Add soundcloud as a provider, try to sync / play a song

### What version of Home Assistant Core are your running

2023.12.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
@gieljnssns

**Comment by Subcode** [comment]
Any update on this?

**Comment by OzGav** [comment]
Sorry no haven’t heard from the dev. Maybe they are on holidays

**Comment by Subcode** [comment]
Looks like the dev is active on other repos, i might try and debug the issue myself when i have time. But unfortunately am very busy so its more likely this wont happen within months.

**Comment by gieljnssns** [comment]
I haven't used SoundCloud in a long time.
I'll try to make some time in the next few days to reproduce these errors and hopefully find a solution.

**Comment by gieljnssns** [comment]
Have you tried to remove and re-add the provider?

**Comment by Subcode** [comment]
Tried adding the provider again but same errors, but i also see you updated the comment.

**Comment by gieljnssns** [comment]
@Subcode How many tracks you have liked in soundcloud?

**Comment by Subcode** [comment]
Approx 800 liked tracks.

**Comment by gieljnssns** [comment]
@Subcode Do you have the possibility to restore a backup from before b76 and try if this is working?

**Comment by gieljnssns** [comment]
I think I have found a solution for the sync error. 
https://github.com/music-assistant/server/pull/1042
I can't replicate the playback error. Do all souncloud tracks give the same error?

**Comment by gieljnssns** [comment]
Have you tried the latest beta?

**Comment by LioBoul** [comment]
I have the same error, sync ok but not playback : Échec de l'appel du service media_player/media_play. CastMediaPlayerEntity.media_play Failed: Execution of play timed out after 10.0 s.
I've delete et recreate account.
