### ISSUE TITLE
Error retrieving list of speakers

### ISSUE THREAD

**Issue by T3chArmy** [music-assistant/hass-music-assistant#1700]
### What version of Music Assistant has the issue?
2023.6.0b6
2.0.0b78

### The problem

Trying to open list of speakers fails

### How to reproduce

Attempt to select a speaker to play to

### Relevant log output

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:145
First occurred: December 13, 2023 at 16:00:40 (281 occurrences)
Last logged: 00:31:08

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 201, in fetch_initial_state
    await self._players.fetch_state()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 294, in fetch_state
    for player in await self.get_players():
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/players.py", line 65, in get_players
    return [Player.from_dict(item) for item in await self.client.send_command("players/all")]
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 168, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: players/all

### What version of Home Assistant Core are your running

2023.12.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Have you just started MA? That error normally occurs when you are trying to access the front end before the server has properly started

**Comment by T3chArmy** [comment]
Ahh, here we go. That pointed me to this issue:

```
2023-12-14 00:45:42.582 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-14 00:45:42.582 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-14 00:45:42.583 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 106, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 665, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_id
s```

**Comment by OzGav** [comment]
OK it looks like you have tried to upgrade between unsupported versions. If you can roll back to b75 then upgrade straight to b78. If you can't then you are going to have to remove and reinstall the addon

**Comment by OzGav** [comment]
Either that or you have restarted the addon during the database migration

**Comment by T3chArmy** [comment]
Thank you for the info. I'll take a closer look in the morning!
