### ISSUE TITLE
No Providers, no players

### ISSUE THREAD

**Issue by Tanjohnson99** [music-assistant/hass-music-assistant#1705]
### What version of Music Assistant has the issue?

2.0.0b78

### The problem

2023-12-14 17:17:50.891 INFO (MainThread) [music_assistant] Starting Music Assistant Server (742ab40287a94aaa94ffa8137defd980) version 2.0.0b78 - uvloop: False
2023-12-14 17:17:50.967 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2023-12-14 17:17:51.015 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-14 17:17:51.015 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-14 17:17:51.016 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 106, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 665, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids
2023-12-14 17:18:20.309 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: players/all
2023-12-14 17:18:20.395 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: music/recently_played_items
2023-12-14 17:18:20.397 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: music/recently_played_items
2023-12-14 17:18:20.397 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: music/recently_played_items
2023-12-14 17:18:20.397 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: music/browse
2023-12-14 17:18:22.164 WARNING (MainThread) [music_assistant.webserver] [140019360736784] Invalid command: players/all
2023-12-14 17:18:22.228 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: config/providers
2023-12-14 17:18:27.714 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: config/players
2023-12-14 17:18:29.503 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: config/providers/get
2023-12-14 17:18:30.432 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: config/players
2023-12-14 17:18:30.914 WARNING (MainThread) [music_assistant.webserver] [140019360652176] Invalid command: config/core

### How to reproduce

Start the add-on

### What version of Home Assistant Core are your running

2023.12.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by robingeek** [comment]
I can confirm this same issue
Running on Home Assistant Blue
Core 2023.12.2
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

log output...
2023-12-15 11:55:23.485 INFO (MainThread) [music_assistant] Starting Music Assistant Server (f98fa3b3866f4bb785646fdfc11513e5) version 2.0.0b78 - uvloop: False
2023-12-15 11:55:23.524 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2023-12-15 11:55:23.562 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-15 11:55:23.563 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-15 11:55:23.564 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 106, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 665, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids
2023-12-15 11:56:08.863 WARNING (MainThread) [music_assistant.webserver] [281472854335504] Invalid command: players/all

**Comment by OzGav** [comment]
OK it looks like you have tried to upgrade between unsupported versions. If you can roll back to b75 then upgrade straight to b78. If you can't then you are going to have to remove and reinstall the addon
