### ISSUE TITLE
Setup Failed

### ISSUE THREAD

**Issue by haggot** [music-assistant/hass-music-assistant#1706]
### What version of Music Assistant has the issue?

2.0.0b78

### The problem

I was having issues with MASS and I had to reinstall and now the integration will not complete setup, it goes through a loop of initialising and then saying failed setup

### How to reproduce

uninstall and then reinstall MASS from HACS and integrations

### Relevant log output

2023-12-15 10:36:59.684 INFO (MainThread) [music_assistant] Starting Music Assistant Server (b99f571e83ef4c5dac71c64fa63e2fd6) version 2.0.0b78 - uvloop: False
2023-12-15 10:36:59.754 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2023-12-15 10:36:59.771 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-15 10:36:59.771 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-15 10:36:59.773 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 106, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 665, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids
2023-12-15 10:37:19.105 WARNING (MainThread) [music_assistant.webserver] [547534612048] Invalid command: players/all

### What version of Home Assistant Core are your running

2023.12.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
OK it looks like you have tried to upgrade between unsupported versions or the DB upgrade was interrupted . If you can roll back to b75 via a backup then upgrade straight to b78. If you can't then you are going to have to remove and reinstall the addon
