### ISSUE TITLE
Playback stops after 1 song

### ISSUE THREAD

**Issue by ddorsett** [music-assistant/hass-music-assistant#1716]
### What version of Music Assistant has the issue?

2.0.0b78

### The problem

Playing a playlist or album from the server web UI plays only a single song then stops.

### How to reproduce

Pick an album or playlist, click Play.
First song plays
Playback stops

### Relevant log output

2023-12-21 18:00:04.428 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1709, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: unbound prefix: line 1, column 950

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/webserver.py", line 122, in _handle_catch_all
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/helpers.py", line 36, in _handle_request
    status = await self.event_handler.handle_notify(headers, body)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/event_handler.py", line 160, in handle_notify
    service.notify_changed_state_variables(changes)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/client.py", line 457, in notify_changed_state_variables
    self.on_event(self, changed_state_variables)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 381, in _on_event
    dlna_handle_notify_last_change(state_variable)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 214, in dlna_handle_notify_last_change
    service.notify_changed_state_variables(changes_0)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/client.py", line 457, in notify_changed_state_variables
    self.on_event(self, changed_state_variables)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 386, in _on_event
    self._update_current_track_meta_data(state_variable)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 1077, in _update_current_track_meta_data
    items = didl_lite.from_xml_string(xml, strict=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/didl_lite/didl_lite.py", line 1065, in from_xml_string
    xml_el = defusedxml.ElementTree.fromstring(xml_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1711, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1618, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: unbound prefix: line 1, column 950

### Additional information

Running MA Server on a separate machine from HA, docker on Linux host
I don't always see errors in the log

### What version of Home Assistant Core are your running

2023.12.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by bj61251** [comment]
I'm also having this problem, playing on a Chromecast speaker group from Deezer and/or Plex sources.

**Comment by ezpl** [comment]
I am experiencing the very same thing. HomeAssistant OS on i386 / streaming from Tidal.
A restart of MA usualy solves it.

**Comment by OzGav** [comment]
Duplicate https://github.com/music-assistant/hass-music-assistant/issues/1657
