### ISSUE TITLE
Error performing database migration from 25 to 27

### ISSUE THREAD

**Issue by ezpl** [music-assistant/hass-music-assistant#1726]
### What version of Music Assistant has the issue?

2.0.0 BETA 78

### The problem

Music assistant does not start after update

### How to reproduce

-

### Relevant log output

2023-12-28 08:12:56.176 INFO (MainThread) [music_assistant] Starting Music Assistant Server (7e5a479268a7451d91d9226a40de2962) version 2.0.0b78 - uvloop: False
2023-12-28 08:12:56.211 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://10.0.20.22:8095
2023-12-28 08:12:56.447 INFO (MainThread) [music_assistant.music] Performing database migration from 25 to 27
2023-12-28 08:12:56.447 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2023-12-28 08:12:56.448 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 174, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 139, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 106, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 665, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 151, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids

### What version of Home Assistant Core are your running

2024.1.0b0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You have probably interrupted the database upgrade by restarting. You need to rollback to beta 75 via a backup and then upgrade again. If you can’t do this then delete and reinstall the addon. I think there might also be a problem with the HA beta as well, check discord.

**Comment by ezpl** [comment]
Thanks. You are probably right about the restart. I did not have much to loose, so reinstalled MA and now it works again 🙂
