### ISSUE TITLE
Sync issues with Deezer provider

### ISSUE THREAD

**Issue by etique57** [music-assistant/hass-music-assistant#1731]
### What version of Music Assistant has the issue?

2.0.0b79

### The problem

With the Deezer provider (I haven't any other provider), playback works fine the first time, but as soon as something is "synced" with the library, it basically disappears.
Artists => albums don't show
Albums => songs don't show

### How to reproduce

- Log in with the Deezer provider
- Select album
- play songs
- refresh page

Songs disappear

- remove from library
- refresh page

Songs appear again

### Relevant log output

2023-12-30 09:17:10.285 INFO (MainThread) [music_assistant] Loaded music provider Deezer Etienne
2023-12-30 09:17:12.066 WARNING (MainThread) [music_assistant.music] Sync task for Deezer Etienne completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 386, in sync_library
    library_item = await controller.add_item_to_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 164, in add_item_to_library
    library_item = await self._add_library_item(item)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 379, in _add_library_item
    track_artists = await self._get_artist_mappings(item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 690, in _get_artist_mappings
    artist_mapping = await self._get_artist_mapping(artist)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 708, in _get_artist_mapping
    artist = await self.mass.music.artists.get_provider_item(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 438, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 260, in get_item
    return await self.get_artist(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 261, in get_artist
    return self.parse_artist(artist=await self.client.get_artist(artist_id=int(prov_artist_id)))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 202, in get_artist
    return await self.request("GET", f"artist/{artist_id}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 173, in request
    raise DeezerErrorResponse(json_data)
deezer.exceptions.DeezerErrorResponse: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
2023-12-30 09:19:57.412 ERROR (MainThread) [music_assistant.webserver] [140216523919568] Error handling message: CommandMessage(message_id=24, command='music/albums/get_album', args={'item_id': '260', 'provider_instance_id_or_domain': 'library'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 70, in get
    album = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 162, in get
    library_item = await self.get_library_item_by_prov_id(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 295, in get_library_item_by_prov_id
    return await self.get_library_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 284, in get_library_item
    raise MediaNotFoundError(f"{self.media_type.value} not found in library: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: album not found in library: 260

### Additional information

I'm using the Home Assistant addon

### What version of Home Assistant Core are your running

2023.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Is this a new issue related to the upgrade to b79 or are you a new user that has started with b79?

**Comment by etique57** [comment]
Nope, I've been using it for quite a few releases and as far as I can recall it has always been an issue.

I can start from scratch again if you think it's worth a shot!

**Comment by OzGav** [comment]
Yes I do. Fully remove the addon and reinstall and see how you go.

**Comment by etique57** [comment]
Ok so I uninstall/installed the addon but I think I still observe the same behavior.

First time I access an album, I see it properly:
![image](https://github.com/music-assistant/hass-music-assistant/assets/24211083/7ba8aaf0-45cc-4465-8d16-d0729d51a2d7)

If I hit refresh, the tracks disappear:
![image](https://github.com/music-assistant/hass-music-assistant/assets/24211083/02c239cb-1ef4-4aa9-9726-6e4116a01624)

Here's what seems to be the relevant log output though the timestamp is a bit offset (refresh occurred between 11:48:30 and 11:48:44 and the logs state 11:50:03) so I'm not too sure. There's no other errors around that time though. I'll increase the verbosity and try to refresh again.

`2023-12-31 11:50:03.640 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-29368' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 155, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError
2023-12-31 11:50:04.133 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-29372' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 155, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError`

**Comment by etique57** [comment]
Some other logs during similar actions:
```
2023-12-31 11:54:57.710 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-29433' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 155, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError
2023-12-31 11:54:57.964 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-29436' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 155, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError
2023-12-31 11:55:17.744 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2023-12-31 11:55:17.746 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2023-12-31 11:55:19.341 WARNING (MainThread) [music_assistant.music] Sync task for Deezer completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 571, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 386, in sync_library
    library_item = await controller.add_item_to_library(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 164, in add_item_to_library
    library_item = await self._add_library_item(item)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 379, in _add_library_item
    track_artists = await self._get_artist_mappings(item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 690, in _get_artist_mappings
    artist_mapping = await self._get_artist_mapping(artist)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 708, in _get_artist_mapping
    artist = await self.mass.music.artists.get_provider_item(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 438, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 260, in get_item
    return await self.get_artist(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 261, in get_artist
    return self.parse_artist(artist=await self.client.get_artist(artist_id=int(prov_artist_id)))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 202, in get_artist
    return await self.request("GET", f"artist/{artist_id}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/deezer/client.py", line 173, in request
    raise DeezerErrorResponse(json_data)
deezer.exceptions.DeezerErrorResponse: {'error': {'type': 'DataException', 'message': 'no data', 'code': 800}}
2023-12-31 11:55:20.614 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-29650' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 155, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError
2023-12-31 11:55:20.680 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-29652' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 155, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError
2023-12-31 11:55:47.740 DEBUG (MainThread) [music_assistant.music.album] added Candide Crush to database

```

**Comment by OzGav** [comment]
@arctixdev ?

**Comment by arctixdev** [comment]
Its because when you initially open a new artist/album/track it shows the Deezer version of that media item (Shown by the Deezer logo next to the favorite button). And then once you do that music assistant starts adding it to your library. When you then refresh it it shows the library version of that media item (Shown by the library icon next to the favorite button), that hasnt been fully parsed yet and is therefore incomplete... 

You can switch to the Deezer view again with the button to the right (Shown in the picture)
![image](https://github.com/music-assistant/hass-music-assistant/assets/74015378/45054f7e-bb22-41e6-b398-7ef03c3d452c)

This is a Music Assistant design choice that i dont really agree with.. But once the entire media item has been parsed it should also show all the tracks in library view.

**Comment by OzGav** [comment]
Actually the other thing to note here is what are you "Adding to the Library"? If it is the ARTIST then what you see is normal as Jonathan has indicated. No tracks or albums will appears unless you add those tracks or albums to the database. I don't use Deezer but this is consistent with how Spotify works. What I would say however is that last I checked when adding an album the tracks aren't automatically added from that album. That is to be fixed.

**Comment by etique57** [comment]
> Its because when you initially open a new artist/album/track it shows the Deezer version of that media item (Shown by the Deezer logo next to the favorite button). And then once you do that music assistant starts adding it to your library. When you then refresh it it shows the library version of that media item (Shown by the library icon next to the favorite button), that hasnt been fully parsed yet and is therefore incomplete...
> 
> You can switch to the Deezer view again with the button to the right (Shown in the picture) ![image](https://private-user-images.githubusercontent.com/74015378/293586741-45054f7e-bb22-41e6-b398-7ef03c3d452c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTQ4NzIsIm5iZiI6MTcwNDExNDU3MiwicGF0aCI6Ii83NDAxNTM3OC8yOTM1ODY3NDEtNDUwNTRmN2UtYmIyMi00MWU2LWIzOTgtN2VmMDNjM2Q0NTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEzMDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYWEzMDdjNTJhMjBiZDFiYWU1YWE1NjFjNWQyMmQ5NTgwZmRkNjVjYjU3MmJiMjk0NWJkOTE0NjMwOGVjZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DS-8NrI3vjf-8nj04PHLzSQfBNljF-vZxZP8Uje_r-o)
> 
> This is a Music Assistant design choice that i dont really agree with.. But once the entire media item has been parsed it should also show all the tracks in library view.

Indeed! wow never noticed that, thanks for the hint.

What do you mean "parsed"? Do you mean played?

**Comment by etique57** [comment]
> Actually the other thing to note here is what are you "Adding to the Library"? If it is the ARTIST then what you see is normal as Jonathan has indicated. No tracks or albums will appear unless you add those tracks or albums to the database. I don't use Deezer but this is consistent with how Spotify works. What I would say however is that last I checked when adding an album the tracks aren't automatically added from that album. That is to be fixed.

Understand. I actually don't add anything to the library, for some reason it's automatic. But it is "liked" on my deezer profile and it gets added automatically because of that.

So the "issue" in my case is that when a "top level" item (artist/album) is added, then the underlying items (album/track) are not added automatically, and the default view being the "library" view if added, it shows nothing.

I get it, I think we can close the issue then! Or I can open a new one, but it seems to be a design choice (which I now understand better).

Thanks a bunch and happy new year!

**Comment by OzGav** [comment]
There is info in the docs about this behaviour as it does come up a bit.

**Comment by arctixdev** [comment]
> What do you mean "parsed"? Do you mean played?

I mean the media item info getting "downloaded" from Deezer into the Music Assistant database 🙂 

> Thanks a bunch and happy new year!

Thanks, you too!
