### ISSUE TITLE
Spotify authorization timeout getting token

### ISSUE THREAD

**Issue by kdkavanagh** [music-assistant/hass-music-assistant#1734]
### What version of Music Assistant has the issue?

2.0.0b80

### The problem

Just installed the latest version of the server and am unable to authenticate with spotify.   I've got the container configured with a macvlan network instead of `host` due to how my network/hosts are set up - macvlan should ostensibly function the same as `host` though (i.e all ports forwarded)

Confirmed from within the docker container that I can at least hit the auth url that librespot initially tries to use:
```
root@b1aaedf5c228:/data# curl apresolve.spotify.com
{"ap_list":["ap-gue1.spotify.com:4070","ap-gue1.spotify.com:443","ap-gue1.spotify.com:80","ap-gew4.spotify.com:4070","ap-gae2.spotify.com:443","ap-gew1.spotify.com:80"]}

root@b1aaedf5c228:/data# ping ap-gue1.spotify.com
PING ap-gue1.spotify.com (34.158.253.218) 56(84) bytes of data.
64 bytes from 218.253.158.34.bc.googleusercontent.com (34.158.253.218): icmp_seq=1 ttl=57 time=52.9 ms
^C64 bytes from 34.158.253.218: icmp_seq=2 ttl=57 time=36.9 ms
```

### How to reproduce

From a fresh install, attempt to login to spotify

### Relevant log output

The logs do print "authorized" a number of times after I start the login process.  Not sure how to interpret that:
```
hass-music-assistant_1       | authorized                                                                                                                               
hass-music-assistant_1       | authorized                                                                                                                               
hass-music-assistant_1       | authorized                                                                                                                               
hass-music-assistant_1       | 2024-01-01 01:39:31.378 ERROR (MainThread) [music_assistant.webserver] [139843333535696] Error handling message: CommandMessage(message_i
d=13, command='config/providers/save', args={'provider_domain': 'spotify', 'values': {'username': 'xxx@gmail.com', 'password': 'xxx', 'log_level': 'DEBUG'}})                                                                                                                                                                   
hass-music-assistant_1       | Traceback (most recent call last):                                                                                                       
hass-music-assistant_1       |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 403, in load_provider                            
hass-music-assistant_1       |     provider = await prov_mod.setup(self, prov_manifest, conf)                                                                           
hass-music-assistant_1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                           
hass-music-assistant_1       |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 75, in setup                 
hass-music-assistant_1       |     await prov.handle_setup()                                                                                                            
hass-music-assistant_1       |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 119, in handle_setup         
hass-music-assistant_1       |     await self.login()                                                                                                                   
hass-music-assistant_1       |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 589, in login                
hass-music-assistant_1       |     tokeninfo = await self._get_token()                                                                                                  
hass-music-assistant_1       |                 ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                  
hass-music-assistant_1       |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/spotify/__init__.py", line 635, in _get_token           
hass-music-assistant_1       |     await librespot.wait()                                                                                                               
hass-music-assistant_1       |   File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 137, in wait                                                              
hass-music-assistant_1       |     return await self._transport._wait()                                                                                                 
hass-music-assistant_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                 
hass-music-assistant_1       |   File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 230, in _wait                                                        
hass-music-assistant_1       |     return await waiter                                                                                                                  
hass-music-assistant_1       |            ^^^^^^^^^^^^                                                                                                                  
hass-music-assistant_1       | asyncio.exceptions.CancelledError 
```

### What version of Home Assistant Core are your running

2023.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Synology NAS

**Comment by OzGav** [comment]
I’m sorry to say that we don’t have the capacity to help users with non standard network installs. The MA requirements are fairly clear. You will have to try and resolve this one elsewhere, feel free to open a discussion and see if anyone else can help or try on our discord server.
