### ISSUE TITLE
Error thrown when adding item to library

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1741]
### What version of Music Assistant has the issue?

2.0.0.b81

### The problem

When reviewing the logs the error shown below was noticed.

### How to reproduce

Not sure  just noticed it in the logs

### Relevant log output

```

2024-01-09 12:36:49.394 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2342' coro=<ArtistsController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py:58> exception=MissingField('title', <class 'str'>, <class 'music_assistant.server.providers.musicbrainz.MusicBrainzRecording'>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 69, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 125, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 262, in get_artist_mbid
    if mbid := await musicbrainz.get_musicbrainz_artist_id(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 218, in get_musicbrainz_artist_id
    if mb_artist := await self.get_artist_details_by_track(artist.name, ref_track):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 396, in get_artist_details_by_track
    result = await self.get_recording_details(ref_track.mbid, isrc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 334, in get_recording_details
    return MusicBrainzRecording.from_dict(replace_hyphens(result))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 10, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "title" of type str is missing in MusicBrainzRecording instance
```

### What version of Home Assistant Core are your running

2024.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
I hate API's that don't give consistent results, sigh...

I'll mak ethe models more forgiving (again).

**Comment by OzGav** [comment]
Fixed in beta82
