### ISSUE TITLE
smb shares not mounting in new update

### ISSUE THREAD

**Issue by n0tOdd** [music-assistant/hass-music-assistant#1754]
### What version of Music Assistant has the issue?

 2.0.0b80

### The problem

Is anyone else having problems with smb shares not working after the last update?
im running music assistant as an addon in home assistant now if that makes any difference 

### How to reproduce

Mount a smb share

### Relevant log output

`2024-01-03 05:23:05.529 INFO (MainThread) [music_assistant.providers.filesystem_smb] Mounting //192.168.86.187/Media/Music/Disk1 to /tmp/filesystem_smb
2024-01-03 05:23:35.527 ERROR (MainThread) [music_assistant.webserver] [139657506689232] Error handling message: CommandMessage(message_id=23, command='config/providers/save', args={'provider_domain': 'filesystem_smb', 'values': {'host': '192.168.86.187', 'share': 'Media', 'username': 'n0tme', 'password': 'Removed#', 'subfolder': 'Music\\Disk1', 'mount_options': 'noserverino,file_mode=0775,dir_mode=0775,uid=0,gid=0', 'missing_album_artist_action': 'skip', 'log_level': 'GLOBAL'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 403, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 45, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 141, in handle_setup
    await self.mount()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_smb/__init__.py", line 193, in mount
    _, stderr = await proc.communicate()
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 200, in communicate
    stdin, stdout, stderr = await tasks.gather(stdin, stdout, stderr)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 180, in _read_stream
    output = await stream.read()
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 701, in read
    block = await self.read(self._limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 708, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 540, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 402, in load_provider
    async with asyncio.timeout(30):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 256, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 718, in _add_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 405, in load_provider
    raise SetupFailedError(f"Provider {domain} did not load within 30 seconds") from err
music_assistant.common.models.errors.SetupFailedError: Provider filesystem_smb did not load within 30 seconds
2024-01-03 05:23:46.303 ERROR (MainThread) [music_assistant.webserver] [139657009552464] Error handling message: CommandMessage(message_id=19, command='config/providers/reload', args={'instance_id': 'filesystem_smb'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 308, in reload_provider
    config = await self.get_provider_config(instance_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 189, in get_provider_config
    raise KeyError(f"No config found for provider id {instance_id}")
KeyError: 'No config found for provider id filesystem_smb'`

### Additional information

The smb share is accesable from every other computer on the lan and i can mount it in home assistant with no problem

### What version of Home Assistant Core are your running

2023.12.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
No I am not. I would check you server settings to make sure something hasn’t updated there by coincidence. Do check the MA settings again though as the error does seem to relate to the config.
Other ideas are to remove and the re-add the provider. Do NOT restart the host if you do this as it will interrupt the clean up. The nuclear option is to remove and reinstall MA.

**Comment by n0tOdd** [comment]
Tried all of this with the same problem, ended up with a fresh install of ma and use local file provider pointed to the smb share mounted with home assistant instead. It works but it just feels wrong doing it like that 😅

**Comment by OzGav** [comment]
Look carefully at the mount command you used in HA and see if there are any differences to MA. If it works in HA the it should work the same in MA or indeed there may be a bug (although to my knowledge that part of the code wasn’t touched)

**Comment by OzGav** [comment]
Do you have any updates on this? If not we will close it.

**Comment by n0tOdd** [comment]
Todays home assistant OS update will probably fix it,
it worked for a time mounted with ha os, but the same problem started coming there to, so i hope this update fixes everything
"Revert kernel patch causing failures on CIFS share disk usage"

**Comment by n0tOdd** [comment]
Fixed with todays update of HA OS
