### ISSUE TITLE
Deezer infinite loading on playlist

### ISSUE THREAD

**Issue by MateoGreil** [music-assistant/hass-music-assistant#1777]
### What version of Music Assistant has the issue?

2.0.0b81

### The problem

When I try to load a certain playlist, I face to an infinite loading.
I guess that's cause I got some "personal song" in this playlist : with deezer, you can upload your own mp3 songs.
-> When I remove these songs from the playlist, all is working back

### How to reproduce

Try to load a Deezer playlist with "personal song" (mp3 uploaded song).

### Relevant log output

```
2024-01-10 13:24:29.293 ERROR (MainThread) [music_assistant.webserver] [140046147838160] Error handling message: CommandMessage(message_id=18, command='music/playlists/playlist_tracks', args={'item_id': '1', 'provider_instance_id_or_domain': 'library'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 362, in _run_handler
    async for item in result:
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 149, in tracks
    async for track in self._get_provider_playlist_tracks(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 320, in _get_provider_playlist_tracks
    async for item in provider.get_playlist_tracks(item_id):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 304, in get_playlist_tracks
    yield self.parse_track(
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/deezer/__init__.py", line 597, in parse_track
    item_id=str(track.artist.id),
                ^^^^^^^^^^^^^^^
AttributeError: 'Artist' object has no attribute 'id'
```

### What version of Home Assistant Core are your running

2024.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

macOS

**Comment by OzGav** [comment]
To test can you take that song out of the playlist and try again?

**Comment by MateoGreil** [comment]
Yes, all is working good when I remove these songs

**Comment by OzGav** [comment]
Ok @arctixdev any thing that can be done about this?

**Comment by arctixdev** [comment]
Hmm i will try to take a look at it later today

**Comment by dbondarchuk** [comment]
Same problem here. Once I removed my mp3 from my favorites - I was able to load my Favourite tracks playlist
Playlists with my own mp3s are stuck on loading in the UI

**Comment by OzGav** [comment]
That’s good info. @arctixdev

**Comment by lyonzy** [comment]
I've fixed this on a local copy I'm running - it's caused by the Deezer API not returning `id` for some artists, for example:
```json
```
