### ISSUE TITLE
mass.search service crashes when mass server response contains tracks from spotify

### ISSUE THREAD

**Issue by fyhertz** [music-assistant/hass-music-assistant#1781]
### What version of Music Assistant has the issue?

2024.1.0b2

### The problem

The problem is that `compact_item` in `services.py` tries to pop keys from a list when the dict it receives from the server contains a list of lists.

### How to reproduce

I don't really know, but with a spotify account setup, all searches fail when track is checked.

### Relevant log output

Here is a stack trace from hass:

```
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
homeassistant  |     await func(hass, connection, msg)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 782, in handle_execute_script
homeassistant  |     script_result = await script_obj.async_run(
homeassistant  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1587, in async_run
homeassistant  |     return await asyncio.shield(run.async_run())
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 426, in async_run
homeassistant  |     await self._async_step(log_exceptions=False)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 479, in _async_step
homeassistant  |     self._handle_exception(
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 502, in _handle_exception
homeassistant  |     raise exception
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _async_step
homeassistant  |     await getattr(self, handler)()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 713, in _async_call_service_step
homeassistant  |     response_data = await self._async_run_long_action(
homeassistant  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 675, in _async_run_long_action
homeassistant  |     return long_task.result()
homeassistant  |            ^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
homeassistant  |     response_data = await coro
homeassistant  |                     ^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
homeassistant  |     return await target(service_call)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/mass/services.py", line 69, in handle_search
homeassistant  |     compact_item(item)
homeassistant  |   File "/config/custom_components/mass/services.py", line 62, in compact_item
homeassistant  |     compact_item(subitem)
homeassistant  |   File "/config/custom_components/mass/services.py", line 56, in compact_item
homeassistant  |     item.pop(key, None)
homeassistant  | TypeError: pop expected at most 1 argument, got 2
```

And here is a problematic reply from the mass server, you can see that `external_ids` is a list of one element that itself contains a list:

```json
{
   "media_type":"track",
   "item_id":"1lCRw5FEZ1gPDNPzy1K4zW",
   "provider":"spotify",
   "name":"We Are The Champions",
   "provider_mappings":[
      {
         "item_id":"1lCRw5FEZ1gPDNPzy1K4zW",
         "provider_domain":"spotify",
         "provider_instance":"spotify",
         "available":true,
         "audio_format":{
            "content_type":"ogg",
            "sample_rate":44100,
            "bit_depth":16,
            "channels":2,
            "output_format_str":"ogg",
            "bit_rate":320
         },
         "url":"https://open.spotify.com/track/1lCRw5FEZ1gPDNPzy1K4zW",
         "details":"None"
      }
   ],
   "external_ids":[
      [
         "isrc",
         "GBUM71029619"
      ]
   ], ...
}
```

### Additional information

Seems like a server issue, it's strange that external_ids is a list!

### What version of Home Assistant Core are your running

2024.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
We will close this soon if we don’t receive any more info.

**Comment by fyhertz** [comment]
Here is an example of a search that fails, but they all fail really when I search for a track:

```json
services: mass.search
data:
  limit: 5
  media_type:
    - track
  name: something
```

And here is the response when I patch `compact_item` to handle a list of lists:

```json
artists: []
albums: []
tracks:
  - media_type: track
    item_id: 0Fk2JzsQIhZvfm5AC0FRKG
    provider: spotify
    name: Something Going On
    external_ids:
      - - isrc
        - FRX872019105
    sort_name: something going on
    uri: spotify://track/0Fk2JzsQIhZvfm5AC0FRKG
    duration: 308
    version: Kompa Gouyad Extended Mix
    artists:
      - media_type: artist
        item_id: 2DBaDAcrh5sf17yR1qbnsy
        provider: spotify
        name: Kaysha
        external_ids: []
        sort_name: kaysha
        uri: spotify://artist/2DBaDAcrh5sf17yR1qbnsy
      - media_type: artist
        item_id: 1HbVmlLVon4MWfiMZmZ9kR
        provider: spotify
        name: Dj Benjimix
        external_ids: []
        sort_name: benjimix
        uri: spotify://artist/1HbVmlLVon4MWfiMZmZ9kR
      - media_type: artist
        item_id: 18zQrhTEkqtdwBXW4HTapp
        provider: spotify
        name: Gellokeyzz
        external_ids: []
        sort_name: gellokeyzz
        uri: spotify://artist/18zQrhTEkqtdwBXW4HTapp
      - media_type: artist
        item_id: 00eXN0mxI8gYKIRlrpBD6p
        provider: spotify
        name: G-Mixx
        external_ids: []
        sort_name: g-mixx
        uri: spotify://artist/00eXN0mxI8gYKIRlrpBD6p
      - media_type: artist
        item_id: 6gJHWIsO12jAZRCofnBrEH
        provider: spotify
        name: JustGerdy
        external_ids: []
        sort_name: justgerdy
        uri: spotify://artist/6gJHWIsO12jAZRCofnBrEH
    album:
      media_type: album
      item_id: 1YhWmO4SE7x0h02vgFv5at
      provider: spotify
      name: Something Going On
      external_ids: []
      sort_name: something going on
      uri: spotify://album/1YhWmO4SE7x0h02vgFv5at
      version: Kompa Gouyad Extended Mix
      year: 2020
      artists:
        - media_type: artist
          item_id: 2DBaDAcrh5sf17yR1qbnsy
          provider: spotify
          name: Kaysha
          external_ids: []
          sort_name: kaysha
          uri: spotify://artist/2DBaDAcrh5sf17yR1qbnsy
      album_type: single
playlists: []
radio: []
```

As you can see, `external_ids` is a list of lists. Is it by design or a server issue?

**Comment by fyhertz** [comment]
Looking at the server source code, it seems expected, see: https://github.com/music-assistant/server/commit/866ad760ce7e7baf6c1fdddaab708a44951d7afc#diff-0978b2897cdb1b19ecb1b4df73d6f8fea8df0b7fc294bc62dfbaf80a7cf70b13R205

**Comment by OzGav** [comment]
Thanks. This will get looked at in due course. If you identify a fix PRs are welcome

**Comment by OzGav** [comment]
Please try again with beta 85 as this is working for me now.

**Comment by OzGav** [comment]
If this is still a problem we can reopen

**Comment by jacobswe** [comment]
I am still getting this error, same recreation as above. Whenever I include 'track' as a media_type, the search fails giving the TypeError: pop expected at most 1 argument, got 2 trace. Everything on my system should be up to date though, so I'm curious if this is still broken for anyone else.

**Comment by jacobswe** [comment]
Thanks for reopening this, I just opened a PR that should fix this. It seems there may be deeper issues with the `external_ids` field (should be a flat list?) but it shouldn't be relevant to this PR since even if that is fixed it would still be a list and trigger this edge case.

**Comment by blairun** [comment]
Can this issue be reopened? After updating to the latest, I still cannot search for tracks from spotify.

fails searching for tracks
![Screenshots](https://github.com/music-assistant/hass-music-assistant/assets/1585872/b4c4a326-27b7-46d2-97c1-2a726adfa857)

succeeds with all other media types
![Screenshot2](https://github.com/music-assistant/hass-music-assistant/assets/1585872/74f636ac-a760-4fa6-9424-739652eae10c)

**Comment by jacobswe** [comment]
2024.1.0 is the latest release and the fix is not included in that. You can install the repo manually if you need this functionality now, or you can wait until the next release or RC is cut.

**Comment by OzGav** [comment]
2024.2.0 has been released.
