### ISSUE TITLE
cannot play media with group player

### ISSUE THREAD

**Issue by H30lth** [music-assistant/hass-music-assistant#1787]
### What version of Music Assistant has the issue?

2024.1.0b2

### The problem

When I try to play music from any provider as a group to squeezlite players it doesn't play. Though plays fine when an individual player is selected

### How to reproduce

Select media
Play from group device

### Relevant log output

  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 41, in get_artist
    return await asyncio.to_thread(_get_artist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 37, in _get_artist
    user = ytm.get_user(channelId=prov_artist_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/browsing.py", line 312, in get_user
    user = {'name': nav(response, ['header', 'musicVisualHeaderRenderer'] + TITLE_TEXT)}
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 82, in nav
    raise err
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 76, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'musicVisualHeaderRenderer

### Additional information

Tried playing group player without a home assistant intergration and also after a fresh reinstall. Still has the same error.

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
What do you mean by “play from group device”? Do you mean play to a universal group?

**Comment by H30lth** [comment]
Sorry yes.

**Comment by OzGav** [comment]
Looks like a YTM problem. Do you have another music provider to try? Radiobrowser is good if you have nothing else

**Comment by H30lth** [comment]
I have tried with spotify and an nsf unfortunately same issue.

**Comment by H30lth** [comment]
I just attempted again and got some log files about id3 tags. Im not sure how to find the play log. I assumed it would  come up as an error if anything.
File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 729, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]
2024-01-15 22:05:41.472 ERROR (MainThread) [music_assistant.providers.filesystem_smb] Error processing Zombies/Zombies - Time Of The Season.mp3 - missing ID3 tag [albumartist]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 326, in sync_library
    track = await self._parse_track(item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 729, in _parse_track
    raise InvalidDataError("missing ID3 tag [albumartist]")
music_assistant.common.models.errors.InvalidDataError: missing ID3 tag [albumartist]

**Comment by OzGav** [comment]
Ok you need to properly tag your music to fix the last error. There is an option to ignore it in the local provider settings

**Comment by H30lth** [comment]
Thankyou I'll give that a go. It plays the file fine when I select a single player.

**Comment by OzGav** [comment]
Understood. Exactly what players are you trying to group?

**Comment by H30lth** [comment]
At the moment only 2 players both running picoreplayer using squeezelite. Separately they work great. 
They used to work but since about 3 versions ago began running into problems. Thought it could be something my end but ran out of ideas.

**Comment by OzGav** [comment]
Yeah ok. Will have to wait for someone else to see if they can recreate this as I only have multiple chromecast devices.

**Comment by H30lth** [comment]
Thanks for trying to help 🙂

**Comment by OzGav** [comment]
Beta 83 includes improvements to playback and groups. Please see if this has resolved your issue

**Comment by H30lth** [comment]
Amazing it has. Thankyou for the improvements!!!!
