### ISSUE TITLE
Media Panel in Home Assistant UI not working since 2024.1

### ISSUE THREAD

**Issue by hendrik-hog** [music-assistant/hass-music-assistant#1792]
### What version of Music Assistant has the issue?

2024.1.3

### The problem

I run into an unknown error when trying to send a TTS message to a music assistant device using the media panel in the UI.

### How to reproduce

* Open media panel in Home Assistant UI
* Select webbrowser as destination
* Select Text-to-speech, then Google
* Switch destination to entity provided by music assistant (Google Cast device)
* Unknown error appears

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: components/media_player/__init__.py:1298
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14. Januar 2024 um 21:36:07 (15 occurrences)
Last logged: 16:13:49

[140523260739904] Error handling message: Unknown error (unknown_error) Hendrik from 10.0.10.31 (Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/UQ1A.231205.015; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.194 Mobile Safari/537.36 Home Assistant/2023.12.4-11898 (Android 14; Pixel 8 Pro))
[140517128838976] Error handling message: Unknown error (unknown_error) Hendrik from 10.0.10.35 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.12.1 (io.robbie.HomeAssistant; build:2023.508; macOS 14.2.1) Mobile/HomeAssistant, like Safari)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1298, in websocket_browse_media
    if MediaPlayerEntityFeature.BROWSE_MEDIA not in player.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

### Additional information

Also reported this bug to https://github.com/home-assistant/core/issues/108101

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Ok that error is originating in HA and MA does not yet support TTS. So nothing we can do here
