### ISSUE TITLE
Get errors when there is an 's in the folder name

### ISSUE THREAD

**Issue by mfabiani53** [music-assistant/hass-music-assistant#1801]
### What version of Music Assistant has the issue?

2.0.0b82

### The problem

2024-01-19 15:07:44.504 ERROR (MainThread) [music_assistant.providers.filesystem_smb] Error processing Tom Petty - Studio Discography/Tom Petty & The Heartbreakers - She's The One 1996/13 - Angel Dream (No. 2).flac - near "s": syntax error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/filesystem_local/base.py", line 327, in sync_library
    await self.mass.music.tracks.add_item_to_library(track, metadata_lookup=False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 149, in add_item_to_library
    library_item = await self.update_item_in_library(cur_item.item_id, item)  # noqa: SIM114
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 208, in update_item_in_library
    await self._set_track_album(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 418, in _set_track_album
    elif existing := await self.mass.music.artists.get_library_item_by_prov_id(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 296, in get_library_item_by_prov_id
    for item in await self.get_library_items_by_prov_id(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 386, in get_library_items_by_prov_id
    paged_list = await self.library_items(limit=limit, offset=offset, extra_query=query)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 163, in library_items
    return await super().library_items(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 115, in library_items
    items = await self._get_library_items_by_query(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 617, in _get_library_items_by_query
    for db_row in await self.mass.music.database.get_rows_from_query(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 54, in get_rows_from_query
    return await self._db.execute_fetchall(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 209, in execute_fetchall
    return await self._execute(self._execute_fetchall, sql, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 85, in _execute_fetchall
    cursor = self._conn.execute(sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "s": syntax error

### How to reproduce

Every time  there is a scan of the library

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
this will be fixed in b139

**Comment by OzGav** [comment]
@mfabiani53 please confirm this is fixed when b139 is released

**Comment by OzGav** [comment]
Closing due no further followup. Assuming fixed.
