### ISSUE TITLE
Music not playing queue

### ISSUE THREAD

**Issue by supershree** [music-assistant/hass-music-assistant#1810]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

When playing a playlist from youtube music, music stops after playing one song. 

### How to reproduce

Select youtube playlist, play through song, music stops. I can skip to next song and it will eventually play

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Windows

**Comment by senderbell** [comment]
I have the same problem on Spotify. The music stops after some tracks. I had to create an automation that turns the music back on when it detects a break.

**Comment by senderbell** [comment]
I'm using Google chromecast players.

**Comment by OzGav** [comment]
@senderbell are they in a group?

**Comment by senderbell** [comment]
Yes, they are in group but the group was created via Google Home app.

**Comment by OzGav** [comment]
@senderbell ok that is a known issue which is fixed in the next beta

**Comment by rodgers86** [comment]
This is also happening to me. 

YouTube music as source. 

Sonos speakers as devices. 

Only happened since updating to 2.00b83

plays one song then stops. Tried various playlists. 

Running on HAOS on Proxmox.

**Comment by rodgers86** [comment]
I actually use any other providers!

**Comment by OzGav** [comment]
Ok but what happens if you manually add tracks to the queue does it stop then? Just trying to work out if this is only happening when you listen to a playlist. Also how are you instigating playback, via an automation or via the MA UI?

**Comment by OzGav** [comment]
@supershree also still waiting on more info from you as to what players you are using and if they are grouped.

**Comment by supershree** [comment]
I'm using YouTube music and not using grouped speakers.

Thanks!

**Comment by OzGav** [comment]
@supershree thanks. Are you able to try any other providers? Trying to work out if this is YT only.

**Comment by almostserious** [comment]
I have a similar issue. However, its not always the case.
In my trials, when i play to a chromecast group the song that plays simply plays on repeat several times.

In the logs i then see the following output:

```
KeyError: 'streamingData'
2024-01-23 14:48:56.365 ERROR (MainThread) [music_assistant.webserver] [139707437933584] Error handling message: CommandMessage(message_id=157, command='music/item_by_uri', args={'uri': 'ytmusic://track/zZ29lDumb9U'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 309, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 333, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 69, in get
    track = await super().get(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 187, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 438, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 267, in get_item
    return await self.get_track(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 314, in get_track
    if track_obj := await get_track(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 94, in get_track
    return await asyncio.to_thread(_get_song)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 91, in _get_song
    track["streamingData"] = track_obj["streamingData"]
```

I just tried it again on a single chromecast speaker, and it played fine. Going back to play on the Group now works fine too.

**Comment by supershree** [comment]
I don't have anything besides youtube

**Comment by OzGav** [comment]
Please check again with beta 86

**Comment by OzGav** [comment]
Closing assuming all is well with this.
