### ISSUE TITLE
mass.play_media radio mode not working

### ISSUE THREAD

**Issue by lor74** [music-assistant/hass-music-assistant#1816]
### What version of Music Assistant has the issue?

2.0.0b84

### The problem

Cannot reproduce playlist with radio mode on

### How to reproduce

```
        - service: mass.play_media
          target:
            device_id: e325948e0c54ba0b8ea12bbc6d11b162
          data:
            media_type: playlist
            media_id: "Artist Name"
            radio_mode: "on"
            enqueue: replace
```

### Relevant log output

QUOBUZ PROVIDER
```
2024-01-23 08:18:46.939 ERROR (MainThread) [music_assistant.webserver] [548224243152] Error handling message: CommandMessage(message_id='a9cea024172646d99b018df6384e8640', command='players/queue/play_media', args={'queue_id': 'aa:aa:fb:39:1a:2c', 'media': ['qobuz://playlist/1989170'], 'option': 'replace', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 230, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 886, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 590, in dynamic_tracks
    return await self._get_dynamic_tracks(ref_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 379, in _get_dynamic_tracks
    raise UnsupportedFeaturedException(
music_assistant.common.models.errors.UnsupportedFeaturedException: No Music Provider found that supports requesting similar tracks.
```
SPOTIFY PROVIDER
```
2024-01-23 08:27:48.729 ERROR (MainThread) [music_assistant.webserver] [548213042768] Error handling message: CommandMessage(message_id='33e05d08a0cb49fdbe19f3bf062c930c', command='players/queue/play_media', args={'queue_id': 'aa:aa:fb:39:1a:2c', 'media': ['spotify://playlist/37i9dQZF1DZ06evO1zmK7O'], 'option': 'play', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 230, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 886, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 590, in dynamic_tracks
    return await self._get_dynamic_tracks(ref_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 379, in _get_dynamic_tracks
    raise UnsupportedFeaturedException(
music_assistant.common.models.errors.UnsupportedFeaturedException: No Music Provider found that supports requesting similar tracks.
2024-01-23 08:33:29.630 ERROR (MainThread) [music_assistant.webserver] [548213042768] Error handling message: CommandMessage(message_id='f2c5767b840e4df3b036f78dabdae59f', command='players/queue/play_media', args={'queue_id': 'aa:aa:fb:39:1a:2c', 'media': ['spotify://artist/5LlJgNc8PgsXsloNEw2uDW'], 'option': 'play', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 230, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 886, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 590, in dynamic_tracks
    return await self._get_dynamic_tracks(ref_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 379, in _get_dynamic_tracks
    raise UnsupportedFeaturedException(
music_assistant.common.models.errors.UnsupportedFeaturedException: No Music Provider found that supports requesting similar tracks.
```

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
I was wondering if that might happen. Only certain providers support radio mode. That error says to me that no provider will accept an artist as the starting point for radio mode. Those URIs you were getting before probably were for tracks. So you could change your input selects to be of the form “Artist - Track” and see if it works then.

**Comment by OzGav** [comment]
Actually you may be right. I get errors when requesting tracks. This will get looked at in due course

**Comment by OzGav** [comment]
Actually there is something else going on which may be causing this. Will check if this is still a problem once the other problem is resolved.

**Comment by OzGav** [comment]
Please check with beta 85 as this is working fine for me now.

**Comment by lor74** [comment]
Hi, yes it’s working also for me. Thanks.
