### ISSUE TITLE
Annoyingly 1 Station from TuneIn Radio not working

### ISSUE THREAD

**Issue by brinzlee** [music-assistant/hass-music-assistant#1826]
### What version of Music Assistant has the issue?

 2.0.0b85

### The problem

I have been using Music Assistant Beta 2 for ages and been using TuneIn to play my favourite music station on my google device. This has now stopped working. All other stations work. And it works directly from TuneIn. I have tried to delete TuneIn and re add it and update the database but no luck. I have included the log which contains many errors when I click on this station.

### How to reproduce

Play Radio Essex using the TuneIn App within Music Assistant

### Relevant log output

2024-01-24 15:47:12.572 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 965, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_proto.py", line 224, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Expected HTTP/:

    b'RPC-ERR authentication failed\n'
      ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 482, in serve_queue_item_stream
    await set_stream_details(self.mass, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 277, in set_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/tunein/__init__.py", line 230, in get_stream_details
    url_resolved, supports_icy = await resolve_radio_stream(self.mass, stream["url"])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 541, in resolve_radio_stream
    async with mass.http_session.head(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 601, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 967, in start
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message="Expected HTTP/:\n\n  b'RPC-ERR authentication failed\\n'\n    ^", url=URL('https://playoutonestreaming.com/proxy/essex?mp=/stream')

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
I just tried the url at the end of your log post and it works ok in my browser. Out of interest have you tried entering that url manually on the radio stations view?

**Comment by brinzlee** [comment]
Yes I tried it manually in a browser and it worked. Thats why I thought maybe there was some sort of bug in music assistant.

**Comment by OzGav** [comment]
Yeah I didn't mean in the browser I meant via the MA radio stations view. The menu in the top right has the option to manually add a stream URL. However, I just tried it and that doesn't work either but with a different error. Might take a while until this can get looked at unfortunately. If you can find a different stream URL then try that. All I can surmise at the moment is that the stream URL changed and that has caused a problem...

**Comment by marcelveldt** [comment]
I have reproduced the issue - will be fixed in the beta (beta89) later today.
