### ISSUE TITLE
Unable to group Sonos players via interface - only by using "Add Group Player" but then unable to play any music

### ISSUE THREAD

**Issue by milkplus27** [music-assistant/hass-music-assistant#1836]
### What version of Music Assistant has the issue?

2.0.0b86

### The problem

I am unable to group Sonos players (Play:1 and Arc) together via the interface.

When I try to group two or more players together it just stops the music and puts all players on idle - unless the Arc is outputting TV audio, in which case it continues and other players stop. But nothing gets grouped either way.

Played around with it some more. I created a group player of Play:1 and Arc which seems to have broken things again. Group won't play any music, and also now can't play anything on individual players again - this now appears to be regardless of whether the file is hires or not. (see: https://github.com/music-assistant/hass-music-assistant/issues/1823 for reference)

Looking at the Sonos app, it's spitting out an error msg (see attached) and trying to play music on the speaker group (even though the speakers are not grouped in the Sonos app) even if I tell MA to only play on one speaker.

If i delete the Player Group, things go back to normal and i can play music to players individually but still unable to group.

### How to reproduce

Try to group Sonos players together but can't. Create Player Group from Settings, unable to play music on it.

### Relevant log output

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/core.py", line 849, in stop
    self.avTransport.Stop([("InstanceID", 0), ("Speed", 1)])
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 701 received: Transition not available from 192.168.1.247
2024-01-27 08:10:15.545 ERROR (MainThread) [music_assistant.webserver] [140629247423312] Error handling message: CommandMessage(message_id=36, command='players/cmd/sync', args={'player_id': 'RINCON_B8E93752747A01400', 'target_player': 'RINCON_48A6B8B07BFF01400'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 74, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 671, in cmd_sync
    await player_provider.cmd_sync(player_id, target_player)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 518, in cmd_sync
    sonos_player.soco_device.join, self.sonosplayers[target_player].soco
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SonosPlayer' object has no attribute 'soco'
2024-01-27 08:14:48.216 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (Gerald Wilson Big Band - Teri) to player Kitchen
2024-01-27 08:15:11.860 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (Gerald Wilson Big Band - Nancy Jo) to player Kitchen
2024-01-27 08:17:40.917 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (Gerald Wilson Big Band - Nancy Jo) to player Kitchen
2024-01-27 08:18:04.437 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (Gerald Wilson Big Band - Milestones) to player Kitchen
2024-01-27 08:20:16.914 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (Gerald Wilson Big Band - Milestones) to player Kitchen
2024-01-27 08:20:37.152 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (Gerald Wilson Big Band - Latino) to player Kitchen
2024-01-27 08:22:00.090 ERROR (MainThread) [music_assistant.webserver] [140629650476176] Error handling message: CommandMessage(message_id=16, command='players/cmd/sync', args={'player_id': 'RINCON_B8E93752747A01400', 'target_player': 'RINCON_48A6B8B07BFF01400'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 372, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 74, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 671, in cmd_sync
    await player_provider.cmd_sync(player_id, target_player)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 518, in cmd_sync
    sonos_player.soco_device.join, self.sonosplayers[target_player].soco
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SonosPlayer' object has no attribute 'soco'
2024-01-27 08:22:34.168 INFO (MainThread) [music_assistant.players] Player registered: ugp_ljcmlmdf/Kitchen + Living Room 
2024-01-27 08:23:08.026 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:23:08.060 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:23:13.127 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_B8E93752747A01400/command/next.mp3) to player Kitchen
2024-01-27 08:23:18.049 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_48A6B8B07BFF01400/command/next.mp3) to player Living Room
2024-01-27 08:23:18.051 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen + Living Room  - crossfade: False
2024-01-27 08:23:18.053 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:23:18.084 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:23:19.765 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue Kitchen + Living Room 
2024-01-27 08:24:33.989 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:24:34.054 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:24:39.116 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_B8E93752747A01400/command/next.mp3) to player Kitchen
2024-01-27 08:24:44.012 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_48A6B8B07BFF01400/command/next.mp3) to player Living Room
2024-01-27 08:24:44.013 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen + Living Room  - crossfade: False
2024-01-27 08:24:44.033 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:24:44.136 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:24:45.494 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue Kitchen + Living Room 
2024-01-27 08:24:57.044 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:24:57.090 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:25:02.148 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_B8E93752747A01400/command/next.mp3) to player Kitchen
2024-01-27 08:25:07.056 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_48A6B8B07BFF01400/command/next.mp3) to player Living Room
2024-01-27 08:25:07.057 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen + Living Room  - crossfade: False
2024-01-27 08:25:07.061 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:25:07.259 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:25:08.672 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue Kitchen + Living Room 
2024-01-27 08:26:04.850 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:26:04.918 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:26:09.981 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_B8E93752747A01400/command/next.mp3) to player Kitchen
2024-01-27 08:26:14.871 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_48A6B8B07BFF01400/command/next.mp3) to player Living Room
2024-01-27 08:26:14.872 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen + Living Room  - crossfade: False
2024-01-27 08:26:14.879 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:26:14.908 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:26:16.185 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue Kitchen + Living Room 
2024-01-27 08:26:40.512 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:26:40.556 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:26:45.607 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_B8E93752747A01400/command/next.mp3) to player Kitchen
2024-01-27 08:26:50.534 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_48A6B8B07BFF01400/command/next.mp3) to player Living Room
2024-01-27 08:26:50.536 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen + Living Room  - crossfade: False
2024-01-27 08:26:50.539 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:26:50.825 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:26:53.056 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue Kitchen + Living Room 
2024-01-27 08:30:48.808 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:30:48.855 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:30:53.923 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_B8E93752747A01400/command/next.mp3) to player Kitchen
2024-01-27 08:30:58.831 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_48A6B8B07BFF01400/command/next.mp3) to player Living Room
2024-01-27 08:30:58.833 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen + Living Room  - crossfade: False
2024-01-27 08:30:58.835 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:30:59.058 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:31:00.204 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue Kitchen + Living Room 
2024-01-27 08:32:01.538 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:32:01.581 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:32:06.654 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_B8E93752747A01400/command/next.mp3) to player Kitchen
2024-01-27 08:32:11.562 INFO (MainThread) [music_assistant.providers.sonos] Enqued next track (http://192.168.1.155:8096/RINCON_48A6B8B07BFF01400/command/next.mp3) to player Living Room
2024-01-27 08:32:11.564 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen + Living Room  - crossfade: False
2024-01-27 08:32:11.565 WARNING (MainThread) [music_assistant.streams] Player RINCON_48A6B8B07BFF01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:32:11.821 WARNING (MainThread) [music_assistant.streams] Player RINCON_B8E93752747A01400 is making multiple requests to the same stream, playback may be disturbed!
2024-01-27 08:32:12.627 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue Kitchen + Living Room
![Screenshot_20240127-083157](https://github.com/music-assistant/hass-music-assistant/assets/20435315/2325ae5e-a64e-41b3-97f3-38cb195c33f0)

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by boxofrabbits** [comment]
I'm experiencing similar since the latest update. I'm unable to 'Sync' Sonos players. Normally I'd play something in the dining room and then press the link button next to the office and they'd both sync up beautifully. 

But since theast update attempting to sync them does nothing. Have attempted a reinstall. Works fine from the Sonos app syncing the two, doesn't work from MA.
![Screenshot_20240127-105035](https://github.com/music-assistant/hass-music-assistant/assets/75987600/20845cb2-e197-4bc5-9a39-29348231d145)

**Comment by marcelveldt** [comment]
Will be fixed in next update (b87)

**Comment by OzGav** [comment]
@milkplus27 and @boxofrabbits please confirm this has been fixed

**Comment by marcelveldt** [comment]
Sorry, problems are not fixed in b87 - it will take more some more time to look into the issues with sonos players.
If you can, restore a backup of b85, otherwise wait for tomorrow so I can fix the problem

**Comment by OzGav** [comment]
Related issue https://github.com/music-assistant/hass-music-assistant/issues/1833

**Comment by OzGav** [comment]
Please try again with beta88

**Comment by boxofrabbits** [comment]
> Please try again with beta88

Sorry how do I do this? Does it require manual installation?

**Comment by OzGav** [comment]
If you are using HAOS just go to settings>>addons and select Music Assistant and you should see the update waiting. If you are using docker then however you do your installs then install the latest

**Comment by OzGav** [comment]
We will close this soon as it is assumed to be fixed.

**Comment by milkplus27** [comment]
will test this tonight and report back. thanks for prioritising it :)

**Comment by milkplus27** [comment]
seems to be sorted on my end, too. thanks for the great work!
