### ISSUE TITLE
Different errors after latest update

### ISSUE THREAD

**Issue by canedje** [music-assistant/hass-music-assistant#1839]
### What version of Music Assistant has the issue?

Latest (Docker under Unraid, I do not know how to read latest version) serverversion: 2.0.b87

### The problem

After latest update different errors occur.
I can not enter settings of my local filesystem. The app is crashing trying that.
Bladeren is not working. Keeping spinning
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/c7e77fa6-931c-43a4-b165-690f29b435b8)

The music assistant logo not showing up. etc.
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/6d435ff8-a838-4635-a7cc-f673411107b5)

It is keeping running the latest playlist, while stoppped
MA is not usable anymore
EDIT: I renamed the data directory and did a restart.
Music Assistant is starting up, but trying  adding: Filesystem (local disk) is crashing the docker. There are no fields to fill in anymore, and everything is stuc. A restart is needed to enter again:
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/ec50defc-3a4c-481d-855e-65cbb3ac3316)

### How to reproduce

After startup docker  it is like that

### Relevant log output

2024-01-27 22:04:17.168 INFO (MainThread) [music_assistant] Starting Music Assistant Server (3f360a89e58f426885a2f94962931abb) version 2.0.0b87 - uvloop: False
2024-01-27 22:04:36.207 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.2.240:8095
2024-01-27 22:04:36.480 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-01-27 22:04:36.524 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
2024-01-27 22:04:36.524 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.2.240:8096
2024-01-27 22:04:36.591 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-01-27 22:04:36.591 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-01-27 22:04:36.591 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-01-27 22:04:36.591 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-01-27 22:04:36.591 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-01-27 22:04:36.592 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-01-27 22:04:36.592 INFO (MainThread) [music_assistant] Loaded music provider URL
2024-01-27 22:04:36.609 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-01-27 22:04:36.609 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-01-27 22:04:36.609 INFO (MainThread) [music_assistant.providers.slimproto] Started SLIMProto server on port 3483
2024-01-27 22:04:36.609 INFO (MainThread) [music_assistant.providers.slimproto.cli] Registering jsonrpc endpoints on the webserver
2024-01-27 22:04:36.611 INFO (MainThread) [music_assistant] Loaded music provider Filesystem (local disk)
2024-01-27 22:04:36.611 INFO (MainThread) [music_assistant.providers.slimproto.cli] Starting (telnet) CLI on port 9090
2024-01-27 22:04:36.611 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2024-01-27 22:04:36.761 INFO (MainThread) [music_assistant.players] Player registered: c5710169-3535-9787-b7f4-8bddd4612c2a/Woonkamer
2024-01-27 22:04:36.947 INFO (MainThread) [music_assistant.players] Player registered: 14734ecf-26cd-2a91-6d3a-5d8e60a06758/Google Home Zithoek
2024-01-27 22:04:37.153 INFO (MainThread) [music_assistant.players] Player registered: RINCON_000E58BE297501400/Tv Hoek
2024-01-27 22:04:37.587 INFO (MainThread) [music_assistant.players] Player registered: RINCON_B8E93751C96801400/Eetkamer
2024-01-27 22:04:37.734 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as edwardhogeveen
2024-01-27 22:04:37.734 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-01-27 22:04:37.743 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-01-27 22:04:37.901 INFO (MainThread) [music_assistant.players] Player registered: 58ae265a-6f2e-31e1-4ade-e76ba5bdfb1e/Google Home overloop
2024-01-27 22:04:38.279 INFO (MainThread) [music_assistant.players] Player registered: uuid:0bebc200-00c8-1000-87c7-0c89109bd8b2/[TV]Samsung LED46
2024-01-27 22:04:38.643 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-279' coro=<PlayerQueuesController._check_enqueue_next.<locals>._enqueue_next() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py:967> exception=SoCoUPnPException()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 971, in _enqueue_next
    await self.mass.players.enqueue_next_queue_item(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 632, in enqueue_next_queue_item
    await player_prov.enqueue_next_queue_item(player_id=player_id, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 628, in enqueue_next_queue_item
    await self._enqueue_item(sonos_player, url=url, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 742, in _enqueue_item
    await asyncio.to_thread(
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from 192.168.2.52
2024-01-27 22:04:40.718 WARNING (MainThread) [music_assistant.providers.filesystem_local] Blues/The Blues Collection 01 - 92 (MP3@VBR)/The Blues Collection 58 - Eddie Boyd - Third Degree/02 - I Got The Blues.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-01-27 22:04:40.879 WARNING (MainThread) [music_assistant.providers.filesystem_local] Blues/The Blues Collection 01 - 92 (MP3@VBR)/The Blues Collection 58 - Eddie Boyd - Third Degree/15 - I Got The Blues.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-01-27 22:04:41.377 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (local disk) completed
2024-01-27 22:04:42.402 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-01-27 22:04:46.580 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-326' coro=<PlayerQueuesController._check_enqueue_next.<locals>._enqueue_next() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py:967> exception=SoCoUPnPException()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 971, in _enqueue_next
    await self.mass.players.enqueue_next_queue_item(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 632, in enqueue_next_queue_item
    await player_prov.enqueue_next_queue_item(player_id=player_id, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 628, in enqueue_next_queue_item
    await self._enqueue_item(sonos_player, url=url, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 742, in _enqueue_item
    await asyncio.to_thread(
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from 192.168.2.52
2024-01-27 22:04:56.591 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-327' coro=<PlayerQueuesController._check_enqueue_next.<locals>._enqueue_next() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py:967> exception=SoCoUPnPException()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 971, in _enqueue_next
    await self.mass.players.enqueue_next_queue_item(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 632, in enqueue_next_queue_item
    await player_prov.enqueue_next_queue_item(player_id=player_id, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 628, in enqueue_next_queue_item
    await self._enqueue_item(sonos_player, url=url, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 742, in _enqueue_item
    await asyncio.to_thread(
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from 192.168.2.52
2024-01-27 22:05:06.639 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-328' coro=<PlayerQueuesController._check_enqueue_next.<locals>._enqueue_next() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py:967> exception=SoCoUPnPException()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 971, in _enqueue_next
    await self.mass.players.enqueue_next_queue_item(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 632, in enqueue_next_queue_item
    await player_prov.enqueue_next_queue_item(player_id=player_id, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 628, in enqueue_next_queue_item
    await self._enqueue_item(sonos_player, url=url, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/sonos/__init__.py", line 742, in _enqueue_item
    await asyncio.to_thread(
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.11/site-packages/soco/services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from 192.168.2.52

### Additional information

I does run it standalone as a docker under Unraid, not via Home Assistant.
So HA environment is not interesting

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Serverversion

2.0.b87

**Comment by TheWebMachine** [comment]
I can confirm that the MA logo is not showing up, even on HAOS with Add-On. I confirmed on both mobile app and desktop browser. 

I can't confirm the other issue you report, but I was about to create an Issue for the logo and figured I would chime in here, instead.

**Comment by marcelveldt** [comment]
**beta87 has several issues - please revert (restore backup) to version b86 or b65**
I'm looking into the issues one by one but it will take me some time to work trough. Remember, its beta so stuff like this can happen unfortunately. Let's working though a couple more betas so we can finally launch a stable version 😉

**Comment by OzGav** [comment]
Appears to the the same as https://github.com/music-assistant/hass-music-assistant/issues/1840 ?

**Comment by OzGav** [comment]
Please try again with beta88
