### ISSUE TITLE
Can't play YouTube Music 

### ISSUE THREAD

**Issue by dacmcbibs** [music-assistant/hass-music-assistant#1841]
### What version of Music Assistant has the issue?

20.0.0b87

### The problem

Youtube Music will not queue any music

### How to reproduce

try to play anything from youtube music

### Additional information

2024-01-27 21:19:31.135 ERROR (MainThread) [music_assistant.webserver] [22581819333584] Error handling message: CommandMessage(message_id=166, command='players/queue/play_media', args={'queue_id': 'bf53f8a8-cb3d-dbb9-1685-0a555e0ad29a', 'media': ['library://track/159']})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 373, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 345, in play_media
    queue.radio_source += radio_mode
TypeError: 'bool' object is not iterable

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
beta 87 has a bunch of issue unfortunately. Please advise if this is still an issue after 88 comes out in a day or so.

**Comment by miketarg** [comment]
Same issue here but I'm using both radio and spotcast.

I have changed anything and I'm getting this error when trying to run scripts to stat the music:-

Failed to call service script/spotcast_start_random_radio_station. 'bool' object is not iterable

**Comment by bj61251** [comment]
I'm seeing this same 'bool' object is not iterable error when using Media Extractor to try and play a podcast episode from an XML Url on a Music Assistant speaker group device

**Comment by nikito** [comment]
Same issue here as well. Will report back on next beta 🙂

**Comment by OzGav** [comment]
Please try again with beta88

**Comment by dacmcbibs** [comment]
Can confirm that YouTube Music is working in b88
