### ISSUE TITLE
Can't play any music on Sonos

### ISSUE THREAD

**Issue by Dekadinious** [music-assistant/hass-music-assistant#1844]
### What version of Music Assistant has the issue?

2.0.0b88

### The problem

After the upgrade that broke a lot of stuff, I have not been able to play music on my Sonos speakers. I can maybe get it to work by manually going into Music Assistant and choosing a song, but I have been able to do that once and have tried 20 times.

Nothing happens.

I waited for b88 in the hope that it would fix it, but it has not. I can't play from automations either...

### How to reproduce

I don't know what to write here. I just try to play on my Sonos PLAY:1 from Spotify, and nothing happens. I have two speakers, none of them work.

### Relevant log output

2024-01-29 12:23:31.730 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 456, in serve_queue_item_stream
    await set_stream_details(self.mass, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 293, in set_stream_details
    loudness, gain_correct = await get_gain_correct(mass, streamdetails)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 313, in get_gain_correct
    player_settings = await mass.config.get_player_config(streamdetails.queue_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 329, in get_player_config
    if prov := self.mass.get_provider(raw_conf["provider"]):
                                      ~~~~~~~~^^^^^^^^^^^^
KeyError: 'provider'
2024-01-29 12:23:33.829 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 456, in serve_queue_item_stream
    await set_stream_details(self.mass, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 293, in set_stream_details
    loudness, gain_correct = await get_gain_correct(mass, streamdetails)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 313, in get_gain_correct
    player_settings = await mass.config.get_player_config(streamdetails.queue_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 329, in get_player_config
    if prov := self.mass.get_provider(raw_conf["provider"]):
                                      ~~~~~~~~^^^^^^^^^^^^
KeyError: 'provider'
2024-01-29 12:23:35.554 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 456, in serve_queue_item_stream
    await set_stream_details(self.mass, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 293, in set_stream_details
    loudness, gain_correct = await get_gain_correct(mass, streamdetails)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 313, in get_gain_correct
    player_settings = await mass.config.get_player_config(streamdetails.queue_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 329, in get_player_config
    if prov := self.mass.get_provider(raw_conf["provider"]):
                                      ~~~~~~~~^^^^^^^^^^^^
KeyError: 'provider'
2024-01-29 12:23:37.860 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 456, in serve_queue_item_stream
    await set_stream_details(self.mass, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 293, in set_stream_details
    loudness, gain_correct = await get_gain_correct(mass, streamdetails)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 313, in get_gain_correct
    player_settings = await mass.config.get_player_config(streamdetails.queue_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 329, in get_player_config
    if prov := self.mass.get_provider(raw_conf["provider"]):
                                      ~~~~~~~~^^^^^^^^^^^^
KeyError: 'provider'
2024-01-29 12:23:44.835 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/streams.py", line 456, in serve_queue_item_stream
    await set_stream_details(self.mass, queue_item=queue_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 293, in set_stream_details
    loudness, gain_correct = await get_gain_correct(mass, streamdetails)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 313, in get_gain_correct
    player_settings = await mass.config.get_player_config(streamdetails.queue_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 329, in get_player_config
    if prov := self.mass.get_provider(raw_conf["provider"]):
                                      ~~~~~~~~^^^^^^^^^^^^
KeyError: 'provider'

### Additional information

I have tried removing and adding the integration and reinstalling the addon. I have also tried removing and adding the speakers. Information of note is that my speakers show up twice, both as a Sonos device and as a Music Assistant device, in my Home Assistant. I don't know if that is to be expected. The entities are showing up as media_player.name_2 on both of the Music Assistant ones.

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
The two sets of speakers are because HA is detecting them and creating entities and so is MA.

Firstly, can you play something without issue to the HA discovered entities?

**Comment by Dekadinious** [comment]
Very quick to answer here, thanks!

I can play TTS and radio on the HA entities from my dashboard. I cannot, however, get them to start a song that has been loaded into them from Spotify and Music Assistant. If I click play, nothing happens.

I also added the MA entity to my dashboard and tried to play radio there. Nothing happened. The logs look the same after that attempt.

**Comment by OzGav** [comment]
You mention radio above do you actually mean a radio station? I am trying to work out if this is a Spotify issue or a Sonos issue. Can you go through and explain what does work.

**Comment by Dekadinious** [comment]
Yes, so I mean going here:

![image](https://github.com/music-assistant/hass-music-assistant/assets/37292177/ff99ac14-b94a-48ca-aceb-b6d0aae2ee35)

And finding a radio station. That works. TTS also works. So playing media on the HA entities work. But if I go into MA and try playing a song, nothing happens.

But my dashboard changes to the song I tried to play:

![image](https://github.com/music-assistant/hass-music-assistant/assets/37292177/f146c235-546c-4478-853c-8370917347dc)

This is the HA entity. If I click play here now, nothing happens.

**Comment by OzGav** [comment]
What if you try playing a radio station from MA?

**Comment by Dekadinious** [comment]
Tried it now via Tune-In. It loads up in the bottom, but it does not start playing:

![image](https://github.com/music-assistant/hass-music-assistant/assets/37292177/5f79a14d-09f8-4429-b321-4771818c2d0d)

The dashboard also changes, but the play button does nothing here either.

**Comment by OzGav** [comment]
Do you have any other players besides Sonos?

**Comment by Dekadinious** [comment]
Good thinking!

I have a Chromecast and a Samsung TV. Just turned them both on now. The Chromcast is listed as "off" and can't be selected, but I successfully played music from Spotify on my Samsung TV with Music Assistant!

**Comment by OzGav** [comment]
OK I am assuming you are doing everything through the MA interface. You should be able to turn on the Chromecast 
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/db5f1077-4c32-4bda-ac3f-30b7ec8b059a)

But it is starting to sound like a Sonos issue. Confirm TuneIN also plays ok to the TV. What type of provider is the TV showing as?

**Comment by Dekadinious** [comment]
The dropdown was not available, but I guess it was just a lag from turning it on. I can confirm that I can play both Spotify and Sonos through Chromecast and the TV.

![image](https://github.com/music-assistant/hass-music-assistant/assets/37292177/e83a61ad-4f22-408e-8e24-7a2847cbdb69)

![image](https://github.com/music-assistant/hass-music-assistant/assets/37292177/dc6ce55b-7ff6-49ec-9ab9-624666e16e46)

**Comment by OzGav** [comment]
OK so it appears this is a Sonos issue. What type of speaker is it? Is there anything unusual about the network situation with the Sonos speakers compared to the TV?

**Comment by Dekadinious** [comment]
It is a Sonos PLAY:1 and I can't way that there is anything different with the network setup. I have a Deco Wifi Mesh, but all these units are connected to the same endpoint.

I made an automation on b85 or b86 and that has worked flawlessly until the upgrade that broke the "Advanced" menu and made HA freeze. I am not sure exactly what version because I have auto update enabled. But I made a button for my kid to play his favorite songs, and that automation was very heavily used and worked every single time until that update.

So I am not really sure where to look to debug this.

**Comment by Dekadinious** [comment]
Great, appreciated!

**Comment by marcelveldt** [comment]
Bug identified - I'll fix it for beta90
Only happens to fresh setups

**Comment by marcelveldt** [comment]
Beta 90 has been pushed with a fix, can you please test. ?

**Comment by Dekadinious** [comment]
I can confirm that this is working now :)

Thanks for the extremely fast response and fix. Unheard of!
