### ISSUE TITLE
Airplay player provider doesn't work (slimproto missing)

### ISSUE THREAD

**Issue by formatBCE** [music-assistant/hass-music-assistant#1865]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

Airplay provider doesn't work after latest update. It got disabled, and when I try to enable it I'm getting described error.
![Screenshot_20240202_054817_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/10116550/bd1af6d6-acb0-4adf-ae6e-3bd84a27a8d9)

### How to reproduce

Try to add Airplay player provider.

### Relevant log output

2024-02-02 05:47:17.442 ERROR (MainThread) [music_assistant.webserver] [281472699254992] Error handling message: CommandMessage(message_id=17, command='config/providers/save', args={'provider_domain': 'airplay', 'values': {'log_level': 'GLOBAL', 'enabled': True, 'name': 'Airplay'}, 'instance_id': 'airplay'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 373, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 264, in save_provider_config
    config = await self._update_provider_config(instance_id, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 693, in _update_provider_config
    await self._load_provider_config(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 777, in _load_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 410, in load_provider
    raise SetupFailedError(
music_assistant.common.models.errors.SetupFailedError: Provider airplay depends on slimproto which is not available.

### What version of Home Assistant Core are your running

2024.1.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Have you tried restarting MA? If that doesn’t work try restarting HA and if that doesn’t work restart the host

**Comment by formatBCE** [comment]
> Have you tried restarting MA? If that doesn’t work try restarting HA and if that doesn’t work restart the host 

Did all the stuff. I'm former admin, so reboot is first.

Today there was update to add-on, but it didn't help.

**Comment by OzGav** [comment]
You are the only person reporting this so please think about what might be unusual about your install

**Comment by formatBCE** [comment]
> You are the only person reporting this so please think about what might be unusual about your install 

It was working for 6 months before updating add-on. Right after add-on update it stopped working. During 2-3 last months the only things I changed in my setup was installing updates.

**Comment by OzGav** [comment]
If it’s not too inconvenient I would remove the addon and reinstall and see what happens then

**Comment by formatBCE** [comment]
> If it’s not too inconvenient I would remove the addon and reinstall and see what happens then

I actually just did it, and yeah, it fixed the problem. Will have to setup things again, but at least it works. Thank you!
