### ISSUE TITLE
mass.play_media radio mode doesn't work

### ISSUE THREAD

**Issue by lor74** [music-assistant/hass-music-assistant#1866]
### What version of Music Assistant has the issue?

2.0.0b90 

### The problem

Cann'ot start playlist in radio mode from mass.play_media.

### How to reproduce

```
          service: mass.play_media
          target:
            device_id: e325948e0c54ba0b8ea12bbc6d11b162
          data:
            media_type: playlist
            media_id: "The White Buffalo"
            radio_mode: "on"
            enqueue: replace
```

### Relevant log output

```
2024-02-03 08:25:12.165 ERROR (MainThread) [music_assistant.webserver] [547324730576] Error handling message: CommandMessage(message_id='c7a6e77dab334b4f8b776bac03c28a97', command='players/queue/play_media', args={'queue_id': 'aa:aa:fb:39:1a:2c', 'media': ['qobuz://playlist/14382953'], 'option': 'replace', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 373, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 357, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 1021, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 591, in dynamic_tracks
    return await self._get_dynamic_tracks(ref_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/playlists.py", line 380, in _get_dynamic_tracks
    raise UnsupportedFeaturedException(
music_assistant.common.models.errors.UnsupportedFeaturedException: No Music Provider found that supports requesting similar tracks.
```

### Additional information

I have both spotify and quobuz provider enabled.
If I disable quobuz provider it works. So i guess radio mode is not supported from quobuz and quobuz is the first provider used to get the playlist.

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
I believe the problem here is you are trying to pass a playlist to the provider which isn't supported. You have to use an artist, album or track.

**Comment by lor74** [comment]
If ia change as you suggested.... and enable only quobux provider I still got the error. Please tell me If I have open a new Issue... or If you ca re-open this.

REQUEST:
```
service: mass.play_media
target:
  device_id: e325948e0c54ba0b8ea12bbc6d11b162
data:
  media_type: artist
  media_id: The White Buffalo
  radio_mode: "on"
  enqueue: replace
```


LOG:
```
2024-02-15 07:15:11.762 ERROR (MainThread) [music_assistant.providers.radiobrowser] Error occurred while communicating with the Radio Browser API
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/radios/radio_browser.py", line 90, in _request
    response = await self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 693, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('https://at1.api.radio-browser.info/json/stats')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/radiobrowser/__init__.py", line 84, in handle_setup
    await self.radios.stats()
  File "/usr/local/lib/python3.11/site-packages/radios/radio_browser.py", line 123, in stats
    response = await self._request("stats")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/radios/radio_browser.py", line 112, in _request
    raise RadioBrowserConnectionError(msg) from exception
radios.exceptions.RadioBrowserConnectionError: Error occurred while communicating with the Radio Browser API
2024-02-15 07:43:41.293 ERROR (MainThread) [music_assistant.webserver] [546899325520] Error handling message: CommandMessage(message_id='dc895d58335b4f3e800aeab2f091948d', command='players/queue/play_media', args={'queue_id': 'aa:aa:fb:39:1a:2c', 'media': ['library://artist/57'], 'option': 'replace', 'radio_mode': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 355, in play_media
    tracks = await self._get_radio_tracks(queue_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 1026, in _get_radio_tracks
    tracks += await ctrl.dynamic_tracks(radio_item.item_id, radio_item.provider)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 595, in dynamic_tracks
    return await self._get_dynamic_tracks(ref_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 424, in _get_dynamic_tracks
    raise UnsupportedFeaturedException(msg)
music_assistant.common.models.errors.UnsupportedFeaturedException: No Music Provider found that supports requesting similar tracks.
2024-02-15 07:43:52.198 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1127' coro=<analyze_audio() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py:175> exception=AttributeError("'NoneType' object has no attribute 'get_audio_stream'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 222, in analyze_audio
    await writer_task
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/audio.py", line 211, in writer
    async for audio_chunk in music_prov.get_audio_stream(streamdetails):
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_audio_stream'
```

**Comment by OzGav** [comment]
Can you go through the UI, right click on a track and see if you can see START RADIO. If you can, select it and see if the queue is populated with tracks. Either way please report back.

**Comment by OzGav** [comment]
OK I expect that you won't see that option as Qobuz does not support radio mode. Thus what you are seeing is expected behaviour. You can't use a playlist as the media_id and the provider has to support the option

**Comment by lor74** [comment]
Ok in this case can you manage this? There is the possibility to “force” a provider instead disabling quobuz (the actual workaround).

**Comment by OzGav** [comment]
Ok please explain what the problem is. How many music providers are you using and which ones? If you disable qobuz what happens then?

**Comment by lor74** [comment]
Thanks. 
I am using 2 providers 

- Spotify
- Quobuz

Using mass.play_media with radio mode enabled in a script that change every 30 minutes the playlist 

```
service: mass.play_media
target:
  device_id: e325948e0c54ba0b8ea12bbc6d11b162
data:
  media_type: artist
  media_id: The White Buffalo
  radio_mode: "on"
  enqueue: replace
```
or

```
service: mass.play_media
target:
  device_id: e325948e0c54ba0b8ea12bbc6d11b162
data:
  media_type: playlist
  media_id: The White Buffalo
  radio_mode: "on"
  enqueue: replace

```

sometimes it fails, no queue and no music playing.
Using radio_mode I have also noticed that all the tracks are from spotify (OGG format).
If I disable quobuz I have no issue.

If I disable spotify and use just quobuz the script (and in general mass.play_media with radio_mode on) doesn't work.

It's possible to impement a "quobuz skip" if radio_mode is enabled?

Thanks again for you time.

**Comment by lor74** [comment]
Ok thanks.
