### ISSUE TITLE
v1.1.15 - Turning OFF Volume Normalization prevents playback

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#187]
I have an error if I turn OFF Volume Normalization from the queue and then add/play music. The song won't play and I get the following 2 x log errors. Turning Volume Normalization back ON will fix the issue.

Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405
First occurred: 7:54:14 PM (31 occurrences)
Last logged: 8:21:54 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py", line 145, in serve_queue_stream
    start_streamdetails = await queue.queue_stream_prepare()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 732, in queue_stream_prepare
    return await get_stream_details(self.mass, next_item, self.queue_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 242, in get_stream_details
    loudness, gain_correct = await get_gain_correct(
TypeError: cannot unpack non-iterable int object
Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:388
Integration: Google Cast (documentation, issues)
First occurred: 7:59:22 PM (27 occurrences)
Last logged: 8:21:54 PM

Failed to cast media http://192.168.1.74:8095/media_player.shield.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

**Comment by marcelveldt** [comment]
this should be fixed with 1.1.7

**Comment by vk2him** [comment]
Confirmed fixed - playback is faster with normalization off so thats a bonus - thanks

**Comment by marcelveldt** [comment]
That shouldn't be noticeable because volume normalization barely causes any overhead and is lossless.
