### ISSUE TITLE
Cannot browse to Plex albums or tracks, library sync completes with errors

### ISSUE THREAD

**Issue by vhsdream** [music-assistant/hass-music-assistant#1882]
### What version of Music Assistant has the issue?

2.0.0b92

### The problem

After adding Plex as a provider it begins to sync but in the log completes 'with errors'. On the main page of the Integration only Artists appear. Via browsing  I cannot browse to albums or tracks. There are errors in the logs about these. Browsing to Artists and Playlists works as expected. These errors prevent me being able to browse an artist's albums or tracks on their page.

### How to reproduce

Add Plex as provider
Wait for sync.
Check logs, see error regarding sync
Attempt to browse to Albums, or Tracks
Check logs, see errors regarding browse

### Relevant log output

Sync error:

> 2024-02-07 12:18:26.183 WARNING (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 572, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 367, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 583, in get_library_albums
    yield await self._parse_album(album)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 376, in _parse_album
    self._get_item_mapping(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 261, in _get_item_mapping
    return ItemMapping(
           ^^^^^^^^^^^^
  File "<string>", line 12, in __init__
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 215, in __post_init__
    self.sort_name = create_sort_name(self.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/helpers/util.py", line 51, in create_sort_name
    input_str = input_str.lower().strip()
                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

Browse error:

> 2024-02-07 12:22:47.956 ERROR (MainThread) [music_assistant.webserver] [139938156119056] Error handling message: CommandMessage(message_id=33, command='music/browse', args={'path': 'plex--9CtYeCnh://albums'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 363, in _run_handler
    async for item in result:
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 282, in browse
    async for item in prov.browse(path):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 286, in browse
    async for album in self.get_library_albums():
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 583, in get_library_albums
    yield await self._parse_album(album)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 376, in _parse_album
    self._get_item_mapping(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/plex/__init__.py", line 261, in _get_item_mapping
    return ItemMapping(
           ^^^^^^^^^^^^
  File "<string>", line 12, in __init__
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 215, in __post_init__
    self.sort_name = create_sort_name(self.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/helpers/util.py", line 51, in create_sort_name
    input_str = input_str.lower().strip()
                ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

### Additional information

Screenshot of an artist page:
![image](https://github.com/music-assistant/hass-music-assistant/assets/67816022/24312c66-dd02-43e1-98ba-670359ab822b)

### What version of Home Assistant Core are your running

2024.1.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Home Assistant OS virtualized in Proxmox VE

**Comment by HomeAssistantNewbie** [comment]
+1 on this one, still ocurring on current version

2024-03-27 16:52:23.347 INFO (MainThread) [music_assistant] Loaded music provider Plex Media Server Library
2024-03-27 16:52:25.234 WARNING (MainThread) [music_assistant.music] Sync task for Plex Media Server Library completed with errors
2024-03-27 16:52:25.658 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 107, in scan_artist_metadata
    await self.mass.music.artists.get(artist.item_id, artist.provider, lazy=False)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 210, in get
    await add_task
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 71, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 239, in get_artist_mbid
    ref_albums = await self.mass.music.artists.albums(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 200, in albums
    return await self.get_provider_artist_albums(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 321, in get_provider_artist_albums
    items = await prov.get_artist_albums(item_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/plex/__init__.py", line 732, in get_artist_albums
    albums.append(await self._parse_album(album_obj))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/plex/__init__.py", line 429, in _parse_album
    self._get_item_mapping(
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/plex/__init__.py", line 315, in _get_item_mapping
    return ItemMapping(
           ^^^^^^^^^^^^
  File "<string>", line 12, in __init__
  File "/usr/local/lib/python3.12/site-packages/music_assistant/common/models/media_items.py", line 236, in __post_init__
    self.sort_name = create_sort_name(self.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/common/helpers/util.py", line 51, in create_sort_name
    input_str = input_str.lower().strip()

**Comment by marcelveldt** [comment]
Looks like its receiving artists with no name (None/null) - if you have a look at your plex library, anything that stands out that might cause it ?

We'll add a few more guards in the code for this to happen but just that you know that is crashing because it received unexpected data.

**Comment by vhsdream** [comment]
> Looks like its receiving artists with no name (None/null) - if you have a look at your plex library, anything that stands out that might cause it ?
> 
> We'll add a few more guards in the code for this to happen but just that you know that is crashing because it received unexpected data.

Turns out this was the case. 2 out of nearly 1000 artists. @marcelveldt thank you so much! Turns out I am not as adept at reading Python errors as I thought.
