### ISSUE TITLE
mass.play_media fails completely when one of the (Spotify) playlists causes an error

### ISSUE THREAD

**Issue by DutchJaFO** [music-assistant/hass-music-assistant#1889]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

I'm a calendar trigger to start this script every day :
'alias: Start muziek (week)
sequence:
  - service: script.set_standard_volume
    data: {}
  - service: mass.play_media
    target:
      entity_id: media_player.hobbyruimte
    data:
      enqueue: replace
      media_id:
        - Bad girls & boys
        - Rockabilly Mania
        - 'SKÁLD: the complete playlist'
        - This is Bush
        - This is AC/DC
        - This is Iron Maiden
        - This is Moloko
      media_type: playlist
mode: single
icon: mdi:file-music'

Today the script failed to play music at all.
The timeline-trace showed this :
![image](https://github.com/music-assistant/hass-music-assistant/assets/39138434/5109aff5-8e68-45c0-9c7b-d72fc4650219)

Entering the reported link 'spotify://playlist/37i9dQZF1DZ06evO3KIUZW' into my browser showed it was the "This is Iron Maiden" playlist that had caused an error. The music assistant log appears to have additional detail.

Starting the script again did not reproduce the error.

### How to reproduce

The 'script.set_standard_volume' uses mediaplayer calls to set volume and enable shuffle.

This may not be easy to reproduce, because usually the script works perfectly.

### Relevant log output

2024-02-09 06:00:16.891 ERROR (MainThread) [music_assistant.providers.spotify] playlists/37i9dQZF1DZ06evO49hLQA/tracks - {'error': {'status': 502, 'message': 'Bad gateway.'}}
2024-02-09 06:00:16.967 ERROR (MainThread) [music_assistant.providers.spotify] playlists/37i9dQZF1DZ06evO3KIUZW - {'error': {'status': 502, 'message': 'Error while loading resource'}}
2024-02-09 06:00:16.968 ERROR (MainThread) [music_assistant.webserver] [139824425099152] Error handling message: CommandMessage(message_id='fcfea6cfd2094b1a97add5e830205874', command='players/queue/play_media', args={'queue_id': 'RINCON_949F3EF61A0801400', 'media': ['library://playlist/190', 'library://playlist/187', 'spotify://playlist/5qPtR75ufTvUKTB6Nbz0Rv', 'library://playlist/142', 'library://playlist/140', 'spotify://playlist/37i9dQZF1DZ06evO3KIUZW', 'library://playlist/141'], 'option': 'replace', 'radio_mode': None})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 289, in play_media
    media_item = await self.mass.music.get_item_by_uri(item)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 310, in get_item_by_uri
    return await self.get_item(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 334, in get_item
    return await ctrl.get(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 188, in get
    details = await self.get_provider_item(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 455, in get_provider_item
    raise MediaNotFoundError(
music_assistant.common.models.errors.MediaNotFoundError: playlist://37i9dQZF1DZ06evO3KIUZW not found on provider spotify

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 373, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 292, in play_media
    raise MediaNotFoundError(f"Invalid uri: {item}") from err
music_assistant.common.models.errors.MediaNotFoundError: Invalid uri: spotify://playlist/37i9dQZF1DZ06evO3KIUZW

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Seems like an upstream problem. If Spotify doesn’t return a valid result then there is not much MA can do?

**Comment by OzGav** [comment]
Fair point. This will get looked at in due course.

**Comment by marcelveldt** [comment]
fixed in b144

**Comment by OzGav** [comment]
@DutchJaFO can you please confirm this has been fixed

**Comment by OzGav** [comment]
We are tidying up so I will close this but we will reopen if you still have a problem.

**Comment by Whaxion** [comment]
Hello,

I've the same issue. I can't play any playlist created by Spotify via Music Assistant.
I'm using the version 2.3.4 and I'm trying with playlists like:
* https://open.spotify.com/playlist/37i9dQZF1E4s96jJgqDgvl
* https://open.spotify.com/playlist/37i9dQZF1EIVmkna7DTk3K
* https://open.spotify.com/playlist/37i9dQZF1DZ06evO4rvWRa

I have this error in the logs
```
2024-12-22 19:52:10.419 WARNING (MainThread) [music_assistant.player_queues] Skipping https://open.spotify.com/playlist/37i9dQZF1E4s96jJgqDgvl: playlist://37i9dQZF1E4s96jJgqDgvl not found on provider spotify
2024-12-22 19:52:10.419 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: No playable items found
```

When I try to do a search on the web UI, I don't get any result and get this error:
```
2024-12-22 20:07:40.997 WARNING (MainThread) [music_assistant.music] playlist://37i9dQZF1E4s96jJgqDgvl not found on provider spotify
```
But when I try another playlist (that is not created by Spotify), it show me a result in the search.

It seems Spotify doesn't answer the same way for its playlists but I don't know what changes...

Is there any workaround to make Spotify created playlist works ?

Thanks!
