### ISSUE TITLE
YT Music not playing a song on google cast

### ISSUE THREAD

**Issue by Wizzard72** [music-assistant/hass-music-assistant#1897]
### What version of Music Assistant has the issue?

2.0.0b92

### The problem

The interface is loading. There are error messages in the log. When I click a song title and select play now on a google cast device nothing happens. Changing the volume works.

### How to reproduce

Start Music Assistant
Select a song
Press play song on a device
Device is silent. Also in Google Home I see that casting is enabled, but no song title is showed and no song is played.

### Relevant log output

2024-02-13 09:54:07.127 INFO (MainThread) [music_assistant] Starting Music Assistant Server (4c19766651724733959c800609e0ddf1) version 2.0.0b92 - uvloop: False
2024-02-13 09:54:07.145 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-02-13 09:54:07.184 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-02-13 09:54:07.313 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-02-13 09:54:07.738 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
2024-02-13 09:54:07.739 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.17.250:8096
2024-02-13 09:54:08.599 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-02-13 09:54:08.601 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-02-13 09:54:08.602 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-02-13 09:54:08.603 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-02-13 09:54:08.603 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-02-13 09:54:08.604 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-02-13 09:54:08.605 INFO (MainThread) [music_assistant] Loaded music provider URL
2024-02-13 09:54:08.850 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-02-13 09:54:08.870 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-02-13 09:54:08.872 INFO (MainThread) [music_assistant.providers.slimproto] Started SLIMProto server on port 3483
2024-02-13 09:54:08.873 INFO (MainThread) [music_assistant.providers.slimproto.cli] Registering jsonrpc endpoints on the webserver
2024-02-13 09:54:08.883 INFO (MainThread) [music_assistant.providers.slimproto.cli] Starting (telnet) CLI on port 9090
2024-02-13 09:54:08.925 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2024-02-13 09:54:09.143 INFO (MainThread) [music_assistant.players] Player registered: uuid:7ea2be91-3ca7-1cb7-0080-0006789970f6/Marantz SR6015
2024-02-13 09:54:09.154 INFO (MainThread) [music_assistant.players] Player registered: 54b27aa2-97bf-a902-cce1-1be27f8695d5/Huiskamer
2024-02-13 09:54:09.613 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-02-13 09:54:09.736 INFO (MainThread) [music_assistant.players] Player registered: aa:aa:c9:d7:33:0e/Marantz SR6015
2024-02-13 09:54:09.894 INFO (MainThread) [music_assistant.players] Player registered: 0095e83b-e914-31ea-a888-31f4e6a683cc/Slaapkamer Paul
2024-02-13 09:54:10.021 INFO (MainThread) [music_assistant.players] Player registered: fdd9dc48-6ef6-f0a6-4d71-2e38c1b4fc7a/Slaapkamer Sarah
2024-02-13 09:54:10.162 INFO (MainThread) [music_assistant.players] Player registered: cf9a891b-48a6-7f6e-2482-4bdb806bffd2/Shield Paul
2024-02-13 09:54:10.190 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
2024-02-13 09:54:17.770 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
2024-02-13 09:54:41.127 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-257' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:123> exception=KeyError('streamingData')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 168, in add_item_to_library
    await self._match(library_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 334, in _match
    prov_track = await self.get_provider_item(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 439, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 268, in get_item
    return await self.get_track(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 315, in get_track
    if track_obj := await get_track(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 93, in get_track
    return await asyncio.to_thread(_get_song)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 90, in _get_song
    track["streamingData"] = track_obj["streamingData"]
                             ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'
2024-02-13 09:57:15.055 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-307' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:123> exception=KeyError('streamingData')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 168, in add_item_to_library
    await self._match(library_item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 334, in _match
    prov_track = await self.get_provider_item(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 439, in get_provider_item
    if item := await provider.get_item(self.media_type, item_id):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 268, in get_item
    return await self.get_track(prov_item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/__init__.py", line 315, in get_track
    if track_obj := await get_track(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 93, in get_track
    return await asyncio.to_thread(_get_song)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/ytmusic/helpers.py", line 90, in _get_song
    track["streamingData"] = track_obj["streamingData"]
                             ~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'

### Additional information

_No response_

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You don’t say whether this ever worked. Are you a new user? What does work? What have you tried to identify the problem such as trying other player providers or other music providers. Have you been through the troubleshooting FAQ?

**Comment by Wizzard72** [comment]
Is has worked before, but that was a couple beta's ago. I saw a YT music issue before and thought it was the same problem, so didn't raise a bug issue.

I use MA from version 1 and now I'm on beta since the beginning.

I only have YT music and no other music provider.

From the fui everything works. I see album art, can open window with more info about the song. Can select the cast devices, can change the volume. When I select play a song the gui shows it's playing.

Errors are raised in the logfile

**Comment by Wizzard72** [comment]
Did a little investigation. It works with my Marantz and shield players, but not with Google Nest Mini and Google Nest Audio
