### ISSUE TITLE
Issue adding Jellyfin as provider (2.0.0b93)

### ISSUE THREAD

**Issue by usbrit** [music-assistant/hass-music-assistant#1900]
### What version of Music Assistant has the issue?

2.0.0b93

### The problem

Trying to add a Jellyfin server I get error:
"List index out of range"

### How to reproduce

Update to 2.0.0b93, attempt to add jellyfin sever at Tailscale IP in range 100.93.XXX.XXX (normal 192.XXX.XXX.XXX IP works)

### What version of Home Assistant Core are your running

2024.1.6

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Please add a snippet of the error that is logged in the music assistant server log

**Comment by OzGav** [comment]
We will close this soon due to no follow up

**Comment by usbrit** [comment]
Log entry:
2024-02-16 12:56:01.031 INFO (ThreadPoolExecutor-0_15) [JELLYFIN.jellyfin_apiclient_python.api] Sending get request to system/info/public
2024-02-16 12:56:06.040 ERROR (ThreadPoolExecutor-0_15) [JELLYFIN.jellyfin_apiclient_python.connection_manager] connect_to_address http://100.93.201.55:8096/ failed
2024-02-16 12:56:06.040 INFO (ThreadPoolExecutor-0_15) [JELLYFIN.jellyfin_apiclient_python.api] Trying to login to http://100.93.201.55:8096//Users/AuthenticateByName as homeassistant
2024-02-16 12:56:06.040 INFO (ThreadPoolExecutor-0_15) [JELLYFIN.jellyfin_apiclient_python.api] Sending post request to Users/AuthenticateByName
2024-02-16 12:56:11.046 ERROR (ThreadPoolExecutor-0_15) [JELLYFIN.jellyfin_apiclient_python.api] HTTPConnectionPool(host='100.93.201.55', port=8096): Max retries exceeded with url: //Users/AuthenticateByName (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3c624bb2d0>, 'Connection to 100.93.201.55 timed out. (connect timeout=5)'))
2024-02-16 12:56:11.046 INFO (ThreadPoolExecutor-0_15) [JELLYFIN.jellyfin_apiclient_python.connection_manager] Failed to login as `homeassistant`
2024-02-16 12:56:11.046 INFO (ThreadPoolExecutor-0_15) [JELLYFIN.jellyfin_apiclient_python.credentials] {}
2024-02-16 12:56:11.047 ERROR (MainThread) [music_assistant.webserver] [139897324275856] Error handling message: CommandMessage(message_id=122, command='config/providers/save', args={'provider_domain': 'jellyfin', 'values': {'url': 'http://100.93.201.55:8096/', 'username': 'homeassistant', 'password': 'XXXXXXXXX', 'log_level': 'GLOBAL'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 261, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 777, in _add_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 427, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/jellyfin/__init__.py", line 117, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/jellyfin/__init__.py", line 197, in handle_setup
    self._jellyfin_server = await self._run_async(connect)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/jellyfin/__init__.py", line 226, in _run_async
    return await self.mass.create_task(call, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/jellyfin/__init__.py", line 188, in connect
    server = credentials["Servers"][0]
             ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

![Add Tailscale IP error](https://github.com/music-assistant/hass-music-assistant/assets/53425475/2b0f7f70-b597-4bec-95d7-11d1d33f0cd7)

**Comment by OzGav** [comment]
@lokiberra

**Comment by lokiberra** [comment]
@usbrit 'homeassistant' is a user on your jellyfin server?

**Comment by usbrit** [comment]
Yes, independent user and password (password blanked with X's)

**Comment by OzGav** [comment]
This might be a networking problem at your end in which case we won’t be able to assist.

**Comment by OzGav** [comment]
We will close this soon unless you can confirm this is not a tail scale issue.

**Comment by usbrit** [comment]
I'm sorry I didn't realise you were wanting a reply.

Tailscale works fine to access the same machine from browser to Jellyfin (I
use the Tailscale networks for internal and external access) so I don't
believe it is an issue.

Is it possible that the current media assistant code does not accept 100.
style IP's?

**Comment by lokiberra** [comment]
Theoretically I don't think it should matter if it has a tailscale IP address. My best guess is that the docker networks make it unusable with tailscale. I tried setting up Jellyfin and Music Assistant in two docker containers with Tailscale clients in both and I couldn't get them to even ping each other. There might be a way to do this but it is beyond my current networking knowledge. Music Assistant doesn't seem able to connect to your IP at all. Is Home Assistant able to connect to your tailscale IP using the Jellyfin component?

**Comment by OzGav** [comment]
We will close this soon due to no followup
