### ISSUE TITLE
Cant add HASS-Musicplayer on b94

### ISSUE THREAD

**Issue by dwyschka** [music-assistant/hass-music-assistant#1907]
### What version of Music Assistant has the issue?

2.0.0b94

### The problem

If i want to add the HASS-Addon-Provider, there is no Authtication Input like in b93. If i try to save, i got an alert with 'url'.

### How to reproduce

![image](https://github.com/music-assistant/hass-music-assistant/assets/25348338/c647089a-a8e4-4af5-a422-1187f887053b)
![image](https://github.com/music-assistant/hass-music-assistant/assets/25348338/2d17ff83-7778-4afd-bdc0-81d1a4960328)

There is no input

### Relevant log output
```
2024-02-15 13:06:02.011 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
2024-02-15 13:07:09.065 ERROR (MainThread) [music_assistant.webserver] [281472423768592] Error handling message: CommandMessage(message_id=20, command='config/providers/save', args={'provider_domain': 'hass', 'values': {'log_level': 'GLOBAL'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 261, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 777, in _add_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 427, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/hass/__init__.py", line 49, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/hass/__init__.py", line 127, in handle_setup
    url = get_websocket_url(self.config.get_value(CONF_URL))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/config_entries.py", line 155, in get_value
    config_value = self.values[key]
                   ~~~~~~~~~~~^^^^^
KeyError: 'url'
2024-02-15 13:07:37.592 ERROR (MainThread) [music_assistant.webserver] [281472423768592] Error handling message: CommandMessage(message_id=26, command='config/providers/save', args={'provider_domain': 'hass', 'values': {'log_level': 'GLOBAL'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 261, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 777, in _add_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 427, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/hass/__init__.py", line 49, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/hass/__init__.py", line 127, in handle_setup
    url = get_websocket_url(self.config.get_value(CONF_URL))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/config_entries.py", line 155, in get_value
    config_value = self.values[key]
                   ~~~~~~~~~~~^^^^^
KeyError: 'url'
2024-02-15 13:08:34.704 ERROR (MainThread) [music_assistant.webserver] [281472424365200] Error handling message: CommandMessage(message_id=18, command='config/providers/save', args={'provider_domain': 'hass', 'values': {'log_level': 'GLOBAL'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 261, in save_provider_config
    config = await self._add_provider_config(provider_domain, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 777, in _add_provider_config
    await self.mass.load_provider(config)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 427, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/hass/__init__.py", line 49, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/hass/__init__.py", line 127, in handle_setup
    url = get_websocket_url(self.config.get_value(CONF_URL))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/config_entries.py", line 155, in get_value
    config_value = self.values[key]
                   ~~~~~~~~~~~^^^^^
KeyError: 'url'
```

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by Smarthome-Creator** [comment]
Same here.

**Comment by chrisghu** [comment]
same for me. I was able to add the instance of home assistant in b93 and it was working well. After upgrade to b94 the connection to home assistant has been lost with an red exclamation mark. I thought re-adding the connection might solve the problem but in b94 I cannot add any url in the webinterface now (which was possible in b93). I guess thats why the error happens --> no field to insert the URL in web interface, therefore no url-key after saving.

**Comment by Smarthome-Creator** [comment]
I could not add it to MA version 93 either. 
I use HA OS on a Pi and when I pasted the URL, the popup did not open at all in Safari, in Firefox and chromium based browsers (on macOS), the URL could not be reached after opening the popup.

**Comment by OzGav** [comment]
This will be fixed in b95

**Comment by UsbBitMinter** [comment]
any eta on b95? I cannot use MA at all right now. Thank you in advance!

**Comment by OzGav** [comment]
Soon? Sorry but it is a small team.

**Comment by chrisghu** [comment]
issue is solved. I have checked it with the current b97 release.

**Comment by collateral87** [comment]
Can anyone tell me, what i have to input in the url and token fields?
