### ISSUE TITLE
Cant start with latest 

### ISSUE THREAD

**Issue by bibitocarlos** [music-assistant/hass-music-assistant#1908]
### What version of Music Assistant has the issue?

2024.1.0

### The problem

My music assistant assistant cant start with latest, it used to work perfectly before .

### How to reproduce

Use latest version

### Relevant log output

2024-02-15 08:08:19.028 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/music_assistant/client/client.py", line 201, in fetch_initial_state
await self._players.fetch_state()
File "/usr/local/lib/python3.12/site-packages/music_assistant/client/players.py", line 288, in fetch_state
for player in await self.get_players():
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/music_assistant/client/players.py", line 65, in get_players
return [Player.from_dict(item) for item in await self.client.send_command("players/all")]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/music_assistant/client/client.py", line 168, in send_command
return await future
^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: players/all

### What version of Home Assistant Core are your running

2024.2.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by bibitocarlos** [comment]
Fixed, was linked to this issue :

https://github.com/music-assistant/hass-music-assistant/issues/1458
