### ISSUE TITLE
Airplay does not work

### ISSUE THREAD

**Issue by Smarthome-Creator** [music-assistant/hass-music-assistant#1920]
### What version of Music Assistant has the issue?

[2.0.0 BETA 97] - 18.02.2024

### The problem

With the latest update, Airplay no longer works.

### How to reproduce

Restart the add on and reboot HA.

### Relevant log output

`2024-02-18 16:40:45.882 INFO (MainThread) [music_assistant] Loaded music provider URL
2024-02-18 16:40:45.887 ERROR (MainThread) [music_assistant] Error loading provider(instance) Airplay
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 497, in load_provider
    await self.load_provider(prov_conf)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 427, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/airplay/__init__.py", line 122, in setup
    await prov.handle_setup()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/airplay/__init__.py", line 487, in handle_setup
    self._cliraop_bin = await self.get_cliraop_binary()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/airplay/__init__.py", line 923, in get_cliraop_binary
    raise RuntimeError(msg)
RuntimeError: Unable to locate RAOP Play binary for linux/aarch64`

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by spycle** [comment]
+1

**Comment by OzGav** [comment]
Try b99

**Comment by marcelveldt** [comment]
This should be fixed in beta 99. In beta 100 we have included some more enhancements for airplay even.

**Comment by Smarthome-Creator** [comment]
@marcelveldt, thanks for all the work, it's a great add-on.
