### ISSUE TITLE
"Add music provider" not available, no way to add any provider.

### ISSUE THREAD

**Issue by machielkreiken** [music-assistant/hass-music-assistant#1936]
### What version of Music Assistant has the issue?

2.0.0b102

### The problem

Ever since I installed the add-on I haven't been able to get it working.
I don't see any option to add a music provider in the settings panel. It's just blank.

<img width="1109" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/28918979/2db1cb52-7b2e-469b-b9f5-bc6b2166c840">

### How to reproduce

No clear way to reproduce.

### Relevant log output

`
2024-02-20 15:06:06.400 WARNING (MainThread) [music_assistant.music] DATABASE MIGRATION IN PROGRESS - THIS CAN TAKE A WHILE
2024-02-20 15:06:06.405 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=OperationalError('duplicate column name: external_ids')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 175, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 150, in start
    await self.music.setup(await self.config.get_core_config("music"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 111, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 682, in _setup_database
    await self.database.execute(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 154, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: duplicate column name: external_ids
`

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by machielkreiken** [comment]
Found similar issue https://github.com/music-assistant/hass-music-assistant/issues/1705
However no clear solution. I already reinstalled the addon.

I'll try to remove the repository too and completely reinstall from scratch and report back.

**Comment by machielkreiken** [comment]
Can confirm, reinstalling an old version through HACS fixes the issue.
