### ISSUE TITLE
MusicAssistant' object has no attribute 'aiobrowser'

### ISSUE THREAD

**Issue by dxh000130** [music-assistant/hass-music-assistant#1942]
### What version of Music Assistant has the issue?

2.0.0b103

### What version of the Home Assistant Integration have you got installed?

2014.1.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

2024-02-22 10:28:24.521 ERROR (MainThread) [music_assistant.webserver] [546471939024] Error handling message: CommandMessage(message_id=130, command='config/providers/save', args={'provider_domain': 'airplay', 'values': {'enabled': False}, 'instance_id': 'airplay'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 259, in save_provider_config
    config = await self._update_provider_config(instance_id, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/config.py", line 711, in _update_provider_config
    await self.mass.unload_provider(config.instance_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 455, in unload_provider
    self.aiobrowser.types.discard(mdns_type)
    ^^^^^^^^^^^^^^^
AttributeError: 'MusicAssistant' object has no attribute 'aiobrowser'

### How to reproduce

Disable airplar or change airplay name

### Music Providers

Spoitfy

### Player Providers

Airplay

### What version of Home Assistant Core are your running

2024.1.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Thanks. This is being looked at.

**Comment by marcelveldt** [comment]
his is fixed in the next release, only happens when you reload a provider.
