### ISSUE TITLE
Subsonic API doesn't show tracks with Nextcloud Music

### ISSUE THREAD

**Issue by Kimono8137** [music-assistant/hass-music-assistant#1949]
### What version of Music Assistant has the issue?

2.0.0b103

### What version of the Home Assistant Integration have you got installed?

2024.1.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Connect to Nextcloud Music using Subsonic and Music Assistant shows artists and a few albums but no tracks after multiple attempts to sync/reload.

### How to reproduce

1. Add Subsonic Media Server Library from Nextcloud with Legacy Auth
2. Library starts syncing and stops
3. Click to sync or reload

### Music Providers

Nextcloud Music

### Player Providers

N/A

### Relevant log output

File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/libopensonic/connection.py", line 2361, in getAlbumInfo2
    return AlbumInfo(dres['albumInfo'])
                     ~~~~^^^^^^^^^^^^^
KeyError: 'albumInfo'
2024-02-23 00:49:31.551 WARNING (zeroconf-ServiceBrowser-_googlecast._tcp-46) [pychromecast.dial] Failed to determine cast type for host <unknown> (<urlopen error _ssl.c:989: The handshake operation timed out>) (services:{ServiceInfo(type='host', data=('192.168.1.244', 8009)), ServiceInfo(type='mdns', data='C4A-3528753f74c8bff92b0403e631f149c4._googlecast._tcp.local.')})
2024-02-23 00:49:31.552 INFO (MainThread) [music_assistant.players] Player registered: 3528753f-74c8-bff9-2b04-03e631f149c4/Amplifier
2024-02-23 00:49:39.812 WARNING (ThreadPoolExecutor-0_13) [py.warnings] /usr/local/lib/python3.11/site-packages/libopensonic/media/media_base.py:65: UserWarning: Artist object returned by server is missing required field 'sortName'
  warn(f"{self.get_class_name()} object returned by server is missing required field '{key}'")

2024-02-23 03:47:59.349 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-02-23 03:48:01.185 WARNING (MainThread) [music_assistant.music] Sync task for Open Subsonic Media Server Library completed with errors
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 586, in run_sync
  |     await provider.sync_library(media_types)
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 392, in sync_library
  |     library_item = await controller.add_item_to_library(
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 134, in add_item_to_library
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 135, in add_item_to_library
    |     for track in await self._get_provider_album_tracks(item.item_id, item.provider):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 280, in _get_provider_album_tracks
    |     full_album = await self.get_provider_item(item_id, provider_instance_id_or_domain)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 442, in get_provider_item
    |     if item := await provider.get_item(self.media_type, item_id):
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 267, in get_item
    |     return await self.get_album(prov_item_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/opensubsonic/sonic_provider.py", line 519, in get_album
    |     sonic_info = await self._run_async(self._conn.getAlbumInfo2, aid=prov_album_id)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/opensubsonic/sonic_provider.py", line 398, in _run_async
    |     return await self.mass.create_task(call, *args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    |     return await loop.run_in_executor(None, func_call)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    |     result = self.fn(*self.args, **self.kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/libopensonic/connection.py", line 2361, in getAlbumInfo2
    |     return AlbumInfo(dres['albumInfo'])
    |                      ~~~~^^^^^^^^^^^^^
    | KeyError: 'albumInfo'
    +------------------------------------
2024-02-23 06:47:59.349 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-02-23 06:48:01.234 WARNING (MainThread) [music_assistant.music] Sync task for Open Subsonic Media Server Library completed with errors
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 586, in run_sync
  |     await provider.sync_library(media_types)
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 392, in sync_library
  |     library_item = await controller.add_item_to_library(
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 134, in add_item_to_library
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/local/lib/python3.11/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 135, in add_item_to_library
    |     for track in await self._get_provider_album_tracks(item.item_id, item.provider):
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/albums.py", line 280, in _get_provider_album_tracks
    |     full_album = await self.get_provider_item(item_id, provider_instance_id_or_domain)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 442, in get_provider_item
    |     if item := await provider.get_item(self.media_type, item_id):
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 267, in get_item
    |     return await self.get_album(prov_item_id)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/opensubsonic/sonic_provider.py", line 519, in get_album
    |     sonic_info = await self._run_async(self._conn.getAlbumInfo2, aid=prov_album_id)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/opensubsonic/sonic_provider.py", line 398, in _run_async
    |     return await self.mass.create_task(call, *args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    |     return await loop.run_in_executor(None, func_call)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    |     result = self.fn(*self.args, **self.kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/libopensonic/connection.py", line 2361, in getAlbumInfo2
    |     return AlbumInfo(dres['albumInfo'])
    |                      ~~~~^^^^^^^^^^^^^
    | KeyError: 'albumInfo'
    +------------------------------------

### Additional information

It appears the sync feature is timing out before syncing the complete collection. Everytime I hit sync or reload it adds a 1-2 ablums to the listings but no tracks.

### What version of Home Assistant Core are your running

2024.2.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@khers

**Comment by khers** [comment]
Please provide the logs for this. I do not have access to a Nextcloud server to test (is there a demo server up somewhere?).

**Comment by khers** [comment]
This is a problem with Nextcloud, according to the API documentation here: https://opensubsonic.netlify.app/docs/endpoints/getalbuminfo2/ the JSON object returned by getAlbumInfo2 must contain a field names 'albumInfo'. I don't know what it does contain, but you could find out using the linked library above.

**Comment by Kimono8137** [comment]
> getAlbumInfo2

I tried to using py-opensonic but I couldn't figure out writting an appropriate script. Here is a Nextcloud test server though:
 [https://nextcloudtest.crabdance.com/index.php/apps/music/subsonic](url) Username: admin Password: 8cxr4kkLW4b8

**Comment by Kimono8137** [comment]
There is a known bug with Nextcloud Music, [https://github.com/owncloud/music/issues/1123](url)

Closing this issue
