### ISSUE TITLE
DLNA Speaker, no state

### ISSUE THREAD

**Issue by milou161185** [music-assistant/hass-music-assistant#1979]
### What version of Music Assistant has the issue?

2.0.0b106

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Hello, I have a Xiaomi Mi Network Speaker that does not work correctly from Music Assistant (DLNA player). Music playback works, but I have no feedback (the title played is not displayed, nor the duration of the song or the progress in the song). My other players  type ChomeCast work correctly.

### How to reproduce

play a song or a playlist

### Music Providers

local -> don't work
spotify -> don't work

### Player Providers

DLNA -> don't work
ChromeCast -> OK

### Relevant log output

2024-03-06 10:07:00.606 ERROR (MainThread) [music_assistant.webserver] [140321818128912] Error handling message: CommandMessage(message_id=24, command='players/queue/play_media', args={'queue_id': 'uuid:c2b51011-6d4f-e8ce-c439-97654865ab21-MR', 'media': ['library://playlist/26']})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 377, in play_media
    await self.play_index(queue_id, 0)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 653, in play_index
    await self.mass.players.play_media(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 617, in play_media
    await player_prov.play_media(
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 167, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 393, in play_media
    await self.poll_player(dlna_player.udn)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 497, in poll_player
    await dlna_player.device.async_update(do_ping=do_ping)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 350, in async_update
    await self._async_poll_state_variables(
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/profile.py", line 469, in _async_poll_state_variables
    self._on_event(service, changed_state_variables)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 400, in _on_event
    self.on_event(service, state_variables)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 671, in _handle_event
    dlna_player = self.dlnaplayers[udn]
                  ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'uuid:c2b51011-6d4f-e8ce-c439-97654865ab21'
2024-03-06 10:07:45.742 WARNING (MainThread) [music_assistant.players] Error while requesting latest state from player Mi Speaker: 'uuid:c2b51011-6d4f-e8ce-c439-97654865ab21'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 868, in _poll_players
    await player_prov.poll_player(player_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 497, in poll_player
    await dlna_player.device.async_update(do_ping=do_ping)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 350, in async_update
    await self._async_poll_state_variables(
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/profile.py", line 469, in _async_poll_state_variables
    self._on_event(service, changed_state_variables)
  File "/usr/local/lib/python3.11/site-packages/async_upnp_client/profiles/dlna.py", line 400, in _on_event
    self.on_event(service, state_variables)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/dlna/__init__.py", line 671, in _handle_event
    dlna_player = self.dlnaplayers[udn]
                  ~~~~~~~~~~~~~~~~^^^^^
KeyError: 'uuid:c2b51011-6d4f-e8ce-c439-97654865ab21'

### Additional information

_No response_

### What version of Home Assistant Core are your running

2024.2.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Yeah it is the flakey DLNA protocol. This may not get looked at for a while as it is time consuming trying to patch all these different players. Then again the devs may see an easy fix. You will need to be patient with this one.

**Comment by milou161185** [comment]
ok, no problem. This speaker is Airplay compatible, but i can't see in the speaker list with airplay protocol active. Maybe it's an old version of this protocol?

**Comment by OzGav** [comment]
MA supports Airplay 1 so not sure why this would not be seen? Check the logs during MA startup when the players are discovered to see if any errors are thrown.

**Comment by milou161185** [comment]
a have the line in the log :
2024-03-06 16:41:03.605 INFO (MainThread) [music_assistant.players] Player registered: ap3cbd3e11102d/Mi Speaker

but no speaker in the list

**Comment by OzGav** [comment]
Ok please raise a separate issue for that as it relates to Airplay and not DLNA

**Comment by marcelveldt** [comment]
Is this still an issue with the recent beta (b124) ?

**Comment by milou161185** [comment]
Yes, next button work, but no state of the song playing

**Comment by marcelveldt** [comment]
What do you mean exactly with "no state" ? No state where ?
So music is playing but you are missing metadata somewhere ?

**Comment by milou161185** [comment]
when I say "no state", I mean that the sound comes out of the speaker, but the cursor indicating the duration of the song does not move, the play button does not work and neither does the power button.

**Comment by marcelveldt** [comment]
> when I say "no state", I mean that the sound comes out of the speaker, but the cursor indicating the duration of the song does not move, the play button does not work and neither does the power button.

Where? In what interface ? Can you make a screenshot ?

**Comment by milou161185** [comment]
![image](https://github.com/music-assistant/hass-music-assistant/assets/52327475/468acfb3-13d9-4e66-9c1c-a4e1848855f1)

here, when a song is playing, the title is displayed but the cursor don't move and the play button don't work

**Comment by OzGav** [comment]
@milou161185 Can you edit your initial post and remove the pasted log excerpt and ATTACH the entire logfile.

**Comment by OzGav** [comment]
@milou161185 please ATTACH the entire log file as requested above. If there is no further followup we will close this.

**Comment by OzGav** [comment]
Closing due to no followup
