### ISSUE TITLE
Squeezelite32 Player Name Not Recognized and Error 

### ISSUE THREAD

**Issue by rjgrandy** [music-assistant/hass-music-assistant#1995]
### What version of Music Assistant has the issue?

2.0.0b108

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Squeezelite32 player has trouble connecting. MA does not pull the player name and error is generated.

### How to reproduce

MA is started and Squeezelite32 tries to connect

### Music Providers

NA

### Player Providers

Slimproto

### Relevant log output

```
2024-03-12 19:24:18.483 INFO (MainThread) [music_assistant] Starting Music Assistant Server (74cf7b755c724197911e9cd719dc3b76) version 2.0.0b108 - uvloop: False
2024-03-12 19:24:18.490 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-03-12 19:24:18.500 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-03-12 19:24:18.544 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-03-12 19:24:18.639 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
2024-03-12 19:24:18.639 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.1.199:8096
2024-03-12 19:24:19.285 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-03-12 19:24:19.285 INFO (MainThread) [music_assistant] Loaded music provider URL
2024-03-12 19:24:19.285 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-03-12 19:24:19.285 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-03-12 19:24:19.285 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-03-12 19:24:19.285 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-03-12 19:24:19.286 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-03-12 19:24:19.286 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-03-12 19:24:19.346 WARNING (MainThread) [music_assistant.providers.tunein] Email address detected instead of username, it is advised to use the tunein username instead of email.
2024-03-12 19:24:19.346 INFO (MainThread) [music_assistant] Loaded music provider Tune-In Radio
2024-03-12 19:24:19.350 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-03-12 19:24:19.585 INFO (MainThread) [music_assistant.players] Player registered: 727ebdd9-3bb3-0fb6-84fb-d34352213ef9/Living Room Chromecast
2024-03-12 19:24:19.698 INFO (MainThread) [music_assistant.players] Player registered: 6c82a694-23d9-6468-a678-1cbd7a88a762/Garage Speaker
2024-03-12 19:24:19.725 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-03-12 19:24:20.375 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
2024-03-12 19:24:20.596 INFO (MainThread) [music_assistant.players] Player registered: ap8c4b14147508/ESP32-Master
2024-03-12 19:24:20.605 INFO (MainThread) [music_assistant.players] Player registered: apa0a3b38b3bb8/ESP-LR-Echo
2024-03-12 19:24:20.634 INFO (MainThread) [music_assistant.players] Player registered: ap1097bdd40964/ESP-Formal
2024-03-12 19:24:21.582 INFO (MainThread) [music_assistant.players] Player registered: uuid:84816532-a92b-11ec-90eb-e051fa60e5c7/Living Room TV
2024-03-12 19:24:21.645 INFO (MainThread) [music_assistant.players] Player registered: ap1097bdd41534/ESP-Patio
2024-03-12 19:24:21.663 INFO (MainThread) [music_assistant.players] Player registered: ap8c4b1415b99c/ESP-LR
2024-03-12 19:24:25.587 INFO (MainThread) [music_assistant.players] Player registered: ap8c4b14145c10/ESP-Kitchen
2024-03-12 19:24:25.617 INFO (MainThread) [music_assistant.players] Player registered: ap1097bdd4012c/ESP-Echo-AP
2024-03-12 19:24:31.286 INFO (MainThread) [aioslimproto.server] Starting SLIMProto server on port 3483
2024-03-12 19:24:31.286 INFO (MainThread) [aioslimproto.server.cli] Starting (legacy/telnet) SLIMProto CLI on port 9090
2024-03-12 19:24:31.287 INFO (MainThread) [aioslimproto.server.cli] Starting SLIMProto JSON RPC CLI on port 9000
2024-03-12 19:24:31.288 INFO (MainThread) [music_assistant] Loaded player provider Slimproto (Squeezebox players)
2024-03-12 19:24:31.505 INFO (MainThread) [music_assistant.providers.slimproto] Player squeezeplay: 4e:71:d4:1d:7e:9d connected
2024-03-12 19:24:31.506 INFO (MainThread) [music_assistant.players] Player registered: 4e:71:d4:1d:7e:9d/'Media_Room'
2024-03-12 19:24:31.585 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: 10:97:bd:d4:09:64 connected
2024-03-12 19:24:31.588 INFO (MainThread) [music_assistant.players] Player registered: 10:97:bd:d4:09:64/unknown device: 10:97:bd:d4:09:64
2024-03-12 19:24:31.591 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: 8c:4b:14:15:b9:9c connected
2024-03-12 19:24:31.594 INFO (MainThread) [music_assistant.players] Player registered: 8c:4b:14:15:b9:9c/unknown device: 8c:4b:14:15:b9:9c
2024-03-12 19:24:31.599 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: 8c:4b:14:14:5c:10 connected
2024-03-12 19:24:31.620 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: 10:97:bd:d4:15:34 connected
2024-03-12 19:24:31.620 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: 8c:4b:14:14:75:08 connected
2024-03-12 19:24:31.622 INFO (MainThread) [music_assistant.players] Player registered: 8c:4b:14:14:5c:10/unknown device: 8c:4b:14:14:5c:10
2024-03-12 19:24:31.627 INFO (MainThread) [music_assistant.players] Player registered: 10:97:bd:d4:15:34/unknown device: 10:97:bd:d4:15:34
2024-03-12 19:24:31.629 INFO (MainThread) [music_assistant.players] Player registered: 8c:4b:14:14:75:08/unknown device: 8c:4b:14:14:75:08
2024-03-12 19:24:31.676 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: 10:97:bd:d4:01:2c connected
2024-03-12 19:24:31.697 INFO (MainThread) [music_assistant.players] Player registered: 10:97:bd:d4:01:2c/unknown device: 10:97:bd:d4:01:2c
2024-03-12 19:24:34.232 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:24:34.234 INFO (MainThread) [music_assistant.players] Player registered: a0:a3:b3:8b:3b:b8/unknown device: a0:a3:b3:8b:3b:b8
2024-03-12 19:24:38.574 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-03-12 19:24:42.256 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:24:42.767 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
2024-03-12 19:24:50.280 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:24:58.313 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:25:06.350 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-445' coro=<SlimClient._socket_reader() done, defined at /usr/local/lib/python3.11/site-packages/aioslimproto/client.py:564> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 571, in _socket_reader
    data = await self._reader.read(64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 711, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 543, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 999, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-03-12 19:25:06.352 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-461' coro=<SlimClient._socket_reader() done, defined at /usr/local/lib/python3.11/site-packages/aioslimproto/client.py:564> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 571, in _socket_reader
    data = await self._reader.read(64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 711, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 543, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 999, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-03-12 19:25:06.350 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:25:14.374 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:25:22.398 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:25:30.451 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:25:38.484 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:25:46.520 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-503' coro=<SlimClient._socket_reader() done, defined at /usr/local/lib/python3.11/site-packages/aioslimproto/client.py:564> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 571, in _socket_reader
    data = await self._reader.read(64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 711, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 543, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 999, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-03-12 19:25:46.521 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-545' coro=<SlimClient._socket_reader() done, defined at /usr/local/lib/python3.11/site-packages/aioslimproto/client.py:564> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 571, in _socket_reader
    data = await self._reader.read(64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 711, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 543, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 999, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-03-12 19:25:46.521 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-571' coro=<SlimClient._socket_reader() done, defined at /usr/local/lib/python3.11/site-packages/aioslimproto/client.py:564> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioslimproto/client.py", line 571, in _socket_reader
    data = await self._reader.read(64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 711, in read
    await self._wait_for_data('read')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 543, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 999, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-03-12 19:25:46.520 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:25:54.562 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
2024-03-12 19:26:02.591 INFO (MainThread) [music_assistant.providers.slimproto] Player unknown device: a0:a3:b3:8b:3b:b8 connected
```

### What version of Home Assistant Core are your running

2024.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Like already responded on discord: This player is reconnecting over and over.
You either have 2 players with the same mac address somehow or this player has gone haywire.

I can handle the snowball effect of the reconnects in the handshake in the code but there is also some work to do on the player.

**Comment by OzGav** [comment]
OP fixed problem and reported on Discord https://discord.com/channels/753947050995089438/1098864184185331752/1217709624057135105
