### ISSUE TITLE
Universal Group Player plays media but not powered on

### ISSUE THREAD

**Issue by Alundran** [music-assistant/hass-music-assistant#1996]
### What version of Music Assistant has the issue?

2.0.0b106

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When playing media through a Universal Group Player after upgrading to 2.0.0b106, the media plays but the player group isn't powered on. This means that although music is playing, no artist/song information is displayed in the front-end of music assistant or displayed on the associated media_player entity. If you power on the group, nothing appears to happen. However, if you power on the group via the media_player entity, it does seem to then power on the group and associated song/artist info is shown.

### How to reproduce

1. Ensure all players are turned off
2. Create a Universal Group Player and add two slim proto players
3. Power on the Universal Group Player, notice that the devices are powered on but the group isn't
4. Play media on the Universal Group Player. Notice that music plays, but no song/artist info is shown
5. Check the players and see that the Universal Group Player is still powered off. Try powering it on again and refresh the page - it stays off.
6. Power on the group via the media_player entity, notice it now powers on and song/artist info is shown

### Music Providers

Spotify

### Player Providers

Universal Group Player, Slimproto

### Relevant log output

`2024-03-13 11:21:13.553 INFO (MainThread) [music_assistant] Starting Music Assistant Server (d04764398e1f48bba45fa6c07719f84e) version 2.0.0b108 - uvloop: False
2024-03-13 11:21:13.561 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-03-13 11:21:13.570 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.1.113:8095
2024-03-13 11:21:13.654 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-03-13 11:21:13.827 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
2024-03-13 11:21:13.827 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.1.113:8096
2024-03-13 11:21:14.528 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-55' coro=<ArtistsController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py:60> exception=InvalidFieldValue('provider_mappings', set[music_assistant.common.models.media_items.ProviderMapping], {'item_id': '500', 'provider_domain': 'library', 'provider_instance': 'library', 'available': True}, <class 'music_assistant.common.models.media_items.Artist'>)>
Traceback (most recent call last):
  File "<string>", line 39, in __mashumaro_from_dict__
  File "<string>", line 39, in <listcomp>
  File "<string>", line 31, in __mashumaro_from_dict__
ValueError: Argument for music_assistant.common.models.media_items.ProviderMapping.__mashumaro_from_dict__ method should be a dict instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/artists.py", line 68, in add_item_to_library
    item = Artist.from_item_mapping(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/common/models/media_items.py", line 285, in from_item_mapping
    return cls.from_dict(
           ^^^^^^^^^^^^^^
  File "<string>", line 41, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "provider_mappings" of type set[ProviderMapping] in Artist has invalid value {'item_id': '500', 'provider_domain': 'library', 'provider_instance': 'library', 'available': True}
2024-03-13 11:21:14.867 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-03-13 11:21:14.867 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-03-13 11:21:14.868 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-03-13 11:21:14.868 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-03-13 11:21:14.868 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-03-13 11:21:14.868 INFO (MainThread) [music_assistant] Loaded music provider URL
2024-03-13 11:21:14.871 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-03-13 11:21:14.871 INFO (MainThread) [aioslimproto.server] Starting SLIMProto server on port 3483
2024-03-13 11:21:14.872 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-03-13 11:21:14.925 INFO (MainThread) [music_assistant.players] Player registered: ugp_2/All House Player
2024-03-13 11:21:14.925 INFO (MainThread) [music_assistant.players] Player registered: ugp_n4eux9gq/Kitchen Visual Player
2024-03-13 11:21:14.931 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-03-13 11:21:14.987 INFO (MainThread) [aioslimproto.server.cli] Starting (legacy/telnet) SLIMProto CLI on port 9090
2024-03-13 11:21:15.037 INFO (MainThread) [aioslimproto.server.cli] Starting SLIMProto JSON RPC CLI on port 9000
2024-03-13 11:21:15.044 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2024-03-13 11:21:15.398 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-03-13 11:21:15.849 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as dezmond95
2024-03-13 11:21:15.849 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-03-13 11:21:16.068 INFO (MainThread) [music_assistant.players] Player registered: 73d21ff8-02fa-4ef0-ff18-667188d6d572/Del SHIELD
2024-03-13 11:21:16.511 INFO (MainThread) [music_assistant] Loaded music provider RadioBrowser
2024-03-13 11:21:17.219 INFO (MainThread) [music_assistant.providers.slimproto] Player squeezeplay: 02:42:ac:14:00:02 connected
2024-03-13 11:21:17.224 INFO (MainThread) [music_assistant.players] Player registered: 02:42:ac:14:00:02/2140bdf31e69
2024-03-13 11:21:17.264 INFO (MainThread) [music_assistant.providers.slimproto] Player squeezeplay: d8:3a:dd:39:05:a2 connected
2024-03-13 11:21:17.266 INFO (MainThread) [music_assistant.players] Player registered: d8:3a:dd:39:05:a2/squeezeplay: d8:3a:dd:39:05:a2
2024-03-13 11:21:17.283 INFO (MainThread) [music_assistant.providers.slimproto] Player squeezeplay: d8:3a:dd:70:ce:87 connected
2024-03-13 11:21:17.285 INFO (MainThread) [music_assistant.players] Player registered: d8:3a:dd:70:ce:87/squeezeplay: d8:3a:dd:70:ce:87
2024-03-13 11:21:23.008 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-03-13 11:21:23.009 INFO (MainThread) [music_assistant.music] Sync task for RadioBrowser completed`

### Additional information

This started occuring after upgrading to b106. 

### What version of Home Assistant Core are your running

2024.2.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please check if this is still an issue in b109

**Comment by Alundran** [comment]
Seems resolved for me on latest. Thanks!
