### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by vhillaire** [music-assistant/hass-music-assistant#2000]
### What version of Music Assistant has the issue?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

![screen-2024-03-14-15-01-52](https://github.com/music-assistant/hass-music-assistant/assets/3893881/b93bd769-eb53-44e7-8f45-fdabe0a65257)
After adding the MA repository from HACS then rebooting going to setting add integration this error pops up

### How to reproduce

Follow the instruction for installation

### Music Providers

Didn't get far enough

### Player Providers

Didn't get far enough

### Relevant log output

![screen-2024-03-14-15-01-52](https://github.com/music-assistant/hass-music-assistant/assets/3893881/d5027e62-ea30-4a70-b3f7-d94b054390b4)

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You have added the same picture in the logs section?

Has the server correctly installed?

**Comment by vhillaire** [comment]
2024-03-14 18:33:58.745 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 25, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 68, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 197, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 405, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 502, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/config_flow.py", line 310, in async_step_on_supervisor
    await install_repository(self.hass)
  File "/config/custom_components/mass/addon.py", line 27, in install_repository
    return await hassio.send_command(command, payload=payload, timeout=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 592, in send_command
    raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: Can't add https://github.com/music-assistant/home-assistant-addon, already in the store

**Comment by vhillaire** [comment]
No, it still won't install. Does it think it's already there?

**Comment by OzGav** [comment]
OK you need to be very specific when you say "it" wont install. What is "it"? Via HACS you are trying to install the INTEGRATION. I asked about the server which is the ADDON. So please look in HA settings and see if the ADDON is installed. If it isn't then look at the docs here https://music-assistant.io/installation/ and try the SECONDARY method. If that works then go back and try and install the Integration again.

**Comment by vhillaire** [comment]
Awesome thank you

**Comment by nimbling** [comment]
I'm getting the same error.

`homeassistant.components.hassio.handler.HassioAPIError: Can't add https://github.com/music-assistant/home-assistant-addon, already in the store`

suggests to me the integration tries to add the url to the add-on store while it's already there, and fails on it?

**Comment by OzGav** [comment]
Have you tried what is suggested two posts above?

**Comment by nimbling** [comment]
@OzGav Thanks for helping!
Yes, I can install the Addon just fine by itself.

When I try installing the integration this fails with an "unknown error" - likely because it tries to add the add-on repo to the add-on store without graciously failing if it's already there.

If I remove the add-on and it's url from the add-on store, and *then* install the integration, it fails as described above.

I have rebooted my pi5 after every step, hoping it would help, but it did not.

**Comment by nimbling** [comment]
Turns out I was two versions behind in HACS. After updating that, the integration + Addon installation worked!
