### ISSUE TITLE
Multiple Issues after last update 

### ISSUE THREAD

**Issue by fin05** [music-assistant/hass-music-assistant#2007]
### What version of Music Assistant has the issue?

2.0.0b109

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Problem 1. When a track ends the next track does not start 
Problem 2. If I fast forward a song the audio does not come back on - the time moves but it stays silent
Problem 3. Sometimes I start a track and and there's no sound until I adjust the volume to a different level

### How to reproduce

I have uninstalled the addon and reinstalled - rebooted HA several times 

### Music Providers

Plex and youtube music

### Player Providers

Airplay

### Relevant log output

  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/images.py", line 49, in _create_image
    img = Image.open(BytesIO(img_data))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f371687c180>
2024-03-15 16:09:55.657 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 379, in handle_imageproxy
    image_data = await self.get_thumbnail(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 360, in get_thumbnail
    thumbnail = await get_image_thumb(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/images.py", line 55, in get_image_thumb
    return await asyncio.to_thread(_create_image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/images.py", line 49, in _create_image
    img = Image.open(BytesIO(img_data))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f3716ed7f10>
2024-03-15 16:10:22.731 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 379, in handle_imageproxy
    image_data = await self.get_thumbnail(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 360, in get_thumbnail
    thumbnail = await get_image_thumb(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/images.py", line 55, in get_image_thumb
    return await asyncio.to_thread(_create_image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/images.py", line 49, in _create_image
    img = Image.open(BytesIO(img_data))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f3716f21ee0>
2024-03-15 16:10:34.221 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Main Area - crossfade: False
2024-03-15 16:16:06.561 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 379, in handle_imageproxy
    image_data = await self.get_thumbnail(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 360, in get_thumbnail
    thumbnail = await get_image_thumb(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/images.py", line 55, in get_image_thumb
    return await asyncio.to_thread(_create_image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/images.py", line 49, in _create_image
    img = Image.open(BytesIO(img_data))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f3716ed23e0>

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
As per the instructions in the issue template you haven’t provided any details about what does work. For example, you list Airplay as the player provider, do you have any other other player types and do they work ok?

**Comment by fin05** [comment]
I only use airplay - I just tried Chromecast and DLNA and same issues

**Comment by fin05** [comment]
I can start a track and it will play - once the track ends it does not go to the next track on the playlist - it doesn't matter if its from Plex or Youtube same issues.  The issue I listed are global no matter what provider or player I use

**Comment by OzGav** [comment]
If you created a backup then go back to b108 and confirm that the issue does not occur

**Comment by fin05** [comment]
Ok Ill try that then get back to you

**Comment by fin05** [comment]
Yes the issues are all resolved when I restored the back up

**Comment by OzGav** [comment]
Please try again when beta 111 is released

**Comment by niteguide** [comment]
I can say that the issues described above also appears under 2.0.0b111 with chromcast as well as with airplay. It takes a lot of time until I hear something even if the song appears to be playing within MA. When the song finally starts on the player it will also not start from the beginning but 10-30 seconds later. 
I am not completely new to HA but yet have to find out how to get relevant log files for these kind of issues. So maybe one has a hint for me how to do that an I will be happy to provide the data.

**Comment by OzGav** [comment]
Just supply the entire log file after downloading it from the settings and then drag and drop it here so it is added as an attachment.

**Comment by niteguide** [comment]
Okay, here you go. Hope this helps somehow. 
[d5369777_music_assistant_beta_2024-03-16T21-10-52.978Z.log](https://github.com/music-assistant/hass-music-assistant/files/14625282/d5369777_music_assistant_beta_2024-03-16T21-10-52.978Z.log)

**Comment by niteguide** [comment]
And here with debugging enabled. 
[home-assistant_mass_2024-03-16T21-20-13.296Z.log](https://github.com/music-assistant/hass-music-assistant/files/14625292/home-assistant_mass_2024-03-16T21-20-13.296Z.log)

**Comment by niteguide** [comment]
I have checked all the problems mentioned above with b116 installed (chromecast, airplay). Songs now immediately start from the beginning. When a track ends another starts. Also fast forward does work. In my opinion this case can be closed.

**Comment by OzGav** [comment]
I will close his then. Please open a new issue with the logs attached when the no sound problem occurs.
