### ISSUE TITLE
V1.1.11: Still some symbol related errors

### ISSUE THREAD

**Issue by AvdWerfhorst** [music-assistant/hass-music-assistant#201]
Unfortunately there are still some issues related to symbols. In this case the folder it logs is "/media/Music/Bassie". While the true name is "/media/Music/Bassie & Adriaan"

`Logger: aiohttp.server
Source: custom_components/mass/panel.py:91
Integration: Music Assistant ([documentation](https://github.com/music-assistant/hass-music-assistant), [issues](https://github.com/music-assistant/hass-music-assistant/issues))
First occurred: 8:58:09 AM (43 occurrences)
Last logged: 9:00:44 AM
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/config/custom_components/mass/panel.py", line 91, in get
    data = await mass.metadata.get_thumbnail(url, size=size)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/__init__.py", line 235, in get_thumbnail
    thumbnail = await create_thumbnail(self.mass, path, size)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/images.py", line 37, in create_thumbnail
    raise FileNotFoundError(f"Image not found: {path}")
FileNotFoundError: Image not found: /media/Music/Bassie`

**Comment by marcelveldt** [comment]
Childhood memories... "Bassie & Adriaan" :-)

Strange, I did test explicitly with the ampersand in the album name.
The frontend quests a thumbnail from the backend using the image proxy. 

Just to confirm can you force refresh your browser ? (most browsers is shift + F5) 
That will make sure you're actually using the latest version of the frontend.

On my side I will do some more tests.

**Comment by AvdWerfhorst** [comment]
If you ever introduce a feature to generate a random playlist, I will request a feature to exclude things like "Bassie & Adriaan". Else I will get at the most unexpected moments "Hallo vriendjes" or even a whole audio adventure ;-P

I think you are right, there was still an old frontend version loaded. Force refresh, reload home assistant to start with a fresh log. And these messages are gone now.

**Comment by marcelveldt** [comment]
haha, "allemamaggies" (of hoe schrijf je dat) ;-)

And yes, I'm now focused on getting a stable baseline. After that there will be some great features such as smart playlists which indeed need some way to exclude specific content. 

Good to hear that the browser cache clear resolved the issue.
