### ISSUE TITLE
Music Assistant will not start after I upgrade from version 2.0.0b108 to any newer version

### ISSUE THREAD

**Issue by palliki** [music-assistant/hass-music-assistant#2015]
### What version of Music Assistant has the issue?

2.0.0b109 or newer

### What version of the Home Assistant Integration have you got installed?

v2024.3.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Whenever I update Music Assistant version 2.0.0b108 to any newer version, Music Assistant will not start.  The logs (see below), appear to indicate that it does not start because of failing to perform database migration from 27 to 28.

If I restore to version 2.0.0b108, Music Assistant starts and all appears to work fine again.

### How to reproduce

Music Assistant will always not start if I update version 2.0.0b108.

### Music Providers

Built-in /generic provider, File system, Plex, RadioBrowser, Spotify, Tunein Radio

### Player Providers

Slimproto, Airplay, Chromecast, UPnP/ DLNA, SONOS

### Relevant log output

2024-03-16 19:18:04.208 INFO (MainThread) [music_assistant] Starting Music Assistant Server (a53e2b9c12724ef18fb27a2b026fd469) version 2.0.0b111 - uvloop: False
2024-03-16 19:18:04.219 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-03-16 19:18:04.226 WARNING (MainThread) [music_assistant.cache] Performing database migration from 27 to 28
2024-03-16 19:18:29.673 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 211, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 144, in start
    await self.cache.setup(await self.config.get_core_config("cache"))
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/cache.py", line 76, in setup
    await self._setup_database()
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/cache.py", line 198, in _setup_database
    await self.database.execute(f"DROP TABLE IF EXISTS {DB_TABLE_CACHE}")
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/helpers/database.py", line 154, in execute
    return await self._db.execute(query, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 193, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 132, in _execute
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosqlite/core.py", line 115, in run
    result = function()
             ^^^^^^^^^^
sqlite3.DatabaseError: database disk image is malformed

### Additional information

Logs appear to relate failure to start with failure to perform database migration from 27 to 28.

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Unusual. It’s not ideal but you could just start again with a fresh install?

**Comment by palliki** [comment]
In the end I had to start again with a new install to get g=things working again

**Comment by nirnachmani** [comment]
I am facing exactly the same issue (exact error message and behavior) but with version 2.0.0b131. It takes a few hours to rebuilt the database... no way of fixing it?

**Comment by OzGav** [comment]
Are you saying it is fixed after a few hours of rebuilding? If the DB gets corrupted then an uninstall and reinstall is the only way.

**Comment by grishkevicheu** [comment]
I have similar problem 

log of start:
2024-04-19 19:47:01.633 DEBUG (MainThread) [music_assistant.server.controllers.config] Started with empty storage: No persistent storage file found.
2024-04-19 19:47:01.635 DEBUG (MainThread) [music_assistant.server.controllers.config] Started.
2024-04-19 19:47:01.635 INFO (MainThread) [music_assistant] Starting Music Assistant Server (60b6e997a7ad4a828405d268a326fa4c) version 2.0.0b138 - HA add-on: True
2024-04-19 19:47:01.649 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-04-19 19:47:02.231 DEBUG (MainThread) [music_assistant.cache] Running automatic cleanup...
2024-04-19 19:47:02.246 DEBUG (MainThread) [music_assistant.cache] Automatic cleanup finished (cleaned up 0 records)
2024-04-19 19:47:02.261 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-04-19 19:47:02.814 DEBUG (MainThread) [music_assistant.music] Compacting database...
2024-04-19 19:47:02.836 DEBUG (MainThread) [music_assistant.music] Compacting database done
2024-04-19 19:47:02.836 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-04-19 19:47:03.215 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-04-19 19:47:03.216 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.1.167:8097
2024-04-19 19:47:03.260 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Airplay
2024-04-19 19:47:03.292 DEBUG (MainThread) [music_assistant] Loaded manifest for provider fanart.tv Metadata provider
2024-04-19 19:47:03.298 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Deezer
2024-04-19 19:47:03.300 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Filesystem (local disk)
2024-04-19 19:47:03.309 DEBUG (MainThread) [music_assistant] Loaded manifest for provider SONOS
2024-04-19 19:47:03.316 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Qobuz
2024-04-19 19:47:03.331 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Filesystem (remote share)
2024-04-19 19:47:03.339 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Tune-In Radio
2024-04-19 19:47:03.349 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Jellyfin Media Server Library
2024-04-19 19:47:03.372 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Home Assistant MediaPlayers
2024-04-19 19:47:03.389 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Plex Media Server Library
2024-04-19 19:47:03.401 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Open Subsonic Media Server Library
2024-04-19 19:47:03.410 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Snapcast
2024-04-19 19:47:03.412 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Universal Group Player
2024-04-19 19:47:03.419 DEBUG (MainThread) [music_assistant] Loaded manifest for provider YouTube Music
2024-04-19 19:47:03.432 DEBUG (MainThread) [music_assistant] Loaded manifest for provider TheAudioDB Metadata provider
2024-04-19 19:47:03.446 DEBUG (MainThread) [music_assistant] Loaded manifest for provider UPnP/DLNA Player provider
2024-04-19 19:47:03.466 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Soundcloud
2024-04-19 19:47:03.471 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Home Assistant
2024-04-19 19:47:03.473 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Chromecast
2024-04-19 19:47:03.483 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Slimproto (Squeezebox players)
2024-04-19 19:47:03.492 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Fully Kiosk Browser
2024-04-19 19:47:03.505 DEBUG (MainThread) [music_assistant] Loaded manifest for provider RadioBrowser
2024-04-19 19:47:03.508 DEBUG (MainThread) [music_assistant] Loaded manifest for provider MusicBrainz Metadata provider
2024-04-19 19:47:03.515 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Spotify
2024-04-19 19:47:03.518 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Tidal
2024-04-19 19:47:03.527 DEBUG (MainThread) [music_assistant] Loaded manifest for provider Music Assistant
2024-04-19 19:47:03.537 DEBUG (MainThread) [music_assistant] Starting Zeroconf broadcast...
2024-04-19 19:47:03.653 DEBUG (ThreadPoolExecutor-0_5) [soco.data_structures_entry] soco.data_structures_entry imported
log of start2:
.......
2024-04-19 19:54:27.871 DEBUG (ThreadPoolExecutor-0_6) [soco.data_structures_entry] soco.data_structures_entry imported
log of start3:
.......
2024-04-19 19:55:30.991 DEBUG (ThreadPoolExecutor-0_13) [soco.data_structures_entry] soco.data_structures_entry imported

Music Assistant BETA version: 2.0.0b131.... 138 (will deleted and install again )
Home Assistant Core 2024.4.3
Supervisor 2024.04.0
Operating System debian 12
User interface 20240404.2

**Comment by OzGav** [comment]
Firstly don’t add to closed issues, you are lucky I saw this. Secondly, we are clear in our docs to not paste log entries and don’t use debug unless asked. I am not even sure what you added at the bottom. So please go through the troubleshooting page of the docs and open a new issue if that does not help and include all the info requested.
