### ISSUE TITLE
If a bound network interface is removed/down it renders Music assistant unusable. 

### ISSUE THREAD

**Issue by dragon2611** [music-assistant/hass-music-assistant#2022]
### What version of Music Assistant has the issue?

2.0.0.b114

### What version of the Home Assistant Integration have you got installed?

2024.3.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If the streamserver is bound to a specific network interface in HassOS but then that interface is unavailable it breaks Music assistant, This in itself is not that unexpected, but the problem is you cannot then get to the settings to unbind the interface.

![image](https://github.com/music-assistant/hass-music-assistant/assets/6185399/4d10f764-4865-4692-be08-b2c2acb91521)

### How to reproduce

Bind MusicAssistant to an interface in core > streamserver

### Music Providers

N/A

### Player Providers

N/A

### Full log output

`2024-03-18 09:05:38.128 INFO (MainThread) [music_assistant] Starting Music Assistant Server (404ead21ce104b419123afe485ac3ddc) version 2.0.0b114 - uvloop: False
2024-03-18 09:05:38.132 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-03-18 09:05:38.143 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-03-18 09:05:38.170 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-03-18 09:05:38.230 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
2024-03-18 09:05:38.230 INFO (MainThread) [music_assistant.streams] Starting server on  192.168.5.20:8096 - base url: http://192.168.5.20:8096
2024-03-18 09:05:38.232 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.12/site-packages/music_assistant/__main__.py", line 211, in start_mass
    await mass.start()
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/server.py", line 150, in start
    await self.streams.setup(await self.config.get_core_config("streams"))
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 335, in setup
    await self._server.setup(
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/webserver.py", line 74, in setup
    await self._tcp_site.start()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_runner.py", line 119, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1573, in create_server
    raise OSError('could not bind on any address out of %r'
OSError: could not bind on any address out of [('192.168.5.20', 8096)]
2024-03-18 09:05:40.810 WARNING (MainThread) [music_assistant.webserver] Invalid command: players/all
2024-03-18 09:05:40.943 WARNING (MainThread) [music_assistant.webserver] Invalid command: music/recently_played_items
2024-03-18 09:05:40.943 WARNING (MainThread) [music_assistant.webserver] Invalid command: music/browse
2024-03-18 09:05:43.813 WARNING (MainThread) [music_assistant.webserver] Invalid command: config/providers
2024-03-18 09:05:46.623 WARNING (MainThread) [music_assistant.webserver] Invalid command: config/core
2024-03-18 09:07:38.518 WARNING (MainThread) [music_assistant.webserver] Invalid command: players/all
2024-03-18 09:07:38.665 WARNING (MainThread) [music_assistant.webserver] Invalid command: music/recently_played_items
2024-03-18 09:07:38.666 WARNING (MainThread) [music_assistant.webserver] Invalid command: music/browse
2024-03-18 09:07:41.512 WARNING (MainThread) [music_assistant.webserver] Invalid command: config/providers
2024-03-18 09:07:42.903 WARNING (MainThread) [music_assistant.webserver] Invalid command: config/core
2024-03-18 09:10:26.890 WARNING (MainThread) [music_assistant.webserver] Invalid command: config/providers`

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by dragon2611** [comment]
Maybe IP binding is something that could be passed in via the Add-ON configuration (Via a docker env variable) then you'd be able to easily unset/reset it if MA cannot start.

**Comment by marcelveldt** [comment]
I just fixed this one, available from b146
