### ISSUE TITLE
Latest version does not play AAC formatted radio streams

### ISSUE THREAD

**Issue by rich33584** [music-assistant/hass-music-assistant#2074]
### What version of Music Assistant has the issue?

2.0.0b125

### What version of the Home Assistant Integration have you got installed?

2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

AAC Formatted radio streams will not play. 
.mp3 formatted streams will play. 

### How to reproduce

Try playing an AAC formatted radio stream.

### Music Providers

Tune In radio

### Player Providers

Snapcast

### Full log output

2024-03-27 12:19:38.380 INFO (MainThread) [music_assistant] Starting Music Assistant Server (0c8904fdce4d47079414476b55c4db72) version 2.0.0b125 - HA add-on: True
2024-03-27 12:19:38.384 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-03-27 12:19:38.389 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-03-27 12:19:38.422 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-03-27 12:19:38.541 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-03-27 12:19:38.541 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.86.193:8097
2024-03-27 12:19:38.711 INFO (MainThread) [music_assistant] Loaded music provider URL Player
2024-03-27 12:19:38.711 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-03-27 12:19:38.713 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-03-27 12:19:38.713 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-03-27 12:19:38.713 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-03-27 12:19:38.713 WARNING (MainThread) [music_assistant.providers.tunein] Email address detected instead of username, it is advised to use the tunein username instead of email.
2024-03-27 12:19:38.713 INFO (MainThread) [music_assistant] Loaded music provider Tune-In Radio
2024-03-27 12:19:38.762 INFO (MainThread) [music_assistant.music] Sync task for URL Player completed
2024-03-27 12:19:38.763 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-03-27 12:19:38.763 INFO (MainThread) [music_assistant] Loaded music provider Filesystem (local disk)
2024-03-27 12:19:38.763 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-03-27 12:19:38.764 INFO (MainThread) [music_assistant.providers.snapcast.snapserver] Starting builtin Snapserver...
2024-03-27 12:19:38.768 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-03-27 12:19:38.772 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2024-03-27 12:19:39.119 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-03-27 12:19:39.715 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as 31j352q5l2tf6mizq4q546i6vmqy
2024-03-27 12:19:39.715 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-03-27 12:19:41.083 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-03-27 12:19:41.084 WARNING (MainThread) [music_assistant.music] Sync task for Filesystem (local disk) completed with errors
2024-03-27 12:19:42.531 INFO (MainThread) [music_assistant.providers.snapcast] Started connection to Snapserver 127.0.0.1:1705
2024-03-27 12:19:42.531 INFO (MainThread) [music_assistant] Loaded player provider Snapcast
2024-03-27 12:19:42.531 INFO (MainThread) [music_assistant.players] Player registered: 2c:cf:67:07:de:71/livingroomsatellite
2024-03-27 12:19:42.532 INFO (MainThread) [music_assistant.players] Player registered: 2c:cf:67:0b:8c:a3/mbsatellite
2024-03-27 12:19:42.532 INFO (MainThread) [music_assistant.players] Player registered: 2c:cf:67:0b:77:ba/garagesatellite
2024-03-27 12:19:42.532 INFO (MainThread) [music_assistant.players] Player registered: 2c:cf:67:07:e4:94/loftsatellite
2024-03-27 12:19:42.695 INFO (MainThread) [music_assistant.players] Player registered: ap0009b0f35d11/Pioneer SC-LX704 F35D11
2024-03-27 12:19:42.696 INFO (MainThread) [music_assistant.players] Player registered: uuid:b0f35d11-0011-5dBB-b000-0009b0f35d11/Surround System
2024-03-27 12:19:48.280 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-03-27 12:19:51.297 INFO (MainThread) [music_assistant.players] Player registered: e35ab133-c5a8-85e7-5afb-2cbb9722e553/Surround System
2024-03-27 12:19:51.364 INFO (MainThread) [music_assistant.players] Player registered: 959d305f-15cc-e8d7-dd03-a49b69ba4d78/Family Room chromecast
2024-03-27 12:19:51.424 INFO (MainThread) [music_assistant.players] Player registered: 051eb5fc-3f4f-673a-b944-6419c7de2ca3/SHIELD
2024-03-27 12:19:57.079 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue livingroomsatellite - crossfade: False
2024-03-27 12:20:18.113 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 71, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 248, in get_artist_mbid
    ref_tracks = await self.mass.music.artists.tracks(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 185, in tracks
    return await self.get_provider_artist_toptracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 261, in get_provider_artist_toptracks
    artist = await self.get(item_id, provider_instance_id_or_domain, add_to_library=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 198, in get
    raise MediaNotFoundError(msg)
music_assistant.common.models.errors.MediaNotFoundError: Item not found: None/None
2024-03-27 12:20:18.120 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 71, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 119, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 248, in get_artist_mbid
    ref_tracks = await self.mass.music.artists.tracks(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 185, in tracks
    return await self.get_provider_artist_toptracks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 261, in get_provider_artist_toptracks
    artist = await self.get(item_id, provider_instance_id_or_domain, add_to_library=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 198, in get
    raise MediaNotFoundError(msg)
music_assistant.common.models.errors.MediaNotFoundError: Item not found: None/None
2024-03-27 12:20:21.266 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue livingroomsatellite - crossfade: False

### Additional information

2.0.0b119 Works. Ive been hoping an update will fix it, but to no avail..

### What version of Home Assistant Core are your running

2024.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Did you try to clear the cache ?
MA settings --> Core tab --> Cache controller --> Press the clear cache button

**Comment by rich33584** [comment]
My apologies. That did the trick. I thought I tried that, but evidently not..
Thanks for your time.
