### ISSUE TITLE
TTS doesn't work on Slimproto Group

### ISSUE THREAD

**Issue by Alundran** [music-assistant/hass-music-assistant#2075]
### What version of Music Assistant has the issue?

2.0.0b125

### What version of the Home Assistant Integration have you got installed?

2024.2.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Using TTS targeted to a Slimproto group doesn't seem to work. The music stops playing as if TTS is playing but no sound.

### How to reproduce

Play a TTS message targeted to a Slimproto group

### Music Providers

Spotify

### Player Providers

Slimproto Group

### Full log output

```
2024-03-27 17:17:39.977 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: list indices must be integers or slices, not float
2024-03-27 17:17:51.697 INFO (MainThread) [music_assistant.players] Playback announcement to player Kitchen Player (with pre-announce: False): http://192.168.1.113:8123/api/tts_proxy/8c2bbe03546e470d11cf791840d6b1c8de0a6098_en-ie_b51835fb6e_cloud.mp3
[mp3 @ 0x55d50c874440] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'http://192.168.1.113:8123/api/tts_proxy/8c2bbe03546e470d11cf791840d6b1c8de0a6098_en-ie_b51835fb6e_cloud.mp3':
  Metadata:
    Text            : Cloud
  Duration: 00:00:03.98, start: 0.000000, bitrate: 50 kb/s
  Stream #0:0: Audio: mp3, 24000 Hz, mono, fltp, 48 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> flac (native))
Press [q] to stop, [?] for help
[flac @ 0x55d50c89f8c0] encoding as 24 bits-per-sample, more is considered experimental. Add -strict experimental if you want to encode more than 24 bits-per-sample
Output #0, flac, to 'pipe:':
  Metadata:
    Text            : Cloud
    encoder         : Lavf60.3.100
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s32 (24 bit), 128 kb/s
    Metadata:
      encoder         : Lavc60.3.100 flac
size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[flac @ 0x55d50c884180] unable to rewrite FLAC header.
size=     263kB time=00:00:04.00 bitrate= 538.0kbits/s speed=16.9x    
video:0kB audio:255kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.183712%
2024-03-27 17:18:00.334 INFO (MainThread) [music_assistant.players] Playback announcement to player Kitchen Player (with pre-announce: False): http://192.168.1.113:8123/api/tts_proxy/8c2bbe03546e470d11cf791840d6b1c8de0a6098_en-ie_b51835fb6e_cloud.mp3
2024-03-27 17:18:00.335 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: list indices must be integers or slices, not float
2024-03-27 17:18:04.195 INFO (MainThread) [music_assistant.players] Playback announcement to player Kitchen Player (with pre-announce: False): http://192.168.1.113:8123/api/tts_proxy/8c2bbe03546e470d11cf791840d6b1c8de0a6098_en-ie_b51835fb6e_cloud.mp3
[mp3 @ 0x55fd3a421440] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'http://192.168.1.113:8123/api/tts_proxy/8c2bbe03546e470d11cf791840d6b1c8de0a6098_en-ie_b51835fb6e_cloud.mp3':
  Metadata:
    Text            : Cloud
  Duration: 00:00:03.98, start: 0.000000, bitrate: 50 kb/s
  Stream #0:0: Audio: mp3, 24000 Hz, mono, fltp, 48 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> flac (native))
Press [q] to stop, [?] for help
[flac @ 0x55fd3a44c8c0] encoding as 24 bits-per-sample, more is considered experimental. Add -strict experimental if you want to encode more than 24 bits-per-sample
Output #0, flac, to 'pipe:':
  Metadata:
    Text            : Cloud
    encoder         : Lavf60.3.100
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s32 (24 bit), 128 kb/s
    Metadata:
      encoder         : Lavc60.3.100 flac
size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[flac @ 0x55fd3a431180] unable to rewrite FLAC header.
size=     263kB time=00:00:04.00 bitrate= 538.0kbits/s speed=  17x    
video:0kB audio:255kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.183712%
2024-03-27 17:18:43.268 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen Party Player - crossfade: True
2024-03-27 17:27:56.977 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen Party Player - crossfade: True
2024-03-27 17:59:12.897 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen Party Player - crossfade: True
2024-03-27 18:06:09.075 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as dezmond95
2024-03-27 18:14:42.052 INFO (MainThread) [music_assistant.players] Playback announcement to player Kitchen Player (with pre-announce: False): http://192.168.1.113:8123/api/tts_proxy/3992f8886671ba3331b1584ad82df2ae910459a3_en-ie_e09b5a0968_cloud.mp3
2024-03-27 18:14:42.052 INFO (MainThread) [music_assistant.players] Playback announcement to player Kitchen Party Player (with pre-announce: None): http://192.168.1.113:8123/api/tts_proxy/3992f8886671ba3331b1584ad82df2ae910459a3_en-ie_e09b5a0968_cloud.mp3
2024-03-27 18:14:42.070 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen Party Player - crossfade: False
2024-03-27 18:14:42.137 WARNING (MainThread) [music_assistant.streams] Received unhandled GET request to /multi/syncgroup_rfddassw/cyUj6TpTt7vMGJy8q5JJfR/02:42:ac:14:00:02/http://192.168.1.113:8123/api/tts_proxy/3992f8886671ba3331b1584ad82df2ae910459a3_en-ie_e09b5a0968_cloud.mp3.flac from 192.168.1.252
headers: <CIMultiDictProxy('Host': '192.168.1.113:8097', 'Connection': 'close', 'Accept': '*/*', 'Cache-Control': 'no-cache', 'User-Agent': 'VLC/3.0.9 LibVLC/3.0.9', 'Range': 'bytes=0-')>

2024-03-27 18:14:42.167 WARNING (MainThread) [music_assistant.streams] Received unhandled GET request to /multi/syncgroup_rfddassw/cyUj6TpTt7vMGJy8q5JJfR/d8:3a:dd:39:05:a2/http://192.168.1.113:8123/api/tts_proxy/3992f8886671ba3331b1584ad82df2ae910459a3_en-ie_e09b5a0968_cloud.mp3.flac from 192.168.1.159
headers: <CIMultiDictProxy('Host': '192.168.1.113:8097', 'Connection': 'close', 'Accept': '*/*', 'Cache-Control': 'no-cache', 'User-Agent': 'VLC/3.0.9 LibVLC/3.0.9', 'Range': 'bytes=0-')>

2024-03-27 18:14:52.643 ERROR (MainThread) [music_assistant.streams] Abort multi client stream job for queue Kitchen Party Player: clients did not connect within timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 239, in _stream_job_runner
    await self._all_clients_connected.wait()
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 238, in _stream_job_runner
    async with asyncio.timeout(10):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
2024-03-27 18:15:15.627 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen Party Player - crossfade: True
2024-03-27 18:20:07.789 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed (re-)subscribing to: uuid:79892097-b3f1-e476-6c2c-9481fc2262ad, reason: UpnpConnectionError('ClientConnectorError(ConnectionKey(host=\'192.168.1.197\', port=1703, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(113, "Connect call failed (\'192.168.1.197\', 1703)"))', None)
2024-03-27 18:56:45.996 INFO (MainThread) [music_assistant.players] Playback announcement to player Kitchen Party Player (with pre-announce: None): http://192.168.1.113:8123/api/tts_proxy/0504cbae68c58937ad5a5dea1a66de58300d3504_en-ie_b51835fb6e_cloud.mp3
2024-03-27 18:56:46.556 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Kitchen Party Player - crossfade: False
2024-03-27 18:56:46.614 WARNING (MainThread) [music_assistant.streams] Received unhandled GET request to /multi/syncgroup_rfddassw/5B3jhRTDMPtqkdzVrht4Rk/d8:3a:dd:39:05:a2/http://192.168.1.113:8123/api/tts_proxy/0504cbae68c58937ad5a5dea1a66de58300d3504_en-ie_b51835fb6e_cloud.mp3.flac from 192.168.1.159
headers: <CIMultiDictProxy('Host': '192.168.1.113:8097', 'Connection': 'close', 'Accept': '*/*', 'Cache-Control': 'no-cache', 'User-Agent': 'VLC/3.0.9 LibVLC/3.0.9', 'Range': 'bytes=0-')>

2024-03-27 18:56:46.643 WARNING (MainThread) [music_assistant.streams] Received unhandled GET request to /multi/syncgroup_rfddassw/5B3jhRTDMPtqkdzVrht4Rk/02:42:ac:14:00:02/http://192.168.1.113:8123/api/tts_proxy/0504cbae68c58937ad5a5dea1a66de58300d3504_en-ie_b51835fb6e_cloud.mp3.flac from 192.168.1.252
headers: <CIMultiDictProxy('Host': '192.168.1.113:8097', 'Connection': 'close', 'Accept': '*/*', 'Cache-Control': 'no-cache', 'User-Agent': 'VLC/3.0.9 LibVLC/3.0.9', 'Range': 'bytes=0-')>

2024-03-27 18:56:57.137 ERROR (MainThread) [music_assistant.streams] Abort multi client stream job for queue Kitchen Party Player: clients did not connect within timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 239, in _stream_job_runner
    await self._all_clients_connected.wait()
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 238, in _stream_job_runner
    async with asyncio.timeout(10):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

### What version of Home Assistant Core are your running

2024.2.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This should be fixed in b130. Advise if not and we can reopen

**Comment by Pittermaennchen** [comment]
I just had a very similar issue and could not find a way to fix this. Using TTS targeted to a Slimproto player or a RaspberryPi does not work. The music stops playing as if TTS is playing but no sound.

In my logs I found an issue: **The IP-adress is referring to an old instance of my Home Assistant OS, when I used a different device as Home Assistant-Server in my network. But nowadays the IP and the port are wrong. How and where can I change those?**

> AttributeError: 'StreamDetails' object has no attribute 'seconds_skipped'. Did you mean: 'seconds_streamed'?
2024-04-08 02:02:12.957 INFO (MainThread) [music_assistant.players] Playback announcement to player Squeezeplayer Moto G (5S) (Logitech Media Server (with pre-announce: True): http://192.168.178.XX:8123/api/tts_proxy/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3_de-de_6e8b81ac47_cloud.mp3
2024-04-08 02:02:12.957 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: unhandled errors in a TaskGroup (1 sub-exception)
2024-04-08 02:05:43.489 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/deezer/__init__.py", line 494, in on_streamed
    await self.gw_client.log_listen(last_track=streamdetails)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/deezer/gw_client.py", line 182, in log_listen
    "seek": 1 if last_track.seconds_skipped else 0,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StreamDetails' object has no attribute 'seconds_skipped'. Did you mean: 'seconds_streamed'?
2024-04-08 02:05:XX.447 INFO (MainThread) [music_assistant.players] Playback announcement to player Squeezeplayer Moto G (5S) (Logitech Media Server (with pre-announce: True): http://192.168.178.XX:8123/api/tts_proxy/475f7ae642916bf5cb816dfbe99dee2e95593310_de-de_6e8b81ac47_tts.home_assistant_cloud.mp3
2024-04-08 02:06:02.489 ERROR (MainThread) [music_assistant.webserver] **Error handling message: players/cmd/play_announcement: Unable to retrieve info for http://192.168.178.XX:8123/api/tts_proxy/**475f7ae642916bf5cb816dfbe99dee2e95593310_de-de_6e8b81ac47_tts.home_assistant_cloud.mp3: Connection timed out
2024-04-08 02:06:32.286 INFO (MainThread) [music_assistant.players] Playback announcement to player Squeezeplayer Moto G (5S) (Logitech Media Server (with pre-announce: True): http://192.168.178.XX:8123/api/tts_proxy/475f7ae642916bf5cb816dfbe99dee2e95593310_sw-cd_-_tts.piper.mp3
2024-04-08 02:06:34.613 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: Unable to retrieve info for http://192.168.178.XX:8123/api/tts_proxy/475f7ae642916bf5cb816dfbe99dee2e95593310_sw-cd_-_tts.piper.mp3: No route to host
2024-04-08 02:08:32.445 INFO (MainThread) [music_assistant.players] Playback announcement to player raspberrypi (with pre-announce: True): http://192.168.178.XX:8123/api/tts_proxy/475f7ae642916bf5cb816dfbe99dee2e95593310_sw-cd_-_tts.piper.mp3
2024-04-08 02:08:46.710 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: Unable to retrieve info for http://192.168.178.XX:8123/api/tts_proxy/475f7ae642916bf5cb816dfbe99dee2e95593310_sw-cd_-_tts.piper.mp3: No route to host
2024-04-08 02:08:51.246 INFO (MainThread) [music_assistant.players] Playback announcement to player raspberrypi (with pre-announce: True): http://192.168.178.XX:8123/api/tts_proxy/475f7ae642916bf5cb816dfbe99dee2e95593310_de-de_6e8b81ac47_tts.home_assistant_cloud.mp3
2024-04-08 02:09:05.142 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: Unable to retrieve info for http://192.168.178.XX:8123/api/tts_proxy/475f7ae642916bf5cb816dfbe99dee2e95593310_de-de_6e8b81ac47_tts.home_assistant_cloud.mp3: No route to host
2024-04-08 02:17:25.847 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue raspberrypi - crossfade: False
2024-04-08 02:21:21.799 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/deezer/__init__.py", line 494, in on_streamed
    await self.gw_client.log_listen(last_track=streamdetails)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/deezer/gw_client.py", line 182, in log_listen
    "seek": 1 if last_track.seconds_skipped else 0,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StreamDetails' object has no attribute 'seconds_skipped'. Did you mean: 'seconds_streamed'?
2024-04-08 02:23:14.944 INFO (MainThread) [music_assistant.players] Playback announcement to player raspberrypi (with pre-announce: True): http://192.168.178.XX:8123/api/tts_proxy/1e0bc0a9623dd93bb05ca2e0d4b3862b6859e406_de-de_6e8b81ac47_cloud.mp3
2024-04-08 02:23:27.350 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: Unable to retrieve info for http://192.168.178.XX:8123/api/tts_proxy/1e0bc0a9623dd93bb05ca2e0d4b3862b6859e406_de-de_6e8b81ac47_cloud.mp3: No route to host
2024-04-08 02:37:07.463 INFO (MainThread) [music_assistant.players] Playback announcement to player raspberrypi (with pre-announce: True): http://192.168.178.XX:8123/api/tts_proxy/1e0bc0a9623dd93bb05ca2e0d4b3862b6859e406_de-de_6e8b81ac47_cloud.mp3
2024-04-08 02:37:21.910 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: Unable to retrieve info for http://192.168.178.XX:8123/api/tts_proxy/1e0bc0a9623dd93bb05ca2e0d4b3862b6859e406_de-de_6e8b81ac47_cloud.mp3: No route to host
2024-04-08 02:38:48.631 INFO (MainThread) [music_assistant.players] Playback announcement to player raspberrypi (with pre-announce: True): http://192.168.178.XX:8123/api/tts_proxy/1e0bc0a9623dd93bb05ca2e0d4b3862b6859e406_de-de_6e8b81ac47_cloud.mp3
2024-04-08 02:39:03.285 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: Unable to retrieve info for http://192.168.178.XX:8123/api/tts_proxy/1e0bc0a9623dd93bb05ca2e0d4b3862b6859e406_de-de_6e8b81ac47_cloud.mp3: No route to host

**Comment by OzGav** [comment]
Please go and read the troubleshooting section of the docs

**Comment by Pittermaennchen** [comment]
Thank you!

> Make sure the HA internal url is set correctly. HA SETTINGS>>SYSTEM>>NETWORK>>Home Assistant URL>>Local network (set to automatic or use your internal HA IP). If it is automatic you can try changing it to http://your.internal.ip:8123/

This was my problem. I changed to automatic and now the TTS-Sound is played!

On one of my players I now have an obviously not MA-related issue: After the tts-sound it cracks and then jumps to the next song. But on a slimproto-/Squeezelight-Player it works fine. Thank you a lot for your awesome work!!!

**Comment by OzGav** [comment]
That might be an MA issue. Is it DLNA per chance? Either way if it is a problem for you open a new issue with all the info requested on the troubleshooting page and on the issue template
