### ISSUE TITLE
V1.1.13: analyze audio exception

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#209]
Noticed this exception:
```
Logger: music_assistant.mass
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:243 
First occurred: 14:17:24 (1 occurrences) 
Last logged: 14:17:24

Job [Analyze audio for file://track/albumsacdcfulldiscographyaddc74jailbreak05babypleasedontgomp3] failed with error 'NoneType' object has no attribute 'decode'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 170, in analyze_audio
    loudness = float(stdout.decode().strip())
ValueError: could not convert string to float: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 177, in analyze_audio
    stderr.decode(),
AttributeError: 'NoneType' object has no attribute 'decode'
```

Note: Didn't hamper playback

**Comment by marcelveldt** [comment]
this should be fixed in v1.1.14

**Comment by erkr** [comment]
Not seen yet, will keep an eye on this today👍

**Comment by erkr** [comment]
Not seen anymore👍
