### ISSUE TITLE
Problem with installing MA

### ISSUE THREAD

**Issue by sanderjohan** [music-assistant/hass-music-assistant#211]
After installing with HACS I see the following error in the logs

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 85, in async_setup_entry
    MusicProviderConfig(
  File "<string>", line 9, in __init__
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/config.py", line 32, in __post_init__
    ) + base_str[-1]
IndexError: string index out of range

I am using HA Supervised installed on a NUC

**Comment by marcelveldt** [comment]
Did you enable one of the music providers without filling in the username ?

**Comment by marcelveldt** [comment]
Added a small fix in the 1.1.15 release for this issue. You will now be notified of what is wrong with the config instead of a crash.
