### ISSUE TITLE
Error adding Spotify as Music Provider "Provider spotify did not load within 30 seconds"

### ISSUE THREAD

**Issue by chesapeakesoja** [music-assistant/hass-music-assistant#2130]
### What version of Music Assistant has the issue?

2.0.0b136

### What version of the Home Assistant Integration have you got installed?

2024.3.6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When attempting to add Spotify as a Music Provider, I receive the error "Provider spotify did not load within 30 seconds." I have tried this with two separate users on my Premium Family plan attempting to use the email address as the user name as well as the Spotify-assigned user (random numbers that Spotify assigns as user). I see the issue either way and it is persistent; I have been unable to add Spotify as a Music Provider

### How to reproduce

1. Go to Settings in MA
2. Select Add Music Provider > Spotify
3. Enter credentials to authenticate
4. Click Save
5. Wait 30 seconds
6. Receive error

### Music Providers

Spotify is the only provider for which I have experienced this issue.

I have successfully added Tidal, TuneIn, Plex Media Server Library, and RadioBrowser without any issues.

### Player Providers

I have not experienced this with any Player Providers. 

### Full log output

2024-04-15 14:59:34.163 INFO (MainThread) [music_assistant] Starting Music Assistant Server (a24d325b4550428ca7dd2852c52c4716) version 2.0.0b136 - HA add-on: True
2024-04-15 14:59:34.182 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-04-15 14:59:34.216 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-04-15 14:59:34.252 WARNING (MainThread) [music_assistant.webserver] Invalid command: players/all
2024-04-15 14:59:34.272 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-04-15 14:59:34.959 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-04-15 14:59:34.959 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.10.10:8097
2024-04-15 14:59:36.222 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-04-15 14:59:36.223 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-04-15 14:59:36.224 INFO (MainThread) [music_assistant] Loaded music provider URL
2024-04-15 14:59:36.225 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-04-15 14:59:36.246 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-04-15 14:59:36.249 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-04-15 14:59:36.259 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-04-15 14:59:36.260 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-04-15 14:59:36.294 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-04-15 14:59:36.385 INFO (MainThread) [music_assistant.players] Player registered: 676c6b97-cf78-01a8-4dd1-860ef4a41b6b/Master Bedroom speaker
2024-04-15 14:59:36.473 INFO (MainThread) [music_assistant.players] Player registered: 6249c5e0-ca29-4a17-9730-f64960f8dd9c/Christmas Party
2024-04-15 14:59:36.584 INFO (MainThread) [music_assistant.players] Player registered: 8b7d1fee-5f1e-4f5b-a133-43e9dff8dd57/Chromecasts
2024-04-15 14:59:36.668 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-04-15 14:59:36.691 INFO (MainThread) [music_assistant.players] Player registered: apa0d05b4e0d2e/samsung soundbar s801b
2024-04-15 14:59:36.700 INFO (MainThread) [music_assistant.players] Player registered: ap48a6b8ff9710/living room sonos
2024-04-15 14:59:36.719 INFO (MainThread) [music_assistant.players] Player registered: apbbbbcd46df59/living room sonos+
2024-04-15 14:59:36.726 INFO (MainThread) [music_assistant.players] Player registered: apbbbb1010e637/kitchen sonos+
2024-04-15 14:59:36.738 INFO (MainThread) [music_assistant] Loaded music provider Tidal
2024-04-15 14:59:36.751 INFO (MainThread) [music_assistant.players] Player registered: apbbbb6465e150/smarttv 4k+
2024-04-15 14:59:36.768 INFO (MainThread) [music_assistant.players] Player registered: ap48a6b8ff9c3e/kitchen sonos
2024-04-15 14:59:36.782 INFO (MainThread) [music_assistant.players] Player registered: ap907065902b31/soundtouch 10
2024-04-15 14:59:36.795 INFO (MainThread) [music_assistant.players] Player registered: apbbbbc432c9c3/soundtouch 10+
2024-04-15 14:59:36.832 INFO (MainThread) [music_assistant.players] Player registered: 23453024-18ae-f8ca-5093-aa7bf0a6836a/Garage speaker
2024-04-15 14:59:36.908 INFO (MainThread) [music_assistant.players] Player registered: RINCON_48A6B8FF9C3E01400/Kitchen Sonos
2024-04-15 14:59:36.912 WARNING (MainThread) [soco.events_asyncio] Could not bind to 192.168.10.10:1400: [Errno 98] Address already in use
2024-04-15 14:59:36.941 INFO (MainThread) [music_assistant.players] Player registered: 87b91054-0991-930b-01a4-af53a440ee7a/Backyard speaker
2024-04-15 14:59:37.166 INFO (MainThread) [music_assistant.players] Player registered: RINCON_48A6B8FF971001400/Living Room Sonos
2024-04-15 14:59:37.261 INFO (MainThread) [music_assistant.music] Sync task for Tidal completed
2024-04-15 14:59:37.341 INFO (MainThread) [music_assistant.players] Player registered: 87753ab5-13ce-4bfb-571d-37a83b6d14f4/Alarm Clock
2024-04-15 14:59:38.715 INFO (MainThread) [music_assistant.players] Player registered: uuid:3550ac82-bc74-11ed-adca-e7f1b948fbb7/SmartTV 4K
2024-04-15 14:59:38.990 WARNING (MainThread) [async_upnp_client.profiles.dlna] Only InstanceID 0 is supported
2024-04-15 14:59:38.997 INFO (MainThread) [music_assistant.players] Player registered: uuid:BO5EBO5E-F00D-F00D-FEED-907065902B31/SoundTouch 10
2024-04-15 14:59:39.021 WARNING (MainThread) [async_upnp_client.profiles.dlna] Only InstanceID 0 is supported
2024-04-15 15:00:06.280 ERROR (MainThread) [music_assistant] Error loading provider(instance) RadioBrowser
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/server.py", line 455, in load_provider
    provider = await prov_mod.setup(self, prov_manifest, conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/radiobrowser/__init__.py", line 48, in setup
    await prov.handle_async_init()
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/radiobrowser/__init__.py", line 83, in handle_async_init
    await self.radios.stats()
  File "/usr/local/lib/python3.12/site-packages/radios/radio_browser.py", line 126, in stats
    response = await self._request("stats")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/radios/radio_browser.py", line 92, in _request
    response = await self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/server.py", line 454, in load_provider
    async with asyncio.timeout(30):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/server.py", line 538, in load_provider
    await self.load_provider(prov_conf)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/server.py", line 458, in load_provider
    raise SetupFailedError(msg) from err
music_assistant.common.models.errors.SetupFailedError: Provider radiobrowser did not load within 30 seconds
2024-04-15 15:10:03.193 WARNING (MainThread) [music_assistant.metadata] en-us is not a valid language
2024-04-15 15:10:53.425 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: Provider spotify did not load within 30 seconds
2024-04-15 15:15:08.355 WARNING (MainThread) [music_assistant.metadata] en-us is not a valid language
2024-04-15 15:17:27.789 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: Provider spotify did not load within 30 seconds
2024-04-15 15:21:39.080 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: Provider spotify did not load within 30 seconds
2024-04-15 15:28:51.286 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: Provider spotify did not load within 30 seconds

### Additional information

I have been unable to see anything in the FAQ or past issues that resembles this. I am running HAOS with a pretty standard network setup. Attempting to log in with multiple users to determine whether the issue was tied to one user account seemed to be logical.

### What version of Home Assistant Core are your running

2024.4.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Couple of things. Good first issue report. If you can just delete log file and attach it rather than pasting. Secondly, b137 was just released so try that. Lastly I see another error in there saying the radio browser failed to load as well so something is going on with your setup I think but let’s see with b137.

**Comment by OzGav** [comment]
Also please advise how you have installed HAOS. Is it running directly on your machine or in VM?

**Comment by chesapeakesoja** [comment]
Thanks. I've updated the log, as requested, so that it is attached rather than plain text. The RadioBrowser failure was something I saw but restarting that seemed to resolve the issue. I'll update to b137 and attempt this again before providing another update.

HAOS is installed directly on the system rather than in a VM. It's a ZimaBoard 832.

**Comment by chesapeakesoja** [comment]
After an update, I am still receiving the same error (and RadioBrowser also failed to load). New log attached.
[MAlog_137b.txt](https://github.com/music-assistant/hass-music-assistant/files/14998550/MAlog_137b.txt)

**Comment by chesapeakesoja** [comment]
Due to some slow loads when attempting to download HACS integrations, I found a recommendation to disable IPv6 and this seems to have resolved the issue with both HACS as well as Spotify authentication.

Hopefully this helps anyone else who may encounter this issue.
