### ISSUE TITLE
V1.1.14: add track to db exception

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#214]
Noticed this exception:
```
Logger: music_assistant.mass
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:243 
First occurred: 18:11:02 (1 occurrences) 
Last logged: 18:11:02

Job [Add spotify://track/6SDQYfdsaLlOoRRUPyv3Ix to database] failed with error 'NoneType' object is not subscriptable.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/tracks.py", line 54, in add
    db_item = await self.add_db_item(item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/tracks.py", line 148, in add_db_item
    track_albums = await self._get_track_albums(track, db=db)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/tracks.py", line 254, in _get_track_albums
    mapping = await self._get_album_mapping(base_track.album, db=db)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/tracks.py", line 281, in _get_album_mapping
    db_artist = await self.mass.music.albums.add_db_item(album, db=db)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 147, in add_db_item
    item_id = new_item["item_id"]
TypeError: 'NoneType' object is not subscriptable
```
And this one
```
Logger: music_assistant.mass
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:243 
First occurred: 17:47:44 (117 occurrences) 
Last logged: 17:48:14

Job [Add database://album/1064 to database] failed with error 'NoneType' object has no attribute 'name'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 95, in add
    await self._match(db_item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 250, in _match
    if await find_prov_match(provider):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 222, in find_prov_match
    f"{db_album.artist.name} - {db_album.name}",
AttributeError: 'NoneType' object has no attribute 'name'
```

Can't give much more context, was browsing the collection to see what is missing

**Comment by marcelveldt** [comment]
I've just guarded the code for this this afternoon. It means you have a file somewhere with some missing ID3 tags.

**Comment by erkr** [comment]
Yep, there are a few tags missing. During the import this morning I got ca 5 times a warning. But the chance is reasonably low it was one of these two examples. One was even a Spotify track.

**Comment by marcelveldt** [comment]
I think this one should be gone in 1.1.15

**Comment by erkr** [comment]
Didn't see these exceptions during the new import 👍
I only see the error you logged on purpose (thx):
```
Logger: music_assistant.mass.music.file
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py:185 
First occurred: 11:01:44 (11 occurrences) 
Last logged: 11:20:19

Error processing /media/MP3_normalized/Albums/Jimi Hendrix/The best Of/Jimi Hendrix - Foxy Lady (Shaka Remix).mp3
Error processing /media/MP3_normalized/Albums/Jimi Hendrix/The best Of/Jimi Hendrix Machine Gun.mp3
Error processing /media/MP3_normalized/Albums/Jimi Hendrix/The best Of/Jimi Hendrix Foxy Lady 06 Live @ Rainbow Bridge Maui, Hawaii, USA 1970.mp3
Error processing /media/MP3_normalized/Albums/Type O Negative/Type O Negative Tribute ( Instrumental) - Love You To Death Remastered.mp3
Error processing /media/MP3_normalized/Albums/Type O Negative/Type O Negative - Black No. 1 - Symphonic Tribute.mpg.mp3
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 153, in sync_library
    if track := await self._parse_track(entry.path, checksum):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 442, in _parse_track
    assert tags.title, "Required tag title is missing"
AssertionError: Required tag title is missing
```
