### ISSUE TITLE
Errors logged while starting MA

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#2170]
### What version of Music Assistant has the issue?

2024b141

### What version of the Home Assistant Integration have you got installed?

Not installed 

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I start  MA, errors are logged. The  home, albums and artist 
pages don't load, guess that is related

### How to reproduce

I just start MA with only two Spotify accounts.
This stated with the  latest  beta 

### Music Providers

Spotify 

### Player Providers

Na

### Full log output

2024-04-29 10:21:53.769 INFO (MainThread) [music_assistant] Starting Music Assistant Server (189e68ed964e45f0a359925f26f88b90) version 2.0.0b141 - HA add-on: True - Safe mode: False
2024-04-29 10:21:53.788 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-04-29 10:21:53.877 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-04-29 10:21:55.773 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-04-29 10:21:55.773 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.178.47:8096
2024-04-29 10:21:55.784 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.178.47:8095
2024-04-29 10:21:56.891 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-04-29 10:21:56.893 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-04-29 10:21:56.898 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-04-29 10:21:56.899 INFO (MainThread) [music_assistant] Loaded music provider Tune-In Radio
2024-04-29 10:21:57.153 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-04-29 10:21:57.155 INFO (MainThread) [music_assistant] Loaded music provider Music Assistant
2024-04-29 10:21:57.163 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-04-29 10:21:57.181 INFO (MainThread) [music_assistant.providers.builtin] Starting migration...
2024-04-29 10:21:57.192 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2024-04-29 10:21:57.664 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as 116886463
2024-04-29 10:21:57.666 INFO (MainThread) [music_assistant] Loaded music provider Spotify Hanneke
2024-04-29 10:21:58.636 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as eric.kreuwels
2024-04-29 10:21:58.636 INFO (MainThread) [music_assistant] Loaded music provider Spotify Eric
2024-04-29 10:22:13.297 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-04-29 10:22:13.331 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-04-29 10:22:18.405 INFO (MainThread) [music_assistant.music] Sync task for Spotify Hanneke completed
2024-04-29 10:22:27.209 INFO (MainThread) [music_assistant.music] Sync task for Spotify Eric completed
2024-04-29 10:22:27.231 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "<string>", line 20, in __mashumaro_from_dict__
  File "<string>", line 40, in __mashumaro_from_dict__
ValueError: Argument for music_assistant.common.models.media_items.AudioFormat.__mashumaro_from_dict__ method should be a dict instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 39, in __mashumaro_from_dict__
  File "<string>", line 22, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "audio_format" of type AudioFormat in ProviderMapping has invalid value None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 208, in scan_artist_metadata
    async for artist in self.mass.music.artists.iter_library_items():
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 164, in iter_library_items
    next_items = await self.library_items(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 174, in library_items
    return await super().library_items(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 142, in library_items
    items = await self._get_library_items_by_query(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 629, in _get_library_items_by_query
    self.item_cls.from_dict(self._parse_db_row(db_row))
  File "<string>", line 41, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "provider_mappings" of type set[ProviderMapping] in Artist has invalid value [{'item_id': '1ahkrwSQpxabomNFWQi9wZ', 'provider_domain': 'spotify', 'provider_instance': 'spotify', 'available': True, 'url': 'https://open.spotify.com/artist/1ahkrwSQpxabomNFWQi9wZ', 'audio_format': {'content_type': '?', 'sample_rate': 44100, 'bit_depth': 16, 'channels': 2, 'output_format_str': '?', 'bit_rate': 320}, 'details': None}, {'item_id': '51Blml2LZPmy7TTiAg47vQ', 'provider_domain': 'spotify', 'provider_instance': 'spotify', 'available': True, 'url': None, 'audio_format': None, 'details': None}]

### What version of Home Assistant Core are your running

2024.4.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
b142 is rescanning as we speak. So far so good. Noticed this in my new log (the result of 140 upgrades 😊)
``` 
Database schema too old - Resetting library/database - a full rescan will be performed, this can take a while!
```

**Comment by marcelveldt** [comment]
great!
cache warning will be fixed in next beta

**Comment by erkr** [comment]
I just Checked the log, and noticed another error in the log.  Ca 15 minutes after startup.
MA was not used, just started after the upgrade.
``` 
2024-04-29 19:21:28.489 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1013, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 218, in scan_artist_metadata
    await self.mass.music.artists.get(artist.item_id, artist.provider, lazy=False)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 210, in get
    await add_task
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 73, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 230, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 373, in get_artist_mbid
    if mbid := await musicbrainz.get_musicbrainz_artist_id(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 224, in get_musicbrainz_artist_id
    if mb_artist := await self.get_artist_details_by_track(artist.name, ref_track):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 416, in get_artist_details_by_track
    result = await self.get_recording_details(ref_track.mbid, isrc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 337, in get_recording_details
    if (result := await self.get_data(f"isrc/{isrsc}")) and result.get("recordings"):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/cache.py", line 258, in wrapped
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 436, in get_data
    async with (
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

**Comment by marcelveldt** [comment]
That is kind of unavoidable - it was a connection issue/hiccup leading to a failed request.
Do you have debug logging enabled or not ? Because stack traces should usually only be printed when debug log is on

**Comment by erkr** [comment]
No debug logging is off
