### ISSUE TITLE
Artist Art Missing after update to b143 and "refresh item" won't work.

### ISSUE THREAD

**Issue by M0uC0** [music-assistant/hass-music-assistant#2185]
### What version of Music Assistant has the issue?

2.0.0b143

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After updating to b143 all my artist art turned M.I.A.

If i go an artist page and press "refresh item", nothing.. and in log i get something like:

2024-05-02 12:06:17.896 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 73, in add_item_to_library
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 230, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 373, in get_artist_mbid
    if mbid := await musicbrainz.get_musicbrainz_artist_id(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 224, in get_musicbrainz_artist_id
    if mb_artist := await self.get_artist_details_by_track(artist.name, ref_track):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 416, in get_artist_details_by_track
    result = await self.get_recording_details(ref_track.mbid, isrc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 342, in get_recording_details
    if result := await self.get_data(f"recording/{recording_id}?inc=artists+releases"):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/cache.py", line 259, in wrapped
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 436, in get_data
    async with (
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 696, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://musicbrainz.org/ws/2/recording/50c4b4ef-ae0a-3bb1-ac5a-0f1356eaafc5?inc=artists+releases&fmt=json')
2024-05-02 12:06:20.843 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/refresh_item: 404, message='Not Found', url=URL('http://musicbrainz.org/ws/2/recording/50c4b4ef-ae0a-3bb1-ac5a-0f1356eaafc5?inc=artists+releases&fmt=json')

### How to reproduce

Selecting "Artist" tab.
result - no artist art.. all m.i.a. since last update.

Select an Artist.
result - no artist art on top bar.

Press the 3 dots.
Then press "Refresh item"
result - nothing

### Music Providers

Filesystem (local disk)

### Player Providers

Slimproto
Chromecast

### What version of Home Assistant Core are your running

2024.5.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Yeah I have seen similar. Some times a refresh fixes it and sometimes it causes the Artist to disappear (until you refresh the whole Artist view)

**Comment by M0uC0** [comment]
When you say " refresh the whole Artist view ", do you mean the "Refresh the items listing" button on the top of the Artists tab?
Because i already did it.. and nothing..
Already removed some artists and "Synchronize now" button in provider...
Artist appeared again in the list.. but no art.

**Comment by OzGav** [comment]
Yes it’s a bug I have marked it as such and it will get looked at soon

**Comment by OzGav** [comment]
Yes looks good to me.
