### ISSUE TITLE
Playing to player from Automation results in error

### ISSUE THREAD

**Issue by mhoogenbosch** [music-assistant/hass-music-assistant#2212]
### What version of Music Assistant has the issue?

2.0.0b147 (but in 145 and 146 too)

### What version of the Home Assistant Integration have you got installed?

2024.5.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When trying to start a 'radio' station, but also a spotify playlist, from an automation with the service 'mass.play_media' it results in the following error:

```
Logger: homeassistant.helpers.entity
Bron: helpers/entity.py:950
Eerst voorgekomen: 04:00:18 (368 gebeurtenissen)
Laatst gelogd: 10:22:53

Update for media_player.kantoor_squeeze fails
Update for media_player.squeezeplay_34_92_1d_ca_f6_c7_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 950, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1293, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/squeezebox/media_player.py", line 284, in async_update
    await self._player.async_update()
  File "/usr/local/lib/python3.12/site-packages/pysqueezebox/player.py", line 360, in async_update
    if "playlist_timestamp" in response and "playlist_tracks" in response:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable
```

The same station to the same player works when using the GUI of Music Assistent

### How to reproduce

Create an automation with the following action:

```
alias: Q music Nederland afspelen
service: mass.play_media
metadata: {}
data:
  media_id: 538
  media_type: radio
target:
  entity_id: media_player.kantoor_squeeze
```

### Music Providers

Radio Browser
Spotify

### Player Providers

Slimproto

### Full log output

[musicassistant.log](https://github.com/music-assistant/hass-music-assistant/files/15246055/musicassistant.log)

Relevant portion I guess:

```
2024-05-08 10:20:01.530 WARNING (MainThread) [music_assistant.webserver] Invalid command: players/queue/all
2024-05-08 10:20:42.011 WARNING (MainThread) [music_assistant.webserver] Invalid command: players/queue/all
```

Where it says it detected input at 10:27:55 I manually started the stream.

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You haven’t listed the correct integration version. Please refer to HACS and post that info

**Comment by mhoogenbosch** [comment]
Erm, there is a 2024.5.0 available. Didn't see this yet in my updates. I'll frist try this.

**Comment by OzGav** [comment]
Yes…

**Comment by mhoogenbosch** [comment]
After updating, removing all players and restarting everyting again unfortunately it still doesn't work. The mentioned error is gone, but the automation doesn't seem to be doing anything at all. 

Unfortunately no error in the logs from HA, but not in the logs from MA either.

**Comment by OzGav** [comment]
I would start by using the service call tab in the dev tools and see if that part works. Is the radio station called 538? If not where did you get that number from?
