### ISSUE TITLE
Integration 2024.4 doesn’t connect add on

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#2215]
### What version of Music Assistant has the issue?

b147

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I updated the add-on , that broke the integration:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/7b1bd5a1-dcb4-40c4-87a9-e59263f814d8)
Restarting HA or reinstalling the add-on doesn’t fix it

### How to reproduce

Described

### Music Providers

Spotify

### Player Providers

CC

### Full log output

HA log, every retry to initialise:
``` 
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:147
First occurred: 14:37:22 (14 occurrences)
Last logged: 14:49:21

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/client.py", line 211, in fetch_initial_state
    await self._players.fetch_state()
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/players.py", line 309, in fetch_state
    for queue in await self.get_player_queues():
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/players.py", line 171, in get_player_queues
    for item in await self.client.send_command("players/queue/all")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/client/client.py", line 176, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: players/queue/all
``` 

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Ah missed that one
