### ISSUE TITLE
Queue Button: don't show queue but single song

### ISSUE THREAD

**Issue by Teddydm71** [music-assistant/hass-music-assistant#2219]
### What version of Music Assistant has the issue?

2.0.0b147

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

when i click queue button on UI, don't show the songs in the queue but only the plaied song.

### How to reproduce

Select MA, select player, search songs, add to queue, click on queue button.  

### Music Providers

FileSystem (remote share)

### Player Providers

Chromecast and google home thru HA and also thru chromecast

### Full log output

2024-05-08 15:32:09.149 INFO (MainThread) [music_assistant] Starting Music Assistant Server (f7cc6c6e90f94867a2fd247d1ff62d3c) version 2.0.0b147 - HA add-on: True - Safe mode: False
2024-05-08 15:32:09.162 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-05-08 15:32:09.650 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-05-08 15:32:10.722 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-05-08 15:32:10.723 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.1.104:8097
2024-05-08 15:32:10.731 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-05-08 15:32:10.948 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-05-08 15:32:10.949 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-05-08 15:32:10.949 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-05-08 15:32:10.949 INFO (MainThread) [music_assistant] Loaded music provider Music Assistant
2024-05-08 15:32:11.056 INFO (MainThread) [music_assistant.providers.filesystem_smb] Mounting //192.168.1.20/Public/Musica to /tmp/filesystem_smb--TLdBqVSd
2024-05-08 15:32:11.059 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2024-05-08 15:32:11.072 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-08 15:32:11.505 INFO (MainThread) [music_assistant] Loaded music provider Filesystem (remote share)
2024-05-08 15:32:11.951 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-05-08 15:32:12.155 INFO (MainThread) [music_assistant.players] Player registered: media_player.google_home_soggiorno/Google Home
2024-05-08 15:32:12.156 INFO (MainThread) [music_assistant.players] Player registered: media_player.tv_soggiorno_chromecast/TV Soggiorno - Chromecast
2024-05-08 15:32:12.156 INFO (MainThread) [music_assistant.players] Player registered: media_player.tv_soggiorno_cast/TV Soggiorno - Cast
2024-05-08 15:32:12.157 INFO (MainThread) [music_assistant.players] Player registered: media_player.tv_camera_alessio_cast/TV Samsung Alessio - Cast
2024-05-08 15:32:13.289 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Canzoni di Natale/Faith/Kenny G - Let It Snow, Let It Snow, Let It Snow.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 15:32:13.696 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Canzoni di Natale/Kenny G - Have Yourself A Merry Little Christmas.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 15:32:14.128 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Canzoni di Natale/Michael Buble - Let It Snow.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 15:32:15.674 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Musica Bambini/Margherita Vicario - Cocco Drilli.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 15:32:22.325 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2024-05-08 15:38:15.109 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Musica Italiana/A-E/Eros Ramazzotti/Eros Ramazzotti - Un Emozione Per Sempre.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 15:44:11.146 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_pause: Resume queue requested but queue media_player.tv_soggiorno_chromecast is empty
2024-05-08 15:44:15.538 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_pause: Resume queue requested but queue media_player.tv_soggiorno_chromecast is empty
2024-05-08 18:32:09.670 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-08 18:32:10.520 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Canzoni di Natale/Kenny G - Let It Snow.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 18:32:10.898 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Canzoni di Natale/Miracles - The Holiday Album/Kenny G - Have Yourself A Merry Little Christmas.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 18:32:14.735 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Musica Italiana/R-Z/Varie Italiane/Margherita Vicario - Cocco Drilli.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 18:32:17.163 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Musica Straniera/L-P/Michael BublÃ¨/Michael Buble - Let It Snow.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 18:32:19.815 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed
2024-05-08 18:49:29.323 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 545, in stop
    await self.mass.players.cmd_stop(queue_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 84, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 170, in cmd_stop
    await player_provider.cmd_stop(player_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/__init__.py", line 201, in cmd_stop
    await self.hass_prov.hass.call_service(
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 173, in call_service
    return await self.send_command("call_service", **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 214, in send_command
    return await future
           ^^^^^^^^^^^^
hass_client.exceptions.FailedCommand: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:51:02.915 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_pause: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:51:09.655 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_pause: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:51:26.231 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/power: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:51:42.813 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 545, in stop
    await self.mass.players.cmd_stop(queue_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 84, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 170, in cmd_stop
    await player_provider.cmd_stop(player_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/__init__.py", line 201, in cmd_stop
    await self.hass_prov.hass.call_service(
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 173, in call_service
    return await self.send_command("call_service", **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 214, in send_command
    return await future
           ^^^^^^^^^^^^
hass_client.exceptions.FailedCommand: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:52:02.567 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 545, in stop
    await self.mass.players.cmd_stop(queue_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 84, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 170, in cmd_stop
    await player_provider.cmd_stop(player_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/__init__.py", line 201, in cmd_stop
    await self.hass_prov.hass.call_service(
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 173, in call_service
    return await self.send_command("call_service", **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 214, in send_command
    return await future
           ^^^^^^^^^^^^
hass_client.exceptions.FailedCommand: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:52:09.855 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 545, in stop
    await self.mass.players.cmd_stop(queue_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 84, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 170, in cmd_stop
    await player_provider.cmd_stop(player_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/__init__.py", line 201, in cmd_stop
    await self.hass_prov.hass.call_service(
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 173, in call_service
    return await self.send_command("call_service", **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 214, in send_command
    return await future
           ^^^^^^^^^^^^
hass_client.exceptions.FailedCommand: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:52:12.492 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_pause: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:52:13.972 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_pause: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 18:52:19.631 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 545, in stop
    await self.mass.players.cmd_stop(queue_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 84, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/players.py", line 170, in cmd_stop
    await player_provider.cmd_stop(player_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/hass_players/__init__.py", line 201, in cmd_stop
    await self.hass_prov.hass.call_service(
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 173, in call_service
    return await self.send_command("call_service", **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 214, in send_command
    return await future
           ^^^^^^^^^^^^
hass_client.exceptions.FailedCommand: Command failed: Entity media_player.skyq_ita0498312015d does not support this service.
2024-05-08 19:23:52.328 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Musica Straniera/Q-Z/Spice Girls/Spice Girls - Say You Will Be There.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 19:26:15.200 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue TV Soggiorno - Chromecast - crossfade: False
2024-05-08 19:38:14.264 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Musica Italiana/A-E/Andrea Guerra/Andrea Guerra - Yo so Maria - Maria de Buenos Aires.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 19:58:03.013 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-05-08 19:58:52.896 INFO (MainThread) [music_assistant.players] Player registered: ugp_y8rzqtla/All Players
2024-05-08 20:37:34.942 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-05-08 20:37:35.014 INFO (MainThread) [music_assistant.players] Player registered: 3355f007-e263-d448-d94a-519091bf3a05/Google Home Soggiorno
2024-05-08 20:39:49.482 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/power: Resume queue requested but queue 3355f007-e263-d448-d94a-519091bf3a05 is empty
2024-05-08 20:41:04.689 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/power: Resume queue requested but queue 3355f007-e263-d448-d94a-519091bf3a05 is empty
2024-05-08 20:42:49.729 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-05-08 20:42:49.754 INFO (MainThread) [music_assistant.players] Player removed: Sky Q
2024-05-08 20:42:49.754 INFO (MainThread) [music_assistant.players] Player removed: Google Home
2024-05-08 20:42:49.755 INFO (MainThread) [music_assistant.players] Player removed: TV Soggiorno - Cast
2024-05-08 20:44:20.950 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Google Home Soggiorno - crossfade: True
2024-05-08 20:55:10.204 INFO (MainThread) [music_assistant.players] Player removed: Google Home Soggiorno
2024-05-08 20:55:10.205 INFO (MainThread) [music_assistant.players] Player removed: TV Soggiorno Chromecast
2024-05-08 20:55:32.623 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-05-08 20:55:32.645 INFO (MainThread) [music_assistant.players] Player registered: media_player.google_home_soggiorno/Google Home
2024-05-08 21:04:31.624 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue All Players - crossfade: False
2024-05-08 21:07:16.808 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue All Players
2024-05-08 21:32:09.674 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-08 21:32:11.042 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Canzoni di Natale/Faith/Kenny G - Let It Snow, Let It Snow, Let It Snow.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 21:32:11.333 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Canzoni di Natale/Kenny G - Have Yourself A Merry Little Christmas.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 21:32:11.625 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Canzoni di Natale/Michael Buble - Let It Snow.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 21:32:13.024 WARNING (MainThread) [music_assistant.providers.filesystem_smb] Musica Bambini/Margherita Vicario - Cocco Drilli.mp3 is missing ID3 tag [albumartist], using track artist(s) as fallback
2024-05-08 21:32:20.203 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (remote share) completed

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Yes this has been temporarily disabled.

also please follow the instructions in multiple places and attach the log instead of pasting it.
