### ISSUE TITLE
Error executing script. Unexpected error for call_service at pos 2: Field "disc_number" of type int in AlbumTrack has invalid value None

### ISSUE THREAD

**Issue by cooljimy84** [music-assistant/hass-music-assistant#2223]
### What version of Music Assistant has the issue?

2.0.0b147

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

when asking to play some music, like "play music from toy story" i get then error
`Error executing script. Unexpected error for call_service at pos 2: Field "disc_number" of type int in AlbumTrack has invalid value None`

### How to reproduce

Follow the MASS setup for year of the voice setup, so you can ask to play music.

### Music Providers

local & Deezer

### Player Providers

sonos

### Full log output

[log.log](https://github.com/music-assistant/hass-music-assistant/files/15264095/log.log)

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Linux

**Comment by cooljimy84** [comment]
HASS logs

```
intent_script:
  PlayWhateverOnAreaEn:
    action:
      - service: conversation.process
        data:
          agent_id: 0b88ea95c0fc146d951c3ca7c5c59e0b
          text: "{{query}}"
        response_variable: response_from_ai
      - service: mass.play_media
        data: "{{response_from_ai.response.speech.plain.speech|from_json}}"
        target:
          area_id: "{{area}}"
    speech:
      text: "Playing {{query}} now"
```

custom sentences
```
language: "en"
intents:
  PlayWhateverOnAreaEn:
    data:
      - sentences:
          - (Play|Listen) {query} [in] [the] {area}
  cancelcommand:
    data:
      - sentences:
          - (cancel|nevermind|never mind) {query}
          - (cancel|nevermind|never mind)
  stopcommand:
    data:
      - sentences:
          - (stop|stop playback|stop playing) {query}
          - (stop|stop playback|stop playing)

lists:
  query:
    wildcard: true
```

```
2024-05-09 14:58:36.122 DEBUG (MainThread) [homeassistant.components.conversation] Processing: <music from toy story in>
2024-05-09 14:58:36.123 DEBUG (MainThread) [homeassistant.components.conversation.agent_manager] Processing in en: music from toy story in
2024-05-09 14:58:37.736 ERROR (MainThread) [homeassistant.helpers.script.intent_script_playwhateveronareaen] Intent Script PlayWhateverOnAreaEn: Error executing script. Unexpected error for call_service at pos 2: Field "disc_number" of type int in AlbumTrack has invalid value None
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/mass/media_player.py", line 454, in _async_play_media_advanced
    await self.mass.player_queues.play_media(
  File "/srv/homeassistant/lib/python3.12/site-packages/music_assistant/client/player_queues.py", line 208, in play_media
    await self.client.send_command(
  File "/srv/homeassistant/lib/python3.12/site-packages/music_assistant/client/client.py", line 254, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.MusicAssistantError: Field "disc_number" of type int in AlbumTrack has invalid value None
2024-05-09 14:58:37.739 ERROR (MainThread) [homeassistant.components.conversation.default_agent] Unexpected intent error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/intent.py", line 116, in async_handle
    result = await handler.async_handle(intent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/intent_script/__init__.py", line 177, in async_handle
    action_res = await action.async_run(slots, intent_obj.context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 1731, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 451, in async_run
    await self._async_step(log_exceptions=False)
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 503, in _async_step
    self._handle_exception(
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 533, in _handle_exception
    raise exception
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/mass/media_player.py", line 454, in _async_play_media_advanced
    await self.mass.player_queues.play_media(
  File "/srv/homeassistant/lib/python3.12/site-packages/music_assistant/client/player_queues.py", line 208, in play_media
    await self.client.send_command(
  File "/srv/homeassistant/lib/python3.12/site-packages/music_assistant/client/client.py", line 254, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.MusicAssistantError: Field "disc_number" of type int in AlbumTrack has invalid value None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/conversation/default_agent.py", line 348, in async_process
    intent_response = await intent.async_handle(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/intent.py", line 123, in async_handle
    raise IntentUnexpectedError(f"Error handling {intent_type}") from err
homeassistant.helpers.intent.IntentUnexpectedError: Error handling PlayWhateverOnAreaEn
```

**Comment by erkr** [comment]
@cooljimy84 you provided info already. Thanks. But I think, for the devs, it is useful to have the value of the response_variable as well

**Comment by marcelveldt** [comment]
I think this one is fixed already - there was a small bug in Deezer but it should be fixed in the 2.0 release

**Comment by cooljimy84** [comment]
Awesome news ! I'll keep my eye open for that.
Beautifully work on this project people !

**Comment by OzGav** [comment]
Beta 2.0.0 is released. Please confirm if this is fixed.

**Comment by cooljimy84** [comment]
updated docker to 2.0.0b148
and HACS to 2024.5.1

and it works fine as expected now. thanks for that speedyness.
