### ISSUE TITLE
Error seting up provider - Home Assistant Mediaplayers

### ISSUE THREAD

**Issue by bacco007** [music-assistant/hass-music-assistant#2254]
### What version of Music Assistant has the issue?

2.0.2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Pressing Save to add the HA Media Player provider I get the following error

```
players has unexpected type: <class 'NoneType'>
```

### How to reproduce

1. Go to Settings
2. Select Add Player Provider
3. Select Home Assistant Mediaplayers
4. Select Save

### Music Providers

N/A

### Player Providers

HA Mediaplayers doesnt work
Sonos, Airplay and Chromecast work

### Full log output

2024-05-12 09:53:03.492 INFO (MainThread) [music_assistant] Starting Music Assistant Server (ebc4420adf744b8daab35b1e57daf191) version 2.0.2 - HA add-on: True - Safe mode: False
2024-05-12 09:53:03.496 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-05-12 09:53:03.538 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-05-12 09:53:03.631 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-05-12 09:53:03.631 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.1.90:8097
2024-05-12 09:53:03.636 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-05-12 09:53:03.787 INFO (MainThread) [music_assistant] Loaded music provider Music Assistant
2024-05-12 09:53:03.787 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-05-12 09:53:03.787 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-05-12 09:53:03.787 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-05-12 09:53:03.787 INFO (MainThread) [music_assistant] Loaded music provider Tune-In Radio
2024-05-12 09:53:03.813 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-05-12 09:53:03.819 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2024-05-12 09:53:03.909 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-12 09:53:04.168 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-05-12 09:53:04.171 INFO (MainThread) [music_assistant.players] Player registered: ap48a6b88863cc/office
2024-05-12 09:53:04.173 INFO (MainThread) [music_assistant.players] Player registered: ap38420b9123c8/bedroom
2024-05-12 09:53:04.174 INFO (MainThread) [music_assistant.players] Player registered: ap0499b99e2b2d/bedroom (2)
2024-05-12 09:53:04.474 INFO (MainThread) [music_assistant.players] Player registered: RINCON_48A6B88863CC01400/Office
2024-05-12 09:53:04.476 WARNING (MainThread) [soco.events_asyncio] Could not bind to 192.168.1.90:1400: [Errno 98] Address already in use
2024-05-12 09:53:04.580 INFO (MainThread) [music_assistant.players] Player registered: RINCON_38420B9123C801400/Bedroom
2024-05-12 09:53:05.001 INFO (MainThread) [music_assistant] Loaded music provider RadioBrowser
2024-05-12 09:53:05.088 INFO (MainThread) [music_assistant.players] Player registered: ap58d34916a4d3/Bedroom
2024-05-12 09:53:05.162 INFO (MainThread) [music_assistant.players] Player registered: apa4cf99c7a8cb/Office HomePod
2024-05-12 09:53:06.091 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as 1230918973
2024-05-12 09:53:06.092 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-05-12 09:53:09.384 WARNING (MainThread) [music_assistant.providers.tunein] Unable to retrieve info for http://media.on.net/radio/playlist.m3u: Connection timed out
2024-05-12 09:53:09.402 INFO (MainThread) [music_assistant.music] Sync task for Tune-In Radio completed
2024-05-12 09:53:09.402 INFO (MainThread) [music_assistant.music] Sync task for RadioBrowser completed
2024-05-12 09:53:18.481 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-12 10:18:46.838 INFO (MainThread) [music_assistant.players] Player registered: ap9c760e31ae47/tbMacStudio
2024-05-12 10:23:14.158 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-05-12 10:23:14.829 INFO (MainThread) [music_assistant.players] Player registered: 683ce7c5-f8e2-5096-ec60-af7dce786292/tbPixelTablet
2024-05-12 10:23:15.261 INFO (MainThread) [music_assistant.players] Player registered: 5dec7c03-ac6c-e9a2-4387-6eb2aee2bdfc/SHIELD
2024-05-12 10:23:22.196 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 318, in _process_messages
    raise ConnectionFailed
hass_client.exceptions.ConnectionFailed: Connection failed.
2024-05-12 10:23:23.626 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: players has unexpected type: <class 'NoneType'>
2024-05-12 10:23:31.990 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 318, in _process_messages
    raise ConnectionFailed
hass_client.exceptions.ConnectionFailed: Connection failed.
2024-05-12 10:24:19.748 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 318, in _process_messages
    raise ConnectionFailed
hass_client.exceptions.ConnectionFailed: Connection failed.
2024-05-12 10:26:27.394 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 318, in _process_messages
    raise ConnectionFailed
hass_client.exceptions.ConnectionFailed: Connection failed.
2024-05-12 10:27:40.465 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 318, in _process_messages
    raise ConnectionFailed
hass_client.exceptions.ConnectionFailed: Connection failed.
2024-05-12 10:27:41.575 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: players has unexpected type: <class 'NoneType'>

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Are you saying you can't add ANY HA media player? If not then list which players work and which don't

**Comment by disconn3ct** [comment]
No players at all.

![Screenshot_20240512_084403](https://github.com/music-assistant/hass-music-assistant/assets/397465/9533049f-f769-486d-915a-5b9073f86f23)

**Comment by OzGav** [comment]
It looks like MA has discovered some other players. Do they work ok? 

Is the plugin provider installed ok?
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/ee273060-5d2e-49da-88eb-57f0774716f9)

**Comment by disconn3ct** [comment]
Cast players are working, and it did install the provider.

**Comment by bacco007** [comment]
> Are you saying you can't add ANY HA media player? If not then list which players work and which don't

I did under Player Providers - Sonos, Chromecast and Airplay all work

Home Assistant plugin provider is also installed

**Comment by cmsimike** [comment]
I'm also getting `hass_client.exceptions.ConnectionFailed: Connection failed.` and have not been able to populate the media player list using the Home Assistant media players provider. On 2.0.0 and 2.0.2.

**Comment by LoricOSC** [comment]
Make sure to enable the web server in Settings->Core->Web Server (frontend and api)

**Comment by OzGav** [comment]
You do not *need* to enable that port. It is disabled by default for security reasons

**Comment by cmsimike** [comment]
Didn't seem to matter if it's enabled for me or not, even trying to sync after it being enabled. I've disabled the port for the time being.

**Comment by OzGav** [comment]
Yeah that setting has nothing to do with this report. So confirm you can see the list of HA players that are available to select but when you select one you get that error?

**Comment by bacco007** [comment]
I don't see a list of HA players

**Comment by OzGav** [comment]
For reference this is what you should see. Maybe you don’t have any suitable HA players? 
![IMG_1248](https://github.com/music-assistant/hass-music-assistant/assets/19848947/a045d64e-9c31-48f6-9287-7faaaffcaba3)

**Comment by OzGav** [comment]
Also you have listed the wrong integration version in your report. Look in HACS and report the version you are running. It should be 2024.5.0

**Comment by bacco007** [comment]
> Also you have listed the wrong integration version in your report

Well that's what is getting reported in integration setup

![image](https://github.com/music-assistant/hass-music-assistant/assets/6810572/855323a5-2842-4b26-aabe-ef63d1e9852f)

> For reference this is what you should see

I only see this, pressing save is what generates the error in my original report

![image](https://github.com/music-assistant/hass-music-assistant/assets/6810572/3b5375f2-a602-4f2e-93bc-979446c6007f)

**Comment by OzGav** [comment]
@bacco007 clear your browser cache. If that doesn’t work clear the MA cache (MA SETTINGS>> CORE>> CACHE CONTROLLER)

**Comment by OzGav** [comment]
@cmsimike you have a different issue. Please open your own report

**Comment by bacco007** [comment]
> clear your browser cache. If that doesn’t work clear the MA cache

Done - still get same error

**Comment by OzGav** [comment]
Have you restarted MA? Try a full host reboot?

**Comment by bacco007** [comment]
Done both (separately), no change either time

**Comment by OzGav** [comment]
Ok will have to wait for Marcel as I don’t know why that page isn’t rendering properly.

**Comment by indykoning** [comment]
I've got the exact same issue where no media players are rendered.
This is most certainly related to
> 2024-05-13 22:31:00.016 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 318, in _process_messages
    raise ConnectionFailed
hass_client.exceptions.ConnectionFailed: Connection failed.

As this happens right before the nonexistent player list shows.
I'm guessing it's incorrect connection details to the supervisor api

**Comment by collateral87** [comment]
> 2024-05-13 22:31:00.016 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
> Traceback (most recent call last):
> File "/usr/local/lib/python3.12/site-packages/hass_client/client.py", line 318, in _process_messages
> raise ConnectionFailed
> hass_client.exceptions.ConnectionFailed: Connection failed.

I dont have the issue, that i cant see window, but i have this in my logs (ConnectionFailed) and cant setup any HA-mediaplayer. I can select it, but it does not appear in my playerlist.
I have server version [2.1.0 BETA 1] and integration version [2024.5.1].

**Comment by OzGav** [comment]
@collateral87 if you don’t have the same issue as this then raise a new one.

**Comment by collateral87** [comment]
> @collateral87 if you don’t have the same issue as this then raise a new one. 

Ok, i thinked this is the right place, because the error message is exactly the same as the autor has.

**Comment by OzGav** [comment]
But this whole discussion is about how the OP doesn’t see anything in the media player list which you say you can see?

**Comment by OzGav** [comment]
If you are running the beta please try with the latest version of the server as well as use the current beta of the integration 2024.7.1b0

**Comment by OzGav** [comment]
Please try with beta 14 and try clearing the cache MA SETTINGS>>CORE>>CACHE CONTROLLER>>CONFIGURE>>CLEAR CACHE

**Comment by OzGav** [comment]
We will close this soon due to no follow up. (rc2 is the latest to try)
