### ISSUE TITLE
ClientConnectorError: Cannot connect to host musicbrainz.org:80 ssl:default [Network is unreachable]

### ISSUE THREAD

**Issue by MankiniChykan** [music-assistant/hass-music-assistant#2260]
### What version of Music Assistant has the issue?

 2.0.2 

### What version of the Home Assistant Integration have you got installed?

 2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Error in logs

### How to reproduce

Error in Logs in persistent

### Music Providers

N/A

### Player Providers

N/A

### Full log output

2024-05-12 19:35:39.686 INFO (MainThread) [music_assistant] Starting Music Assistant Server (fcfc08ea18b34a91802397c804b09602) version 2.0.2 - HA add-on: True - Safe mode: False
2024-05-12 19:35:39.703 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-05-12 19:35:39.974 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-05-12 19:35:41.606 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-05-12 19:35:41.607 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.1.58:8097
2024-05-12 19:35:41.614 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.1.58:8095
2024-05-12 19:35:42.478 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-05-12 19:35:42.480 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-05-12 19:35:42.487 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-05-12 19:35:42.488 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-05-12 19:35:42.570 INFO (MainThread) [music_assistant] Loaded music provider Music Assistant
2024-05-12 19:35:42.576 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-05-12 19:35:42.580 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-05-12 19:35:42.664 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-05-12 19:35:42.686 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2024-05-12 19:35:42.692 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2024-05-12 19:35:42.736 INFO (MainThread) [music_assistant.players] Player registered: 1a114bbb-3a7e-734d-eadc-8c7abc6ada1e/SHIELD
2024-05-12 19:35:42.804 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-05-12 19:35:42.845 INFO (MainThread) [music_assistant.players] Player registered: 16d666ff-19d9-467c-9e11-3727440d081e/Speaker Group
2024-05-12 19:35:43.035 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-05-12 19:35:44.499 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
2024-05-12 19:35:44.649 INFO (MainThread) [music_assistant.providers.spotify] Successfully logged in to Spotify as alli-6
2024-05-12 19:35:44.649 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-05-12 19:36:15.672 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
2024-05-12 19:36:28.140 INFO (MainThread) [music_assistant.music] Sync task for Spotify completed
2024-05-12 19:36:42.981 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 659, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 221, in scan_artist_metadata
    await self.mass.music.artists.get(artist.item_id, artist.provider, lazy=False)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 309, in get
    await add_task
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 97, in add_item_to_library
    await self.mass.metadata.get_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 357, in get_metadata
    await self.get_artist_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 233, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 392, in get_artist_mbid
    if mbid := await musicbrainz.get_musicbrainz_artist_id(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 226, in get_musicbrainz_artist_id
    if mb_artist := await self.get_artist_details_by_track(artist.name, ref_track):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 418, in get_artist_details_by_track
    result = await self.get_recording_details(ref_track.mbid, isrc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 339, in get_recording_details
    if (result := await self.get_data(f"isrc/{isrc}")) and result.get("recordings"):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/cache.py", line 259, in wrapped
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/throttle_retry.py", line 71, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 439, in get_data
    async with (
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host musicbrainz.org:80 ssl:default [Network is unreachable]
2024-05-12 19:36:45.586 INFO (MainThread) [music_assistant.players] Player registered: 21bd5d81-3cdf-4f2f-834f-11888d0407dc/Display Group

### Additional information

- The player still plays music
- Currently have an error in home assistant **- host_internet: false**
- I currently have. **ha jobs options --ignore-conditions internet_host** active to install updates
- I do have the MA Web Server (frontend and api) **exposed on port 8095**

My host internet false error occurred around the same time I activated the MA exposed port 8095 (most likely unrelated)

This is running on a HA Blue ODROID.

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
The error seems pretty clear. There is no Internet connection. Why do you think this is not the case?

**Comment by MankiniChykan** [comment]
Everything else is working. Music plays etc.

**Comment by OzGav** [comment]
It’s difficult to say from here but the error is NETWORK IS UNREACHABLE which is raised at the OS level. Then you mentioned something about HA also having internet errors appearing. Given you are the only person to have reported something like this then it is likely a configuration issue at your end.

**Comment by OzGav** [comment]
We will close this soon unless you can provide some more info that suggests this is a MA problem.
