### ISSUE TITLE
snapclients need  tlc before be used in the addon webclient

### ISSUE THREAD

**Issue by Bram-diederik** [music-assistant/hass-music-assistant#2263]
### What version of Music Assistant has the issue?

2.0.2

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I cant directly use snapclients added to the addon. I need to play some using using the integration 1st. 

### How to reproduce

add a (existing) snapserver. 
players are shown in the addon.
select music select the snapcast speaker. (no speaker selected)
Unable to play music

find the snapcast player in the mass integration. play browse to some music play it.

Now you can use the player in the addon webclient

### Music Providers

spotify,local

### Player Providers

snapcast

### Full log output

2024-05-12 13:10:29.181 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:30.184 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:31.190 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:32.196 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:33.202 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:34.204 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:34.918 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 97, in add_item_to_library
    await self.mass.metadata.get_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 357, in get_metadata
    await self.get_artist_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 233, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 371, in get_artist_mbid
    ref_albums = await self.mass.music.artists.albums(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 127, in albums
    full_artist = await self.get(item_id, provider_instance_id_or_domain)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 249, in get
    library_item = await self.get_library_item_by_prov_id(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 404, in get_library_item_by_prov_id
    return await self.get_library_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 393, in get_library_item
    raise MediaNotFoundError(msg)
music_assistant.common.models.errors.MediaNotFoundError: artist not found in library: 359
2024-05-12 13:10:34.975 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 97, in add_item_to_library
    await self.mass.metadata.get_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 357, in get_metadata
    await self.get_artist_metadata(item)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 233, in get_artist_metadata
    artist.mbid = await self.get_artist_mbid(artist)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 371, in get_artist_mbid
    ref_albums = await self.mass.music.artists.albums(artist.item_id, artist.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 127, in albums
    full_artist = await self.get(item_id, provider_instance_id_or_domain)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 249, in get
    library_item = await self.get_library_item_by_prov_id(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 404, in get_library_item_by_prov_id
    return await self.get_library_item(item_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 393, in get_library_item
    raise MediaNotFoundError(msg)
music_assistant.common.models.errors.MediaNotFoundError: artist not found in library: 359
2024-05-12 13:10:35.208 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:36.211 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:37.212 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:38.216 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:39.220 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:40.224 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:41.228 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:42.237 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:43.243 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:10:44.249 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:22.295 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:23.300 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:24.304 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:25.308 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:26.311 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:27.315 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:28.318 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:29.321 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:30.325 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:31.336 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:32.338 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:33.340 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:34.344 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:35.348 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:36.350 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:37.352 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:38.961 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:38.962 ERROR (MainThread) [music_assistant] Error doing task: Unhandled exception in client_connected_cb
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/airplay/__init__.py", line 982, in _handle_dacp_request
    await writer.drain()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
2024-05-12 13:14:39.888 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:40.892 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:41.895 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 597655DEF225@Snapcast._raop._tcp.local.: /ctrl-int/1/getproperty?properties=dmcp.volume
2024-05-12 13:14:42.897 INFO (MainThread) [music_assistant.providers.airplay] Unknown DACP request for 

### Additional information

https://github.com/music-assistant/hass-music-assistant/assets/53519837/d496a4a0-1c9d-4449-b767-8326d6b446e8

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by Bram-diederik** [comment]
[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15286141/log.txt)

**Comment by janstadt** [comment]
I’m also seeing this with AirPlay. 

Unknown DACP request for D83ADDBACD16@Noahs Room._raop._tcp.local

**Comment by SantiagoSotoC** [comment]
@Bram-diederik Does this keep happening to you? I never experienced it
