### ISSUE TITLE
HomePod: FileNotFoundError: Image not found

### ISSUE THREAD

**Issue by Mariusthvdb** [music-assistant/hass-music-assistant#244]
getting this error on an image, while the image url itself is correct

```
2022-05-25 15:09:12 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1086, in get
    data, content_type = await player.async_get_media_image()
  File "/config/custom_components/mass/media_player.py", line 271, in async_get_media_image
    img_data = await self.mass.metadata.get_thumbnail(self.media_image_url)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/__init__.py", line 235, in get_thumbnail
    thumbnail = await create_thumbnail(self.mass, path, size)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/images.py", line 37, in create_thumbnail
    raise FileNotFoundError(f"Image not found: {path}")
FileNotFoundError: Image not found: /api/media_player_proxy/media_player.homepod_keuken?token=d9eb6303redactedc65d2ade60&cache=https://is5-ssl.mzstatic.com/image/thumb/Podcasts126/v4/85/22/10/852210ed-3653-93d5-fd68-ddfaa3bb7268/mza_15656445976366504695.jpg/600x600bb.jpg
```

checking https://is5-ssl.mzstatic.com/image/thumb/Podcasts126/v4/85/22/10/852210ed-3653-93d5-fd68-ddfaa3bb7268/mza_15656445976366504695.jpg/600x600bb.jpg reveals the NOS podcast icon. (Which I dont have a clue where this comes from, because I wasnt listening to it at all....)

Still the media-control card shows it:

<img width="510" alt="Schermafbeelding 2022-05-25 om 15 40 06" src="https://user-images.githubusercontent.com/33354141/170276344-5851eb3d-5ee3-4842-b4ce-832eb8c74b91.png">

and when playing plays a music stream of the music files on my iPhone  instead.

Also causing huge loads of inspector trouble, with on the core HA media_player.homepod_keuken, as on the media_player.mass_homepod_keuken entity:

<img width="823" alt="Schermafbeelding 2022-05-25 om 15 40 29" src="https://user-images.githubusercontent.com/33354141/170277241-29f3baa5-a712-40c3-a03b-6ba5ad79b16d.png">

I do believe it also causes 127.0.0.1 bans I have been experiencing since I lastly installed Mass update .16

For now, Ive removed the HomePod from Mass, the device is too unstable to use in HA

**Comment by marcelveldt** [comment]
It is strange and I've seen it more often. The HA image proxy tries to use the MA image proxy which can not make "chocola" of the request. The image request should not end up on this endpoint at all. Weird... I will try to investigate and reproduce.

**Comment by Mariusthvdb** [comment]
thanks, meanwhile I posted in Frontend too, since it mentions the media-control-card: https://github.com/home-assistant/frontend/issues/12776

**Comment by marcelveldt** [comment]
should be fixed in beta4
