### ISSUE TITLE
1.1.17 Error after update

### ISSUE THREAD

**Issue by Firesphere** [music-assistant/hass-music-assistant#247]
I get the following error in the logs after updating:
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:105
Integration: Music Assistant (documentation, issues)
First occurred: 12:50:41 PM (1 occurrences)
Last logged: 12:50:41 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 112, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 105, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 81, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 45, in setup
    await self._migrate()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 221, in _migrate
    await db.execute(f"ALTER TABLE {TABLE_ALBUMS} DROP COLUMN artist;")
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 170, in execute
    return await connection.execute(query, values)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 295, in execute
    return await self._connection.execute(built_query)
  File "/usr/local/lib/python3.9/site-packages/databases/backends/sqlite.py", line 128, in execute
    await cursor.execute(query_str, args)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "DROP": syntax error
```

**Comment by Firesphere** [comment]
Given I've had not set up much yet, I solved it by deleting the db. I don't think that's a valid path forward for future updates though?

**Comment by Symbiot78** [comment]
same here.

**Comment by marcelveldt** [comment]
What a strange error. As if sqlite did not accept the query. I will try if I can reproduce that one.
Can you share some details about the platform you guys are running ?

**Comment by marcelveldt** [comment]
OK I found out that DROP column was introduced in sqlite 3.35.0 a year ago so the explanation is that Alpine (on which the Home Assistant image is based on) has an old version... I will provide a hotfix soon

**Comment by marcelveldt** [comment]
I've provided version 1.1.18 which prevents this issue from happening but if it already impacted you, there's no other way than to delete the music_assistant.db file in the config folder.
