### ISSUE TITLE
Error during start music from YouTube music

### ISSUE THREAD

**Issue by clpodes** [music-assistant/hass-music-assistant#2486]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

This all happens starting today.
I'm trying to listen to music from Yahoo music but it doesn't work anymore, meaning I always get an error which I report in the log.
I checked and no other device is running yahoo music.

### How to reproduce

Open music assistant and play music from Yahoo

### Music Providers

Yhaoo music

### Player Providers

Google cast

### Full log output

2024-06-15 15:45:05.839 DEBUG (MainThread) [music_assistant.providers.builtin] Start sync of playlist items.
2024-06-15 15:45:05.874 DEBUG (MainThread) [music_assistant.music.playlist] updated All favorited tracks in database: (id 1)
2024-06-15 15:45:05.906 DEBUG (MainThread) [music_assistant.music.playlist] updated Random Artist (from library) in database: (id 2)
2024-06-15 15:45:05.926 INFO (MainThread) [music_assistant.players] Player registered: 0fe9ab8e-d4ac-b81a-c4ca-c4f4b1e86b17/s01
2024-06-15 15:45:05.932 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-45) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={MDNSServiceInfo(name='Google-Cast-Group-2add34254e6c41c9a3da508c4e06de8b._googlecast._tcp.local.')}, uuid=UUID('2add3425-4e6c-41c9-a3da-508c4e06de8b'), model_name='Google Cast Group', friendly_name='All_auto', host='192.168.10.128', port=32090, cast_type='group', manufacturer='Google Inc.')
2024-06-15 15:45:05.965 DEBUG (Thread-6) [music_assistant.providers.chromecast] [s01] Cast device availability changed: CONNECTED
2024-06-15 15:45:05.967 DEBUG (MainThread) [music_assistant.music.playlist] updated Random Album (from library) in database: (id 3)
2024-06-15 15:45:06.020 DEBUG (MainThread) [music_assistant.music.playlist] updated 500 Random tracks (from library) in database: (id 4)
2024-06-15 15:45:06.050 INFO (MainThread) [music_assistant.players] Player registered: 2add3425-4e6c-41c9-a3da-508c4e06de8b/All_auto
2024-06-15 15:45:06.068 DEBUG (MainThread) [music_assistant.music.playlist] updated Recently played tracks in database: (id 5)
2024-06-15 15:45:06.081 DEBUG (Thread-7) [music_assistant.providers.chromecast] [All_auto] Cast device availability changed: CONNECTED
2024-06-15 15:45:06.093 DEBUG (MainThread) [music_assistant.providers.builtin] Start sync of radio items.
2024-06-15 15:45:06.113 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-06-15 15:45:06.115 DEBUG (MainThread) [music_assistant.music] Performing database cleanup...
2024-06-15 15:45:06.143 DEBUG (Thread-7) [music_assistant.providers.chromecast] s01 is added to multizone: 2add3425-4e6c-41c9-a3da-508c4e06de8b
2024-06-15 15:45:06.155 DEBUG (MainThread) [music_assistant.music] Database cleanup done
2024-06-15 15:45:06.439 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-45) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={MDNSServiceInfo(name='Nest-Audio-9acc708c80f8f550d1b391ba7c120db0._googlecast._tcp.local.')}, uuid=UUID('9acc708c-80f8-f550-d1b3-91ba7c120db0'), model_name='Nest Audio', friendly_name='s99', host='192.168.10.138', port=8009, cast_type='audio', manufacturer='Google Inc.')
2024-06-15 15:45:06.525 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
2024-06-15 15:45:06.528 DEBUG (MainThread) [music_assistant.providers.ytmusic] Start sync of artist items.
2024-06-15 15:45:06.548 INFO (MainThread) [music_assistant.players] Player registered: 9acc708c-80f8-f550-d1b3-91ba7c120db0/s99
2024-06-15 15:45:06.578 DEBUG (Thread-8) [music_assistant.providers.chromecast] [s99] Cast device availability changed: CONNECTED
2024-06-15 15:45:06.766 DEBUG (MainThread) [music_assistant.providers.ytmusic] Start sync of album items.
2024-06-15 15:45:06.984 DEBUG (MainThread) [music_assistant.providers.ytmusic] Start sync of track items.
2024-06-15 15:45:07.193 DEBUG (MainThread) [music_assistant.providers.ytmusic] Start sync of playlist items.
2024-06-15 15:45:07.452 DEBUG (MainThread) [music_assistant.music.playlist] updated Musica che ti piace (YouTube Music) in database: (id 6)
2024-06-15 15:45:07.488 DEBUG (MainThread) [music_assistant.music.playlist] updated Puntate per dopo in database: (id 7)
2024-06-15 15:45:07.506 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
2024-06-15 15:45:07.508 DEBUG (MainThread) [music_assistant.music] Performing database cleanup...
2024-06-15 15:45:07.531 DEBUG (MainThread) [music_assistant.music] Database cleanup done
2024-06-15 15:45:11.567 DEBUG (MainThread) [music_assistant.server.controllers.config] Saved data to persistent storage
2024-06-15 15:45:35.983 DEBUG (Thread-4) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={HostServiceInfo(host='192.168.10.128', port=8009), MDNSServiceInfo(name='Nest-Audio-0fe9ab8ed4acb81ac4cac4f4b1e86b17._googlecast._tcp.local.')}, uuid=UUID('0fe9ab8e-d4ac-b81a-c4ca-c4f4b1e86b17'), model_name='Nest Audio', friendly_name='s01', host='192.168.10.128', port=8009, cast_type='audio', manufacturer='Google Inc.')
2024-06-15 15:45:35.983 DEBUG (Thread-4) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={HostServiceInfo(host='192.168.10.128', port=32090), MDNSServiceInfo(name='Google-Cast-Group-2add34254e6c41c9a3da508c4e06de8b._googlecast._tcp.local.')}, uuid=UUID('2add3425-4e6c-41c9-a3da-508c4e06de8b'), model_name='Google Cast Group', friendly_name='All_auto', host='192.168.10.128', port=32090, cast_type='group', manufacturer='Google Inc.')
2024-06-15 15:45:36.177 DEBUG (Thread-4) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={HostServiceInfo(host='192.168.10.138', port=8009), MDNSServiceInfo(name='Nest-Audio-9acc708c80f8f550d1b391ba7c120db0._googlecast._tcp.local.')}, uuid=UUID('9acc708c-80f8-f550-d1b3-91ba7c120db0'), model_name='Nest Audio', friendly_name='s99', host='192.168.10.138', port=8009, cast_type='audio', manufacturer='Google Inc.')
2024-06-15 15:46:52.426 DEBUG (MainThread) [music_assistant.webserver] Handling command players/all
2024-06-15 15:46:52.515 DEBUG (MainThread) [music_assistant.webserver] Handling command player_queues/all
2024-06-15 15:46:52.623 DEBUG (MainThread) [music_assistant.webserver] Handling command providers/manifests
2024-06-15 15:46:52.715 DEBUG (MainThread) [music_assistant.webserver] Handling command providers
2024-06-15 15:46:52.829 DEBUG (MainThread) [music_assistant.webserver] Handling command music/synctasks
2024-06-15 15:46:52.833 DEBUG (MainThread) [music_assistant.webserver] Handling command music/artists/count
2024-06-15 15:46:52.913 DEBUG (MainThread) [music_assistant.webserver] Handling command music/albums/count
2024-06-15 15:46:52.982 DEBUG (MainThread) [music_assistant.webserver] Handling command music/playlists/count
2024-06-15 15:46:53.059 DEBUG (MainThread) [music_assistant.webserver] Handling command music/radios/count
2024-06-15 15:46:53.136 DEBUG (MainThread) [music_assistant.webserver] Handling command music/tracks/count
2024-06-15 15:46:53.208 DEBUG (MainThread) [music_assistant.webserver] Handling command music/recently_played_items
2024-06-15 15:46:53.286 DEBUG (MainThread) [music_assistant.webserver] Handling command music/artists/library_items
2024-06-15 15:46:53.360 DEBUG (MainThread) [music_assistant.webserver] Handling command music/albums/library_items
2024-06-15 15:46:53.439 DEBUG (MainThread) [music_assistant.webserver] Handling command music/playlists/library_items
2024-06-15 15:46:53.518 DEBUG (MainThread) [music_assistant.webserver] Handling command music/radios/library_items
2024-06-15 15:46:53.588 DEBUG (MainThread) [music_assistant.webserver] Handling command music/tracks/library_items
2024-06-15 15:47:05.272 DEBUG (MainThread) [music_assistant.webserver] Handling command players/cmd/power
2024-06-15 15:47:05.273 DEBUG (MainThread) [music_assistant.players] Handling command cmd_power for player s01
2024-06-15 15:47:05.273 DEBUG (ThreadPoolExecutor-0_22) [music_assistant.providers.chromecast] Launching App C35B0678.
2024-06-15 15:47:05.273 INFO (ThreadPoolExecutor-0_22) [pychromecast.controllers] Receiver:Launching app C35B0678
2024-06-15 15:47:06.244 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-45) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={HostServiceInfo(host='192.168.10.128', port=8009), MDNSServiceInfo(name='Nest-Audio-0fe9ab8ed4acb81ac4cac4f4b1e86b17._googlecast._tcp.local.')}, uuid=UUID('0fe9ab8e-d4ac-b81a-c4ca-c4f4b1e86b17'), model_name='Nest Audio', friendly_name='s01', host='192.168.10.128', port=8009, cast_type='audio', manufacturer='Google Inc.')
2024-06-15 15:47:06.338 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-45) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={HostServiceInfo(host='192.168.10.128', port=8009), MDNSServiceInfo(name='Nest-Audio-0fe9ab8ed4acb81ac4cac4f4b1e86b17._googlecast._tcp.local.')}, uuid=UUID('0fe9ab8e-d4ac-b81a-c4ca-c4f4b1e86b17'), model_name='Nest Audio', friendly_name='s01', host='192.168.10.128', port=8009, cast_type='audio', manufacturer='Google Inc.')
2024-06-15 15:47:44.521 DEBUG (MainThread) [music_assistant.webserver] Handling command player_queues/play_pause
2024-06-15 15:47:45.062 DEBUG (MainThread) [music_assistant.providers.ytmusic] Creating a new cipher
2024-06-15 15:47:46.186 DEBUG (MainThread) [music_assistant.providers.ytmusic] Deciphered URL HTTP status: 403
2024-06-15 15:47:46.187 DEBUG (MainThread) [music_assistant.providers.ytmusic] Invalid playback URL encountered. Retrying with new signature timestamp.
2024-06-15 15:47:47.292 DEBUG (MainThread) [music_assistant.providers.ytmusic] Creating a new cipher
2024-06-15 15:47:48.359 DEBUG (MainThread) [music_assistant.providers.ytmusic] Deciphered URL HTTP status: 403
2024-06-15 15:47:48.359 DEBUG (MainThread) [music_assistant.providers.ytmusic] Invalid playback URL encountered. Retrying with new signature timestamp.
2024-06-15 15:47:49.582 DEBUG (MainThread) [music_assistant.providers.ytmusic] Creating a new cipher
2024-06-15 15:47:50.581 WARNING (MainThread) [asyncio] Executing <TimerHandle when=7732.880141363 _set_result_unless_cancelled(<Future finis...events.py:449>, None) at /usr/local/lib/python3.12/asyncio/futures.py:311 created at /usr/local/lib/python3.12/asyncio/tasks.py:661> took 0.257 seconds
2024-06-15 15:47:50.648 DEBUG (MainThread) [music_assistant.providers.ytmusic] Deciphered URL HTTP status: 403
2024-06-15 15:47:50.649 DEBUG (MainThread) [music_assistant.providers.ytmusic] Invalid playback URL encountered. Retrying with new signature timestamp.
2024-06-15 15:47:51.650 DEBUG (MainThread) [music_assistant.providers.ytmusic] Creating a new cipher
2024-06-15 15:47:52.697 DEBUG (MainThread) [music_assistant.providers.ytmusic] Deciphered URL HTTP status: 403
2024-06-15 15:47:52.697 DEBUG (MainThread) [music_assistant.providers.ytmusic] Invalid playback URL encountered. Retrying with new signature timestamp.
2024-06-15 15:47:53.977 DEBUG (MainThread) [music_assistant.providers.ytmusic] Creating a new cipher
2024-06-15 15:47:54.963 WARNING (MainThread) [asyncio] Executing <TimerHandle when=7737.178509525 AsyncEngine._async_cache_cleanup() created at /usr/local/lib/python3.12/site-packages/zeroconf/_engine.py:126> took 0.346 seconds
2024-06-15 15:47:55.033 DEBUG (MainThread) [music_assistant.providers.ytmusic] Deciphered URL HTTP status: 403
2024-06-15 15:47:55.034 DEBUG (MainThread) [music_assistant.providers.ytmusic] Invalid playback URL encountered. Retrying with new signature timestamp.
2024-06-15 15:47:56.299 DEBUG (MainThread) [music_assistant.providers.ytmusic] Creating a new cipher
2024-06-15 15:47:57.269 WARNING (MainThread) [asyncio] Executing <TimerHandle when=7739.572115883 _set_result_unless_cancelled(<Future finis...events.py:449>, None) at /usr/local/lib/python3.12/asyncio/futures.py:311 created at /usr/local/lib/python3.12/asyncio/tasks.py:661> took 0.106 seconds
2024-06-15 15:47:57.343 DEBUG (MainThread) [music_assistant.providers.ytmusic] Deciphered URL HTTP status: 403
2024-06-15 15:47:57.344 WARNING (MainThread) [music_assistant.providers.ytmusic] Could not resolve a valid URL for item '-PU9GA9VLTw'. Are you playing music on another device using the same account?
2024-06-15 15:47:57.344 WARNING (MainThread) [music_assistant.audio] Could not resolve a valid URL for item '-PU9GA9VLTw'.
2024-06-15 15:47:57.344 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id=18, command='player_queues/play_pause', args={'queue_id': '0fe9ab8e-d4ac-b81a-c4ca-c4f4b1e86b17'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/webserver.py", line 351, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 594, in play_pause
    await self.play(queue_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 564, in play
    await self.resume(queue_id)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 694, in resume
    await self.play_index(queue_id, resume_item.queue_item_id, resume_pos, fade_in)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 726, in play_index
    queue_item.streamdetails = await get_stream_details(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 374, in get_stream_details
    raise MediaNotFoundError(f"Unable to retrieve streamdetails for {queue_item}")
music_assistant.common.models.errors.MediaNotFoundError: Unable to retrieve streamdetails for QueueItem(queue_id='0fe9ab8e-d4ac-b81a-c4ca-c4f4b1e86b17', queue_item_id='8aaa11a681004cb1929d53152b2fa6d5', name='Relaxing Piano Life - Coffee Shop Music - Relax Jazz Cafe Guitar (Instrumental Background)', duration=3600, sort_index=1, streamdetails=None, media_item=Track(item_id='-PU9GA9VLTw', provider='ytmusic', name='Coffee Shop Music - Relax Jazz Cafe Guitar (Instrumental Background)', version='', sort_name='coffee shop music - relax jazz cafe guitar (instrumental background)', uri='ytmusic://track/-PU9GA9VLTw', external_ids=set(), media_type=<MediaType.TRACK: 'track'>, provider_mappings={ProviderMapping(item_id='-PU9GA9VLTw', provider_domain='ytmusic', provider_instance='ytmusic--SKYBjPxF', available=False, audio_format=AudioFormat(content_type=<ContentType.M4A: 'm4a'>, sample_rate=44100, bit_depth=16, channels=2, output_format_str='m4a', bit_rate=320), url=None, details=None)}, metadata=MediaItemMetadata(description=None, review=None, explicit=None, images=[MediaItemImage(type=<ImageType.LANDSCAPE: 'landscape'>, path='https://i.ytimg.com/vi/-PU9GA9VLTw/maxresdefault.jpg', provider='ytmusic--SKYBjPxF', remotely_accessible=True)], genres=None, mood=None, style=None, copyright=None, lyrics=None, label=None, links=None, chapters=None, performers=None, preview=None, popularity=None, cache_checksum=None, last_refresh=None), favorite=False, position=None, duration=3600, artists=[ItemMapping(item_id='UCuJIQ2e3oMVKycaZQhAXd4A', provider='ytmusic', name='Relaxing Piano Life', version='', sort_name='relaxing piano life', uri='ytmusic://artist/UCuJIQ2e3oMVKycaZQhAXd4A', external_ids=set(), media_type=<MediaType.ARTIST: 'artist'>, available=True, image=MediaItemImage(type=<ImageType.THUMB: 'thumb'>, path='https://lh3.googleusercontent.com/dEtg7CWJmSgGTtRqDn6brW4Ld74oUCdcUQkHjDjMGzdMac0y9_YUqK7dmcLodWq03VH0RR3gBVFsPN0=w600-h600-p', provider='ytmusic--SKYBjPxF', remotely_accessible=True))], album=None, disc_number=None, track_number=None), image=None, index=0)

### Additional information

Core 2024.6.2
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240610.0

### What version of Home Assistant Core are your running

2024.6.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Windows

**Comment by OzGav** [comment]
There is no Yahoo music provider?

**Comment by clpodes** [comment]
Sorry for my mistake, it's my first time reporting a problem with Music Assistant / home assistant
If you think I have made a serious mistake, please delete my report, even if the problem is still present.

**Comment by OzGav** [comment]
There is no Yahoo music provider. Did you mean YouTube?

**Comment by clpodes** [comment]
Yes, sorry, YUTUBE Music

my brain is really tired :)

**Comment by marcelveldt** [comment]
This is authentication issues. Are you listening to music already on this account ?
Note that YTM only accepts one stream at the same time.

**Comment by clpodes** [comment]
I had read it, but I DO NOT have any active device with this account

**Comment by clpodes** [comment]
I also tried to create a new account, but even with this new one the problem appears the same
See Attachment
[MASS_log.txt](https://github.com/user-attachments/files/15848240/MASS_log.txt)

**Comment by OzGav** [comment]
Is this a paid account?

**Comment by clpodes** [comment]
No but until last night it worked.
I also tried switching accounts.

**Comment by marcelveldt** [comment]
> No but until last night it worked. I also tried switching accounts.

It is clearly stated in the documentation that you need a PAID / PREMIUM account. 
We do not support free accounts

**Comment by clpodes** [comment]
OK, I'll create paid accounts and re-testing
Grazie

**Comment by clpodes** [comment]
Hi, I activated a paid account, but it keeps giving me an error
I'll put the log
[MASS_log1.txt](https://github.com/user-attachments/files/15848710/MASS_log1.txt)

**Comment by OzGav** [comment]
It has been reported elsewhere that there is something broken with YouTube music at the moment.
