### ISSUE TITLE
Setting up entry Music Assistant for mass ERROR

### ISSUE THREAD

**Issue by Krzysztonek** [music-assistant/hass-music-assistant#249]
Hi,
After last update to 1.1.18 I'm not able to initiate the Music Assistant. Please, see the below logs:

```
Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:105
Integration: Music Assistant (documentation, issues)
First occurred: 20:23:58 (1 occurrences)
Last logged: 20:23:58

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 112, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 105, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 81, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 45, in setup
    await self._migrate()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 216, in _migrate
    await db.execute(f"ALTER TABLE {TABLE_ALBUMS} ADD artists json;")
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 170, in execute
    return await connection.execute(query, values)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 295, in execute
    return await self._connection.execute(built_query)
  File "/usr/local/lib/python3.9/site-packages/databases/backends/sqlite.py", line 128, in execute
    await cursor.execute(query_str, args)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: duplicate column name: artists`
```

Please advise.

**Comment by marcelveldt** [comment]
Just delete the music_assistant.db file in your configuration folder and reload the integration.

**Comment by Krzysztonek** [comment]
It helped, indeed. Thank you, @marcelveldt! 🍺
