### ISSUE TITLE
No apple music playlists

### ISSUE THREAD

**Issue by OptimusGREEN** [music-assistant/hass-music-assistant#2563]
### What version of Music Assistant has the issue?

2.1.0b8

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have connected my apple music account fine and tracks play no problem.
I have no playlists showing up though, none of my apple music playlists are listed.

### How to reproduce

click on playlists

### Music Providers

apple music

### Player Providers

chromecast

### Full log output

[log.txt](https://github.com/user-attachments/files/16074850/log.txt)

### What version of Home Assistant Core are your running

2024.6.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by MarvinSchenkel** [comment]
Can you check if this works properly with beta 9? Please do a full re-install (i.e. delete the beta addon and re-install it)

**Comment by OptimusGREEN** [comment]
Will this remove all my settings music providers and speakers? Will I have to set it up from scratch or is that all persistent data?

**Comment by MarvinSchenkel** [comment]
For your beta addon, yes. But it will not interfere with the stable addon. However, you can try without removing the old beta first.

**Comment by OptimusGREEN** [comment]
[log.txt](https://github.com/user-attachments/files/16109668/log.txt)

I uninstalled and reinstalled, re-setup apple music on beta 10 and playlists still aren't showing unfortunatley, I've attached the log.

**Comment by MarvinSchenkel** [comment]
> [log.txt](https://github.com/user-attachments/files/16109668/log.txt)
> 
> I uninstalled and reinstalled, re-setup apple music on beta 10 and playlists still aren't showing unfortunatley, I've attached the log.

Can you enable debug logging and try again? The current log does not show much information

**Comment by OptimusGREEN** [comment]
[log.txt](https://github.com/user-attachments/files/16112076/log.txt)

Here you go.

I see lines saying its starting sync for albums and artists but don't see one for playlists.

**Comment by MarvinSchenkel** [comment]
Hm, I can see it starts syncing tracks and never starts syncing playlists. However, I do not see an error after the tracks start syncing. Are you sure you waited long enough before pulling the log? I can imagine an error occurs during the syncing of tracks, which is why you do not see any playlists.

**Comment by OptimusGREEN** [comment]
Possibly not. I'll try again tonight.

Regards

John Green

**Comment by OptimusGREEN** [comment]
[log.txt](https://github.com/user-attachments/files/16116551/log.txt)

I waited until logging appeared to stop updatng and then clicked on syn in apple settings and waited for it to appear to stop just to make sure.

**Comment by OptimusGREEN** [comment]
I updated to the latest beta this morning and the playlists are now showing so I'll close this issue. Thanks for the great work.

**Comment by Kebo2r** [comment]
@MarvinSchenkel.  Still seeing this on beta 13.  No tracks or playlist listed.  albums artists show fine.  Here's I think pertinent debug logs if it helps.  Have reinstalled, synced, etc.

2024-07-07 07:13:28.359 DEBUG (MainThread) [music_assistant.webserver] Handling command music/tracks/count
2024-07-07 07:13:28.368 DEBUG (MainThread) [music_assistant.webserver] Handling command music/recently_played_items
2024-07-07 07:13:28.387 DEBUG (MainThread) [music_assistant.webserver] Handling command music/artists/library_items
2024-07-07 07:13:28.398 DEBUG (MainThread) [music_assistant.webserver] Handling command music/albums/library_items
2024-07-07 07:13:28.412 DEBUG (MainThread) [music_assistant.webserver] Handling command music/playlists/library_items
2024-07-07 07:13:28.425 DEBUG (MainThread) [music_assistant.webserver] Handling command music/radios/library_items
2024-07-07 07:13:28.434 DEBUG (MainThread) [music_assistant.webserver] Handling command music/tracks/library_items
2024-07-07 07:13:30.706 DEBUG (MainThread) [aiohttp.server] Ignored premature client disconnection.
2024-07-07 07:13:56.072 DEBUG (MainThread) [music_assistant.providers.apple_music] Skipping sync of item apple_music://album/80330790 because it is unavailable
2024-07-07 07:13:56.142 WARNING (MainThread) [music_assistant.providers.apple_music] Skipping sync of item apple_music://album/l.t1loxSf - error details: Album is missing artist(s)
2024-07-07 07:13:56.171 WARNING (MainThread) [music_assistant] Exception in task Task-94 - target: <coroutine object MusicController._start_provider_sync.<locals>.run_sync at 0x7fb2387e7f10>: 'attributes'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/music.py", line 700, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/models/music_provider.py", line 397, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/apple_music/__init__.py", line 196, in get_library_albums
    yield self._parse_album(item)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/apple_music/__init__.py", line 422, in _parse_album
    attributes = relationships.get("catalog", {})["data"][0]["attributes"]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'attributes'
2024-07-07 07:13:56.172 WARNING (MainThread) [music_assistant.music] Sync task for Apple Music completed with errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/music.py", line 700, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/models/music_provider.py", line 397, in sync_library
    async for prov_item in self._get_library_gen(media_type):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/apple_music/__init__.py", line 196, in get_library_albums
    yield self._parse_album(item)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/apple_music/__init__.py", line 422, in _parse_album
    attributes = relationships.get("catalog", {})["data"][0]["attributes"]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'attributes'
2024-07-07 07:13:56.174 DEBUG (MainThread) [music_assistant.music] Performing database cleanup...
2024-07-07 07:13:56.203 DEBUG (MainThread) [music_assistant.music] Database cleanup done
