### ISSUE TITLE
"Failed to Connect" when adding to Home Assistant

### ISSUE THREAD

**Issue by seve-martinez** [music-assistant/hass-music-assistant#2574]
### What version of Music Assistant has the issue?

2.0.7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When trying to add Music Assistant server to Home Assistant, I get an ambiguous "Failed to connect" error message.

What I have verified:
- MA server is running and i can access it at <ip-addr>:8095 from a remote PC
- The HA container can also access this

When I restart Home Assistant, the MA server will show up in the "discovered" section with the proper url and port. However, clicking submit returns the same error.

**Setup**
Main OS: Fedora CoreOS
- Home Assistant running in a container via podman (using default bridge network).
- Music Assistant server running in a container using host network and privileged as instructed
`podman run -d --network host --privileged -v mass:/data ghcr.io/music-assistant/server`
- Added MA via HACS

Upon restart:
![Screenshot 2024-07-05 at 4 27 36 PM](https://github.com/music-assistant/hass-music-assistant/assets/20816697/eaffc2ef-50aa-4860-ae35-a0c2c3bdd50d)

Manual addition:
![Screenshot 2024-07-05 at 4 27 57 PM](https://github.com/music-assistant/hass-music-assistant/assets/20816697/5d98291d-453d-49c3-81c5-8dbceac5934b)

### How to reproduce

Spin up HA container

`podman run --name home-assistant -p 8123:8123 --cap-add=NET_RAW --cap-add=NET_ADMIN -v ha_config:/config:Z homeassistant/home-assistant`

Spin up MA container
`podman run -d --network host --privileged -v mass:/data ghcr.io/music-assistant/server`

Add HACS to HA:

```console

// Enter container
$ podman exec -it home-assistant /bin/bash

// Add HACS
$ wget -O - https://get.hacs.xyz | bash -
```

Add MA

### Music Providers

NA

### Player Providers

NA

### Full log output

[log.txt](https://github.com/user-attachments/files/16114276/log.txt)

### Additional information

digging into the home-assistant logs i found this stack trace:
```console
2024-07-05 22:49:26.511 ERROR (MainThread) [custom_components.mass] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mass/config_flow.py", line 72, in async_step_manual
    self.server_info = await get_server_info(self.hass, user_input[CONF_URL])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/config_flow.py", line 37, in get_server_info
    async with MusicAssistantClient(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/client.py", line 59, in __init__
    self.connection = WebsocketsConnection(server_url, aiohttp_session)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/connection.py", line 40, in __init__
    self.ws_server_url = get_websocket_url(server_url)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/connection.py", line 28, in get_websocket_url
    raise RuntimeError(msg)
RuntimeError: homeassistant.local:8095 is not a valid url
2024-07-05 22:49:27.171 ERROR (MainThread) [custom_components.mass] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mass/config_flow.py", line 72, in async_step_manual
    self.server_info = await get_server_info(self.hass, user_input[CONF_URL])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/config_flow.py", line 37, in get_server_info
    async with MusicAssistantClient(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/client.py", line 59, in __init__
    self.connection = WebsocketsConnection(server_url, aiohttp_session)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/connection.py", line 40, in __init__
    self.ws_server_url = get_websocket_url(server_url)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/connection.py", line 28, in get_websocket_url
    raise RuntimeError(msg)
RuntimeError: homeassistant.local:8095 is not a valid url
2024-07-05 22:49:36.221 ERROR (MainThread) [custom_components.mass] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mass/config_flow.py", line 72, in async_step_manual
    self.server_info = await get_server_info(self.hass, user_input[CONF_URL])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/config_flow.py", line 37, in get_server_info
    async with MusicAssistantClient(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/client.py", line 59, in __init__
    self.connection = WebsocketsConnection(server_url, aiohttp_session)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/connection.py", line 40, in __init__
    self.ws_server_url = get_websocket_url(server_url)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/connection.py", line 28, in get_websocket_url
    raise RuntimeError(msg)
RuntimeError: 192.168.1.149:8095 is not a valid url
2024-07-05 22:49:39.203 ERROR (MainThread) [custom_components.mass] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mass/config_flow.py", line 72, in async_step_manual
    self.server_info = await get_server_info(self.hass, user_input[CONF_URL])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/config_flow.py", line 37, in get_server_info
    async with MusicAssistantClient(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/client.py", line 59, in __init__
    self.connection = WebsocketsConnection(server_url, aiohttp_session)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/connection.py", line 40, in __init__
    self.ws_server_url = get_websocket_url(server_url)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/music_assistant/client/connection.py", line 28, in get_websocket_url
    raise RuntimeError(msg)
RuntimeError: 192.168.1.149 is not a valid url
```

Which originates here: https://github.com/music-assistant/server/blob/main/music_assistant/client/connection.py#L26
I don't know why the `http://` is getting stripped.

### What version of Home Assistant Core are your running

2024.7.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by seve-martinez** [comment]
Turns out this was an issue with CoreOS and podman. Podman does some dark magic with networking and requires containers to be in a pod to communicate. Even if you put them on the same bridge network when starting them, it still won't work.
