### ISSUE TITLE
Only Default Media Receiver marks when played on Google Nest Hub Max.

### ISSUE THREAD

**Issue by GalaxyGiant** [music-assistant/hass-music-assistant#2603]
### What version of Music Assistant has the issue?

2.1.0b14

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Only Default Media Receiver marks when played on Google Nest Hub Max.

How do I set it up to see song information and cover images on my Google Nest Hub Max?

The music provider added YouTube music.
And I added a home assistant to the plug-in provider.
Finally, I added a home assistant media player as a player provider, and I selected Google Nest Hub Max and Google Home Mini from the player entity.
This is the end of my setup, and I ran a playlist on YouTube Music.
The music played normally, but only the Default Media Receiver message appeared for information about the music.

Please review my settings.

### How to reproduce

The music provider added YouTube music.
And I added a home assistant to the plug-in provider.
Finally, I added a home assistant media player as a player provider, and I selected Google Nest Hub Max and Google Home Mini from the player entity.
This is the end of my setup, and I ran a playlist on YouTube Music.
The music played normally, but only the Default Media Receiver message appeared for information about the music.

### Music Providers

YouTube music

### Player Providers

1. home assistant to the plug-in provider
2. Google Nest Hub Max and Google Home Mini (Not Chromecast)

### Full log output

2024-07-10 00:36:38.414 INFO (MainThread) [music_assistant] Starting Music Assistant Server (d42e88873e1d4d63b310ce4357efa7dc) version 2.1.0b14 - HA add-on: True - Safe mode: False
2024-07-10 00:36:38.423 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-07-10 00:36:39.089 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-07-10 00:36:39.351 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.0.1 with libsoxr support
2024-07-10 00:36:39.351 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.0.33:8097
2024-07-10 00:36:39.357 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-07-10 00:36:39.445 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-07-10 00:36:39.446 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-07-10 00:36:39.446 INFO (MainThread) [music_assistant] Loaded music provider Music Assistant
2024-07-10 00:36:39.446 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-07-10 00:36:39.571 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-07-10 00:36:47.540 WARNING (MainThread) [music_assistant.metadata] ko is not a valid language
2024-07-10 00:37:17.214 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
2024-07-10 00:37:19.014 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
2024-07-10 00:37:31.533 INFO (MainThread) [music_assistant] Loaded plugin provider Home Assistant
2024-07-10 00:37:39.612 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-07-10 00:37:39.707 INFO (MainThread) [music_assistant.players] Player registered: media_player.googlehome1267/Mini
2024-07-10 00:37:39.709 INFO (MainThread) [music_assistant.players] Player registered: media_player.maegseu/Max
2024-07-10 00:38:02.994 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 00:38:38.231 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 00:42:01.573 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-07-10 00:42:03.870 INFO (MainThread) [music_assistant.players] Player registered: f9567dce-1751-e1cf-37f5-b01fd51bbaca/Mini
2024-07-10 00:42:04.045 INFO (MainThread) [music_assistant.players] Player registered: 41de3193-9f22-e62c-f603-358b1e2d772b/Max
2024-07-10 00:42:41.960 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 00:43:20.119 INFO (MainThread) [music_assistant.players] Player removed: Mini
2024-07-10 00:43:20.121 INFO (MainThread) [music_assistant.players] Player removed: Max
2024-07-10 00:43:39.659 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-07-10 00:43:39.724 INFO (MainThread) [music_assistant.players] Player registered: media_player.ytube_music_player/ytube_music_player
2024-07-10 00:43:58.724 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play: Resume queue requested but queue ytube_music_player is empty
2024-07-10 00:44:45.955 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 00:45:27.886 INFO (MainThread) [music_assistant] Loaded player provider Home Assistant MediaPlayers
2024-07-10 00:45:27.954 INFO (MainThread) [music_assistant.players] Player removed: ytube_music_player
2024-07-10 00:46:51.850 WARNING (MainThread) [music_assistant.metadata] ko is not a valid language
2024-07-10 00:47:18.089 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 00:47:22.152 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 00:57:31.419 WARNING (MainThread) [music_assistant.metadata] ko_kr is not a valid language
2024-07-10 01:00:29.319 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:01:37.437 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:02:40.031 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:10:19.789 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:13:48.347 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:16:39.676 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:22:02.921 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/favorites/remove_item: invalid literal for int() with base 10: 'MPREb_iG5q5DIdhdA'
2024-07-10 01:22:04.247 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/favorites/add_item: artist not found in library: 2
2024-07-10 01:22:30.441 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: No playable items found
2024-07-10 01:22:44.645 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/refresh_item: artist not found in library: 2
2024-07-10 01:23:14.623 WARNING (MainThread) [music_assistant.metadata] ko_kr is not a valid language
2024-07-10 01:27:45.861 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:28:34.129 WARNING (MainThread) [music_assistant.metadata] ko_kr is not a valid language
2024-07-10 01:29:51.516 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:32:34.704 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 634, in _metadata_scanner
    await self._update_album_metadata(album)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 465, in _update_album_metadata
    await self.mass.music.artists.update_item_in_library(album.item_id, album)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 150, in update_item_in_library
    await self._update_library_item(item_id, update, overwrite=overwrite)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 339, in _update_library_item
    cur_item = await self.get_library_item(db_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 358, in get_library_item
    raise MediaNotFoundError(msg)
music_assistant.common.models.errors.MediaNotFoundError: artist not found in library: 2
2024-07-10 01:38:11.874 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:40:00.296 WARNING (MainThread) [music_assistant.metadata] ko_kr is not a valid language
2024-07-10 01:42:42.873 WARNING (MainThread) [music_assistant.metadata] ko_kr is not a valid language
2024-07-10 01:44:26.668 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:47:40.380 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Max - crossfade: False
2024-07-10 01:53:30.236 WARNING (MainThread) [music_assistant.metadata] ko is not a valid language

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
You missed an important part in our documentation that says that you should use the builtin player providers to get all functionality. Use Home Assistant players only as last resort if there is no native provider available. 

So add the Chromecast player provider to MA and use those players to get all functionality

**Comment by GalaxyGiant** [comment]
> You missed an important part in our documentation that says that you should use the builtin player providers to get all functionality. Use Home Assistant players only as last resort if there is no native provider available.
> 
> So add the Chromecast player provider to MA and use those players to get all functionality

Thank you.
I missed an important phrase.
I set it the way you said it, and I saw the title and cover image!
