### ISSUE TITLE
V1.1.19: adding playlist to queue issue

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#267]
Really strange thing happen with queuing music. I added a local playlist with 18 tracks to an empty queue ( using play now). But 3 tracks immediately ended up in the played items list instead of next items, and queue didn't start.
Noticed some errors in the log. Second attempt, the whole list was loaded, but only first track was played, and then it paused?!
```
Failed to cast media http://192.168.178.47:8095/media_player.everywhere_57.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
17:41:57 – (ERROR) Google Cast - message first occurred at 17:35:19 and shows up 28 times
Error handling request
17:41:57 – (ERROR) /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py - message first occurred at 17:35:19 and shows up 27 times
Provider ProviderType.DATABASE is not available
17:41:43 – (WARNING) /usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py - message first occurred at 17:35:19 and shows up 4 times
Exception thrown when calling load failed callback
17:35:55 – (ERROR) /usr/local/lib/python3.9/site-packages/pychromecast/controllers/media.py - message first occurred at 17:35:19 and shows up 2 times
```
The details of a relevant error:
```

Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405 
First occurred: 17:35:19 (27 occurrences) 
Last logged: 17:41:57

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py", line 146, in serve_queue_stream
    start_streamdetails = await queue.queue_stream_prepare()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 733, in queue_stream_prepare
    return await get_stream_details(self.mass, next_item, self.queue_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 224, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 438, in get_stream_details
    content_type=ContentType(itempath.split(".")[-1]),
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'MP3' is not a valid ContentType
```

**Comment by erkr** [comment]
After some additional attempts to add local playlists to the queue, the queue is corrupted. When I try to open the queue in the player it keeps loading. This error is in the log:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:835 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 18:01:06 (4 occurrences) 
Last logged: 18:03:26

[547795356016] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 96, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 835, in websocket_playerqueue_items
    result = [x.to_dict() for x in queue.items]
  File "/config/custom_components/mass/websockets.py", line 835, in <listcomp>
    result = [x.to_dict() for x in queue.items]
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

**Comment by erkr** [comment]
I had to reload MA to be able to continue. Common denominator of the queuing issue seems to be problems/exceptions when loading some local tracks.

**Comment by marcelveldt** [comment]
fixed in next (patch) release
https://github.com/music-assistant/music-assistant-lib/pull/348

**Comment by erkr** [comment]
This playlist load correct now!
