### ISSUE TITLE
2.2.0 beta3: Error during (re)sync

### ISSUE THREAD

**Issue by vingerha** [music-assistant/hass-music-assistant#2719]
### What version of Music Assistant has the issue?

2.2.0b3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

```
2024-08-04 06:54:09.005 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 248, in metadata_scanner
    await self._update_artist_metadata(artist)
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 465, in _update_artist_metadata
    if mbid := await self._get_artist_mbid(artist):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/metadata.py", line 668, in _get_artist_mbid
    if mbid := await musicbrainz.get_musicbrainz_artist_id(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 226, in get_musicbrainz_artist_id
    if mb_artist := await self.get_artist_details_by_track(artist.name, ref_track):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 410, in get_artist_details_by_track
    result = await self.get_recording_details(ref_track.mbid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 334, in get_recording_details
    if result := await self.get_data(f"recording/{recording_id}?inc=artists+releases"):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/cache.py", line 261, in wrapped
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/throttle_retry.py", line 124, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/musicbrainz/__init__.py", line 431, in get_data
    async with (
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

### How to reproduce

Went from 2.2.0.b2 to 2.2.0.b3 ...this error popped up during resync

resync on filesystem

### Music Providers

filesystem

### Player Providers

n.a.

### Full log output

_No response_

### Additional information

_No response_

### What version of Home Assistant Core are your running

n.a.

### What type of installation are you running?

n.a.

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You have ticked the box saying you have read the troubleshooting page but you have done nothing that is asked for there nor have you filled out the template above according to the instructions. 
i just tried this and received no error so you need to do a lot more fault finding and provide a lot more information.

**Comment by vingerha** [comment]
I installed 2.2.0b3, then resyn then this popped up, no clue what I need to do more

**Comment by OzGav** [comment]
You could rollback using your backup to confirm that it is indeed caused by this update. You could Google the error. You could work your way through the troubleshooting page and provide information about what worked and what didn’t work. You could attach the full logs……

**Comment by vingerha** [comment]
Yeah...true... and went back ... nothing and forth...nothing ...odd. Only thing I did was apply the new image this morning
