### ISSUE TITLE
Error thrown when trying to seek MA players from Home Assistant?

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2776]
### Discussed in https://github.com/orgs/music-assistant/discussions/2775

<div type='discussions-op-text'>

<sup>Originally posted by **JoeMBlair** August 19, 2024</sup>
I'm trying to seek a media player that was added by Music Assistant in Home Assistant. However it doesn't seem to support media player seek action, it's not in the entity dropdown. Is there another way to do it?</div>

ISSUE is that the MA players in HA throw this error when trying to seek

```
2024-08-19 20:57:23.030 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140161193743488] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 981, in entity_service_call
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.ma_kitchen_speaker does not support this service.
```

**Comment by marcelveldt** [comment]
fixed in 2024.8.1

**Comment by OzGav** [comment]
@joemblair please confirm this has been fixed

**Comment by JoeMBlair** [comment]
> @JoeMBlair please confirm this has been fixed

It has been fixed, working great now
