### ISSUE TITLE
Since latest update Home Assistant MediaPlayers stopped working

### ISSUE THREAD

**Issue by rosicenko** [music-assistant/hass-music-assistant#2890]
### What version of Music Assistant has the issue?

2.2.3

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Since latest update whenever I try to play anything on player connected through Home Assistant (bluetooth, Echo Dot) I receive error:

ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 423, in serve_queue_flow_stream
    await resp.prepare(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 418, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 424, in _start
    await self._prepare_headers()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 452, in _prepare_headers
    raise RuntimeError(
RuntimeError: Using chunked encoding is forbidden for HTTP/1.0

Media players are accessible out of MA.

### How to reproduce

Use player provider in MA: Home Assistant MediaPlayers

### Music Providers

Does not matter.

### Player Providers

Home Assistant MediaPlayers

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16936144/music-assistant.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
We we still updating the docs so look in the player settings and you will see a new option for HTTP profile. Try each option until it works
