### ISSUE TITLE
`UnicodeDecodeError` when radio metadata has Latin-1 character

### ISSUE THREAD

**Issue by johnboiles** [music-assistant/hass-music-assistant#2908]
### What version of Music Assistant has the issue?

2.2.3

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

My RadioBrowser stream didn't work this morning. And I could see `UnicodeDecodeError` in the logs:

```
2024-09-12 09:03:17.568 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for library://radio/2
2024-09-12 09:03:18.435 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for library://radio/2 in 867 milliseconds
2024-09-12 09:03:18.890 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem library://radio/2 to Main Stereo
2024-09-12 09:03:18.898 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: radiobrowser://radio/6ad9e717-71a3-45d1-aace-277da9c7cf98
2024-09-12 09:03:18.903 DEBUG (MainThread) [music_assistant.audio] Start streaming radio with ICY metadata from url https://ais-sa2.cdnstream1.com/2053_128.mp3?cache=888a2e19065dcc8c
2024-09-12 09:03:19.209 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem library://radio/2 to Main Stereo
2024-09-12 09:03:19.217 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: radiobrowser://radio/6ad9e717-71a3-45d1-aace-277da9c7cf98
2024-09-12 09:03:19.227 DEBUG (MainThread) [music_assistant.audio] Start streaming radio with ICY metadata from url https://ais-sa2.cdnstream1.com/2053_128.mp3?cache=888a2e19065dcc8c
2024-09-12 09:03:20.346 ERROR (MainThread) [music_assistant.streams.media_stream] 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 192, in _feed_stdin
    async for chunk in self.audio_input:
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 557, in get_icy_radio_stream
    stream_title = stream_title.group(1).decode()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte
2024-09-12 09:03:20.369 DEBUG (MainThread) [music_assistant.streams.media_stream] stream finished (with code 234) for radiobrowser://radio/6ad9e717-71a3-45d1-aace-277da9c7cf98 - seconds streamed: 0
2024-09-12 09:03:20.654 ERROR (MainThread) [music_assistant.streams.media_stream] 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 192, in _feed_stdin
    async for chunk in self.audio_input:
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 557, in get_icy_radio_stream
    stream_title = stream_title.group(1).decode()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 5: invalid continuation byte
2024-09-12 09:03:20.677 DEBUG (MainThread) [music_assistant.streams.media_stream] stream finished (with code 234) for radiobrowser://radio/6ad9e717-71a3-45d1-aace-277da9c7cf98 - seconds streamed: 0
```

Sure enough the station is currently streaming something with a non-ascii character:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/e8491494-4914-4a29-b394-7fe99e2f684f">

I think we can fix this either by ignoring the characters:

```
stream_title = stream_title.group(1).decode('utf-8', errors='replace')
```

Or by trying both encodings

```
try:
    stream_title = stream_title.group(1).decode()
except UnicodeDecodeError:
    stream_title = stream_title.group(1).decode('iso-8859-1')
```

Or potentially by guessing the encoding (idea from GPT -- I have not done this before)

```
import chardet
result = chardet.detect(stream_title.group(1))
encoding = result['encoding']
stream_title = stream_title.group(1).decode(encoding)
```

### How to reproduce

Try to play a RadioBrowser stream with non-utf8 characters in the metadata.

### Music Providers

RadioBrowser

### Player Providers

ESPHome

### Full log output

[music-assistant (2).log](https://github.com/user-attachments/files/16982680/music-assistant.2.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by johnboiles** [comment]
I might be able to handle this. Probably about time for me to set up a MA server dev environment :)

**Comment by johnboiles** [comment]
Similar PR for ExoPlayer: https://github.com/google/ExoPlayer/commit/18cdd8ece20ba28f41e8f6f8919587e9d5874847

**Comment by johnboiles** [comment]
Here's some test code also to read the metadata from inside a stream:
```python
import requests

def get_icy_metadata(stream_url):
    headers = {
        'Icy-MetaData': '1',  # Request ICY metadata from the server
        'User-Agent': 'Mozilla/5.0'  # Set a User-Agent to mimic a browser
    }

    response = requests.get(stream_url, headers=headers, stream=True)
    
    # Check if the stream provides ICY metadata
    if 'icy-metaint' in response.headers:
        metaint = int(response.headers['icy-metaint'])
        print(f"ICY Meta Interval: {metaint} bytes")

        # Start reading the audio stream and metadata
        stream = response.raw
        while True:
            # Skip the audio data up to the metaint interval
            audio_data = stream.read(metaint)

            # Read the metadata length byte (multiplied by 16 to get metadata size)
            metadata_length = ord(stream.read(1)) * 16

            if metadata_length > 0:
                # Read the actual metadata
                metadata = stream.read(metadata_length).decode('utf-8', errors='ignore')

                print(f"Metadata: {metadata}")

                # Extract the StreamTitle from the metadata
                start = metadata.find("StreamTitle='") + len("StreamTitle='")
                end = metadata.find("';", start)
                if start != -1 and end != -1:
                    stream_title = metadata[start:end]
                    print(f"Current Song: {stream_title}")
            else:
                # print("No metadata available.")
                pass

    else:
        print("This stream does not provide ICY metadata.")

# Example MP3 stream URL
mp3_stream_url = "http://ais-sa2.cdnstream1.com/2053_128.mp3"
get_icy_metadata(mp3_stream_url)
```
