### ISSUE TITLE
Slimproto Group player fails to play with "Using chunked encoding is forbidden for HTTP/1.0"

### ISSUE THREAD

**Issue by vivobg** [music-assistant/hass-music-assistant#2929]
### What version of Music Assistant has the issue?

2.3.0b23

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Trying to play music via a Group Slimproto player results in no music playing, and the error log showing the following:
```
2024-09-16 11:38:10.783 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 352, in serve_queue_item_stream
    await resp.prepare(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 418, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 424, in _start
    await self._prepare_headers()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 452, in _prepare_headers
    raise RuntimeError(
RuntimeError: Using chunked encoding is forbidden for HTTP/1.0
```

This seems related to https://github.com/music-assistant/hass-music-assistant/issues/2809 but for group players.

When NOT using the group, I can play music via each of the individual slimproto players.

### How to reproduce

- Add 2 slimproto software players to a group
- Try to play music via the group

### Music Providers

- Spotify
- Local/SMB

### Player Providers

Slimproto software players, in a group

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17011683/music-assistant.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
This is fixed in 2.3.0b24

**Comment by OzGav** [comment]
@vivobg please confirm this is fixed

**Comment by OzGav** [comment]
This will be closed soon assuming fixed

**Comment by OzGav** [comment]
Closing assumed fixed
