### ISSUE TITLE
"No item with that key"

### ISSUE THREAD

**Issue by HarvsG** [music-assistant/hass-music-assistant#2938]
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

MASS server failed to start after updating
Found errors in the logs

### How to reproduce

Unsure - update to recent version

### Music Providers

![image](https://github.com/user-attachments/assets/bc99bf39-0bf2-4a13-864a-f2df3121e229)

### Player Providers

![image](https://github.com/user-attachments/assets/af563eb8-d27d-458b-b2e4-53e411e8bfe8)

### Full log output

```
2024-09-17 23:24:14.595 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:26:14.606 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:28:14.615 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:30:14.620 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:32:14.624 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:34:14.631 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:36:14.638 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:38:14.645 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:40:14.653 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:42:14.660 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:44:14.668 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:46:14.674 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:48:14.683 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:50:14.690 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:52:14.698 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:54:08.220 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/cache.py", line 207, in auto_cleanup
    await self.delete(db_row["key"])
                      ~~~~~~^^^^^^^
IndexError: No item with that key
2024-09-17 23:54:14.704 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:56:14.713 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-17 23:58:14.718 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:00:14.724 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:02:14.733 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:04:14.741 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:04:28.281 WARNING (Thread-12) [pychromecast.socket_client] [Snug Chromecast(192.168.0.244):8009] Heartbeat timeout, resetting connection
2024-09-18 00:04:58.316 ERROR (Thread-12) [pychromecast.socket_client] [Snug Chromecast(192.168.0.244):8009] Failed to connect to service HostServiceInfo(host='192.168.0.244', port=8009), retrying in 5.0s
2024-09-18 00:06:14.748 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:08:14.757 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:10:14.767 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:12:14.773 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:14:14.780 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:16:14.787 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:18:14.795 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:20:14.805 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:22:14.813 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:24:14.820 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:26:14.825 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:28:14.832 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:30:14.837 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:32:14.845 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:34:14.852 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:36:14.860 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:38:14.870 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:40:14.878 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:42:14.885 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:44:14.891 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:46:14.898 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:48:14.906 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:50:14.913 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:52:14.923 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:54:08.221 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/cache.py", line 207, in auto_cleanup
    await self.delete(db_row["key"])
                      ~~~~~~^^^^^^^
IndexError: No item with that key
2024-09-18 00:54:14.457 INFO (MainThread) [music_assistant.music] Sync task for RadioBrowser completed
2024-09-18 00:54:15.409 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:54:16.376 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-09-18 00:54:16.631 INFO (MainThread) [music_assistant.music] Sync task for Jellyfin Media Server Library completed
2024-09-18 00:54:16.632 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-09-18 00:55:24.176 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-09-18 00:56:15.417 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 00:58:15.425 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:00:15.434 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:02:15.443 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:04:15.449 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:06:15.457 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:08:15.463 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:10:15.467 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:12:15.475 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:14:15.482 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:16:15.491 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:18:15.501 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:20:15.509 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:22:15.519 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:24:15.527 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:26:15.538 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:28:15.547 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:30:15.555 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:32:15.562 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:34:15.569 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:36:15.573 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:38:15.580 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:40:15.587 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:42:15.595 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:44:15.602 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:46:15.610 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:48:15.617 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:50:15.623 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:52:15.629 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
2024-09-18 01:54:08.241 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/cache.py", line 207, in auto_cleanup
    await self.delete(db_row["key"])
                      ~~~~~~^^^^^^^
IndexError: No item with that key
2024-09-18 01:54:15.638 WARNING (MainThread) [music_assistant] Error loading provider(instance) Spotify: Configuration is invalid (will be retried later)
```

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by HarvsG** [comment]
I re-authenticated spotify and I don't see the error anymore

**Comment by OzGav** [comment]
Not sure what happened. No one else has reported this. If you can’t recreate it I’m not sure what can be done

**Comment by HarvsG** [comment]
> Not sure what happened. No one else has reported this. If you can’t recreate it I’m not sure what can be done

https://github.com/music-assistant/server/pull/1674 can be done.
