### ISSUE TITLE
V.06b2: refresh playlist not working for deletes

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#294]
Used the new button to refresh the playlists after I deleted a corrupted playlist. 
Playlist was not removed. Noticed this error:
``` 
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:516 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 14:12:25 (1 occurrences) 
Last logged: 14:12:25

[547997849104] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 98, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 516, in websocket_playlist_tracks
    for item in await mass.music.playlists.tracks(msg[ITEM_ID], msg[PROVIDER])
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/playlists.py", line 47, in tracks
    return await provider.get_playlist_tracks(item_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 312, in get_playlist_tracks
    raise MediaNotFoundError(f"Playlist path does not exist: {playlist_path}")
music_assistant.models.errors.MediaNotFoundError: Playlist path does not exist: /media/MP3_normalized/Albums/NightWish/NightWish.m3u
```

**Comment by marcelveldt** [comment]
should be fixed in beta 6

**Comment by erkr** [comment]
Works!
