### ISSUE TITLE
MASS server: cannot upgrade from 2.2.6 to 2.2.7

### ISSUE THREAD

**Issue by eekamouze** [music-assistant/hass-music-assistant#3002]
### What version of Music Assistant has the issue?

2.2.7

### What version of the Home Assistant Integration have you got installed?

N/A

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Upgrade from docker image 2.2.6 to 2.2.7 fails (using portainer). It restarts with 2.2.6
When trying manual upgrade (docker rm 2.2.6 / docker run 2.2.7) it starts with 2.2.7 but I have several errors like the one below:

```
2024-10-04 14:08:17.466 ERROR (MainThread) [aiohttp.server] Error handling request

Traceback (most recent call last):

  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request

    resp = await request_handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle

    resp = await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/helpers/webserver.py", line 136, in _handle_catch_all

    return await handler(request)

           ^^^^^^^^^^^^^^^^^^^^^^

  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/providers/dlna/helpers.py", line 38, in _handle_request

    url=request.url,

        ^^^^^^^^^^^

  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__

  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_request.py", line 453, in url

    url = URL.build(scheme=self.scheme, host=self.host)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/venv/lib/python3.12/site-packages/yarl/_url.py", line 385, in build

    netloc = cls._make_netloc(

             ^^^^^^^^^^^^^^^^^

  File "/app/venv/lib/python3.12/site-packages/yarl/_url.py", line 1057, in _make_netloc

    ret = cls._encode_host(host)

          ^^^^^^^^^^^^^^^^^^^^^^

  File "/app/venv/lib/python3.12/site-packages/yarl/_url.py", line 1038, in _encode_host

    _host_validate(host)

  File "/app/venv/lib/python3.12/site-packages/yarl/_url.py", line 1607, in _host_validate

    raise ValueError(

ValueError: Host '192.168.1.201:8097' cannot contain ':' (at position 13)
```

### How to reproduce

upgrade from 2.2.6 to 2.2.7

### Music Providers

Spotify
Jellyfin

### Player Providers

DLNA
Sonos 
Airplay
Universal Group Player

### What version of Home Assistant Core are your running

2024.9.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
There were changes with docker. Please review the updated docs and ensure your install is meeting the requirements https://music-assistant.io/installation/

**Comment by Mattie432** [comment]
Noting that I was also unable to upgrade past 2.2.6 via portainer. Error I got via portainer was:
`
failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "mass": executable file not found in $PATH: unknown
`

The command updates in the docs did fix my issue, specifically adding `--security-opt apparmor=unconfined` @eekamouze 

@OzGav it would be nice to have setup changes documented in the release notes. Might make it easier for people to see required changes rather than comparing old->new docs.

**Comment by OzGav** [comment]
Noted. We only had time to update the docs yesterday….

**Comment by eekamouze** [comment]
@Mattie432 thanks for your feedback. Indeed I was able to upgrade adding privileged capabilities and security-opt even if the doc says it is needed to mount smb folders...
Anyway I still have issues (see error log above), and it seems to be related to dlna upnp/dlna player. Since I've disabled it, no more error. Then I enabled it back and the errors came back right away.

**Comment by OzGav** [comment]
DLNA is a separate issue. Review the docs and open issues. If nothing helps then open a new issue.
