### ISSUE TITLE
Radio Mode sometimes use qobuz instead Spotify and fails

### ISSUE THREAD

**Issue by lor74** [music-assistant/hass-music-assistant#3005]
### What version of Music Assistant has the issue?

2.3.0b29

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Using this code for play radio 

```
data:
  media_type: artist
  media_id: '{{ states(''input_select.ma_artist_radio_shuffle'') }}'
  radio_mode: 'on'
  enqueue: replace
target:
  device_id: 4dd4fb32ed7057d755400397cd08f54f
continue_on_error: true
action: mass.play_media
```

![Screenshot 2024-10-05 alle 13 30 39](https://github.com/user-attachments/assets/5af424c5-192e-4a8d-8ebf-30b3731810c9)

It fails to reproduce media and in the error it seems that the artist was searched to quobuz. I have both Spotify and quobuz... but quobuz didn't support radio mode.

`2024-10-05 13:23:55.616 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id='b8041535b29947309b5ef6cd3df8bb17', command='player_queues/play_media', args={'queue_id': 'syncgroup_xnnrwjtk', **'media': ['qobuz://artist/1193948']**, 'option': 'replace', 'radio_mode': True, 'start_item': None})
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/webserver.py", line 362, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 433, in play_media
    tracks = await self._get_radio_tracks(queue_id=queue_id, is_initial_radio_mode=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 1353, in _get_radio_tracks
    for track in await ctrl.dynamic_base_tracks(radio_item.item_id, radio_item.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 663, in dynamic_base_tracks
    return await self._get_dynamic_tracks(ref_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 430, in _get_dynamic_tracks
    raise UnsupportedFeaturedException(msg)
music_assistant.common.models.errors.UnsupportedFeaturedException: No Music Provider found that supports requesting similar tracks.`

### How to reproduce

```
data:
  media_type: artist
  media_id: 'Mike Zito'
  radio_mode: 'on'
  enqueue: replace
target:
  device_id: 4dd4fb32ed7057d755400397cd08f54f
continue_on_error: true
action: mass.play_media
```

### Music Providers

I have both spotify and quobuz ... and radio mode should use spotify since quobuz doesn't support radio mode.

### Player Providers

Airplay

### What version of Home Assistant Core are your running

2024.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by lor74** [comment]
Today it works... and no update of MA was released

```
2024-10-08 08:19:34.624 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue AirPlayGroup - crossfade: False
2024-10-08 08:19:34.624 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: spotify://track/6hP4xqF951GUpSp8ZjU3Qb (Mike Zito/Albert Castiglia/Matt Johnson/Ephraim Lowel/Lewis Stephens - In My Soul) for queue AirPlayGroup
2024-10-08 08:19:34.624 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: spotify://track/6hP4xqF951GUpSp8ZjU3Qb
2024-10-08 08:19:35.639 DEBUG (MainThread) [music_assistant.server.controllers.config] Saved data to persistent storage
```

How can you explain this behaviour? Is something related to Spotify response?

**Comment by OzGav** [comment]
@lor74 it very much could be Spotify

**Comment by lor74** [comment]
Ok do you have a sugguestion on how to debug this?
Thanks

**Comment by OzGav** [comment]
OK we are looking at a possibly similar issue elsewhere. If you try and start radio mode on a local file sometimes the `No Music Provider found that supports requesting similar tracks`. It is also possible that Spotify was temporarily unavailable due to this issue #2863 You didn't attach the full log output as requested so can't say for sure

**Comment by lor74** [comment]
I have reproduced the issue with another artist

```
data:
  media_type: artist
  media_id: Clannad
  radio_mode: "on"
  enqueue: replace
target:
  device_id: 4dd4fb32ed7057d755400397cd08f54f
continue_on_error: true
action: mass.play_media
```

```
2024-10-22 17:51:28.878 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id='61973efee1764383b541bcc43305e34f', command='player_queues/play_media', args={'queue_id': 'syncgroup_xnnrwjtk', 'media': ['qobuz://artist/59303'], 'option': 'replace', 'radio_mode': True, 'start_item': None})
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/webserver.py", line 362, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 462, in play_media
    tracks = await self._get_radio_tracks(queue_id=queue_id, is_initial_radio_mode=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/player_queues.py", line 1387, in _get_radio_tracks
    for track in await ctrl.dynamic_base_tracks(radio_item.item_id, radio_item.provider)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/media/base.py", line 663, in dynamic_base_tracks
    return await self._get_dynamic_tracks(ref_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/media/artists.py", line 430, in _get_dynamic_tracks
    raise UnsupportedFeaturedException(msg)
music_assistant.common.models.errors.UnsupportedFeaturedException: No Music Provider found that supports requesting similar tracks.
```

Please find attached the full log

[music-assistant.log](https://github.com/user-attachments/files/17479006/music-assistant.log)

Hope this help... and thanks again for your support.

**Comment by marcelveldt** [comment]
I -think- I fixed this one - at least I cant reproduce it anymore.
Please test when 2.3.0 is released

**Comment by OzGav** [comment]
@lor74 please confirm this has been fixed

**Comment by lor74** [comment]
Hi @OzGav I have tested on 2.4.0 and it's fixed. Thanks!!! 👍
