### ISSUE TITLE
Error setting up entry Music Assistant for mass

### ISSUE THREAD

**Issue by k-a-r-g** [music-assistant/hass-music-assistant#301]
From log file:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 111, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 104, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 81, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 45, in setup
    await self._migrate()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 238, in _migrate
    await db.execute(f"ALTER TABLE {TABLE_ALBUMS} ADD artists json;")
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 163, in execute
    return await connection.execute(query, values)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 274, in execute
    return await self._connection.execute(built_query)
  File "/usr/local/lib/python3.9/site-packages/databases/backends/sqlite.py", line 133, in execute
    await cursor.execute(query_str, args)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: duplicate column name: artists
```

**Comment by marcelveldt** [comment]
strange something went wrong on your setup with the db.

Please delete the music_assistant.db file from your HA config file and restart HA. That should fix it.

**Comment by k-a-r-g** [comment]
That worked. Thanks!
