### ISSUE TITLE
V.06b2: errors in log

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#302]
I noticed these errors in the log file while casting a radio to my CC:
``` 
Logger: homeassistant.core
Source: components/cast/media_player.py:717 
First occurred: 11:46:10 (8 occurrences) 
Last logged: 11:49:05

Error executing service: <ServiceCall media_player.play_media (c:01G4Q1Q5TSCA4CRNHY238WSNKP): entity_id=['media_player.everywhere_57'], extra=, media_type=music, media_id=http://192.168.178.47:8095/media_player.everywhere_57.flac>
Error executing service: <ServiceCall media_player.play_media (c:01G4Q1Q795D6SX5KRGG304K621): entity_id=['media_player.everywhere_57'], extra=, media_type=music, media_id=http://192.168.178.47:8095/media_player.everywhere_57.flac>
Error executing service: <ServiceCall media_player.play_media (c:01G4Q1Q829Q6S21V9594PS3T7A): entity_id=['media_player.everywhere_57'], extra=, media_type=music, media_id=http://192.168.178.47:8095/media_player.everywhere_57.flac>
Error executing service: <ServiceCall media_player.play_media (c:01G4Q1VMGJPSS8QGR4QKEF9QP9): entity_id=['media_player.everywhere_57'], extra=, media_type=music, media_id=http://192.168.178.47:8095/media_player.everywhere_57.flac>
Error executing service: <ServiceCall media_player.play_media (c:01G4Q1W83B946W0J0K6Y0PR8MX): entity_id=['media_player.everywhere_57'], extra=, media_type=music, media_id=http://192.168.178.47:8095/media_player.everywhere_57.flac>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1722, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 717, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/quick_play.py", line 77, in quick_play
    controller.quick_play(**data)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/media.py", line 544, in quick_play
    raise PyChromecastError()
pychromecast.error.PyChromecastError
``` 

During the 3 minutes these errors occurred, I noticed many strange player state changes in the logbook. It's a cycle of many player changes that don't fit in one screen:
![image](https://user-images.githubusercontent.com/4363599/171995346-df2fcda1-dfb5-4786-9e27-083cba9d3ad3.jpeg)

**Comment by erkr** [comment]
Interesting to note: when there's quick player alternations happen in the logbook, the client pending errors are triggered!

**Comment by erkr** [comment]
Don't see them anymore 👍
