### ISSUE TITLE
RuntimeError: Failed to install package pkce==1.0.3

### ISSUE THREAD

**Issue by thomas-svrts** [music-assistant/hass-music-assistant#3075]
### What version of Music Assistant has the issue?

2.3.0

### What version of the Home Assistant Integration have you got installed?

don't have it

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Since some months MA doesn't start up.
It tries to install dependencies. But isn't allowed.

It runs as a HA addon, installed from the addon repo published here: https://github.com/music-assistant/core

I saw on this forum they are mentioning you should run it in privileged mode, but no clue how to it as a HA addon. Some addons have a setting "Protection mode" you can disable, but MA hasn't. 

### How to reproduce

error at startup:

```
2024-10-25 08:54:35.843 INFO (MainThread) [music_assistant] Starting Music Assistant Server (8f47748dc0ef443aa0ce87ccd5d4b5ec) version 2.3.0 - HA add-on: True - Safe mode: False
2024-10-25 08:54:35.875 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-10-25 08:54:36.226 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-10-25 08:54:38.846 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.1.1 with libsoxr support
2024-10-25 08:54:38.847 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.10.7:8097
2024-10-25 08:54:38.887 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-10-25 08:54:39.948 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 211, in start_mass
    await mass.start()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/server.py", line 161, in start
    await self._load_providers()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/server.py", line 557, in _load_providers
    prov_configs = await self.config.get_provider_configs(include_values=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/config.py", line 176, in get_provider_configs
    await self.get_provider_config(prov_conf["instance_id"])
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/config.py", line 190, in get_provider_config
    config_entries = await self.get_provider_config_entries(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/config.py", line 240, in get_provider_config_entries
    prov_mod = await load_provider_module(provider_domain, prov.requirements)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/helpers/util.py", line 131, in load_provider_module
    await install_package(requirement)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/helpers/util.py", line 64, in install_package
    raise RuntimeError(msg)
RuntimeError: Failed to install package pkce==1.0.3
```

### Music Providers

N/A

### Player Providers

N/A

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
What version of HA are you running? Have you tried completely removing the MA addon and then restarting the host and then readding MA?

**Comment by thomas-svrts** [comment]
HAOS and HA Core 2024.10.3

No I didn't reinstall it, otherwise I have no guarantee that it will work next dependency upgrade.
If you insist I can try...

**Comment by marcelveldt** [comment]
Could it be that there was some sort of internet outage when you tried or maybe pypi not available (where it gets the packages from) ?

**Comment by thomas-svrts** [comment]
internet outage isn't possible. I restarted MA addon already x times over the lasts months, and each time it tries.
The error stays.

**Comment by thomas-svrts** [comment]
I also have next errors in my log:
```
Failed to install package pkce==1.0.3
No module named 'hass_client'
Failed to install package hass-client==1.2.0
```

And shouldn't an update of the MA addon also install those dependencies?
I installed a lot of updates to MA last weeks, found it strange that it then also need install additional stuff. I don't use exotic stuff. pkce and hass-client seems basic.

**Comment by marcelveldt** [comment]
These dependencies are installed at startup to keep the base image small.
Your feature request is another one's annoyance ;-)
One thing we could do is make the packages install to a persistent location.

I can not reproduce this on any setup, not have we seen reports during the beta.
Are you running something like pihole or adguard or whatever ?

**Comment by thomas-svrts** [comment]
I have a Telenet modem (a recent Liberty Global model, that Ziggo also has) that runs safesurf. It blocks some phishing websites, but never had problems with pip install urls. But anyhow I'm disabling that to test.

My HAOS is pretty default. I run 14 addons, but they should be isolated. And install always the latest versions.
I had the beta 2.0 MA for months which worked pretty good. Somewhere august/september the addon stopped working.

**Comment by thomas-svrts** [comment]
I disabled that function on my modem and rebooted modem and HAOS.
Error remains.

**Comment by OzGav** [comment]
No one else is reporting this problem. I am creating and deleting the addon all the time so I am nit sure why you say

> I have no guarantee that it will work next dependency upgrade

I recommend you completely remove the addon, reboot the HOST (not just HA), and then reinstall.

**Comment by thomas-svrts** [comment]
reinstall worked.
