### ISSUE TITLE
V06.b2: add to queue error

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#314]
When choosing add to queue of a Spotify playlist to a group player I have these errors in the log:
``` 
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96 
First occurred: 19:17:20 (2 occurrences) 
Last logged: 19:21:35

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 806, in _save_items
    "items": [x.to_dict() for x in self._items],
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 806, in <listcomp>
    "items": [x.to_dict() for x in self._items],
AttributeError: 'NoneType' object has no attribute 'to_dict'
``` 
And:
``` 
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:837 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 19:17:20 (9 occurrences) 
Last logged: 19:21:54

[547345210960] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 98, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 837, in websocket_playerqueue_items
    result = [x.to_dict() for x in queue.items]
  File "/config/custom_components/mass/websockets.py", line 837, in <listcomp>
    result = [x.to_dict() for x in queue.items]
AttributeError: 'NoneType' object has no attribute 'to_dict'
``` 
When looking into the player queue, it remained refreshing:
![image](https://user-images.githubusercontent.com/4363599/172446716-13e12bc5-6bd0-4b1d-b9c2-8c618252afeb.jpeg)
Had to reload ze MA to get out of this.
Note: Play now works fine!

**Comment by marcelveldt** [comment]
can you recheck this one in beta 5?

**Comment by erkr** [comment]
I just verified this issue :-) Solved 👍
