### ISSUE TITLE
SiriusXM continuously skipping

### ISSUE THREAD

**Issue by nikito** [music-assistant/hass-music-assistant#3144]
### What version of Music Assistant has the issue?

2.4.0b4

### What version of the Home Assistant Integration have you got installed?

2024.11.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When playing a radio station from SiriusXM, the station is skipping/stopping every few seconds, and the following error is occurring repeatedly in the logs:
```
2024-11-07 12:57:08.881 INFO (MainThread) [/app/venv/lib/python3.12/site-packages/sxm/client.py] Received status code 403 on playlist, renewing session
2024-11-07 12:57:15.286 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/sxm/client.py", line 401, in get_segment
    raise SegmentRetrievalException(
sxm.client.SegmentRetrievalException: Received status code 403 on segment, renew session
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/sxm/http.py", line 123, in sxm_handler
    data = await get_playlist_chunk(segment_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/sxm/http.py", line 88, in get_playlist_chunk
    data = await get_segment(segment_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/sxm/http.py", line 44, in get_segment
    data = await sxm.get_segment(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f42d0712450 state=finished raised SegmentRetrievalException>]
2024-11-07 12:57:15.295 INFO (MainThread) [/app/venv/lib/python3.12/site-packages/sxm/client.py] Received status code 403 on playlist, renewing session
2024-11-07 12:57:24.353 INFO (MainThread) [/app/venv/lib/python3.12/site-packages/sxm/client.py] Received status code 403 on playlist, renewing session
2024-11-07 12:57:30.774 INFO (MainThread) [/app/venv/lib/python3.12/site-packages/sxm/client.py] Received status code 403 on playlist, renewing session
2024-11-07 12:57:38.114 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/sxm/client.py", line 401, in get_segment
    raise SegmentRetrievalException(
sxm.client.SegmentRetrievalException: Received status code 403 on segment, renew session
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/sxm/http.py", line 123, in sxm_handler
    data = await get_playlist_chunk(segment_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/sxm/http.py", line 88, in get_playlist_chunk
    data = await get_segment(segment_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/sxm/http.py", line 44, in get_segment
    data = await sxm.get_segment(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f42cee5b050 state=finished raised SegmentRetrievalException>]
2024-11-07 12:57:38.122 INFO (MainThread) [/app/venv/lib/python3.12/site-packages/sxm/client.py] Received status code 403 on playlist, renewing session
```

### How to reproduce

Play any radio station from SiriusXM. In my case I was playing Holiday Traditions.

### Music Providers

SiriusXM

### Player Providers

Chromecast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17667504/music-assistant.log)

### What version of Home Assistant Core are your running

2024.11.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
@btoconnor

**Comment by nikito** [comment]
Little update, today things appear to be working fine so far. Wondering if there was some sort of service issue that could have caused the above? May still be worth looking into to see if there's a way to prevent the exception stack, but otherwise not sure if this can be reproduced if it is due to an intermittent service issue :(

**Comment by OzGav** [comment]
@nikito thanks for the update. Indeed if this cannot be reproduced it is difficult to address.if this is still working for you then please close.

**Comment by nikito** [comment]
Monitored this over the weekend when I had streams going for many hours, issue did not occur again. Going to chalk this one up to some sort of API/Service issue at SiriusXM's side and close. :)
