### ISSUE TITLE
Server wont start - Index out of Range on ffmpeg version

### ISSUE THREAD

**Issue by eximo84** [music-assistant/hass-music-assistant#3199]
### What version of Music Assistant has the issue?

2.3.3

### What version of the Home Assistant Integration have you got installed?

2024.11.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Updated docker container today, container now wont start.

```
music-assistant  | 2024-11-18 21:13:02.387 INFO (MainThread) [music_assistant] Starting Music Assistant Server (8766aed5788d4c27baaa3f961cfd8dd5) version 2.3.2 - HA add-on: False - Safe mode: False
music-assistant  | 2024-11-18 21:13:02.390 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
music-assistant  | 2024-11-18 21:13:02.709 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
music-assistant  | 2024-11-18 21:13:02.755 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
music-assistant  | Traceback (most recent call last):
music-assistant  |   File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
music-assistant  |     await coro
music-assistant  |   File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 211, in start_mass
music-assistant  |     await mass.start()
music-assistant  |   File "/app/venv/lib/python3.12/site-packages/music_assistant/server/server.py", line 153, in start
music-assistant  |     await self.streams.setup(await self.config.get_core_config("streams"))
music-assistant  |   File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 223, in setup
music-assistant  |     ffmpeg_present, libsoxr_support, version = await check_audio_support()
music-assistant  |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
music-assistant  |   File "/app/venv/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 740, in check_audio_support
music-assistant  |     version = output.decode().split("ffmpeg version ")[1].split(" ")[0].split("-")[0]
music-assistant  |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
music-assistant  | IndexError: list index out of range
```

### How to reproduce

docker compose up

### Music Providers

n/a

### Player Providers

n/a

### Full log output

2024-11-18 21:13:02.387 INFO (MainThread) [music_assistant] Starting Music Assistant Server (8766aed5788d4c27baaa3f961cfd8dd5) version 2.3.2 - HA add-on: False - Safe mode: False
2024-11-18 21:13:02.390 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-11-18 21:13:02.709 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-11-18 21:13:02.755 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 211, in start_mass
    await mass.start()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/server.py", line 153, in start
    await self.streams.setup(await self.config.get_core_config("streams"))
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 223, in setup
    ffmpeg_present, libsoxr_support, version = await check_audio_support()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 740, in check_audio_support
    version = output.decode().split("ffmpeg version ")[1].split(" ")[0].split("-")[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-11-18 21:13:33.120 WARNING (MainThread) [aiorun] Stopping the loop
2024-11-18 21:13:33.121 INFO (MainThread) [aiorun] Entering shutdown phase.
2024-11-18 21:13:33.121 INFO (MainThread) [aiorun] Executing provided shutdown_callback.
2024-11-18 21:13:33.121 INFO (MainThread) [root] shutdown requested!
2024-11-18 21:13:33.121 INFO (MainThread) [music_assistant] Stop called, cleaning up...
2024-11-18 21:13:33.121 INFO (MainThread) [aiorun] Waiting for executor shutdown.
2024-11-18 21:13:33.121 INFO (MainThread) [aiorun] Shutting down async generators
2024-11-18 21:13:33.121 INFO (MainThread) [aiorun] Closing the loop.
2024-11-18 21:13:33.122 INFO (MainThread) [aiorun] Leaving. Bye!
2024-11-18 21:13:33.122 INFO (MainThread) [aiorun] Reraising unhandled exception
2024-11-18 21:13:33.122 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/app/venv/bin/mass", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 213, in main
    run(
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 370, in run
    raise pending_exception_to_raise
  File "/app/venv/lib/python3.12/site-packages/aiorun.py", line 272, in run
    shutdown_callback(loop)
  File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 203, in on_shutdown
    loop.run_until_complete(mass.stop())
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/server.py", line 177, in stop
    await self.streams.close()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/controllers/streams.py", line 275, in close
    await self._server.close()
  File "/app/venv/lib/python3.12/site-packages/music_assistant/server/helpers/webserver.py", line 87, in close
    await self._tcp_site.stop()
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stop'

### Additional information

Previous version was fine, i even tried using 2.3.2 docker and i get the same problem.

### What version of Home Assistant Core are your running

2024.11.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Are you using the docker compose from the docs?

**Comment by eximo84** [comment]
```
services:
  music-assistant:
    image: ghcr.io/music-assistant/server
    container_name: music-assistant
    hostname: music-assistant
    env_file: .env
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
      - /dockerdata/storage/music-assistant:/data
      - /mnt/filestore-media/Music:/media:ro
```

Only difference is I'm running privileged rather than using cap_add and security_opt

My .env just has my user and group id. Nothing special.

Like i said it was working...

**Comment by OzGav** [comment]
What previous version was working?

**Comment by eximo84** [comment]
I've built a new server in the last month so I think 2.3.0 as the older builds are before my new server went online and I pulled down a fresh image. 

I updated recently and it stopped working.

**Comment by OzGav** [comment]
What sort of container are you using?

**Comment by eximo84** [comment]
Docker on Debian VM running on Proxmox

**Comment by OzGav** [comment]
Can you get a to a command line and type `ffmpeg -version`? Have you tried installing a Ubuntu VM and then docker from there?

**Comment by eximo84** [comment]
I can't try but not sure container even starts. Will try later.

**Comment by OzGav** [comment]
Can you try and install in a Ubuntu VM

**Comment by eximo84** [comment]
I will have to setup a new vm and docker. What is the expected outcome? Is Debian and Docker not supported?

**Comment by OzGav** [comment]
No one else is reporting this problem so there is likely something wrong with your setup. The choice of OS is a significant factor so I am suggesting you try a different one.

**Comment by eximo84** [comment]
I made a backup of my docker storage and redeployed the container fresh and it starts. I'll need to set everything up but clearly some issue with my config caused this. 

Can be closed.
