### ISSUE TITLE
V.06b3: time out while playing radio

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#321]
While playing a radio stream, it spontaneously stopped, but could be resumed in the ui. In the logging this error seemed related:
``` 
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96 
First occurred: 20:11:03 (1 occurrences) 
Last logged: 20:11:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 373, in _queue_stream_runner
    self.queue.signal_next = True
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 74, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 329, in writer
    async for audio_chunk in self._get_queue_stream():
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 495, in _get_queue_stream
    async for chunk in get_media_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 448, in get_media_stream
    mass.add_job(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 74, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 423, in writer
    async for audio_chunk in music_prov.get_audio_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/tunein.py", line 169, in get_audio_stream
    async for chunk in get_radio_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 468, in get_radio_stream
    audio_chunk = await resp.content.readexactly(meta_int)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 441, in readexactly
    block = await self.read(n)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 385, in read
    await self._wait("read")
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Comment by erkr** [comment]
V06b5 first impression is that it works fine. To early to close. Add the completed label

**Comment by erkr** [comment]
I haven't seen any related errors or warnings yet, but that is why I didn't close the issue

**Comment by erkr** [comment]
Radio playback no stopped unintended a short while after resuming from a TTS message with this error:
```
Logger: music_assistant
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:244
First occurred: 18:45:14 (2 occurrences)
Last logged: 18:49:24

Job [Analyze audio for tunein://radio/s81378] failed with error Response payload is not completed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 228, in analyze_audio
    LOGGER.debug(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 74, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 206, in analyze_audio
    await writer_task
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 197, in writer
    async for audio_chunk in music_prov.get_audio_stream(streamdetails):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/tunein.py", line 169, in get_audio_stream
    async for chunk in get_radio_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 477, in get_radio_stream
    async for chunk in resp.content.iter_any():
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 35, in __anext__
    rv = await self.read_func()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

**Comment by marcelveldt** [comment]
this one should be fixed in beta 6
