### ISSUE TITLE
Voice commands no longer working in latest beta

### ISSUE THREAD

**Issue by nikito** [music-assistant/hass-music-assistant#3212]
### What version of Music Assistant has the issue?

2.0.4b6

### What version of the Home Assistant Integration have you got installed?

2024.11.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When issuing any voice command to play media, such as "Play the radio station Hallmark" or "Play the playlist 500 random tracks" the conversation hangs, and errors are displayed in the HA and MASS Logs:
HA Log snippet:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/mass/media_player.py:124
integration: Music Assistant (documentation, issues)
First occurred: 7:53:11 AM (5 occurrences)
Last logged: 8:00:07 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/mass/media_player.py", line 121, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 486, in _async_handle_play_media
    if item := await self.mass.music.get_item_by_name(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/music.py", line 623, in get_item_by_name
    search_results = await self.search(
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/music.py", line 431, in search
    await self.client.send_command(
  File "/usr/local/lib/python3.12/site-packages/music_assistant_client/client.py", line 252, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant_models.errors.MusicAssistantError: 'NoneType' object has no attribute 'search'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 124, in wrapper
    raise HomeAssistantError(error_msg) from err
homeassistant.exceptions.HomeAssistantError: 'NoneType' object has no attribute 'search'
```

MA Addon Log snippet:
```
2024-11-22 07:53:11.832 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/search: 'NoneType' object has no attribute 'search'
2024-11-22 07:55:07.342 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/search: 'NoneType' object has no attribute 'search'
2024-11-22 07:56:22.470 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/search: 'NoneType' object has no attribute 'search'
```

### How to reproduce

Issue any voice command to play media, such as "Play radio station Hallmark" or "Play playlist 500 random tracks"

### Music Providers

SiriusXM, Spotify

### Player Providers

Chromecast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17870514/music-assistant.log)

### Additional information

Ensured all intents are present, tested MASS LLM to ensure it is returning proper JSON.

### What version of Home Assistant Core are your running

2024.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
This is fixed in beta 7
