### ISSUE TITLE
ValueError: 'audiobook' is not a valid AlbumType

### ISSUE THREAD

**Issue by konikvranik** [music-assistant/hass-music-assistant#3331]
### What version of Music Assistant has the issue?

2.4.0b7

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I search music, it complains that audiobook is not a valid type

### How to reproduce

Please check log excerpt.

### Music Providers

Tidal, Spotify, YTMusic, local provider, radios.

This one seems to come from local files.

### Player Providers

Snapcast, DLNA

### Full log output

2024-12-20 12:40:37.179 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id=108, command='music/search', args={'search_query': 'a'})
Traceback (most recent call last):
  File "<string>", line 74, in __mashumaro_from_dict__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'audiobook' is not a valid AlbumType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/webserver.py", line 361, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/music.py", line 265, in search
    results_per_provider: list[SearchResults] = await asyncio.gather(
                                                ^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/music.py", line 394, in search_library
    search_results = await ctrl.search(search_query, "library", limit=limit)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/media/base.py", line 294, in search
    return await self.library_items(search=search_query, limit=limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/media/albums.py", line 142, in library_items
    result = await self._get_library_items_by_query(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/media/base.py", line 755, in _get_library_items_by_query
    self.item_cls.from_dict(self._parse_db_row(db_row))
  File "<string>", line 76, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "album_type" of type AlbumType in Album has invalid value 'audiobook'

### What version of Home Assistant Core are your running

standalone MA

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Looks like you have an audiobook in your path and this is not supported as yet. You need to remove those files

**Comment by OzGav** [comment]
And follow the template instructions and don’t post log excerpts ATTACH the FULL log

**Comment by konikvranik** [comment]
Audiobooks are part of my library and I want to listen to them using Music Assistant

**Comment by OzGav** [comment]
You cannot do that right now. It is a feature yet to be implemented

**Comment by OzGav** [comment]
You can vote here https://github.com/orgs/music-assistant/discussions/429 or https://github.com/orgs/music-assistant/discussions/2356

**Comment by acidcoke** [comment]
IMHO this is a bug. I also have this issue when using a version 2.3.4 or greater. On 2.3.3 it works without problem. Audiobooks are just played as superlong tracks.
