### ISSUE TITLE
Radio Mode not working using Spotify App

### ISSUE THREAD

**Issue by lor74** [music-assistant/hass-music-assistant#3377]
### What version of Music Assistant has the issue?

2.4.0b8

### What version of the Home Assistant Integration have you got installed?

Home Assistant Integration

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Using authentication with Spotify App I cann'ot use radio mode. If I clear the authentication and do not insert spotify app client ID radio mode is available but I have many throttling retry (as expected since I am not using my Client ID).

This is the script

```
action: music_assistant.play_media
data:
  media_id: Van Morrison
  media_type: artist
  radio_mode: true
target:
  device_id: caba6b5a7a109e62be346484957a84f9
```

In the logs attached you will found that when I do not use Client ID (having throttling ) the rado mode is working

```
2024-12-28 12:19:55.234 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue airport express di lorenzo (Airplay) - crossfade: False
2024-12-28 12:19:55.234 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: spotify://track/4beWEVoUbjSziAFPy8voaF (Van Morrison - Someone Like You) for queue airport express di lorenzo (Airplay)
```

Using Client ID I got this error
```

2024-12-28 12:22:04.115 ERROR (MainThread) [music_assistant.webserver] Error handling message: CommandMessage(message_id='0cf2a59e37444ecc94f911b1f2cf4727', command='player_queues/play_media', args={'queue_id': 'apac7f3ee81fe7', 'media': ['library://artist/201'], 'option': None, 'radio_mode': True, 'start_item': None})
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/webserver.py", line 361, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/player_queues.py", line 419, in play_media
    tracks = await self._get_radio_tracks(queue_id=queue_id, is_initial_radio_mode=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/player_queues.py", line 1454, in _get_radio_tracks
    for track in await track_ctrl.get_provider_similar_tracks(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/media/tracks.py", line 395, in get_provider_similar_tracks
    return await prov.get_similar_tracks(prov_track_id=prov_mapping.item_id, limit=limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/spotify/__init__.py", line 537, in get_similar_tracks
    items = await self._get_data(endpoint, seed_tracks=prov_track_id, limit=limit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/helpers/throttle_retry.py", line 119, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/providers/spotify/__init__.py", line 903, in _get_data
    raise MediaNotFoundError(f"{endpoint} not found")
music_assistant_models.errors.MediaNotFoundError: recommendations not found
```

### How to reproduce

Change the connection to Spotify using Client ID or leave blank the Client ID.

### Music Providers

Spotify

### Player Providers

Airplay

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/18266014/music-assistant.log)

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Duplicate https://github.com/music-assistant/hass-music-assistant/issues/3241

Add any new info to that issue
