### ISSUE TITLE
unsupported operand type(s) for *: 'NoneType' and 'int' in volume_level on line 178.

### ISSUE THREAD

**Issue by jeroenterheerdt** [music-assistant/hass-music-assistant#345]
Because of the below error, music assistant doesn't load.

Logger: homeassistant
Source: custom_components/mass/player_controls.py:178
Integration: Music Assistant (documentation, issues)
First occurred: 12:01:12 PM (16 occurrences)
Last logged: 2:49:26 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
```
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 990, in state_attributes
    if (value := getattr(self, attr)) is not None:
  File "/config/custom_components/mass/media_player.py", line 202, in volume_level
    return self.player.volume_level / 100
  File "/config/custom_components/mass/player_controls.py", line 178, in volume_level
    return self.entity.volume_level * 100
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by erkr** [comment]
Marcel fixed a player issue today that will be delivered with Beta6. The root cause of that error, seems the same (player_controls.py", line 178):
```
[548232032752] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 98, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 763, in websocket_players
    result = [item.to_dict() for item in mass.players.players]
  File "/config/custom_components/mass/websockets.py", line 763, in <listcomp>
    result = [item.to_dict() for item in mass.players.players]
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player.py", line 331, in to_dict
    "volume_level": int(self.volume_level),
  File "/config/custom_components/mass/player_controls.py", line 178, in volume_level
    return self.entity.volume_level * 100
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by marcelveldt** [comment]
should be fixed in beta 6

**Comment by erkr** [comment]
Let's wait for @jeroenterheerdt if it's solved. I haven't seen it in b6.
