### ISSUE TITLE
Error setting up entry Music Assistant for mass Traceback

### ISSUE THREAD

**Issue by LordNex** [music-assistant/hass-music-assistant#351]
After installing the latest version and adding the integration I received the following error. It appears that it's trying to create a DB table "artists" that already exists and errors. 

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:107 
Integration: Music Assistant (documentation, issues) 
First occurred: 7:49:45 PM (1 occurrences) 
Last logged: 7:49:45 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 114, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 107, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 82, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 45, in setup
    await self._migrate()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 238, in _migrate
    await db.execute(f"ALTER TABLE {TABLE_ALBUMS} ADD artists json;")
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 163, in execute
    return await connection.execute(query, values)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 274, in execute
    return await self._connection.execute(built_query)
  File "/usr/local/lib/python3.9/site-packages/databases/backends/sqlite.py", line 133, in execute
    await cursor.execute(query_str, args)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: duplicate column name: artists

**Comment by marcelveldt** [comment]
That is strange, this is an old bug. What version did you install and do you by any chance remember what version you came from?

**Comment by LordNex** [comment]
The latest version and this is my first time setting it up. I think I added it from HACS a few version back, but today was the first time I’ve added it into Integrations. But I’ve been keeping up with update but just never tried to use it until today, and received this error. Let me know if there is any other info I can give you to help.


On Jun 16, 2022, at 12:53 AM, Marcel van der Veldt ***@***.***> wrote:

﻿

That is strange, this is an old bug. What version did you install and do you by any chance remember what version you came from?

**Comment by marcelveldt** [comment]
For now, the easiest would be if you just remove the integration and re-add it. That will reset the db.
I think there's a small db schema incompatibility with some of the older versions and the current.

**Comment by marcelveldt** [comment]
Fixed the bug nevertheless because there might be others migrating from a pre 2022.6 version, fix is in next version.

**Comment by LordNex** [comment]
Yep that did it. Working good now man! Very cool! Keep up the kick ass coding 👍

**Comment by LordNex** [comment]
Easy enough. I’ll give that a try and report back


On Jun 16, 2022, at 1:11 AM, Marcel van der Veldt ***@***.***> wrote:

﻿

For now, the easiest would be if you just remove the integration and re-add it. That will reset the db.
I think there's a small db schema incompatibility with some of the older versions and the current.
