### ISSUE TITLE
v.06b7: multiple values for argument 'url' Errors  

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#359]
While casting music, what is working fine by the way, I noticed errors in the log:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/player_controls.py:473
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:58:54 (1 occurrences)
Last logged: 19:58:54

[547313428320] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 101, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 925, in websocket_playerqueue_command
    await player_queue.play()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 346, in play
    await self.resume()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 403, in resume
    await self.play_index(resume_item.item_id, resume_pos, fade_in)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 462, in play_index
    await self.queue_stream_start(index, int(seek_position), fade_in, passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 683, in queue_stream_start
    await self.player.play_url(stream.url)
  File "/config/custom_components/mass/player_controls.py", line 473, in play_url
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/quick_play.py", line 77, in quick_play
    controller.quick_play(**data)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/media.py", line 536, in quick_play
    self.play_media(
TypeError: play_media() got multiple values for argument 'url'
```

Update:I think they only occur when starting a stream

**Comment by erkr** [comment]
not seen anymore
