### ISSUE TITLE
v06b7: Spotify stream interrupted

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#360]
Probably just a rare incident, But music playback just spontaneously stopped, initially only a warning in the log:
```
Logger: music_assistant.players.stream
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py:547
First occurred: 20:10:40 (1 occurrences)
Last logged: 20:10:40

Stream error on spotify://track/70YvYr2hGlS01bKRIho1HM
```
followed a few Minutes later by this error:
```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 20:12:03 (1 occurrences)
Last logged: 20:12:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 414, in _queue_stream_runner
    self.queue.signal_next = True
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 74, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 368, in writer
    async for audio_chunk in self._get_queue_stream():
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 533, in _get_queue_stream
    async for is_last_chunk, chunk in get_media_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 441, in get_media_stream
    mass.add_job(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 74, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 406, in writer
    async for audio_chunk in music_prov.get_audio_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/spotify.py", line 317, in get_audio_stream
    raise AudioError(f"Error getting stream from librespot: {stderr.decode()}")
music_assistant.models.errors.AudioError: Error getting stream from librespot: 
```

**Comment by marcelveldt** [comment]
added some additional logging in the final release on spotify if it may happen again

**Comment by erkr** [comment]
I will keep this one open to observe a while

**Comment by marcelveldt** [comment]
you can ignore this one. its the result of the additional logging/exceptions to hunt down the spotify issue which turns out to be a region specific one.
