### ISSUE TITLE
Unable to retrieve Spotify token

### ISSUE THREAD

**Issue by drthanwho** [music-assistant/hass-music-assistant#362]
I do have Spotify Premium but it's not connecting
```
2022-06-16 23:03:36 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Music Assistant' for mass integration not ready yet: Setup failed of provider spotify: Login failed for user xxxxxxxxxx; Retrying in background
2022-06-16 23:03:41 WARNING (MainThread) [music_assistant.music.spotify] Error while retrieving Spotify token, details: b''
2022-06-16 23:03:44 WARNING (MainThread) [music_assistant.music.spotify] Error while retrieving Spotify token, details: b''
2022-06-16 23:03:46 WARNING (MainThread) [music_assistant.music.spotify] Error while retrieving Spotify token, details: b''
2022-06-16 23:03:49 WARNING (MainThread) [music_assistant.music.spotify] Error while retrieving Spotify token, details: b''
2022-06-16 23:03:51 ERROR (MainThread) [music_assistant.music.spotify] Login failed for user xxxxxxxxxx
2022-06-16 23:03:51 ERROR (MainThread) [custom_components.mass] Setup failed of provider spotify: Login failed for user xxxxxxxxxx
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 372, in _register_provider
    if await provider.setup():
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/spotify.py", line 72, in setup
    raise LoginFailed(f"Login failed for user {self.config.username}")
music_assistant.models.errors.LoginFailed: Login failed for user xxxxxxxxxx

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 107, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 84, in setup
    await self.music.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 62, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 375, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider spotify: Login failed for user xxxxxxxxxx
```

**Comment by marcelveldt** [comment]
Did it fail once or does it keep failing?
Can you please tell me a bit about your setup ? Home Assistant install method etc

**Comment by erkr** [comment]
@marcelveldt could it be related to https://github.com/music-assistant/hass-music-assistant/issues/289?

**Comment by marcelveldt** [comment]
The failure of a music provider will indeed fail the component setup, that is on purpose.
HAOS on proxmox. I suppose running on x86-64 hardware ?

The fact that it keeps failing means it can't connect to Spotify somehow using librespot.
Auth is handled by librespot too because that is what we use to get the audio from Spotify into the Music Assistant stream engine.

The fact that you're running in Proxmox tells me you're are rather technical.
Do you have the skills to open a shell in the HA container to test if you can launch the librespot executable there ?
I'm very curious if that fails somehow...

**Comment by drthanwho** [comment]
If it's by design then it's ok I guess. Just wanted to mention it. 

Indeed Proxmox is in an i7 system and HAOS using one of the OVA images. 

I will also try on another HA instance in docker to see if I get the same which might suggest is my network somehow. 

I can definitely get into the container in HAOS as well. If you can tell me what to run though would help

**Comment by drthanwho** [comment]
OK so also on a HA container instance I get the same exact error 

Then thought I would try in a 3rd instance in another house to but there I can't even install the integration. I'm getting `Config flow could not be loaded: undefined` That one is HAOS x86x64 generic image

**Comment by marcelveldt** [comment]
OK, strange, especially that last one. Any errors in the logfile that might be related ?

**Comment by drthanwho** [comment]
OK so the udefined error was just a fluke. Reinstalling the integration fixed that. 

And as for the other problem also fixed it. I was using the actual username but it wanted the email the account was using. I don't know if that's the indented case or you are able to also log in with your username instead of the email?

**Comment by marcelveldt** [comment]
Great to hear its now resolved! Strange about the email, first time i hear that but glad its working now!
