### ISSUE TITLE
Integration not starting

### ISSUE THREAD

**Issue by pauljrich1** [music-assistant/hass-music-assistant#442]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:106
Integration: Music Assistant (documentation, issues)
First occurred: 7:15:13 PM (2 occurrences)
Last logged: 7:16:09 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 113, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 106, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 87, in setup
    await self.streams.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 91, in setup
    await http_site.start()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1506, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('::', 8095, 0, 0): address in use

**Comment by marcelveldt** [comment]
What version of MA are you running ?
The error is strange because if port 8095 is taken it should auto pick the next port instead.

**Comment by pauljrich1** [comment]
2022.6.2 (just downloaded it today).  I'm running HA 2022.6.6.

**Comment by marcelveldt** [comment]
OK, that is strange. The error looks like a race condition in that case were the setup gets retried causing the port in use error. Anyways good that you found the cause.
