### ISSUE TITLE
Play button remains enabled in unavailable player

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#488]
### What version of Music Assistant has the issue?

2022.6.4

### The problem

I physically powered off my chromecasts. The players now remain visible (greyed out). That part seems as intended:
![6AB2556E-1CBF-4587-B01A-B0E37CE5029B](https://user-images.githubusercontent.com/4363599/174894906-2a99c0e1-236c-47bb-9349-eea27025f6ce.jpeg)

Then I noticed the ui player kept focus on the last player that was selected; guess that should not happen:
![4EB81FC5-511F-4B28-BAE5-F15A76A818F6](https://user-images.githubusercontent.com/4363599/174894943-71f3d969-f8dd-45e4-b2fb-08120b6dbc7d.jpeg)

As a result the play button is remained  enabled. So logically throws an error in the log when tapped

### How to reproduce

Physically Switch off players while playing

### Relevant log output

<details>
  <summary>Click to expand!</summary>

Logger: homeassistant.components.websocket_api.http.connection
Source: components/cast/media_player.py:498 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 22:39:31 (2 occurrences) 
Last logged: 22:39:40

[546028798544] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 101, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 925, in websocket_playerqueue_command
    await player_queue.play()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 346, in play
    await self.resume()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 403, in resume
    await self.play_index(resume_item.item_id, resume_pos, fade_in)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 462, in play_index
    await self.queue_stream_start(index, int(seek_position), fade_in, passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 681, in queue_stream_start
    await self.player.play_url(stream.url)
  File "/config/custom_components/mass/player_controls.py", line 503, in play_url
    await self.volume_mute(False)
  File "/config/custom_components/mass/player_controls.py", line 324, in volume_mute
    await self.entity.async_mute_volume(muted)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 704, in async_mute_volume
    await self.hass.async_add_executor_job(self.mute_volume, mute)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 498, in mute_volume
    self._chromecast.set_volume_muted(mute)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/receiver.py", line 186, in set_volume_muted
    self.send_message({MESSAGE_TYPE: "SET_VOLUME", "volume": {"muted": muted}})
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/__init__.py", line 121, in send_message
    self.send_message_nocheck(
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/__init__.py", line 133, in send_message_nocheck
    self._message_func(
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 938, in send_platform_message
    return self.send_message(
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 869, in send_message
    self._ensure_channel_connected(destination_id)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 982, in _ensure_channel_connected
    self.send_message(
  File "/usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py", line 927, in send_message
    raise NotConnected(f"Chromecast {self.host}:{self.port} is connecting...")
pychromecast.error.NotConnected: Chromecast 192.168.178.142:8009 is connecting...
</details>

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

**Comment by marcelveldt** [comment]
fix released in 2022.6.5. Thanks!
