### ISSUE TITLE
2022.6.7 Failing to start

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#544]
### What version of Music Assistant has the issue?

2022.6.7

### The problem

Not starting. Log entry is:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:63
Integration: Music Assistant (documentation, issues)
First occurred: 9:28:12 AM (1 occurrences)
Last logged: 9:28:12 AM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 110, in async_setup_entry
    stream_ip = get_local_ip_from_internal_url(hass)
  File "/config/custom_components/mass/__init__.py", line 63, in get_local_ip_from_internal_url
    return socket.gethostbyname(parsed_uri.netloc)
socket.gaierror: [Errno -2] Name does not resolve

```

### How to reproduce

Error on start

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Fixed in 2022.6.8
