### ISSUE TITLE
_get_request_host     raise NoURLAvailableError

### ISSUE THREAD

**Issue by SeByDocKy** [music-assistant/hass-music-assistant#546]
### What version of Music Assistant has the issue?

2022.6.8

### The problem

Music Assistant can't setup  anymore

### How to reproduce

Just installed last MA 2022.2.8

### Relevant log output

```Logger: homeassistant.config_entries
Source: helpers/network.py:207
First occurred: 9:35:21 AM (1 occurrences)
Last logged: 9:35:21 AM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 115, in async_setup_entry
    stream_ip = get_local_ip_from_internal_url(hass)
  File "/config/custom_components/mass/__init__.py", line 58, in get_local_ip_from_internal_url
    url = get_url(hass, allow_internal=True, allow_external=False)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 168, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 207, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by marcelveldt** [comment]
Please look more careful for duplicates please, there is an existing issue at the top of the list ;-)

https://github.com/music-assistant/hass-music-assistant/issues/545
