### ISSUE TITLE
Job Failed with Server Disconnect

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#566]
### What version of Music Assistant has the issue?

2022.6.9

### The problem

I think looking at the logs the issue is a loss of connection to the fanart.tv server. That server is flaky at the best of times so would be good if MA could more gracefully handle this sort of problem?

### How to reproduce

I expect it will be random depending upon fanart.tv server load

### Relevant log output

```
Logger: music_assistant
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:244
First occurred: 8:36:39 AM (2 occurrences)
Last logged: 8:42:57 AM

Job [Add file://artist/alanismorissette to database] failed with error Server disconnected.
Job [Add spotify://artist/1I5Cu7bqjkRg85idwYsD91 to database] failed with error Server disconnected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/artists.py", line 85, in add
    await self.mass.metadata.get_artist_metadata(item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/__init__.py", line 70, in get_artist_metadata
    if metadata := await self.fanarttv.get_artist_metadata(artist):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/fanarttv.py", line 51, in get_artist_metadata
    if data := await self._get_data(f"music/{artist.musicbrainz_id}"):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/cache.py", line 138, in wrapped
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/fanarttv.py", line 88, in _get_data
    async with self.mass.http_session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Catch exception and log a warning instead?!

**Comment by OzGav** [comment]
sounds good to me...

**Comment by marcelveldt** [comment]
The exception is already catched, hence the error message in the log.
I can change the log level to warning but other than that this is correct. 

The connection to fanart.tv is already throttled and kept to a minimum (lazy loaded).
