### ISSUE TITLE
TuneIn Radio: Stream does not start playing

### ISSUE THREAD

**Issue by pauljwhelan** [music-assistant/hass-music-assistant#589]
### What version of Music Assistant has the issue?

2022.6.10

### The problem

Fresh install of Home Assistant OS on Raspberry Pi 4 (4GB). Music Assistant installed and configured only for TuneIn radio, all available media player devices selected (Google Home, Google Home Mini, Google Chromecast Audio, Ifi Zen Stream and Onkyo TX-NR545 A/V Receiver). I have checked that the TuneIn profile is publicly available and that selected streams play (in browser obviously). No matter what device I select any stream selected will not play. In the case of Google Home devices I get the 'tone' indicating a stream is opening but nothing else.

### How to reproduce

Select any stream from Radio section of Music Assistant

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/player_controls.py:542
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:46:14 (1 occurrences)
Last logged: 15:46:14

[548289266688] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 102, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 1033, in websocket_play_media
    await player_queue.play_media(msg[MEDIA], msg[COMMAND])
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 258, in play_media
    await self.insert(queue_items, 0, passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 521, in insert
    return await self.load(queue_items, passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 505, in load
    await self.play_index(0, passive=passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 463, in play_index
    await self.player.play_url(stream.url)
  File "/config/custom_components/mass/player_controls.py", line 542, in play_url
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/quick_play.py", line 77, in quick_play
    controller.quick_play(**data)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/media.py", line 544, in quick_play
    raise PyChromecastError()
pychromecast.error.PyChromecastError

Logger: music_assistant.players.stream
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py:630
First occurred: 15:48:05 (1 occurrences)
Last logged: 15:48:05

Stream error on database://radio/10

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 15:51:10 (1 occurrences)
Last logged: 15:51:10

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 492, in _queue_stream_runner
    self.queue.signal_next = True
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 441, in writer
    async for audio_chunk in self._get_queue_stream():
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 616, in _get_queue_stream
    async for is_last_chunk, chunk in get_media_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 443, in get_media_stream
    mass.add_job(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 408, in writer
    async for audio_chunk in music_prov.get_audio_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/tunein.py", line 199, in get_audio_stream
    async for chunk in get_radio_stream(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 493, in get_radio_stream
    raise err
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 460, in get_radio_stream
    async with mass.http_session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Hi, just to exclude the obvious, did you try to stream some local stations. Not all radio streams can be played, depending toe region.

**Comment by pauljwhelan** [comment]
Hi, absolutely. I took one radio station and played the same station on the browser via TuneIn and via the Home Assistant Radio Browser Integration as well without issue. I was also able to play the same radio station on a Google Home Mini device via the Home Assistant Radio Browser integration. It only fails when using Music Assistant. I will note, on the Radio Browser integration the radio station I used had 3 streams, one was definitely AAC, which didn´t work, one had no indication of what it was, that didn´t work either but the MP3 stream did work on the Google Home Mini. I don´t know if that's a help or a hindrance but it is what happened.

**Comment by marcelveldt** [comment]
This is related to your network setup. Can you check if you have configured the "internal URL" correctly ?

- Music Assistant uses a local port (default 8095) to stream to players on the local network. 
- If you are running HA yourself in a container, make sure that you use Host network mode.
- Make sure that mediaplayers/speakers are able to reach HA on the local network.
- MA resolves the local IP from the "internal URL" field in the HA config, make sur eto set that correctly.

**Comment by pauljwhelan** [comment]
Hi Marcel, 

Re-did all my networking, got rid of AdGuard 'just in case' and finally got a station to play so I know that it is now working. However that still leaves me with a few questions. I trimmed my Favorites down to 15 stations. I was able to play them all on TuneIn in my browser, I was also able to play them all on the TuneIn app on my phone and I could cast them all to the same Google Home Mini I've been using for my testing. I could also play them all on my Onkyo A/V receiver that has TuneIn access (you actually login to your account so it is a bit different). Finally, I could play most of the stations that I could find on the Radio Browser Integration. At no time was I using a VPN or any other location 'spoofing' tech. Do you have any idea why this could be?
There was some good news! The stream I could play on my Google Home Mini device also played on my Ifi Zen Stream so I'll check Spotify and local music files and let you know so it can be added to the list of Working Devices'

**Comment by erkr** [comment]
Good to hear you have it working! I will close the issue then. We are looking forward for a list of other working devices😎

**Comment by pauljwhelan** [comment]
Eric, I have one stream working but a whole list of others that don't. Is that really working? These are all streams that work on other clients but not Music Assistant.

**Comment by erkr** [comment]
Ok I misunderstood your feedback then. I reopen the issue. Please provide a short list of station URLs that don't work for you. 
(Via the share option)

**Comment by marcelveldt** [comment]
I am very curious because so far I have never discovered a stream that isn't working. Maybe I overlooked some format somehow ?

**Comment by pauljwhelan** [comment]
Hi Eric, yes, the BBC thing sounds regional. Given that I can play the BBC stations on my A/V receiver it would appear there is a difference between accessing the favorites list 'ín the open' as we are doing here and actually logging in to my account as I do with my A/V receiver.

**Comment by jazzyisj** [comment]
I get the same error trying to play WCSX (94.7 Detroit MI).  I can play directly with Google Assistant (hey google play WCSX) which plays with the TuneIn app on cast speakers, but not through Music Assistant **or the Tune In website**.

**Comment by marcelveldt** [comment]
I finally had the time to take a look at this and fix it. 
Next version of MA (2022.7 beta 6) will contain the fix!

**Comment by marcelveldt** [comment]
OK great to hear!
A small ping here or on discord is fine, so we can extend the list of working hardware

**Comment by pauljwhelan** [comment]
> OK great to hear! A small ping here or on discord is fine, so we can extend the list of working hardware

Will do, thanks again Marcel. This is becoming a very complete music system. Respect.
