### ISSUE TITLE
[Bug] Music Assistant fails to load in 2022.7.x

### ISSUE THREAD

**Issue by dmyoung9** [music-assistant/hass-music-assistant#591]
### What version of Music Assistant has the issue?

2022.7.x

### The problem

When setting up the integration in the latest beta versions, it is failing with an error.

### How to reproduce

Add a new instance of the Music Assistant integration.

### Relevant log output

```python
This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:138
Integration: Music Assistant (documentation, issues)
First occurred: 9:07:59 AM (14 occurrences)
Last logged: 9:15:08 AM

Setup failed of provider spotify: Login failed for user drinfernoo
Setup failed of provider spotify:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/spotify.py", line 75, in setup
    int(self.config.username)
ValueError: invalid literal for int() with base 10: 'drinfernoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 385, in _register_provider
    if await provider.setup():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/spotify.py", line 80, in setup
    raise LoginFailed(f"Login failed for user {self.config.username}")
music_assistant.models.errors.LoginFailed: Login failed for user drinfernoo

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 138, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 84, in setup
    await self.music.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 62, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 388, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider spotify: Login failed for user drinfernoo
```

### What version of Home Assistant Core are your running

2022.7.0b3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
Hi, thanks for reporting. A few questions:
- Is this a fresh install? Or an update as your Spotify login fails. So, first time config, or did that same Spotify account work before? 
- Can you load MA when disabling Spotify?

**Comment by dmyoung9** [comment]
I don't have the option to "go back" and disable Spotify once it's already set up, but I have had Spotify set up for awhile now and working fine. Suddenly, with this update, I'm now getting the error.

**Comment by OzGav** [comment]
I think maybe @erkr meant go into the MA config and uncheck the Spotify source and confirm MA now starts?

**Comment by rwr39** [comment]
Same problem here....   This is a new (first time) install.  I've been reading about people having issues with librespot -- don't know if that helps. 

I tried completely removing and multiple restarts -- no joy.   I did uncheck spotify, and it comes up fine without it.  When I hit the check mark on spotify, MA disappears from the side, and shows the login error on the integration panel.



This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:138
Integration: Music Assistant (documentation, issues)
First occurred: 10:26:57 PM (8 occurrences)
Last logged: 10:33:26 PM

Setup failed of provider spotify: Login failed for user xxxx@xxxx.com
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/spotify.py", line 75, in setup
    int(self.config.username)
ValueError: invalid literal for int() with base 10: 'xxxx@xxxx.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 385, in _register_provider
    if await provider.setup():
  File "/usr/local/lib/python3.9/site-packages/music_assistant/music_providers/spotify.py", line 80, in setup
    raise LoginFailed(f"Login failed for user {self.config.username}")
music_assistant.models.errors.LoginFailed: Login failed for user xxxx@xxxx.com

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 138, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/mass.py", line 84, in setup
    await self.music.setup()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 62, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 388, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider spotify: Login failed for user xxxx@xxxx.com

**Comment by marcelveldt** [comment]
Maybe I'm asking the obvious here but you do know that free Spotify accounts are NOT supported ?

**Comment by erkr** [comment]
> I don't have the option to "go back" and disable Spotify once it's already set up, but I have had Spotify set up for awhile now and working fine. Suddenly, with this update, I'm now getting the error.

Okay, so you where using Spotify successfully in earlier releases of music assistant.
To be sure it is the authorization in Spotify that fails; does MA start if you disable Spotify in the integratie config? Are other media sources in MA working?

**Comment by erkr** [comment]
@dmyoung9: If the issue still persists, I can reopen the issue for you
