### ISSUE TITLE
Slow boot and errors on start

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#598]
### What version of Music Assistant has the issue?

2022.7.0b0

### The problem

Had a number of messages about a slow boot…HA says 144.49 secs then two errors. See below

### How to reproduce

Reboot HA

### Relevant log output

```
Logger: homeassistant.bootstrap
Source: bootstrap.py:428 
First occurred: 8:49:34 AM (3 occurrences) 
Last logged: 8:51:35 AM

Waiting on integrations to complete setup: mass
```
```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/mass/number.py:54 
Integration: Music Assistant (documentation, issues) 
First occurred: 8:51:54 AM (1 occurrences) 
Last logged: 8:51:54 AM

Unexpected exception importing platform custom_components.mass.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/mass/number.py", line 51, in <module>
    class CrossfadeDurationEntity(MassBaseEntity, NumberEntity):
  File "/config/custom_components/mass/number.py", line 54, in CrossfadeDurationEntity
    entity_description = NumberEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'native_unit_of_measurement'
```
```
Logger: homeassistant.setup
Source: setup.py:298 
First occurred: 8:51:54 AM (1 occurrences) 
Last logged: 8:51:54 AM

Unable to prepare setup for platform mass.number: Platform not found (Exception importing custom_components.mass.number).
```

### What version of Home Assistant Core are your running

2022.6.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
MA version 2022.7.x is only compatible with HA version 2022.7 +

**Comment by OzGav** [comment]
Ahhh…… I am away from home so this will have to wait as I don’t want to upset the wife is something fails! 😁

**Comment by jazzyisj** [comment]
@marcelveldt - I think if you update the homeassistant version key in [hacs.json](https://github.com/music-assistant/hass-music-assistant/blob/main/hacs.json) users won't even get the option to update if they are not on the minimum version.

**Comment by marcelveldt** [comment]
> @marcelveldt - I think if you update the homeassistant version key in [hacs.json](https://github.com/music-assistant/hass-music-assistant/blob/main/hacs.json) users won't even get the option to update if they are not on the minimum version.

Correct, but that is not what we want in beta stage. I update the minimal version as soon as the stable version of MA 2022.7 is released
