### ISSUE TITLE
Fatal errors during initial sync

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#602]
### What version of Music Assistant has the issue?

2022.7 beta 0

### The problem

At the end of the initial sync, I get the following error in the log and I have no music in the library:

![Screen Shot 351](https://user-images.githubusercontent.com/22878629/177736257-46e5c32e-2729-4181-a462-be9ba88f900f.jpg)

### How to reproduce

Initial sync

### Relevant log output
Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:245
First occurred: 6:23:48 PM (6 occurrences)
Last logged: 6:23:58 PM

Job [Library sync for provider Spotify] failed with error no such table: artists.
Job [Cleanup removed items from database] failed with error no such table: cache.
Job [Library sync for provider Filesystem] failed with error no such table: cache.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 307, in sync_library
    for db_item in await controller.db_items(True):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/media_controller.py", line 76, in db_items
    return await self.get_db_items_by_query(
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/media_controller.py", line 262, in get_db_items_by_query
    for db_row in await self.mass.database.get_rows_from_query(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/database.py", line 107, in get_rows_from_query
    return await self._db.fetch_all(query, params)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 142, in fetch_all
    return await connection.fetch_all(query, values)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 250, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 98, in fetch_all
    async with self._connection.execute(query_str, args) as cursor:
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/context.py", line 41, in aenter
    self._obj = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: no such table: artists

### What version of Home Assistant Core are your running

latest

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by RJ-Make** [comment]
I have similar errors, except Spotify (don't have that), and no media scraped. 

I can browse and play media via the browse and radio buttons. 

I'm on HA core 2022.7. 

and MA 2022.7 beta 0

<img width="1723" alt="2022-07-07_5-21-34" src="https://user-images.githubusercontent.com/8496835/177739863-bb33f475-d547-4d92-a220-b340f16c3614.png">

<img width="1727" alt="2022-07-07_5-22-18" src="https://user-images.githubusercontent.com/8496835/177739888-e2fc556d-6682-4151-8837-61f2b5bf72d4.png">

**Comment by marcelveldt** [comment]
strange, can you try to restart HA or reload the integration ?

**Comment by vk2him** [comment]
Yes I tried that - I even nuked db and resynced with same errors

**Comment by marcelveldt** [comment]
How is that possible... it is trying to sync without the db being initialized ?!
I will get my morning coffee and have another look at the code, maybe I overlooked something stupid.

**Comment by marcelveldt** [comment]
Found the issue. Fix in next version

**Comment by marcelveldt** [comment]
published beta 2 with the fix
