### ISSUE TITLE
YouTube Music Playlists do not show

### ISSUE THREAD

**Issue by Backslashh** [music-assistant/hass-music-assistant#607]
### What version of Music Assistant has the issue?

2022.7.0b1

### The problem

Music Assistant does not retrieve YouTube Music playlists (both user defines playlists or YouTube mixed ones like Supermix).

### How to reproduce

Configure YouTube Music integration.
Wait for sync to run
Open Music Assistant and select the Playlists tile. Observe "No items found".
In Music Assistant, Select Browse > YouTube Music > Playlists. Observe that operation does not complete and nothing loads.

### What version of Home Assistant Core are your running

2022.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Can you please look at your Home Assistant log ? Very good chance there will be an error in there. Can you share the error (or the logfile) here ? Thanks!

**Comment by FairyNatza** [comment]
I think I have the same issue, here is my log:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:856
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:44:55 (9 occurrences)
Last logged: 12:49:34

[547095757056] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 106, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 856, in websocket_browse
    result = await mass.music.browse(msg.get(URI))
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 209, in browse
    return await prov.browse(path)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 274, in browse
    return [x async for x in self.get_library_playlists()]
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 274, in <listcomp>
    return [x async for x in self.get_library_playlists()]
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 234, in get_library_playlists
    playlist.metadata.description = item["description"]
KeyError: 'description'

Maybe not every playlist has a description?

**Comment by FairyNatza** [comment]
I also have the problem that albums wont load.
On Home Assistant restart:

```
Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:245
First occurred: 13:03:31 (1 occurrences)
Last logged: 13:03:31

Job [Library sync for provider Youtube Music] failed with error 'gridRenderer'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 315, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 155, in get_library_albums
    response_albums = response["contents"]["singleColumnBrowseResultsRenderer"][
KeyError: 'gridRenderer'
```

If I try to open the albums:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:856
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:07:41 (1 occurrences)
Last logged: 13:07:41

[547812136592] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 106, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 856, in websocket_browse
    result = await mass.music.browse(msg.get(URI))
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 209, in browse
    return await prov.browse(path)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 268, in browse
    return [x async for x in self.get_library_albums()]
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 268, in <listcomp>
    return [x async for x in self.get_library_albums()]
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 155, in get_library_albums
    response_albums = response["contents"]["singleColumnBrowseResultsRenderer"][
KeyError: 'gridRenderer'
```

**Comment by Symbiot78** [comment]
same here I believe.. it just runs the graphic over the screen over and over again.

`2022-07-08 23:33:00 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140373425592816] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/mass/websockets.py", line 106, in async_get_mass_func
await orig_func(hass, connection, msg, mass)
File "/config/custom_components/mass/websockets.py", line 856, in websocket_browse
result = await mass.music.browse(msg.get(URI))
File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 209, in browse
return await prov.browse(path)
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 274, in browse
return [x async for x in self.get_library_playlists()]
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 274, in <listcomp>
return [x async for x in self.get_library_playlists()]
File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 216, in get_library_playlists
response_playlists = response["contents"]["singleColumnBrowseResultsRenderer"][
IndexError: list index out of range`

**Comment by MarvinSchenkel** [comment]
Fixed in beta 4, please report a new issue if you encounter this issue again.
