### ISSUE TITLE
Setup failed of provider ytmusic: '__Secure-3PAPISID'

### ISSUE THREAD

**Issue by FairyNatza** [music-assistant/hass-music-assistant#609]
### What version of Music Assistant has the issue?

2022.7.0b1

### The problem

The Inti fails when I activate YouTube Music. I have copied the cookie several times. In a private browser sessions and with many new logins. The __Secure-3PAPISID also exists in my copied cookie.

The cookie also works for https://github.com/KoljaWindeler/ytube_music_player, but I think they had the problem in some versions too.

### How to reproduce

Configure Music Assistant, enable YouTube Music, enter a username, insert the cookie and finish the configuration.

### Relevant log output

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:149
Integration: Music Assistant (documentation, issues)
First occurred: 10:30:10 (44 occurrences)
Last logged: 11:02:20

Setup failed of provider ytmusic: '__Secure-3PAPISID'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 407, in _register_provider
    if await provider.setup():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 54, in setup
    await self._initialize_headers(cookie=self.config.password)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 469, in _initialize_headers
    sapisid = ytmusicapi.helpers.sapisid_from_cookie(cookie)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/helpers.py", line 82, in sapisid_from_cookie
    return cookie['__Secure-3PAPISID'].value
KeyError: '__Secure-3PAPISID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 149, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 84, in setup
    await self.music.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 73, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 410, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider ytmusic: '__Secure-3PAPISID'

### What version of Home Assistant Core are your running

2022.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by LukaszP2** [comment]
I try new one and everythis goes ok.

**Comment by FairyNatza** [comment]
Okay, I looked in your code and found out you only need to copy the "cookie:" part of the header.
I followed this link https://ytmusicapi.readthedocs.io/en/latest/setup.html#copy-authentication-headers, to grab the information, but missed the "Just grab the "cookie"." comment under the link in https://github.com/music-assistant/hass-music-assistant/discussions/433#discussioncomment-3104107.
