### ISSUE TITLE
Youtube Music is not working

### ISSUE THREAD

**Issue by dazWiLLiE** [music-assistant/hass-music-assistant#615]
### What version of Music Assistant has the issue?

2022.7.0b1

### The problem

Youtube Music provider in Music assistant is empty.

### How to reproduce

I setup the Youtube Music provider with my name, and the contents of the "cookie".

### Relevant log output

```
2022-07-08 14:03:39 ERROR (MainThread) [music_assistant] Job [Library sync for provider Youtube Music] failed with error list index out of range.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 315, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 122, in get_library_artists
    response_artist = response["contents"]["singleColumnBrowseResultsRenderer"][
IndexError: list index out of range
```

### What version of Home Assistant Core are your running

2022.7.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by dazWiLLiE** [comment]
It fixed itself.

After I added a new album to my library in the Youtube Music app, I suddenly could browse the Youtube Music category in MA.
