### ISSUE TITLE
Spotify disappeared as media source + mass.number failure

### ISSUE THREAD

**Issue by FrankSchoene** [music-assistant/hass-music-assistant#616]
### What version of Music Assistant has the issue?

2022.7.0b1

### The problem

Spotify disappeared as media source but I can search it in the respective integration.

Also I get this in the logs:

Unable to prepare setup for platform mass.number: Platform not found (Exception importing custom_components.mass.number).

and this

Unexpected exception importing platform custom_components.mass.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/mass/number.py", line 51, in <module>
    class CrossfadeDurationEntity(MassBaseEntity, NumberEntity):
  File "/config/custom_components/mass/number.py", line 54, in CrossfadeDurationEntity
    entity_description = NumberEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'native_unit_of_measurement'

### How to reproduce

Just updated to the latest version of the integration

### Relevant log output

Unexpected exception importing platform custom_components.mass.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/mass/number.py", line 51, in <module>
    class CrossfadeDurationEntity(MassBaseEntity, NumberEntity):
  File "/config/custom_components/mass/number.py", line 54, in CrossfadeDurationEntity
    entity_description = NumberEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'native_unit_of_measurement'

### Additional information

no

### What version of Home Assistant Core are your running

2022.6.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Please upgrade to HA 2022.7 ;-)

**Comment by FrankSchoene** [comment]
Thanks Marcel, will wait until 2022.7 is stable.

**Comment by marcelveldt** [comment]
2022.7 stable has been released a few days ago

**Comment by marcelveldt** [comment]
Ok, makes sense. In that case I'll close here.
