### ISSUE TITLE
Unidentified Image Error

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#624]
### What version of Music Assistant has the issue?

2022.7.0b3

### The problem

Error in log related to image errors

### How to reproduce

Occurs on start

### Relevant log output

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/mass/panel.py:91
Integration: Music Assistant (documentation, issues)
First occurred: 12:25:25 PM (4 occurrences)
Last logged: 12:31:52 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/config/custom_components/mass/panel.py", line 91, in get
    data = await mass.metadata.get_thumbnail(url, size=size)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/metadata/__init__.py", line 229, in get_thumbnail
    thumbnail = await create_thumbnail(self.mass, path, size)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/images.py", line 49, in create_thumbnail
    return await mass.loop.run_in_executor(None, _create_image)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/images.py", line 43, in _create_image
    img = Image.open(data)
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f6141a8e0>
```

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
It is probably right but a bit cumbersome that the file is not logged that has the issue...

**Comment by marcelveldt** [comment]
Can you please check if this is fixed in the 2022.7 beta 4 ?

**Comment by OzGav** [comment]
I just deleted and recreated my database and this error did not occur so I will close. Thanks Marcel!

**Comment by marcelveldt** [comment]
> I just deleted and recreated my database and this error did not occur so I will close. Thanks Marcel!

OK, I'm glad it is fixed but not so much that a recreation of the db was needed. My goal is to prevent that.
I think there are a few edge cases left to fix and then that goal is reached.

**Comment by OzGav** [comment]
I wasn’t saying that I had to do that to fix it just that a full database rebuild didn’t result in that error occurring so I think it is safe to say it is fixed…although I’ll keep my eye on the logs 😉
