### ISSUE TITLE
Youtube failed

### ISSUE THREAD

**Issue by PedroKTFC** [music-assistant/hass-music-assistant#628]
### What version of Music Assistant has the issue?

 2022.7.0b1

### The problem

I (think!) I've followed your instructions for configuring Youtube music but I get the error logs below. Note I am now only getting the second log but I have had the first one several times previously as I tried to work out.

Note if I go to Playlists I can get to and play something so I'm pretty sure my configuration is correct.

Can you help? Thanks

### How to reproduce

Browse to Youtube, then click on Artist or Albums

### Relevant log output

```
Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:245
First occurred: 09:45:51 (4 occurrences)
Last logged: 11:04:37

Job [Library sync for provider Youtube Music] failed with error 'musicShelfRenderer'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 315, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 122, in get_library_artists
    response_artist = response["contents"]["singleColumnBrowseResultsRenderer"][
KeyError: 'musicShelfRenderer'
```
and

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:856
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:19:30 (3 occurrences)
Last logged: 11:25:28

[547005244768] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 106, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 856, in websocket_browse
    result = await mass.music.browse(msg.get(URI))
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 209, in browse
    return await prov.browse(path)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 266, in browse
    return [x async for x in self.get_library_artists()]
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 266, in <listcomp>
    return [x async for x in self.get_library_artists()]
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic.py", line 122, in get_library_artists
    response_artist = response["contents"]["singleColumnBrowseResultsRenderer"][
KeyError: 'musicShelfRenderer'

```

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by MarvinSchenkel** [comment]
Fixed in beta 4, please upgrade and report a new issue if you encounter this bug again.
