### ISSUE TITLE
Unable to browse Media Assistant library when using an automation to play music

### ISSUE THREAD

**Issue by skipishere** [music-assistant/hass-music-assistant#634]
### What version of Music Assistant has the issue?

2022.7.0b1

### The problem

When attempting to correct my automations after the database rebuild (as playlist Ids have changed) and clicking in the UI I got errors. Manually changing the IDs in the YAML seems to work around some of the blocking issues but had to trial and error discover the new IDs for playlists (example my playlist use to be ID 4 before the rebuild from 2022.6 -> 2022.7 and is now ID 1)

I've found this occurs regardless if I'm changing an automation or creating a new media play in existing automation or even in a new automation, and occurs no matter what option I select in Media Assistant option 
![image](https://user-images.githubusercontent.com/26724777/178143108-d0fd0ff8-def1-48ad-b6de-1a28727bd30b.png)

### How to reproduce

Add action -> Play media -> Select any media player -> Pick media -> Media Assistant -> Playlists

Then the UI comes up with Media Browsing Error - Unknown error
![image](https://user-images.githubusercontent.com/26724777/178143024-df78e49b-2f5f-469b-bf20-7981c41b5bc3.png)

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_source.py:195
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:04:30 (4 occurrences)
Last logged: 12:22:59

[547585886672] Error handling message: Unknown error (unknown_error)
[547043388016] Error handling message: Unknown error (unknown_error)
[547074932448] Error handling message: Unknown error (unknown_error)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1218, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/mass/media_player.py", line 434, in async_browse_media
    return await media_source.async_browse_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 112, in async_browse_media
    item = await _get_media_item(hass, media_content_id, None).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 86, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/mass/media_source.py", line 139, in async_browse_media
    return await self._build_playlists_listing(mass)
  File "/config/custom_components/mass/media_source.py", line 195, in _build_playlists_listing
    for item in await mass.music.playlists.library()
AttributeError: 'PlaylistController' object has no attribute 'library'

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by skipishere** [comment]
Looks like this is fixed in a later beta version as I've just tested this in b3, will close this
