### ISSUE TITLE
YouTube Music Setup Error

### ISSUE THREAD

**Issue by gettingerr** [music-assistant/hass-music-assistant#636]
### What version of Music Assistant has the issue?

2022.7.0b3

### The problem

Followed the instructions for getting the Request Headers (and they work on a different youtube music integration) but with Music Assistant, when I input and finish setup, I get the error: Retrying setup: Setup failed of provider ytmusic: '__Secure-3PAPISID'

I have tried a couple times to clear and re-input, and have tried using headers from Firefox and Chrome to no avail. Also attempted my username with and without "@gmail.com"

Full Log from Home Assistant:

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:149
Integration: Music Assistant ([documentation](https://github.com/music-assistant/hass-music-assistant), [issues](https://github.com/music-assistant/hass-music-assistant/issues))
First occurred: 8:10:25 AM (22 occurrences)
Last logged: 8:27:31 AM

Setup failed of provider ytmusic: '__Secure-3PAPISID'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 407, in _register_provider
    if await provider.setup():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 69, in setup
    await self._initialize_headers(cookie=self.config.password)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 289, in _initialize_headers
    sapisid = ytmusicapi.helpers.sapisid_from_cookie(cookie)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/helpers.py", line 82, in sapisid_from_cookie
    return cookie['__Secure-3PAPISID'].value
KeyError: '__Secure-3PAPISID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 149, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 84, in setup
    await self.music.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 73, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 410, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider ytmusic: '__Secure-3PAPISID'

### How to reproduce

Go through the setup process for YouTube Music. 

Follow directions for obtaining cookie from:https://ytmusicapi.readthedocs.io/en/latest/setup.html#copy-authentication-headers

Finish setup

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

ODROID

**Comment by marcelveldt** [comment]
https://github.com/music-assistant/hass-music-assistant/discussions/606

**Comment by jiripaskov** [comment]
It is not properly described, what exactly should be copied from browser in Request Headers...

**Comment by MarvinSchenkel** [comment]
Updated the docs for for clarity, please have a look at the docs again #606

**Comment by MarvinSchenkel** [comment]
Yay, you managed to successfully log in :). Also updated the docs with your edge case #606
