### ISSUE TITLE
Can't configure

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#64]
Hi 

Can't configure Music Assistant. So I stripped my settings to just one Chromecast:
![image](https://user-images.githubusercontent.com/4363599/167267078-4d2302f5-1f86-4a6a-8ddd-8d8968c71249.png)

And then only my Spotify account:
![image](https://user-images.githubusercontent.com/4363599/167267127-19a57cfb-cb7e-4f0b-b5ef-a5b9f986d150.png)

After applying these settings:
![image](https://user-images.githubusercontent.com/4363599/167267149-b52b1206-2bd6-455e-9a3b-a7db1830fe3d.png)

But the integration has an error:
![image](https://user-images.githubusercontent.com/4363599/167267028-67eb1052-5337-4458-8c96-0c43cd438263.png)

Don't see hints in the logfile. Reload doesn't help.
Probably something I missed.
Eric

**Comment by marcelveldt** [comment]
There should be a full message/error in the log. Can you please hunt for it so I can have a further look ?

**Comment by erkr** [comment]
Hi Marcel

I see this error, These devices were originally in the list, but I stripped them from the settings :
```
Logger: homeassistant.config_entries
Source: config_entries.py:366
First occurred: 20:03:47 (5 occurrences)
Last logged: 20:29:04

Config entry 'WoonkamerTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
Config entry 'SlaapkamerTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
Config entry 'Music Assistant' for mass integration not ready yet: 'NoneType' object is not subscriptable; Retrying in background
```

**Comment by marcelveldt** [comment]
I think you only see the full stack trace if you press the "view full log" button

**Comment by erkr** [comment]
```
[services.d] starting services
[services.d] done.
2022-05-07 20:03:32 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-07 20:03:32 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration mass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-07 20:03:32 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-07 20:03:32 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-07 20:03:32 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration zha_toolkit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-07 20:03:47 WARNING (MainThread) [homeassistant.config_entries] Config entry 'WoonkamerTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
2022-05-07 20:03:47 WARNING (MainThread) [homeassistant.config_entries] Config entry 'SlaapkamerTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
2022-05-07 20:03:50 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 45, in get
    return await WebSocketHandler(request.app["hass"], request).async_handle()
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 146, in async_handle
    await wsock.prepare(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_ws.py", line 138, in prepare
    payload_writer = await super().prepare(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 131, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 76, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2022-05-07 20:04:40 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: fritz

```

**Comment by marcelveldt** [comment]
I'm afraid that stacktrace is not from Music Assistant.
I'll do some testing to see if I can found out what's going on. I've only published this integration today (after 3 years of work) so sure there is still a bug somewhere ;-)

**Comment by erkr** [comment]
I fully understand :-) 
The fact it can be tried in parallel with my current Spotify solution convinced me to give it a try immediately.
Let me know if I can give more info. I have limited all logging to warnings/errors only ( to limit the logging). But I can temporary enable detailed logging if you indicate what to enable:
```
logger:
  default: warning
  logs:
    fritzconnection: info
```
Maybe somthing like: custom_components.mass?

**Comment by marcelveldt** [comment]
Yeah, try to enable (info or debug) logging for custom_components.mass and 'music_assistant'.
Normally I'd expect the error you mentioned above to be printed in full in the log.

![Schermafbeelding 2022-05-07 om 21 00 51](https://user-images.githubusercontent.com/6389780/167268251-b96ab09a-1d17-4efd-9c48-2e7fdb38cb32.png)

**Comment by erkr** [comment]
I will give it a run :-) and come back

**Comment by erkr** [comment]
Hi
Changed the loggings to debug. At 21:10 I tried to reconfigure. That only reulsted in one line mass logging:
```
2022-05-07 21:04:07 WARNING (MainThread) [homeassistant.config_entries] Config entry 'WoonkamerTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
2022-05-07 21:04:07 WARNING (MainThread) [homeassistant.config_entries] Config entry 'SlaapkamerTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
2022-05-07 21:04:13 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2022-05-07 21:04:15 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
2022-05-07 21:04:15 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Music Assistant' for mass integration not ready yet: 'NoneType' object is not subscriptable; Retrying in background
2022-05-07 21:05:04 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
2022-05-07 21:05:06 ERROR (MainThread) [custom_components.hacs] <HacsTask prosess_queue> failed: <Integration r-renato/hass-xiaomi-mi-flora-and-flower-care> Repository has been requested to be removed.
2022-05-07 21:05:14 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
2022-05-07 21:05:19 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x84'
2022-05-07 21:05:34 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
2022-05-07 21:06:14 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
2022-05-07 21:06:19 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x93'
2022-05-07 21:07:34 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
2022-05-07 21:08:54 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
2022-05-07 21:09:19 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0xc9'
2022-05-07 21:09:49 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0xcf'
2022-05-07 21:10:14 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
111

**Comment by marcelveldt** [comment]
I reproduced it. Only happens on fresh setup. I will fix it now and provide update

**Comment by erkr** [comment]
Thanks. Glad you can reproduce. Looking forward for the update.
Have a nice day

**Comment by marcelveldt** [comment]
I have released version 1.0.8 just now which has the fix for this issue. Thanks!

**Comment by erkr** [comment]
Great and really fast. I will give it a try :-)

**Comment by erkr** [comment]
I'm in :-)

**Comment by marcelveldt** [comment]
Cool! Let me know if you find something else
