### ISSUE TITLE
Disc Number error in logs

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#653]
### What version of Music Assistant has the issue?

2022.7.b4

### The problem

Noticed an error in the logs. I had not seen this error before 2022.7.b4

### How to reproduce

Not sure. Appeared after a reboot after installing 2022.7.b4

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:328 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 8:24:51 AM (4 occurrences) 
Last logged: 8:27:34 AM

[547312376112] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 106, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 328, in websocket_album_tracks
    for item in await mass.music.albums.tracks(msg[ITEM_ID], msg[PROVIDER])
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 63, in tracks
    tracks = itertools.chain.from_iterable(await asyncio.gather(*coros))
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 120, in get_provider_album_tracks
    items = await prov.get_album_tracks(item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/filesystem.py", line 317, in get_album_tracks
    track.disc_number = album_mapping.disc_number
AttributeError: 'NoneType' object has no attribute 'disc_number'

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Hmmm that is an interesting error as it basically means that the album mapping for that track is empty.
This might as well be a race condition somewhere but please keep an eye on it. It happens in the 'get_album_tracks' so when you browse an album, either by playing it or by viewing it in the frontend.

So if you experience an album with missing tracks someday in the frontend, please let me know.
In that case I can take a look at the db what has happened.

**Comment by OzGav** [comment]
Ok I’ll have a look around at the ones I was browsing and see if anything is obvious….

**Comment by OzGav** [comment]
Actually I just remembered there is an album with no tracks at all. I am pretty sure it was ok after previous scans. After viewing it the error was logged again. Anything you would like me to do?

**Comment by marcelveldt** [comment]
Can you have another look if this is fixed with beta8?

**Comment by OzGav** [comment]
Not seeing this error in the logs anymore so will close.
