### ISSUE TITLE
ProviderType.DATABASE is not available

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#662]
### What version of Music Assistant has the issue?

2022.7.0b5

### The problem

Looks similar to this issue https://github.com/music-assistant/hass-music-assistant/issues/564

I used Audacity to resave some flac music files that had missing durations. When I do a REFRESH on the album this error appears in the logs.

### How to reproduce

As above

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:245
First occurred: 9:43:51 PM (1 occurrences)
Last logged: 9:43:51 PM

Job [Add spotify://artist/4gzpq5DPGxSnKTe4SA8HAU to database] failed with error Provider ProviderType.DATABASE is not available.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/artists.py", line 97, in add
    await self.match_artist(db_item)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/artists.py", line 116, in match_artist
    if await self._match(db_artist, provider):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/artists.py", line 289, in _match
    prov_artist = await self.get_provider_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/media_controller.py", line 341, in get_provider_item
    provider = self.mass.music.get_provider(provider_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 130, in get_provider
    raise ProviderUnavailableError(f"Provider {provider_id} is not available")
music_assistant.models.errors.ProviderUnavailableError: Provider ProviderType.DATABASE is not available

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
its a race conditions due to you refreshing the item and the UI opening that same item.
Should be fixed in next release as I tried to wade my way through the edge cases we talked about and especially made the whole "I've adjusted some tags" flow more robust.
