### ISSUE TITLE
error 'duration_seconds' in Library sync for Youtube Music

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#669]
### What version of Music Assistant has the issue?

2022.7b6

### The problem

After the upgrade to beta 6 I saw an error in the log

### How to reproduce

Restart

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:245 
First occurred: 09:38:47 (1 occurrences) 
Last logged: 09:38:47

Job [Library sync for provider Youtube Music] failed with error 'duration_seconds'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 298, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 140, in get_library_playlists
    yield await self._parse_playlist(playlist)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 409, in _parse_playlist
    playlist.metadata.checksum = playlist_obj["duration_seconds"]
KeyError: 'duration_seconds'

### What version of Home Assistant Core are your running

2022.7.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by MarvinSchenkel** [comment]
Already pushing a fix as we speak :)
