### ISSUE TITLE
Start playlist from Home Assistant Media

### ISSUE THREAD

**Issue by ENGBERG80** [music-assistant/hass-music-assistant#677]
### What version of Music Assistant has the issue?

2022.6.10

### The problem

I have an Automation that starts a playlist from Spotify, it runs through Home Assistant Media player. But it does nor work anymore. When i try to start a playlist through Media player it just respons with a error message.

### How to reproduce

Comes with error message when you try to start a playlist from Home Assistant Media player

### What version of Home Assistant Core are your running

2022.7.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Hi @ENGBERG80 
We will look into that. Please include the error from your log in this issue.
Additionally add the party of your automation (the service call) that fails to see if that is composed correctly.
Best Eric

**Comment by ENGBERG80** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_source.py:195 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 22.24.37 (6 occurrences) 
Last logged: 23.27.21

[547545610608] Error handling message: Unknown error (unknown_error)
[547138084032] Error handling message: Unknown error (unknown_error)
[547138085856] Error handling message: Unknown error (unknown_error)
[547325999952] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1218, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/mass/media_player.py", line 434, in async_browse_media
    return await media_source.async_browse_media(
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 112, in async_browse_media
    item = await _get_media_item(hass, media_content_id, None).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 86, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/mass/media_source.py", line 139, in async_browse_media
    return await self._build_playlists_listing(mass)
  File "/config/custom_components/mass/media_source.py", line 195, in _build_playlists_listing
    for item in await mass.music.playlists.library()
AttributeError: 'PlaylistController' object has no attribute 'library'

**Comment by marcelveldt** [comment]
I guess you are on one of the early 2022.7 beta's of MA. Please update to the latest beta 6 and the above error is solved.

**Comment by erkr** [comment]
Thanks for sharing these errors. In order to help Marcel in diagnosing/reproducing the issue, it is helpful to share the automation call that triggers them as well.
Best Eric

**Comment by marcelveldt** [comment]
Fix available in the 2022.7 release!
Please reopen (or create a new issue) if you still may experience issues. Thanks!
