### ISSUE TITLE
Add to queue broken

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#683]
### What version of Music Assistant has the issue?

2022.7.0b7

### The problem

When I tried to add a Spotify playlist to the empty queue of CC group, nothing happened and there was an error in the log

### How to reproduce

Add to queue

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:956 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 19:56:01 (2 occurrences) 
Last logged: 19:56:36

[545782703216] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 106, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 956, in websocket_playerqueue_items
    result = [x.to_dict() for x in queue.items]
  File "/config/custom_components/mass/websockets.py", line 956, in <listcomp>
    result = [x.to_dict() for x in queue.items]
AttributeError: 'NoneType' object has no attribute 'to_dict'

### What version of Home Assistant Core are your running

2022.7.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Still not working in beta 8
Same errors

**Comment by marcelveldt** [comment]
this one is fixed in beta9

**Comment by erkr** [comment]
Yep, thanks!
