### ISSUE TITLE
Spotify Failed to setup

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#695]
### What version of Music Assistant has the issue?

2022.7.0b7

### The problem

Error in the log that Spotify has failed to setup. I only noticed this in the last few days so I am not ruling out a network issue at my end (I do ad blocking that sometimes catches other things) but I thought I would raise it regardless. Perhaps the error could be caught?

### How to reproduce

Occurs for me on boot and then at intervals as the setup tries again.

### Relevant log output

This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:149
Integration: Music Assistant (documentation, issues)
First occurred: 10:35:11 AM (2 occurrences)
Last logged: 10:36:28 AM

Setup failed of provider spotify:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/spotify.py", line 530, in _get_token
    await librespot.wait()
  File "/usr/local/lib/python3.10/asyncio/subprocess.py", line 134, in wait
    return await self._transport._wait()
  File "/usr/local/lib/python3.10/asyncio/base_subprocess.py", line 235, in _wait
    return await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 413, in _register_provider
    if await provider.setup():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/spotify.py", line 70, in setup
    token = await self.get_token()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/spotify.py", line 493, in get_token
    tokeninfo = await asyncio.wait_for(self._get_token(), 5)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 149, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 84, in setup
    await self.music.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 73, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 416, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider spotify: 

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
This has stopped occuring. So closing

**Comment by erkr** [comment]
Thx!
