### ISSUE TITLE
Configuration doesn't reload after making changes

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#70]
Hi

When rerunning the configuration the integration crashed (After a restart it works again!):
```
2022-05-07 22:12:58 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Music Assistant for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 395, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-05-07 22:12:58 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Music Assistant for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 87, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-05-07 22:12:58 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Music Assistant for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 87, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-05-07 22:12:58 INFO (MainThread) [music_assistant.mass] Stop called, cleaning up...
2022-05-07 22:12:58 INFO (MainThread) [music_assistant.mass.stream] Streamserver exited.
```

**Comment by marcelveldt** [comment]
Thanks, I'll have a look at it

**Comment by erkr** [comment]
The info for the spotify assistant is probably not correct (i mixed the assistant names). It was just reconfiguring I guess

**Comment by marcelveldt** [comment]
This only happens at reload ? There's nothing in error ?

**Comment by erkr** [comment]
After a restart, there are no errors! Music assistant is loaded. Not yet used it although ;-)

**Comment by marcelveldt** [comment]
OK, strange. I'll have a look at it on my testmachine later if I can reproduce.

Now play some music ;-)

**Comment by erkr** [comment]
Yes I'm going to do that. I now have my Spotify playlists and TuneIn favorites in the menu. So that looks promising
One question: I have ca 10.000 local media mp3 files( 60GB ). Is it safe to add them or will it choke on that?!

**Comment by erkr** [comment]
And yes I have my fist spotify playlist running 👍 I'm so happy 🥇

**Comment by marcelveldt** [comment]
Great to hear, now let's hope that playback does also work.
About the large music collection: It shouldn't choke but I did not try it with such a large collection. I think it will be busy for a while indexing it all but I made sure while coding that stuff is throttled and resource friendly. The database model is also very simple and optimized for responsiveness. In other words: Just try ?

**Comment by erkr** [comment]
Including my local collection is the next step. Good news with respect to this issue. Since v109 I can update the configuration of Music Assistant without a reloading errors!
