### ISSUE TITLE
Playback Restart Error When Track Started by Another Source After Pause

### ISSUE THREAD

**Issue by RJ-Make** [music-assistant/hass-music-assistant#703]
### What version of Music Assistant has the issue?

2022.5.7

### The problem

1) Start Playing Track From Phone (Plex) to a CCA Speaker
2) Pause Track in MASS
3) Start Track in MASS
4) Track Does Not Re-start and Produces the Error Below

NOTE: This does not take place with the HA's default media player

### How to reproduce

See above

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/media_player.py:329
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:49:57 PM (1 occurrences)
Last logged: 3:49:57 PM

[140523825135968] Item not found: database/1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/mass/media_player.py", line 329, in async_media_play
    await self.player.active_queue.play()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 391, in play
    await self.resume()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 454, in resume
    await self.play_index(0)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 519, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 711, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 272, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 238, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 225, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 248, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/tracks.py", line 36, in get
    track = await super().get(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/media_controller.py", line 170, in get
    raise MediaNotFoundError(
music_assistant.models.errors.MediaNotFoundError: Item not found: database/1

### What version of Home Assistant Core are your running

2022.7.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Not sure I understand this...
So you start playing a track from MA and somehow you like MA to also be able to control this ?

I'm not sure if I even want to support that scenario.
You can use the "underlying entity" if you want to control the origin source ?

**Comment by RJ-Make** [comment]
I don't understand the underlying framework of any of this, so I'm just going by observation. 

Perhaps this scenario, while possible with the native Google HA entity, is simply not with MASS. 

MASS can control volume, and Pause, but not UN-Pause (throws error).  

If not possible, perhaps all MASS entity transport functions can be locked out if the track didn't originate from within MASS?

**Comment by marcelveldt** [comment]
Just to be clear.. You did start/resume the playback from MA or HA ?

**Comment by RJ-Make** [comment]
> Just to be clear.. You did start/resume the playback from MA or HA ?


Failing Scenario (MASS Entity)

1) Start Track From Phone (Plexamp) to a CCA Speaker
2) Pause Track using MASS Entity
3) Unpause Track using MASS Entity
4) Track Does Not Re-start and Produces the Error.

Working Scenario (HA Google Entity)

1) Start Playing Track From Phone (Plexamp) to a CCA Speaker
2) Pause Track using HA Entity
3) Unpause Track using HA Entity
4) Works (track resumes playing). 

If the track is initially started using a MASS entity it unpauses (resumes playing) fine.

Hope this helps.

**Comment by marcelveldt** [comment]
Found the bug and just fixed it. Available in next update (beta10)

**Comment by marcelveldt** [comment]
Fix available in the 2022.7 release!
Please reopen (or create a new issue) if you still may experience issues. Thanks!
