### ISSUE TITLE
Local Tracks Disappearing on Refresh

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#704]
### What version of Music Assistant has the issue?

2022.7.0b9

### The problem

This problem has been seen before and it appears that https://github.com/music-assistant/music-assistant-lib/pull/429 has not fixed it. When refreshing an artist all local tracks appear and errors appear in the logs. (See the first two log entries)

Havig said that before submitting this is tried a FORCE FULL SYNC which brought everything back but the same behaviour occurs. I went to another artist ALANIS MORRISETTE which was showing only local tracks. On the first REFRESH ITEM the Spotify Tracks appeared in the list along with the local tracks but then I did a refresh again and the local tracks disappeared. I thought I would try deleting the artist and rescanning but when I selected DELETE ITEM FROM DATABASE the third error shown below occurred. I saw this also when I deleted a spurious album entry so I am wondering if it occurs because you delete the album but MA stays on that page so it might be trying to reload info for the page which no longer exists. I think when you delete it should automatically move you up one level in the UI

### How to reproduce

Go to ARTIST view and find an artist that has local and Spotify tracks. Select REFRESH ITEM in top right context menu. Observe all local tracks disappear from list. This does not occur with all artists.

### Relevant log output

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:247
First occurred: 11:36:21 AM (2 occurrences)
Last logged: 11:40:05 AM

Job [Add file://album/2celloscelloverse to database] failed with error Artist is missing provider id(s).
Job [Add file://album/acdc74jailbreak to database] failed with error Artist is missing provider id(s).
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 98, in add
    db_item = await self.add_db_item(item, overwrite_existing)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 188, in add_db_item
    return await self.update_db_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 230, in update_db_item
    album_artists = await self._get_album_artists(item, overwrite=True)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 349, in _get_album_artists
    album_artists.add(await self._get_artist_mapping(artist, overwrite))
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 361, in _get_artist_mapping
    artist = await self.mass.music.artists.add_db_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/artists.py", line 203, in add_db_item
    assert item.provider_ids, "Artist is missing provider id(s)"
AssertionError: Artist is missing provider id(s)
------------------------------------------------------------------------------------------------------------------
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:762
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:36:21 AM (2 occurrences)
Last logged: 11:40:05 AM

[547040359040] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 762, in websocket_item
    if item := await mass.music.get_item_by_uri(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 225, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 248, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 36, in get
    if album.artist:
AttributeError: 'NoneType' object has no attribute 'artist'
------------------------------------------------------------------------------------------------------------------
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:867
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:18:15 PM (1 occurrences)
Last logged: 12:18:15 PM

[546753123456] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 867, in websocket_delete_db_item
    await mass.music.delete_db_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/__init__.py", line 287, in delete_db_item
    await ctrl.delete_db_item(db_item_id, recursive)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/artists.py", line 282, in delete_db_item
    await self.mass.music.albums.delete_db_item(db_row["item_id"], recursive)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 279, in delete_db_item
    await self.mass.music.albums.delete_db_item(db_row["item_id"], recursive)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 279, in delete_db_item
    await self.mass.music.albums.delete_db_item(db_row["item_id"], recursive)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 279, in delete_db_item
    await self.mass.music.albums.delete_db_item(db_row["item_id"], recursive)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music/albums.py", line 282, in delete_db_item
    await super().delete_db_item(item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/media_controller.py", line 419, in delete_db_item
    db_item = await self.get_db_item(item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/media_controller.py", line 317, in get_db_item
    raise MediaNotFoundError(f"Album not found in database: {item_id}")
music_assistant.models.errors.MediaNotFoundError: Album not found in database: 4294

### What version of Home Assistant Core are your running

2022.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
please confirm if this is fixed in beta 10

**Comment by OzGav** [comment]
fixed
