### ISSUE TITLE
Tracks added to queue but do not play

### ISSUE THREAD

**Issue by BlackCatPeanut** [music-assistant/hass-music-assistant#752]
### What version of Music Assistant has the issue?

2022.7.2

### The problem

I am using Youtube music as a source and playing to a sonos device. I'm able to search, select and add tracks to the queue however despite selecting Play Now, I see the track added at the bottom but it does not play. I can see a background task start and finish but nothing changes.

### How to reproduce

Search for a Youtube source, press Play button and select Play Now.

### Relevant log output

`Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 11:21:41 AM (12 occurrences)
Last logged: 4:00:32 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 462, in _queue_stream_runner
    async for chunk in ffmpeg_proc.iter_chunked(self.output_chunksize):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 91, in iter_chunked
    chunk = await self.readexactly(n)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 110, in readexactly
    return await self._proc.stdout.readexactly(n)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 434, in _queue_stream_runner
    async with AsyncProcess(ffmpeg_args, True) as ffmpeg_proc:
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 438, in writer
    async for audio_chunk in self._get_queue_stream():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 695, in _get_queue_stream
    seconds_in_buffer,
UnboundLocalError: local variable 'seconds_in_buffer' referenced before assignment
`

### Additional information

I am running HAOS on a Raspberry Pi 4 4GB.

### What version of Home Assistant Core are your running

2022.7.7

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by BlackCatPeanut** [comment]
Sorry, I forgot to add what a great add on you have created! I really enjoyed the webinar a few weeks back. I think HA and MA are onto something big here!

**Comment by marcelveldt** [comment]
Looks like a small issue went into the 2022.7.2 release, I'll provide a fix in the 2022.7.3 release later today.

For now you can try to enable crossfade on the player

**Comment by BlackCatPeanut** [comment]
Thanks Marcel! I installed the update this morning and the behaviour I described has stopped. Once I play the queue, it works fine. I am noticing some strnge buffering behaviour whereby the track shown and the track played are out of sync. But I will report this as a separate issue once I have been able to properly replicate this on a regular basis. Once again, great work on MA!
