### ISSUE TITLE
Dash streams (.mpd) are not accepted

### ISSUE THREAD

**Issue by ezpl** [music-assistant/hass-music-assistant#791]
### What version of Music Assistant has the issue?

2022.8.0b2

### The problem

Streaming using .mpd extension is not accepted

### How to reproduce

Call service:

`
service: media_player.play_media
data:
  media_content_id: https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/dash/nonuk/dash_low/aks/bbc_world_service.mpd
  media_content_type: channel
target:
  entity_id: media_player.mass_my_player`

### Relevant log output

Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:395
Integration: Google Cast (documentation, issues)
First occurred: 09:52:47 (4 occurrences)
Last logged: 09:53:40

Failed to cast media http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/http-icy-mp3-a/vpid/bbc_world_service/format/pls.pls. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

### What version of Home Assistant Core are your running

2022.8.0b6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by ezpl** [comment]
Awesome, will test and confirm.

**Comment by Symbiot78** [comment]
any update? I tried calling this bbc url..

http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/dash/uk/dash_full/ak/bbc_radio_two.mpd

and 

https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/dash/uk/dash_full/ak/bbc_radio_two.mpd

and both fail.

`2023-02-02 22:50:17.911 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140252969918352] Error handling message: Unknown error (unknown_error) from 192.168.1.230 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0)
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/tags.py", line 232, in parse_tags
raise InvalidDataError(error["string"])
music_assistant.models.errors.InvalidDataError: Invalid data found when processing input
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 217, in play_media
media_item = await self.mass.music.get_item_by_uri(item)
File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 231, in get_item_by_uri
return await self.get_item(
File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 252, in get_item
return await self.get_provider(ProviderType.URL).parse_item(item_id)
File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/url/url.py", line 91, in parse_item
item_id, url, media_info = await self._get_media_info(
File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/url/url.py", line 152, in _get_media_info
media_info = await parse_tags(url)
File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/tags.py", line 235, in parse_tags
raise InvalidDataError(
music_assistant.models.errors.InvalidDataError: Unable to retrieve info for https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/dash/uk/dash_full/ak/bbc_radio_two.mpd: Invalid data found when processing input
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 681, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 721, in _handle_entity_call
await result
File "/config/custom_components/mass/media_player.py", line 429, in async_play_media
await self.player.active_queue.play_media(media_id, queue_opt)
File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 220, in play_media
raise MediaNotFoundError(f"Invalid uri: {item}") from err
music_assistant.models.errors.MediaNotFoundError: Invalid uri: https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/dash/uk/dash_full/ak/bbc_radio_two.mpd`

**Comment by Symbiot78** [comment]
I have tried a bunch of different BBC sounds urls.. and none seem to work. 
the mp3 versions (which are being phased out in 2023) work.

but the new stream simply do not work.

this is an example of an m3u8 file downloaded from a link:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=50880,CODECS="mp4a.40.5"
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d48000.norewind.m3u8


if I insert the link in the m3u8 (the next m3u8) 
I get a new file containing:

#EXTM3U
#EXT-X-VERSION:3
## Created with Unified Streaming Platform(version=1.8.4)
#EXT-X-MEDIA-SEQUENCE:261891269
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:6
#USP-X-TIMESTAMP-MAP:MPEGTS=1529897888,LOCAL=2023-02-11T08:28:35.200000Z
#EXT-X-PROGRAM-DATE-TIME:2023-02-11T08:28:35.200000Z
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891269.ts
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891270.ts
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891271.ts
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891272.ts
#EXTINF:6.4, no desc
bbc_radio_two-audio=48000-261891273.ts

**Comment by Symbiot78** [comment]
have opened a new issue instead of continuing here.
