### ISSUE TITLE
Something is Messed Up -- Multiple Errors & Issues 

### ISSUE THREAD

**Issue by RJ-Make** [music-assistant/hass-music-assistant#809]
### What version of Music Assistant has the issue?

2022.8.1

### The problem

I'm not sure when these issues started, either with the 2022.8.1 Core update or 2022.8.1 MA Update but I'm now having functional and UI issues, lots of them.  So many in fact, I'm not sure where to start. 

1) Intermittent Errors and failures when trying to start playing at track.
    1a) Sometime if I move to Played Items I can get a track to play, and that sometimes allows the Queue to start working
2) Play Head (Transport Section) is often out of sync with what shows playing. 
3) The Play Now does not work if another track is playing.
4) If I Select Play Next in a Queue, after the current track completes, the entire MASS system stops working. 
5) When starting a play I'm getting a failed login attempt. I don't understand this, but it ALWAYS coincides with doing something in MASS (Login attempt or request with invalid authentication from homeassistant.localdomain (192.168.1.132). See the log for details.)

There are other issues, but like I said, I'm not sure what the heck is going on.  I hate to dump my MASS setup and start over again, but these don't seem like 'standard' problems.

<img width="790" alt="2022-08-06_9-06-40" src="https://user-images.githubusercontent.com/8496835/183251589-8c289336-33ab-4aaa-ad94-d0a2da6803da.png">

<img width="1710" alt="2022-08-06_9-42-20" src="https://user-images.githubusercontent.com/8496835/183251590-04b3f7f8-5ffc-4b6f-a7ef-f768d17c516d.png">

<img width="1724" alt="2022-08-06_9-16-18" src="https://user-images.githubusercontent.com/8496835/183251594-f5fca2c0-0fa8-4227-ba57-a83ce23a7d01.png">

<img width="1722" alt="2022-08-06_9-16-52" src="https://user-images.githubusercontent.com/8496835/183251600-989d1c77-e8ff-4cd4-ae33-716f065a0214.png">

<img width="1726" alt="2022-08-06_9-24-46" src="https://user-images.githubusercontent.com/8496835/183251605-c6774bb5-a42d-4aa3-aed8-5355ea1a8415.png">

<img width="1723" alt="2022-08-06_9-36-56" src="https://user-images.githubusercontent.com/8496835/183251613-ecded0dd-9986-4222-8885-1a67cf95165b.png">

<img width="355" alt="2022-08-06_9-31-54" src="https://user-images.githubusercontent.com/8496835/183251621-aeb4b3d6-bf27-4430-94c2-32933c6214b1.png">

### How to reproduce

Using the system. 

### Relevant log output

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/mass/panel.py:92
Integration: Music Assistant (documentation, issues)
First occurred: 8:53:30 AM (2 occurrences)
Last logged: 8:54:08 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/config/custom_components/mass/panel.py", line 92, in get
    data = await mass.metadata.get_thumbnail(url, size=size)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/metadata/metadata.py", line 260, in get_thumbnail
    thumbnail = await create_thumbnail(self.mass, path, size)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/images.py", line 45, in create_thumbnail
    img_data = await get_image_data(mass, path)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/images.py", line 38, in get_image_data
    raise FileNotFoundError(f"Image not found: {path}")
FileNotFoundError: Image not found: http://192.168.1.132:8123/media/media/music/Tobymac/Hits Deep Live (2016) [MP3]/12 Undeniable (feat. Colton Dixon) [Live].mp3

AND 

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 8:56:54 AM (2 occurrences)
Last logged: 8:57:05 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 411, in next
    await self.play_index(next_index)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 535, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 712, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 308, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 241, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 231, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 254, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 45, in get
    track = await super().get(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 148, in get
    db_item = await self.get_db_item_by_prov_id(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 348, in get_db_item_by_prov_id
    return await self.get_db_item(provider_item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 335, in get_db_item
    raise MediaNotFoundError(f"Album not found in database: {item_id}")
music_assistant.models.errors.MediaNotFoundError: Album not found in database: 14479

AND

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:1188
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:10:39 AM (2 occurrences)
Last logged: 9:10:50 AM

[139695236201296] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 1188, in websocket_play_media
    await player_queue.play_media(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 275, in play_media
    await self.play_index(cur_index)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 535, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 712, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 308, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 241, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 231, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 254, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/tracks.py", line 45, in get
    track = await super().get(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 148, in get
    db_item = await self.get_db_item_by_prov_id(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 348, in get_db_item_by_prov_id
    return await self.get_db_item(provider_item_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/media/base.py", line 335, in get_db_item
    raise MediaNotFoundError(f"Album not found in database: {item_id}")
music_assistant.models.errors.MediaNotFoundError: Album not found in database: 1

### What version of Home Assistant Core are your running

2022.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by marcelveldt** [comment]
Did you do something to your database file ?
Your log states MediaNotFoundError's on database id's so those id's are no longer there.

**Comment by RJ-Make** [comment]
> 

My only action was updating both HA and MASS.

**Comment by marcelveldt** [comment]
OK, this looks like a browser cache issue where you're still using the previous version of the frontend.
Can you try to force-refresh the browser cache ?

**Comment by RJ-Make** [comment]
Thanks for the help and the clue...

Clearing the cache didn't have any effect. However, at this point I decided to 

1) Shutdown MASS
2) Delete the music_assistant.db
3) Restart MASS
4) Force a Full System.. (probably didn't have to do this part).

This fixed the problems. My guess is that something damaged the db during the HA or MASS update.

**Comment by OzGav** [comment]
Thanks Marcel has been working hard to eliminate the need to rebuild the db but yes during this rapid development phase sometimes it might be the only way.
