### ISSUE TITLE
Error Trying to play stream

### ISSUE THREAD

**Issue by sneedster** [music-assistant/hass-music-assistant#83]
I only have tune-in playlists enabled, and they populated fine, but trying to play any of them results in nothing happening. The following is found in the logs:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:947
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:18:06 AM (1 occurrences)
Last logged: 11:18:06 AM

[140192534498800] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 90, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 947, in websocket_play_media
    await player_queue.play_media(msg[URI], msg[COMMAND])
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 416, in play_media
    media_item = await self.mass.music.get_item_by_uri(uri)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 160, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 174, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 66, in get
    details = await self.get_provider_item(provider_item_id, provider_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 179, in get_provider_item
    item = await provider.get_item(self.media_type, item_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/provider.py", line 193, in get_item
    return await self.get_radio(prov_item_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/tunein.py", line 90, in get_radio
    return await self._parse_radio(item, stream)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/tunein.py", line 124, in _parse_radio
    radio.sort_name = details["preset_number"]
KeyError: 'preset_number'
```

**Comment by marcelveldt** [comment]
fixed in version 1.0.11 (just released)

**Comment by schoeyuk10** [comment]
I'm getting the same error as @sneedster [sneedster](https://github.com/sneedster)

**Comment by marcelveldt** [comment]
@schoeyuk10 are you on version 1.0.11 ?

**Comment by schoeyuk10** [comment]
Yes i am. I assume yours is working ok ?

**Comment by marcelveldt** [comment]
Turns out I forgot to deploy a piece of code (it was waaaaaay past my bed time haha). I'll deploy a new version later today

**Comment by schoeyuk10** [comment]
Lolol, ok. I'll try again later. Thanks for your help.
Oh, while you're on.....my local mp3s aren't showing up either.

**Comment by marcelveldt** [comment]
> Lolol, ok. I'll try again later. Thanks for your help. Oh, while you're on.....my local mp3s aren't showing up either.

OK, a few questions about local mp3s:
- I assume you enabled local files in the settings and set-up the directory on disk (e.g. /media/music) ?
- No errors or warnings in the log ?
- Are your mp3 files properly tagged (ID3 tags with media info) ?

**Comment by schoeyuk10** [comment]
Yes, i enabled the settings
There is nothing in the log
My songs are tagged, as an example....thunderstruck.mp3

**Comment by schoeyuk10** [comment]
Actually, i just refreshed and i get these 2 errors

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:947
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:43:12 (5 occurrences)
Last logged: 09:06:25

[547408382944] Error handling message: Unknown error (unknown_error)
[546956944432] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 90, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 947, in websocket_play_media
    await player_queue.play_media(msg[URI], msg[COMMAND])
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 416, in play_media
    media_item = await self.mass.music.get_item_by_uri(uri)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 160, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 174, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 66, in get
    details = await self.get_provider_item(provider_item_id, provider_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 179, in get_provider_item
    item = await provider.get_item(self.media_type, item_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/provider.py", line 193, in get_item
    return await self.get_radio(prov_item_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/tunein.py", line 90, in get_radio
    return await self._parse_radio(item, stream)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/tunein.py", line 124, in _parse_radio
    radio.sort_name = details["preset_number"]
KeyError: 'preset_number'


Error 2

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:650
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:06:08 (3 occurrences)
Last logged: 09:06:11

[546956944432] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 90, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 650, in websocket_item
    if item := await mass.music.get_item_by_uri(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 149, in get_item_by_uri
    raise MusicAssistantError(f"Not a valid Music Assistant uri: {uri}")
music_assistant.models.errors.MusicAssistantError: Not a valid Music Assistant uri: http://vis.media-ice.musicradio.com/CapitalUK


Doesn't mean anything to me i'm afraid

**Comment by Mariusthvdb** [comment]
Hey Marcel, seeing this error now myself, 'not a valid Uri'. need a new issue for that, or re-open this, not sure what would be best?
