### ISSUE TITLE
Can't setup with youtube music

### ISSUE THREAD

**Issue by xdia88** [music-assistant/hass-music-assistant#857]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:190
Integration: Music Assistant (documentation, issues)
First occurred: 13:57:28 (48 occurrences)
Last logged: 14:51:49

Setup failed of provider ytmusic: '__Secure-3PAPISID'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 435, in _register_provider
    if await provider.setup():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 90, in setup
    await self._initialize_headers(cookie=self.config.password)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 450, in _initialize_headers
    sapisid = ytmusicapi.helpers.sapisid_from_cookie(cookie)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/helpers.py", line 46, in sapisid_from_cookie
    return cookie['__Secure-3PAPISID'].value
KeyError: '__Secure-3PAPISID'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/mass/__init__.py", line 190, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 81, in setup
    await self.music.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 70, in setup
    await self._register_provider(prov_cls(self.mass, prov_conf), prov_conf)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 438, in _register_provider
    raise SetupFailedError(
music_assistant.models.errors.SetupFailedError: Setup failed of provider ytmusic: '__Secure-3PAPISID'

### How to reproduce

i have put in the login cookie and won't setup

### What version of Home Assistant Core are your running

2022.8.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Please refer to the FAQs https://github.com/music-assistant/hass-music-assistant/discussions/709
