### ISSUE TITLE
No such file or directory: 'custom_components/mass/frontend/dist'

### ISSUE THREAD

**Issue by Shulyaka** [music-assistant/hass-music-assistant#916]
### What version of Music Assistant has the issue?

HEAD

### The problem

Error log messages at startup

### How to reproduce

Restart home assistant

### Relevant log output

```2022-09-18 22:22:55.258 INFO (MainThread) [homeassistant.components.switch] Setting up switch.mass
2022-09-18 22:22:55.263 INFO (MainThread) [homeassistant.components.number] Setting up number.mass
2022-09-18 22:22:55.268 INFO (MainThread) [homeassistant.components.select] Setting up select.mass
2022-09-18 22:22:55.272 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/srv/homeassistant/custom_components/mass/__init__.py", line 239, in async_setup_entry
    entry.async_on_unload(await async_register_panel(hass, entry.title))
  File "/srv/homeassistant/custom_components/mass/panel.py", line 35, in async_register_panel
    for filename in os.listdir(panel_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/srv/homeassistant/custom_components/mass/frontend/dist'
2022-09-18 22:22:55.277 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=mass>
2022-09-18 22:22:55.292 DEBUG (MainThread) [homeassistant.bootstrap] Waiting for startup to wrap up
```

### What version of Home Assistant Core are your running

2022.9.5

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
The error suggests something is missing or inaccessible during the install. Please review the first entry here and provide more information https://github.com/music-assistant/hass-music-assistant/discussions/709

**Comment by Shulyaka** [comment]
Doesn't [panel.py:35](https://github.com/music-assistant/hass-music-assistant/blob/main/custom_components/mass/panel.py#L35) just try to open custom_components/mass/[frontend/dist/](https://github.com/music-assistant/hass-music-assistant/blob/main/custom_components/mass/panel.py#L20) directory which is missing in the repository?

**Comment by OzGav** [comment]
That directory is not missing normally

**Comment by Shulyaka** [comment]
I think it was removed a month ago with 42fa1c7 and I can't quite figure out how it is supposed to be combined. A git module?

**Comment by OzGav** [comment]
OK not sure then as I can still see that directory. Have you tried an uninstall and reinstall?

**Comment by Shulyaka** [comment]
Well, I don't use HACS, i just git clone the repo, but since frontend is now on a separate repo, I don't understand how it is supposed to be installed

**Comment by OzGav** [comment]
Ok not sure either. MA is currently undergoing a significant rewrite so I would suggest either use HACS, wait or try on discord.

**Comment by MarvinSchenkel** [comment]
The dist folder is built during the publish pipeline towards HACS, which means it is not part of the repository. 

Please use HACS to install Music Assistant.
