### ISSUE TITLE
Unable to browse YTM

### ISSUE THREAD

**Issue by MarkXal** [music-assistant/hass-music-assistant#956]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

When I attempt to open the YTM folder in music assistant it shows in progress indefinitely and the below error is added to the log. Previously synced music still works.

### How to reproduce

Go to Music Assistant -> Browse -> Youtube Music -> Playlists

### Relevant log output

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:929
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 9:42:11 AM (6 occurrences)
Last logged: 10:02:33 AM

[547929974832] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 929, in websocket_browse
    await mass.music.browse(msg.get("path")),
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 224, in browse
    return await prov.browse(path)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 374, in browse
    items=[x async for x in self.get_library_playlists()],
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 374, in <listcomp>
    items=[x async for x in self.get_library_playlists()],
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 149, in get_library_playlists
    playlists_obj = await get_library_playlists(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 137, in get_library_playlists
    return await loop.run_in_executor(None, _get_library_playlists)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 128, in _get_library_playlists
    playlists = ytm.get_library_playlists(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists
    results = nav(results, ITEM_SECTION + GRID)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 74, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 68, in nav
    root = root[k]
TypeError: 'NoneType' object is not subscriptable

### What version of Home Assistant Core are your running

2022.10.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Please confirm you have a premium YouTube subscription. Has this ever worked?

**Comment by MarkXal** [comment]
Sorry, yes I do have premium and it worked until yesterday. I added a new speaker the same day as the problem started occurring (moved my automation from a google home mini to a nest mini).

**Comment by OzGav** [comment]
Have you tried removing that speaker from MA to see if you can get back to where you were?

**Comment by MarkXal** [comment]
Just did, no success. When I reloaded MA after removing the speaker this error pops up as well:

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232
First occurred: 10:18:22 AM (1 occurrences)
Last logged: 10:18:22 AM

Job [Library sync for provider Youtube Music] failed with error 'NoneType' object is not subscriptable.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 402, in sync_library
    async for prov_item in self._get_library_gen(media_type)():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 141, in get_library_albums
    albums_obj = await get_library_albums(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 117, in get_library_albums
    return await loop.run_in_executor(None, _get_library_albums)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 114, in _get_library_albums
    return ytm.get_library_albums(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 132, in get_library_albums
    return parse_library_albums(
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/library.py", line 29, in parse_library_albums
    results = nav(results, ITEM_SECTION)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 74, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 68, in nav
    root = root[k]
TypeError: 'NoneType' object is not subscriptable

**Comment by OzGav** [comment]
Ok let’s see what @MarvinSchenkel thinks?

**Comment by MarkXal** [comment]
Wanted to add, I also checked this problem with the ytube_music_player integration: https://github.com/KoljaWindeler/ytube_music_player

and it shows the same symptoms and gives the same error, as shown below

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/browse_media.py:67
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:08:50 PM (1 occurrences)
Last logged: 11:08:50 PM

[547291464704] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1232, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1977, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 67, in build_item_response
    media = await hass.async_add_executor_job(media_library.get_library_playlists, BROWSER_LIMIT)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists
    results = nav(results, ITEM_SECTION + GRID)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 74, in nav
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 68, in nav
TypeError: 'NoneType' object is not subscriptable

**Comment by OzGav** [comment]
There is the same issue in that repo https://github.com/KoljaWindeler/ytube_music_player/issues/215 @KoljaWindeler

**Comment by MarkXal** [comment]
Yes! That's is what I have as well. Let me know if you need more info

**Comment by MarvinSchenkel** [comment]
This error shows up when both MA and the Youtube Music Player by KoljaWindeler are installed. Unfortunately we cannot support having both installed due to overlapping dependencies. See https://github.com/music-assistant/hass-music-assistant/issues/663#issuecomment-1185256947 on how to resolve this.

**Comment by MarvinSchenkel** [comment]
I will need to investigate this. This seems to be an issue with a dependent package (ytmusicapi) which could be introduced due to a change on Google's end.

**Comment by erkr** [comment]
I close this one and use issue #215

**Comment by Aasikki** [comment]
I had this issue and just redid the login cookie thing and now it works.

**Comment by MarvinSchenkel** [comment]
> I had this issue and just redid the login cookie thing and now it works.

Yep, that seems to do the trick. I encountered this error as well and a re-loging fixed the issue. Remember, Youtube Music does not have an official API, so weird behaviour and re-logins are expected :-).

**Comment by jonny190** [comment]
I'm seeing the same using a cookie from a private browsing session and after logging out and back in to YouTube music 

2022-11-16 13:26:36.579 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140065119750896] Error handling message: Unknown error (unknown_error) from 192.168.4.254 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 929, in websocket_browse
    await mass.music.browse(msg.get("path")),
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/music.py", line 224, in browse
    return await prov.browse(path)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 374, in browse
    items=[x async for x in self.get_library_playlists()],
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/music_provider.py", line 374, in <listcomp>
    items=[x async for x in self.get_library_playlists()],
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 149, in get_library_playlists
    playlists_obj = await get_library_playlists(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 137, in get_library_playlists
    return await loop.run_in_executor(None, _get_library_playlists)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/helpers.py", line 128, in _get_library_playlists
    playlists = ytm.get_library_playlists(limit=9999)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists
    results = nav(results, ITEM_SECTION + GRID)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 74, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/navigation.py", line 68, in nav
    root = root[k]
TypeError: 'NoneType' object is not subscriptable

The same for Artists, Albums and Tracks with their respective get_library_ calls.

Any suggestions? if its authentication could App passwords be used ?

**Comment by jonny190** [comment]
To be that guy i've been in to HASS and updated the pip module ytmusicapi to ytmusicapi-0.24.0 and it looks to have fixed my issues. Not sure of any other hell i've caused (if any) but so far so good for me and my use case
