### ISSUE TITLE
SRF 4 Radio Station stops playing

### ISSUE THREAD

**Issue by stbrun** [music-assistant/hass-music-assistant#959]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Hello Marcel. I have the problem that the SRF 4 News Swiss radio station stops playing after a few seconds of playing. Other stations work well. Also SRF 3 radio station works well. What could be the problem for this behavior? Thanks for your support! Best regards, Stefan 

### How to reproduce

Play SRF 4 news statuon

### What version of Home Assistant Core are your running

2022.10.15

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Hi Stefan. we can only off limited support for non standard installs but do you have any errors in the logs ?

**Comment by stbrun** [comment]
Hello

Thanks for your feedback!

I run HA officially on a mac mini in a virtual box.

I checked and got the following error:

Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232 
First occurred: 08:43:21 (1 occurrences) 
Last logged: 08:43:21

Job [Analyze audio for tunein://radio/s67023] failed with error 'utf-8' codec can't decode byte 0xe4 in position 24: invalid continuation byte.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 172, in analyze_audio
    async with AsyncProcess(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 192, in analyze_audio
    await writer_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 182, in writer
    async for audio_chunk in music_prov.get_audio_stream(streamdetails):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/tunein/tunein.py", line 202, in get_audio_stream
    async for chunk in get_radio_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 456, in get_radio_stream
    stream_title = stream_title.group(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 24: invalid continuation byte

I hope you can find a solution. Thanks for your support!

Best regards, Stefan 

--------------------------------------------------------


Am 24.10.2022 um 23:13 schrieb OzGav ***@***.***>:


Hi Stefan. we can only off limited support for non standard installs but do you have any errors in the logs ?

**Comment by erkr** [comment]
I tried and have the same issue with that station (others work fine).
Two errors is in my log. First this one:
``` 
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96 
First occurred: 15:04:32 (1 occurrences) 
Last logged: 15:04:32

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 524, in _queue_stream_runner
    async for chunk in ffmpeg_proc.iter_chunked(self.output_chunksize):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 91, in iter_chunked
    chunk = await self.readexactly(n)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 110, in readexactly
    return await self._proc.stdout.readexactly(n)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 496, in _queue_stream_runner
    async with AsyncProcess(ffmpeg_args, True) as ffmpeg_proc:
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 500, in writer
    async for audio_chunk in self._get_queue_stream():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 670, in _get_queue_stream
    async for chunk in get_media_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 387, in get_media_stream
    async with AsyncProcess(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 397, in writer
    async for audio_chunk in music_prov.get_audio_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/tunein/tunein.py", line 202, in get_audio_stream
    async for chunk in get_radio_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 456, in get_radio_stream
    stream_title = stream_title.group(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 51: invalid start byte
``` 
Followed by this one:
``` 
Logger: music_assistant
Source: /usr/local/lib/python3.10/site-packages/music_assistant/mass.py:232 
First occurred: 15:04:30 (2 occurrences) 
Last logged: 15:04:48

Job [Analyze audio for tunein://radio/s67023] failed with error 'utf-8' codec can't decode byte 0xf6 in position 51: invalid start byte.
Job [Analyze audio for tunein://radio/s67023] failed with error 'utf-8' codec can't decode byte 0xe4 in position 47: invalid continuation byte.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 172, in analyze_audio
    async with AsyncProcess(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 192, in analyze_audio
    await writer_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 182, in writer
    async for audio_chunk in music_prov.get_audio_stream(streamdetails):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/tunein/tunein.py", line 202, in get_audio_stream
    async for chunk in get_radio_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 456, in get_radio_stream
    stream_title = stream_title.group(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 51: invalid start byte
```

**Comment by OzGav** [comment]
Yeah I think @marcelveldt needs to have a look at this one...

**Comment by OzGav** [comment]
Just wondering if this has been fixed in MA V2?

**Comment by erkr** [comment]
Just verified, radio station now plays fine for me.
 @stbrun  please file a new issue if it is still not working for you. I will close this old issue now
