### ISSUE TITLE
Errors in filesystem music provider

### ISSUE THREAD

**Issue by vk2him** [music-assistant/hass-music-assistant#96]
I'm seeing this error when adding a local library via the Enable filesystem provider tick box - the files have correct ID3 Tags and I'm using the directory /media which contains my .mp3 files. Here's the error log.

```
Logger: music_assistant.mass
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:242
First occurred: 8:53:36 PM (9 occurrences)
Last logged: 9:51:18 PM

Job [Library sync of artists for provider Filesystem] failed with error argument of type 'NoneType' is not iterable.
Job [Library sync of albums for provider Filesystem] failed with error argument of type 'NoneType' is not iterable.
Job [Library sync of tracks for provider Filesystem] failed with error argument of type 'NoneType' is not iterable.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 380, in _library_items_sync
    for prov_item in await music_provider.get_library_items(media_type):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/provider.py", line 172, in get_library_items
    return await self.get_library_artists()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py", line 124, in get_library_artists
    for track in await self.get_library_tracks(False):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py", line 152, in get_library_tracks
    if track := await self._parse_track(filename):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py", line 307, in _parse_track
    name, version = parse_title_and_version(tag.title)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/util.py", line 90, in parse_title_and_version
    if splitter in title:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by marcelveldt** [comment]
Hmmm, it seems that it is choking on a file without ID3 tags or an error in the ID3 tag, I'll have to better guard the code against that. I'll try to reproduce and provide a fix

**Comment by marcelveldt** [comment]
just published version 1.0.13 to HACS, which should fix this issue. If you still run into this or another issue, please let me know. Thanks for testing!

**Comment by vk2him** [comment]
Thanks for the quick response. The new version now finds some of my local files and is displaying an error in the logs as expected for the files that don't have correct ID3 tags

```
Logger: music_assistant.mass.music.filesystem
Source: /usr/local/lib/python3.9/site-packages/music_assistant/providers/filesystem.py:309
First occurred: 9:04:50 AM (825 occurrences)
Last logged: 9:05:15 AM

Skipping track due to invalid ID3 tags: /media/nasfiles/Unknown Artist/Unknown Album/Jake Chudnow-Shona by Jake Chudnow [myfreemp3.eu].mp3
Skipping track due to invalid ID3 tags: /media/nasfiles/Unknown Artist/Unknown Album/silence.mp3
Skipping track due to invalid ID3 tags: /media/nasfiles/Unknown Artist/Unknown Album/Guy Walks into a Bar.mp3
Skipping track due to invalid ID3 tags: /media/nasfiles/Unknown Artist/Unknown Album/ANW2050_03_Book-Of-Secrets.mp3
Skipping track due to invalid ID3 tags: /media/nasfiles/Unknown Artist/Unknown Album/Heart - Stairway to Heaven.m4a
```

I am now get a slightly different errors in logs and the initial scan never completes and displays errors in logs.

First error:
```
Logger: music_assistant.mass
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:242
First occurred: 8:43:21 AM (2 occurrences)
Last logged: 8:43:21 AM

Job [Library sync of albums for provider Filesystem] failed with error 'NoneType' object has no attribute 'musicbrainz_id'.
Job [Library sync of tracks for provider Filesystem] failed with error 'NoneType' object has no attribute 'musicbrainz_id'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 397, in _library_items_sync
    db_item = await controller.add_db_item(prov_item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/albums.py", line 121, in add_db_item
    if album.artist.musicbrainz_id and album.artist.provider != "database":
AttributeError: 'NoneType' object has no attribute 'musicbrainz_id'

```
Second error in logs

```
Logger: music_assistant.mass.metadata
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/__init__.py:137
First occurred: 8:43:22 AM (3 occurrences)
Last logged: 8:43:32 AM

Unable to get musicbrainz ID for artist Eric Jason Martin; Jeff Harding !
Unable to get musicbrainz ID for artist Beatles !
```
3rd error

```
Logger: music_assistant.mass.audiodb
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/metadata/audiodb.py:268
First occurred: 9:08:03 AM (2 occurrences)
Last logged: 9:08:17 AM

Failed to retrieve artist-mb.php

```

4th error

```
Logger: music_assistant.mass
Source: /usr/local/lib/python3.9/site-packages/music_assistant/mass.py:242
First occurred: 9:10:53 AM (1 occurrences)
Last logged: 9:10:53 AM

Job [Library sync of artists for provider Filesystem] failed with error .
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 390, in _library_items_sync
    db_item = await controller.get(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 68, in get
    return await self.add(details)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/artists.py", line 67, in add
    db_item = await self.add_db_item(item)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/artists.py", line 120, in add_db_item
    assert artist.musicbrainz_id
AssertionError

```

5th

```

Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405
First occurred: 9:14:15 AM (10 occurrences)
Last logged: 9:14:17 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/stream.py", line 136, in serve_queue_stream
    start_streamdetails = await queue.queue_stream_prepare()
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 726, in queue_stream_prepare
    raise err
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 722, in queue_stream_prepare
    return await get_stream_details(self.mass, next_item, self.queue_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/audio.py", line 199, in get_stream_details
    full_item = await mass.music.get_item_by_uri(queue_item.uri)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 163, in get_item_by_uri
    return await self.get_item(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/__init__.py", line 177, in get_item
    return await ctrl.get(
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/tracks.py", line 39, in get
    await self.mass.music.artists.get(artist.item_id, artist.provider)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 66, in get
    details = await self.get_provider_item(provider_item_id, provider_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/media_controller.py", line 184, in get_provider_item
    raise MediaNotFoundError(
music_assistant.models.errors.MediaNotFoundError: artist AC not found on provider filesystem

```

**Comment by vk2him** [comment]
Just to add - the 5th error above - the actual artist is called AC/DC but the error states artist AC not found on provider filesystem  ... is the "/ causing an issue? Thanks

**Comment by marcelveldt** [comment]
Thanks for testing again and the extensive error report. I have just released a new version so too late for today but I will take a good look tomorrow and provide another new version. Thanks for your patience!

**Comment by vk2him** [comment]
No problem - thanks - I think I have found at least another bug so  will log a new issue if needed
