### ISSUE TITLE
MA doesn't start since HA beta core-2022.11.0b0

### ISSUE THREAD

**Issue by gieljnssns** [music-assistant/hass-music-assistant#962]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

MA doesn't start

### How to reproduce

Update HA to `core-2022.11.0b0`

### Relevant log output

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:190
Integration: Music Assistant (documentation, issues)
First occurred: 09:14:36 (1 occurrences)
Last logged: 09:14:36

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 197, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 190, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 79, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 43, in setup
    await self._migrate()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 216, in _migrate
    await self.set_setting("version", str(SCHEMA_VERSION))
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 60, in set_setting
    return await self.insert(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 137, in insert
    return await self.get_row(table, lookup_vals)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 115, in get_row
    return await self._db.fetch_one(sql_query, match)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 148, in fetch_one
    return await connection.fetch_one(query, values)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 257, in fetch_one
    return await self._connection.fetch_one(built_query)
  File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 120, in fetch_one
    metadata = CursorResultMetaData(context, cursor.description)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 164, in __init__
    (
ValueError: not enough values to unpack (expected 5, got 4)

### What version of Home Assistant Core are your running

2022.11.0b0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by gieljnssns** [comment]
When reverting to 2022.10.5 MA is back

**Comment by marcelveldt** [comment]
Yeah, a bump of sqlalcehemy caused the incompatibility. I'll provide a fix soon.

**Comment by marcelveldt** [comment]
Hotfix release is now available on HACS
