### ISSUE TITLE
MASS failing in 2022.11.0

### ISSUE THREAD

**Issue by Phileep** [music-assistant/hass-music-assistant#979]
### What version of Music Assistant has the issue?

2022.8.4 (edited)

### The problem

After upgrading to 2022.11.0, MASS did not start.

Also uninstalled and re-installed MASS - same errors

Environment: 
Home assistant: 2022.11.0
Core running in container (docker)
sqlite standard DB

### How to reproduce

Errors in log on start/restart in 2022.11.0.
Integration not started

### Relevant log output

2022-11-03 12:41:56.702 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Music Assistant for mass
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/mass/__init__.py", line 197, in async_setup_entry
raise exc
File "/config/custom_components/mass/__init__.py", line 190, in async_setup_entry
await mass.setup()
File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 79, in setup
await self.database.setup()
File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 43, in setup
await self._migrate()
File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 216, in _migrate
await self.set_setting("version", str(SCHEMA_VERSION))
File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 60, in set_setting
return await self.insert(
File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 137, in insert
return await self.get_row(table, lookup_vals)
File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 115, in get_row
return await self._db.fetch_one(sql_query, match)
File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 148, in fetch_one
return await connection.fetch_one(query, values)
File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 257, in fetch_one
return await self._connection.fetch_one(built_query)
File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 120, in fetch_one
metadata = CursorResultMetaData(context, cursor.description)
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 164, in __init__
(
ValueError: not enough values to unpack (expected 5, got 4)

### What version of Home Assistant Core are your running

2022.11.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by gieljnssns** [comment]
Are you sure you are using the 2022.11 (beta) version of MA?
https://github.com/music-assistant/hass-music-assistant/issues/962

**Comment by Phileep** [comment]
Apologies - misread as _homeassistant_ version.

Using **Music assistant** current prod version: 2022.8.4 - I have edited issue also.

**Comment by gieljnssns** [comment]
You have to use the MA beta version…

**Comment by OzGav** [comment]
Correct although it's not actually a beta. It's the version that is required for compatibility with HA 2022.11

**Comment by gieljnssns** [comment]
But I think you have to enable beta versions in HACS to show that version. 
![C287F3C5-3B75-41ED-947C-E9CC281B8456](https://user-images.githubusercontent.com/17234951/199676156-597c1e93-d40d-4bc0-b871-4ae1ea60d459.jpeg)

**Comment by Phileep** [comment]
I am struggling to understand why music assistant would need to change versions for the change in home assistant - why does it need to be so closely coupled - I cant see any changes in media player in 2022.11 - especially breaking changes, thay would seem to need an update to music assistant.

Can someone confirm this is a requirement - to update music assistant with each home assistant update?

**Comment by marcelveldt** [comment]
It is not, there was a dependency updated in HA (sqlalchemy) that was causing the conflict. And yes it is closely coupled because MA is a HA integration. So unless we convert it to a standalone add-on there will be issues like this. That said, it only happened twice and for next time we have a better plan.

**Comment by Phileep** [comment]
ahh. So we need to wait for the update in HACS of music assistant before updating home assistant.

How can we flag this for other users of the integration? (this is partly why I raised the issue - for others to not struggle)

**Comment by marcelveldt** [comment]
No, the update is already available. Just update HA and after that update MA
