### ISSUE TITLE
Unable to browse local files - missing ffmpeg dependency

### ISSUE THREAD

**Issue by tikeyknax** [music-assistant/hass-music-assistant#982]
### What version of Music Assistant has the issue?

2022.11.1

### The problem

After installing Music Assistant, I was not able to browse local files. After clicking on Music Assistant -> Browse -> Filesystem, some animation appeared (running black bar) but nothing else happened. Only checking `journalctl` revealed the problem: I was missing `ffprobe` on the machine. After installing `ffmpeg` manually, browsing local media works just fine.

Maybe the dependency could automatically be installed when installing Music Assistant. Otherwise, a hint in the installation instruction or the troublehsooting FAQ would already be very helpful.

### How to reproduce

* Ensure `ffprobe` is not available on the machine running home assistant.
* Click on Music Assistant -> Browse -> Filesystem
* Check `journalctl`.

### Relevant log output

The relevant part of the journalctl is:

```
Nov 05 19:33:51 server-pi python[214523]: 2022-11-05 19:33:51.207 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547424519792] Error handling message: Unknown error (unknown_error) from 192.168.17.30 (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0)
Nov 05 19:33:51 server-pi python[214523]: Traceback (most recent call last):
Nov 05 19:33:51 server-pi python[214523]:   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
Nov 05 19:33:51 server-pi python[214523]:     await func(hass, connection, msg)
Nov 05 19:33:51 server-pi python[214523]:   File "/home/homeassistant/.homeassistant/custom_components/mass/websockets.py", line 114, in async_get_mass_func
Nov 05 19:33:51 server-pi python[214523]:     await orig_func(hass, connection, msg, mass)
Nov 05 19:33:51 server-pi python[214523]:   File "/home/homeassistant/.homeassistant/custom_components/mass/websockets.py", line 929, in websocket_browse
Nov 05 19:33:51 server-pi python[214523]:     await mass.music.browse(msg.get("path")),
Nov 05 19:33:51 server-pi python[214523]:   File "/srv/homeassistant/lib/python3.9/site-packages/music_assistant/controllers/music.py", line 224, in browse
Nov 05 19:33:51 server-pi python[214523]:     return await prov.browse(path)
Nov 05 19:33:51 server-pi python[214523]:   File "/srv/homeassistant/lib/python3.9/site-packages/music_assistant/music_providers/filesystem/filesystem.py", line 189, in browse
Nov 05 19:33:51 server-pi python[214523]:     elif track := await self._parse_track(full_path):
Nov 05 19:33:51 server-pi python[214523]:   File "/srv/homeassistant/lib/python3.9/site-packages/music_assistant/music_providers/filesystem/filesystem.py", line 490, in _parse_track
Nov 05 19:33:51 server-pi python[214523]:     tags = await parse_tags(track_path)
Nov 05 19:33:51 server-pi python[214523]:   File "/srv/homeassistant/lib/python3.9/site-packages/music_assistant/helpers/tags.py", line 224, in parse_tags
Nov 05 19:33:51 server-pi python[214523]:     async with AsyncProcess(
Nov 05 19:33:51 server-pi python[214523]:   File "/srv/homeassistant/lib/python3.9/site-packages/music_assistant/helpers/process.py", line 59, in __aenter__
Nov 05 19:33:51 server-pi python[214523]:     self._proc = await asyncio.create_subprocess_exec(
Nov 05 19:33:51 server-pi python[214523]:   File "/usr/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
Nov 05 19:33:51 server-pi python[214523]:     transport, protocol = await loop.subprocess_exec(
Nov 05 19:33:51 server-pi python[214523]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
Nov 05 19:33:51 server-pi python[214523]:     transport = await self._make_subprocess_transport(
Nov 05 19:33:51 server-pi python[214523]:   File "/usr/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
Nov 05 19:33:51 server-pi python[214523]:     transp = _UnixSubprocessTransport(self, protocol, args, shell,
Nov 05 19:33:51 server-pi python[214523]:   File "/usr/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
Nov 05 19:33:51 server-pi python[214523]:     self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
Nov 05 19:33:51 server-pi python[214523]:   File "/usr/lib/python3.9/asyncio/unix_events.py", line 789, in _start
Nov 05 19:33:51 server-pi python[214523]:     self._proc = subprocess.Popen(
Nov 05 19:33:51 server-pi python[214523]:   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
Nov 05 19:33:51 server-pi python[214523]:     self._execute_child(args, executable, preexec_fn, close_fds,
Nov 05 19:33:51 server-pi python[214523]:   File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
Nov 05 19:33:51 server-pi python[214523]:     raise child_exception_type(errno_num, err_msg, err_filename)
Nov 05 19:33:51 server-pi python[214523]: FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
```

### What version of Home Assistant Core are your running

2022.11.1

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
You may have noticed HA have a warning in the installation instructions that running core is an advanced setup. So we can only assume those users have experience installing the required dependencies. There is a limit to the support we can provide to alternative setups. As you are running on a RPi we would recommend using HAOS to avoid these types of issues. Glad you got it going 👍
