### ISSUE TITLE
YouTube Music Websocket API "Unknown error". Won't play any music from YouTube music.

### ISSUE THREAD

**Issue by Bretthansenpc** [music-assistant/hass-music-assistant#987]
### What version of Music Assistant has the issue?

2022.11.0

### The problem

After updating HA and MA and having to relog into YouTube Music, Music Assistant will not stream Youtube music to my third-gen Chromecast. I can cast from my phone to it but not through music assistant. It says unknown error. I can play local media through it though

### How to reproduce

playing anything from youtube music to the chrome cast.

### Relevant log output

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mass/websockets.py:1106
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:08:43 PM (2 occurrences)
Last logged: 5:09:59 PM

[281473137771184] Error handling message: Unknown error (unknown_error) from 127.0.0.1 (Mozilla/5.0 (Linux; Android 12; LE2127 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36 Home Assistant/beta-2862-66bc2603-2862 (Android 12; LE2127))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 114, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 1106, in websocket_playerqueue_command
    await player_queue.play_index(msg[COMMAND_ARG])
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 535, in play_index
    stream = await self.queue_stream_start(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/models/player_queue.py", line 712, in queue_stream_start
    stream = await self.mass.streams.start_queue_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 322, in start_queue_stream
    streamdetails = await get_stream_details(self.mass, first_item, queue.queue_id)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 253, in get_stream_details
    streamdetails: StreamDetails = await music_prov.get_stream_details(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 394, in get_stream_details
    stream_format = await self._parse_stream_format(track_obj)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/ytmusic/ytmusic.py", line 662, in _parse_stream_format
    for adaptive_format in track_obj["streamingData"]["adaptiveFormats"]:
KeyError: 'streamingData'
`

### What version of Home Assistant Core are your running

2022.11.1

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

ODROID

**Comment by OzGav** [comment]
Hopefully @MarvinSchenkel can have a look at this for you

**Comment by OzGav** [comment]
Just confirm you can play your local media through MA to the chromecast and TTS messages

**Comment by Bretthansenpc** [comment]
Yes I can play Local and TTS also works. Thanks for reminding me!

**Comment by Bretthansenpc** [comment]
Just checked my sonos and Music assistant won't stream YouTube music through that either. Same "streamingdata" error.

**Comment by MarvinSchenkel** [comment]
Can you verify whether this happens with all your songs, or just a specific one?

**Comment by Bretthansenpc** [comment]
> Can you verify whether this happens with all your songs, or just a specific one?

All songs no matter where I pick from either playlists or if I pick a song through artist or any other way :-)

**Comment by Bretthansenpc** [comment]
I edited the ha version to the correct one I'm on 2022.11.1

**Comment by Bretthansenpc** [comment]
For some reason my HA is on python 3.09 so I'm trying to figure out how to upgrade it

**Comment by francais01** [comment]
FYI: I had a similar error message. Running HA in its docker container, so components should be up to date. (Looks like Python 3.10.) Anyway, I redid the cookie capture from music.youtube.com and re-configured Music Assistant and it works now.

**Comment by Bretthansenpc** [comment]
> FYI: I had a similar error message. Running HA in its docker container, so components should be up to date. (Looks like Python 3.10.) Anyway, I redid the cookie capture from music.youtube.com and re-configured Music Assistant and it works now.
> 

Well that worked thank you!!
