### ISSUE TITLE
Music stops playing

### ISSUE THREAD

**Issue by gieljnssns** [music-assistant/hass-music-assistant#996]
### What version of Music Assistant has the issue?

 2022.11.0

### The problem

Sometimes my music suddenly stops playing

### How to reproduce

Play a playlist from spotify through  a sonos group

### Relevant log output

None

### Additional information

<img width="521" alt="Schermafbeelding 2022-11-18 om 10 04 46" src="https://user-images.githubusercontent.com/17234951/202663796-aa432187-74c3-446c-b4a4-94aae4c51fe1.png">
<img width="1161" alt="Schermafbeelding 2022-11-18 om 10 06 22" src="https://user-images.githubusercontent.com/17234951/202664033-c3ad727f-d32b-4cb4-9c4f-61351507be13.png">

<img width="460" alt="Schermafbeelding 2022-11-18 om 10 15 56" src="https://user-images.githubusercontent.com/17234951/202666054-6dde9214-2a88-44ac-be01-3522b444a1a5.png">
This are all sonos players

<img width="526" alt="Schermafbeelding 2022-11-18 om 10 16 18" src="https://user-images.githubusercontent.com/17234951/202666108-f3754e21-0b4b-4bba-a762-202ee1a6ddcb.png">

<img width="533" alt="Schermafbeelding 2022-11-18 om 10 16 30" src="https://user-images.githubusercontent.com/17234951/202666131-589bf969-ad29-4db5-a80f-b61b5f1080c3.png">

### What version of Home Assistant Core are your running

2022.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by erkr** [comment]
The next MA release contains a major refactoring of buffering/streaming. Let's park this issue and check that update once available (December time frame)

**Comment by erkr** [comment]
I today noticed the same issue using Spotify on chromecast devices. But I see timeouts in the log:
``` 
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96 
First occurred: 12:19:17 (2 occurrences) 
Last logged: 14:39:52

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 110, in readexactly
    return await self._proc.stdout.readexactly(n)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 524, in _queue_stream_runner
    async for chunk in ffmpeg_proc.iter_chunked(self.output_chunksize):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 91, in iter_chunked
    chunk = await self.readexactly(n)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 109, in readexactly
    async with _timeout(timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 496, in _queue_stream_runner
    async with AsyncProcess(ffmpeg_args, True) as ffmpeg_proc:
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 500, in writer
    async for audio_chunk in self._get_queue_stream():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 670, in _get_queue_stream
    async for chunk in get_media_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 410, in get_media_stream
    async for chunk in ffmpeg_proc.iter_chunked(chunk_size):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 91, in iter_chunked
    chunk = await self.readexactly(n)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 109, in readexactly
    async with _timeout(timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

**Comment by gieljnssns** [comment]
I haven't seen something like this in my log. I keep an eye on this when it happens again.
Do you have debug enabled?

**Comment by gieljnssns** [comment]
found this in my log
```
Logger: music_assistant.stream
Source: runner.py:119
First occurred: 19 november 2022 om 18:27:52 (2 occurrences)
Last logged: 16:10:49

Got stream request for unknown or finished stream: 8f33bc8db7274de6abd8c5cf47048da9
Got stream request for unknown or finished stream: ee4341ebd2e94eb4893d11537cb3894c
```
But it wasn't when my error occurs.

**Comment by gieljnssns** [comment]
Something else i have frequently, 
When I'm playing music on a sonos group, the music stops on one of the slaves for a couple seconds and then resumes...
Nothing in my logs on the moment this happens...

**Comment by OzGav** [comment]
Thanks. As @erkr suggested above. Let’s wait until next month for the next release and see what we find then.

**Comment by gieljnssns** [comment]
I have some debugging in this case
The music stops playing at 12:53:30
Keuken (192.168.79.84) is coordinator, move is client
![IMG_8712](https://user-images.githubusercontent.com/17234951/208093955-bd33d056-fac7-42d4-b105-59d5d9e4925d.PNG)
![IMG_9121](https://user-images.githubusercontent.com/17234951/208093958-98339ba0-e5aa-4845-ba5f-ad8de24a5140.PNG)
![IMG_9123](https://user-images.githubusercontent.com/17234951/208093963-55d088e9-b213-4142-88c1-40c2ba1fb3d9.PNG)
```
2022-12-16 12:48:58.304 DEBUG (MainThread) [music_assistant.musicbrainz] searching musicbrainz for Spelljammer (albumname: None - album_upc: None - trackname: Lake - track_isrc: None)
2022-12-16 12:48:59.323 DEBUG (MainThread) [music_assistant.musicbrainz] Got MusicbrainzArtistId for Spelljammer after search on trackname Lake --> 0939392c-b743-4ce6-b497-61fe1c88474d
2022-12-16 12:48:59.323 DEBUG (MainThread) [music_assistant.fanarttv] Fetching metadata for Artist Spelljammer on Fanart.tv
2022-12-16 12:48:59.477 DEBUG (MainThread) [music_assistant.audiodb] Fetching metadata for Artist Spelljammer on TheAudioDb
2022-12-16 12:48:59.617 DEBUG (MainThread) [music_assistant.music.artist] updated Spelljammer in database: 449
2022-12-16 12:48:59.622 DEBUG (MainThread) [music_assistant.music.artist] Trying to match artist Spelljammer on provider Filesystem
2022-12-16 12:49:00.014 DEBUG (MainThread) [music_assistant.music.artist] Could not find match for Artist Spelljammer on provider Filesystem
2022-12-16 12:49:00.016 DEBUG (MainThread) [music_assistant.event] media_item_updated database://artist/449
2022-12-16 12:49:00.016 INFO (MainThread) [music_assistant] Finished job [Add spotify://artist/5GX4XzIgGGH93KvmLu85ZV to database] in 11.53 seconds.
2022-12-16 12:49:00.016 DEBUG (MainThread) [music_assistant.event] background_job_finished Add spotify://artist/5GX4XzIgGGH93KvmLu85ZV to database
2022-12-16 12:50:24.514 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.keuken
2022-12-16 12:50:24.592 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.keuken
2022-12-16 12:52:24.635 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x13'
2022-12-16 12:53:18.136 DEBUG (MainThread) [music_assistant.players.stream] client disconnected: 192.168.79.84
2022-12-16 12:53:23.155 DEBUG (MainThread) [music_assistant.helpers.audio] media stream aborted for: spotify://track/6u04aBSTpZDO8MuYC5e3DN
2022-12-16 12:53:23.156 DEBUG (MainThread) [music_assistant.event] background_job_updated Analyze audio for spotify://track/6u04aBSTpZDO8MuYC5e3DN
2022-12-16 12:53:23.156 DEBUG (MainThread) [music_assistant.event] background_job_updated Analyze audio for spotify://track/6u04aBSTpZDO8MuYC5e3DN
2022-12-16 12:53:23.157 DEBUG (MainThread) [music_assistant.helpers.audio] Start analyzing track spotify://track/6u04aBSTpZDO8MuYC5e3DN
2022-12-16 12:53:25.587 DEBUG (MainThread) [music_assistant.players.stream] Stream job f1c466bc94aa4d5bbdabe2fa6404c4ab cleaned up
2022-12-16 12:53:29.132 DEBUG (MainThread) [music_assistant.helpers.audio] Integrated loudness of spotify://track/6u04aBSTpZDO8MuYC5e3DN is: -9.9
2022-12-16 12:53:29.133 INFO (MainThread) [music_assistant] Finished job [Analyze audio for spotify://track/6u04aBSTpZDO8MuYC5e3DN] in 5.98 seconds.
2022-12-16 12:53:29.133 DEBUG (MainThread) [music_assistant.event] background_job_finished Analyze audio for spotify://track/6u04aBSTpZDO8MuYC5e3DN
2022-12-16 12:53:30.561 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.keuken] state_changed - old: playing - new: idle
2022-12-16 12:53:30.561 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.keuken
2022-12-16 12:53:30.564 DEBUG (MainThread) [music_assistant.event] player_updated media_player.keuken
2022-12-16 12:53:30.576 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.move
2022-12-16 12:53:30.581 DEBUG (MainThread) [music_assistant.event] player_updated media_player.move
2022-12-16 12:53:30.582 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.move] on_child_update [media_player.keuken] {'state'}
2022-12-16 12:53:30.603 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.keuken] state_changed - old: idle - new: paused
2022-12-16 12:53:30.603 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.move] state_changed - old: playing - new: paused
```

**Comment by gieljnssns** [comment]
This is another, it is a different error, but the music also stops playing
```
2022-12-27 10:59:30.026 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.keuken
2022-12-27 10:59:49.036 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.keuken
2022-12-27 11:00:56.027 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.keuken
2022-12-27 11:04:08.242 DEBUG (MainThread) [music_assistant.players.stream] client disconnected: 192.168.79.84
2022-12-27 11:04:09.314 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.move] state_changed - old: playing - new: paused
2022-12-27 11:04:09.314 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.move
2022-12-27 11:04:09.316 DEBUG (MainThread) [music_assistant.event] player_updated media_player.move
2022-12-27 11:04:09.318 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.keuken] state_changed - old: playing - new: paused
2022-12-27 11:04:09.318 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.keuken
2022-12-27 11:04:09.319 DEBUG (MainThread) [music_assistant.event] player_updated media_player.keuken
2022-12-27 11:04:09.320 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.2c] state_changed - old: playing - new: paused
2022-12-27 11:04:09.320 DEBUG (MainThread) [music_assistant.event] queue_updated media_player.2c
2022-12-27 11:04:09.321 DEBUG (MainThread) [music_assistant.event] player_updated media_player.2c
2022-12-27 11:04:09.323 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.2c] on_child_update [media_player.move] {'state'}
2022-12-27 11:04:09.323 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.keuken] on_child_update [media_player.move] {'state'}
2022-12-27 11:04:09.326 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.move] on_child_update [media_player.keuken] {'state'}
2022-12-27 11:04:09.326 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.2c] on_child_update [media_player.keuken] {'state'}
2022-12-27 11:04:09.330 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.move] on_child_update [media_player.2c] {'state'}
2022-12-27 11:04:09.330 DEBUG (MainThread) [custom_components.mass.player_controls.media_player.keuken] on_child_update [media_player.2c] {'state'}
2022-12-27 11:04:13.248 DEBUG (MainThread) [music_assistant.helpers.audio] media stream aborted for: tunein://radio/s309321
2022-12-27 11:04:15.249 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 524, in _queue_stream_runner
    async for chunk in ffmpeg_proc.iter_chunked(self.output_chunksize):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 91, in iter_chunked
    chunk = await self.readexactly(n)
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 110, in readexactly
    return await self._proc.stdout.readexactly(n)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 496, in _queue_stream_runner
    async with AsyncProcess(ffmpeg_args, True) as ffmpeg_proc:
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 500, in writer
    async for audio_chunk in self._get_queue_stream():
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/streams.py", line 670, in _get_queue_stream
    async for chunk in get_media_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 387, in get_media_stream
    async with AsyncProcess(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/process.py", line 76, in __aexit__
    await self._attached_task
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 397, in writer
    async for audio_chunk in music_prov.get_audio_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/music_providers/tunein/tunein.py", line 202, in get_audio_stream
    async for chunk in get_radio_stream(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/helpers/audio.py", line 456, in get_radio_stream
    stream_title = stream_title.group(1).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 16: invalid continuation byte
2022-12-27 11:04:15.750 DEBUG (MainThread) [music_assistant.players.stream] Stream job 060d81899152452db44a0ac070dd6ce7 cleaned up

```

**Comment by OzGav** [comment]
Thanks. Hang on to these errors. We will see if they are still present in the next version of MA.

**Comment by MysticNynja** [comment]
When is the next version coming out?  I am using YouTube Music and in its current state I still haven't been able to listen to a full album without at least 1 song cutting out.

**Comment by OzGav** [comment]
Still a few weeks away

**Comment by MysticNynja** [comment]
Ok just as long as it wasn't released and I'm still getting the errors.  Thanks!

**Comment by erkr** [comment]
The next release is a huge overhaul, both the architecture and a lot of new features. I understood it will take another month or so before it can be released.

**Comment by erkr** [comment]
Yes that is probably true 🤓

**Comment by TheNuggMaster** [comment]
Is this still occuring? As i understand a new version came out... I'm new and seem to be having this issue, though with yt music and google cast devices - trying to figure out if it's the same thing as you and if the update fixed it in your case

**Comment by MysticNynja** [comment]
I haven't used this since the update. I'll check this afternoon and reply here.

**Comment by erkr** [comment]
Hi, the new version 2.0 is still under development and not yet released. 
The recent release versions are only patch versions to keep related MA working with new HA versions. 
The playback stability issues are know and will be resolved when the nee MA 2 is ready. MA 2.0 will introduce an add on. Add ons run in their own isolated proces.

**Comment by TheNuggMaster** [comment]
Hi @erkr , thanks for the info - it seems i misinterpreted something. I'll anxiously await the release of MA 2.0 then! Sounds like it'll solve more than one issue i've been having, can't wait. 
Cheers

**Comment by OzGav** [comment]
@gieljnssns please advise if this is resolved in v2

**Comment by gieljnssns** [comment]
Will try tomorrow

**Comment by gieljnssns** [comment]
Solved
